
/* eslint-disable */

module.exports = (function moduleDefinition() {


    /* eslint-disable */
    /**
     * Title
     *
     * @param  {object} input Expected input properties: productCode
     */
    function policyChangeAmendmentRules(input) {
        // destructure input
        const {productCode} = input;

        // select outputs based on conditions
        const allOutputs = [
            {condition: productCode == "IBG3", outputs: {productDescription: "Базис Гарант (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "EBMOAS", outputs: {productDescription: "Стань миллионером", productGroup: "endowment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "EBMZENIT", outputs: {productDescription: "Стань миллионером", productGroup: "endowment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBI3OAS", outputs: {productDescription: "Базис Инвест (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDGP3", outputs: {productDescription: "Драйвер Гарантия (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "EPGPZENIT", outputs: {productDescription: "Премиум Гарант Плюс", productGroup: "endowment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDGV3", outputs: {productDescription: "Драйвер Гарантия (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDGP10", outputs: {productDescription: "Драйвер Гарантия (10 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBGP5", outputs: {productDescription: "Базис Гарант (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "EPGPAKBARS", outputs: {productDescription: "Премиум Гарант Плюс", productGroup: "endowment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDG1ZENIT", outputs: {productDescription: "Драйвер гарантия (1 год)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBGP3", outputs: {productDescription: "Базис Гарант (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "ERC", outputs: {productDescription: "Надежный выбор", productGroup: "endowment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDGP5", outputs: {productDescription: "Драйвер Гарантия (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBG5", outputs: {productDescription: "Базис Гарант (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBA5", outputs: {productDescription: "Базис Актив (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "EPCLZENIT", outputs: {productDescription: "Премиум выбор Лайт", productGroup: "endowment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "ERCP", outputs: {productDescription: "Надежный выбор Премиум", productGroup: "endowment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "CMS", outputs: {productDescription: "Моя стабильность", productGroup: "credit", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: false, insuranceTermEdit: false, riskEdit: false, paymentPeriodTypeEdit: false, reduction: false, noteEdit: false, allowPaymentStateChange: false, policyHolderChange: false, financialVacations: false, paymentPlanEdit: false, removeOrAddInsuredPerson: false}},
            {condition: productCode == "CMS2", outputs: {productDescription: "Моя стабильность 2", productGroup: "credit", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: false, insuranceTermEdit: false, riskEdit: false, paymentPeriodTypeEdit: false, reduction: false, noteEdit: false, allowPaymentStateChange: false, policyHolderChange: false, financialVacations: false, paymentPlanEdit: false, removeOrAddInsuredPerson: false}},
            {condition: productCode == "EHVP", outputs: {productDescription: "Вектор здоровья Премиум", productGroup: "endowment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBGP7", outputs: {productDescription: "Базис Гарант (7 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBG7", outputs: {productDescription: "Базис Гарант (7 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "CACB", outputs: {productDescription: "Гарант защиты", productGroup: "credit", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: false, insuranceTermEdit: false, riskEdit: false, paymentPeriodTypeEdit: false, reduction: false, noteEdit: false, allowPaymentStateChange: false, policyHolderChange: false, financialVacations: false, paymentPlanEdit: false, removeOrAddInsuredPerson: false}},
            {condition: productCode == "ISP", outputs: {productDescription: "Страйк Премиум", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBI3AKCEPT", outputs: {productDescription: "Базис Инвест (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBIP5", outputs: {productDescription: "Базис Инвест Премиум (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBI5", outputs: {productDescription: "Базис Инвест (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBI10", outputs: {productDescription: "Базис Инвест (10 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDG5", outputs: {productDescription: "Драйвер Гарантия (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBG3BFKO", outputs: {productDescription: "Базис Гарант (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "ERCP2", outputs: {productDescription: "Надежный выбор Премиум 2.0", productGroup: "endowment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBG1AKCEPT", outputs: {productDescription: "Базис Гарант (1 год)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBG5BFKO", outputs: {productDescription: "Базис Гарант (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBG3OAS", outputs: {productDescription: "Базис Гарант (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBI3BFKO", outputs: {productDescription: "Базис Инвест (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDG7", outputs: {productDescription: "Драйвер Гарантия (7 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBAP3", outputs: {productDescription: "Базис Актив Премиум (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBG5OAS", outputs: {productDescription: "Базис Гарант (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "ERC2", outputs: {productDescription: "Надежный выбор 2.0", productGroup: "endowment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "CDMS", outputs: {productDescription: "ДМС", productGroup: "credit", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: false, insuranceTermEdit: false, riskEdit: false, paymentPeriodTypeEdit: false, reduction: false, noteEdit: false, allowPaymentStateChange: false, policyHolderChange: false, financialVacations: false, paymentPlanEdit: false, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBAP5", outputs: {productDescription: "Базис Актив Премиум (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBI5BFKO", outputs: {productDescription: "Базис Инвест (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDC5", outputs: {productDescription: "Драйвер. Классика (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBI5OAS", outputs: {productDescription: "Базис Инвест (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDC", outputs: {productDescription: "Драйвер. Купонный", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBI3ZENIT", outputs: {productDescription: "Базис Инвест (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "DEMOACC", outputs: {productDescription: "Демо НСЖ", productGroup: "endowment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBIP3", outputs: {productDescription: "Базис Инвест Премиум (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "EBMAKCEPT", outputs: {productDescription: "Стань миллионером", productGroup: "endowment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDCP3", outputs: {productDescription: "Драйвер. Классика Премиум (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "CMP", outputs: {productDescription: "Моя защита", productGroup: "credit", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: false, insuranceTermEdit: false, riskEdit: false, paymentPeriodTypeEdit: false, reduction: false, noteEdit: false, allowPaymentStateChange: false, policyHolderChange: false, financialVacations: false, paymentPlanEdit: false, removeOrAddInsuredPerson: false}},
            {condition: productCode == "CMP5", outputs: {productDescription: "Моя защита 5", productGroup: "credit", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: false, insuranceTermEdit: false, riskEdit: false, paymentPeriodTypeEdit: false, reduction: false, noteEdit: false, allowPaymentStateChange: false, policyHolderChange: false, financialVacations: false, paymentPlanEdit: false, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBI3", outputs: {productDescription: "Базис Инвест (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDG3", outputs: {productDescription: "Драйвер Гарантия (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDCP5", outputs: {productDescription: "Драйвер. Классика Премиум (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDG10", outputs: {productDescription: "Драйвер Гарантия (10 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "CCP2", outputs: {productDescription: "Защита кредита 2", productGroup: "credit", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: false, insuranceTermEdit: false, riskEdit: false, paymentPeriodTypeEdit: false, reduction: false, noteEdit: false, allowPaymentStateChange: false, policyHolderChange: false, financialVacations: false, paymentPlanEdit: false, removeOrAddInsuredPerson: false}},
            {condition: productCode == "CCP4", outputs: {productDescription: "Защита кредита 4", productGroup: "credit", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: false, insuranceTermEdit: false, riskEdit: false, paymentPeriodTypeEdit: false, reduction: false, noteEdit: false, allowPaymentStateChange: false, policyHolderChange: false, financialVacations: false, paymentPlanEdit: false, removeOrAddInsuredPerson: false}},
            {condition: productCode == "EHVP2", outputs: {productDescription: "Вектор здоровья Премиум 2.0", productGroup: "endowment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBA3BFKO", outputs: {productDescription: "Базис Актив (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDGP7", outputs: {productDescription: "Драйвер Гарантия (7 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "EBMBFKO", outputs: {productDescription: "Стратегия на пять", productGroup: "endowment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBI5ZENIT", outputs: {productDescription: "Базис Инвест (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBG10", outputs: {productDescription: "Базис Гарант (10 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBA3", outputs: {productDescription: "Базис Актив (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDCP", outputs: {productDescription: "Драйвер. Купонный Премиум", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBI2ZENIT", outputs: {productDescription: "Базис Инвест (2 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "ISO", outputs: {productDescription: "Страйк Оптимум", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBGP10", outputs: {productDescription: "Базис Гарант (10 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBA5BFKO", outputs: {productDescription: "Базис Актив (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBI5AKCEPT", outputs: {productDescription: "Базис Инвест (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDFP", outputs: {productDescription: "Драйвер. Фиксированный Премиум", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "DEMOINV", outputs: {productDescription: "Демо ИСЖ", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "CCP", outputs: {productDescription: "Защита кредита", productGroup: "credit", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: false, insuranceTermEdit: false, riskEdit: false, paymentPeriodTypeEdit: false, reduction: false, noteEdit: false, allowPaymentStateChange: false, policyHolderChange: false, financialVacations: false, paymentPlanEdit: false, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBIP10", outputs: {productDescription: "Базис Инвест Премиум (10 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDGV2", outputs: {productDescription: "Драйвер Гарантия (2 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "EFRBFKO", outputs: {productDescription: "Финансовый резерв", productGroup: "endowment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDC3", outputs: {productDescription: "Драйвер. Классика (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBA5SMP", outputs: {productDescription: "Базис Актив (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBA3SMP", outputs: {productDescription: "Базис Актив (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "ERC2SMP", outputs: {productDescription: "Надежный выбор 2.0", productGroup: "endowment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "DEMOEQUITY", outputs: {productDescription: "Демо ДСЖ", productGroup: "equity", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBA3REINVEST", outputs: {productDescription: "Базис Актив (3 года) реинвест", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBA5REINVEST", outputs: {productDescription: "Базис Актив (5 лет) реинвест", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDG1REINVEST", outputs: {productDescription: "Драйвер гарантия (1 год) реинвест", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDG5REINVEST", outputs: {productDescription: "Драйвер Гарантия (5 лет) реинвест", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDG3REINVEST", outputs: {productDescription: "Драйвер Гарантия (3 года) реинвест", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBI3BFKO17", outputs: {productDescription: "Базис Инвест (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBI5BFKO17", outputs: {productDescription: "Базис Инвест (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBI3ZENIT17", outputs: {productDescription: "Базис Инвест (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IBI5ZENIT17", outputs: {productDescription: "Базис Инвест (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "ECOFPVTB", outputs: {productDescription: "Забота о семье", productGroup: "endowment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "ECOFVVTB", outputs: {productDescription: "Забота о семье Ультра", productGroup: "endowment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDG1LIFEINVEST", outputs: {productDescription: "Драйвер гарантия (1 год) реинвест", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDG5LIFEINVEST", outputs: {productDescription: "Драйвер Гарантия (5 лет) реинвест", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDG3LIFEINVEST", outputs: {productDescription: "Драйвер Гарантия (3 года) реинвест", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDGN3", outputs: {productDescription: "Драйвер Гарантия (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDGN5", outputs: {productDescription: "Драйвер Гарантия (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDG3NT", outputs: {productDescription: "Драйвер Гарантия (3 года)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDG5NT", outputs: {productDescription: "Драйвер Гарантия (5 лет)", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: true, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDG2UBRR", outputs: {productDescription: "2 года Драйвер Гарантия", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: false, insuredSumAndPaymentEdit: false, insuranceTermEdit: false, riskEdit: false, paymentPeriodTypeEdit: false, reduction: false, noteEdit: false, allowPaymentStateChange: false, policyHolderChange: false, financialVacations: false, paymentPlanEdit: false, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDG3UBRR", outputs: {productDescription: "3 года Драйвер Гарантия", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: false, insuredSumAndPaymentEdit: false, insuranceTermEdit: false, riskEdit: false, paymentPeriodTypeEdit: false, reduction: false, noteEdit: false, allowPaymentStateChange: false, policyHolderChange: false, financialVacations: false, paymentPlanEdit: false, removeOrAddInsuredPerson: false}},
            {condition: productCode == "IDG5UBRR", outputs: {productDescription: "5 лет Драйвер Гарантия", productGroup: "investment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: false, insuredSumAndPaymentEdit: false, insuranceTermEdit: false, riskEdit: false, paymentPeriodTypeEdit: false, reduction: false, noteEdit: false, allowPaymentStateChange: false, policyHolderChange: false, financialVacations: false, paymentPlanEdit: false, removeOrAddInsuredPerson: false}},
            {condition: productCode == "ECOF2ZENIT", outputs: {productDescription: "Забота о семье 2.0", productGroup: "endowment", policyHolderPersonalDataEdit: true, insuredPersonPersonalDataEdit: true, beneficiaryEdit: true, beneficiarySelection: true, paymentGraceDateProlongation: true, insuredSumAndPaymentEdit: true, insuranceTermEdit: true, riskEdit: true, paymentPeriodTypeEdit: true, reduction: false, noteEdit: false, allowPaymentStateChange: true, policyHolderChange: true, financialVacations: true, paymentPlanEdit: true, removeOrAddInsuredPerson: false}}
        ]
            .filter(r => r.condition)
            .map(r => r.outputs);

        if(allOutputs.length === 0) {
            return undefined;
        }

        // return outputs based on hit policy (UNIQUE)
        return allOutputs[0];

    }


    // exported functions
    return {
        policyChangeAmendmentRules: policyChangeAmendmentRules
    };
})();
