IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_CHANGE_SAT_CONCLUSION_DATE'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_CHANGE_SAT') ) BEGIN
	CREATE INDEX IDX_AA_CHANGE_SAT_CONCLUSION_DATE ON
PAS_IMPL.AA_CHANGE_SAT(CONCLUSION_DATE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_CHANGE_SAT_START_DATE'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_CHANGE_SAT') ) BEGIN
	CREATE INDEX IDX_AA_CHANGE_SAT_START_DATE ON
PAS_IMPL.AA_CHANGE_SAT(START_DATE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_CHANGE_SAT_END_DATE'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_CHANGE_SAT') ) BEGIN
	CREATE INDEX IDX_AA_CHANGE_SAT_END_DATE ON
PAS_IMPL.AA_CHANGE_SAT(END_DATE)
END

------------------
