IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_ITEM_SAT_ITEM_TYPE'
	AND object_id = OBJECT_ID('ACC_IMPL.PAYMENT_ORDER_ITEM_SAT') ) BEGIN
	CREATE INDEX IDX_PO_ITEM_SAT_ITEM_TYPE ON
ACC_IMPL.PAYMENT_ORDER_ITEM_SAT(ITEM_TYPE)
END

------------------
