"use strict";

const excelParser = require('@config-rgsl/infrastructure/lib/ImportLoaderExcelParser');

module.exports = function resultMapping(input) {

    const names = getNames(input);

    const data = {
        importRowNumber: input.$rowNumber.toString(),
        fullName: excelParser.trim(input.fullName),
        surName: names.surName,
        firstName: names.firstName,
        middleName: names.middleName,
        birthDay: excelParser.trim(input.birthDay),
        gender: excelParser.trim(input.gender),
        insuranceAmountRiskCode1: excelParser.trim(input.insuranceAmountRiskCode1),
        insuranceAmount1: excelParser.trim(input.insuranceAmount1),
        insurancePremium1: excelParser.trim(input.insurancePremium1),
        directRate1: excelParser.trim(input.directRate1),
        reinsurancePremium1: excelParser.trim(input.reinsurancePremium1),
        reinsuranceRate1: excelParser.trim(input.reinsuranceRate1),
        insuranceAmountRiskCode2: excelParser.trim(input.insuranceAmountRiskCode2),
        insuranceAmount2: excelParser.trim(input.insuranceAmount2),
        insurancePremium2: excelParser.trim(input.insurancePremium2),
        directRate2: excelParser.trim(input.directRate2),
        reinsurancePremium2: excelParser.trim(input.reinsurancePremium2),
        reinsuranceRate2: excelParser.trim(input.reinsuranceRate2),
        insuranceAmountRiskCode3: excelParser.trim(input.insuranceAmountRiskCode3),
        insuranceAmount3: excelParser.trim(input.insuranceAmount3),
        insurancePremium3: excelParser.trim(input.insurancePremium3),
        directRate3: excelParser.trim(input.directRate3),
        reinsurancePremium3: excelParser.trim(input.reinsurancePremium3),
        reinsuranceRate3: excelParser.trim(input.reinsuranceRate3),
        insuranceAmountRiskCode4: excelParser.trim(input.insuranceAmountRiskCode4),
        insuranceAmount4: excelParser.trim(input.insuranceAmount4),
        insurancePremium4: excelParser.trim(input.insurancePremium4),
        directRate4: excelParser.trim(input.directRate4),
        reinsurancePremium4: excelParser.trim(input.reinsurancePremium4),
        reinsuranceRate4: excelParser.trim(input.reinsuranceRate4),
        insuranceAmountRiskCode5: excelParser.trim(input.insuranceAmountRiskCode5),
        insuranceAmount5: excelParser.trim(input.insuranceAmount5),
        insurancePremium5: excelParser.trim(input.insurancePremium5),
        directRate5: excelParser.trim(input.directRate5),
        reinsurancePremium5: excelParser.trim(input.reinsurancePremium5),
        reinsuranceRate5: excelParser.trim(input.reinsuranceRate5),
        insuranceAmountRiskCode6: excelParser.trim(input.insuranceAmountRiskCode6),
        insuranceAmount6: excelParser.trim(input.insuranceAmount6),
        insurancePremium6: excelParser.trim(input.insurancePremium6),
        directRate6: excelParser.trim(input.directRate6),
        reinsurancePremium6: excelParser.trim(input.reinsurancePremium6),
        reinsuranceRate6: excelParser.trim(input.reinsuranceRate6),
        insuranceAmountRiskCode7: excelParser.trim(input.insuranceAmountRiskCode7),
        insuranceAmount7: excelParser.trim(input.insuranceAmount7),
        insurancePremium7: excelParser.trim(input.insurancePremium7),
        directRate7: excelParser.trim(input.directRate7),
        reinsurancePremium7: excelParser.trim(input.reinsurancePremium7),
        reinsuranceRate7: excelParser.trim(input.reinsuranceRate7),
        insuranceAmountRiskCode8: excelParser.trim(input.insuranceAmountRiskCode8),
        insuranceAmount8: excelParser.trim(input.insuranceAmount8),
        insurancePremium8: excelParser.trim(input.insurancePremium8),
        directRate8: excelParser.trim(input.directRate8),
        reinsurancePremium8: excelParser.trim(input.reinsurancePremium8),
        reinsuranceRate8: excelParser.trim(input.reinsuranceRate8),
        insuranceAmountRiskCode9: excelParser.trim(input.insuranceAmountRiskCode9),
        insuranceAmount9: excelParser.trim(input.insuranceAmount9),
        insurancePremium9: excelParser.trim(input.insurancePremium9),
        directRate9: excelParser.trim(input.directRate9),
        reinsurancePremium9: excelParser.trim(input.reinsurancePremium9),
        reinsuranceRate9: excelParser.trim(input.reinsuranceRate9),
        insuranceAmountRiskCode10: excelParser.trim(input.insuranceAmountRiskCode10),
        insuranceAmount10: excelParser.trim(input.insuranceAmount10),
        insurancePremium10: excelParser.trim(input.insurancePremium10),
        directRate10: excelParser.trim(input.directRate10),
        reinsurancePremium10: excelParser.trim(input.reinsurancePremium10),
        reinsuranceRate10: excelParser.trim(input.reinsuranceRate10),
        insuranceAmountRiskCode11: excelParser.trim(input.insuranceAmountRiskCode11),
        insuranceAmount11: excelParser.trim(input.insuranceAmount11),
        insurancePremium11: excelParser.trim(input.insurancePremium11),
        directRate11: excelParser.trim(input.directRate11),
        reinsurancePremium11: excelParser.trim(input.reinsurancePremium11),
        reinsuranceRate11: excelParser.trim(input.reinsuranceRate11),
        insuranceAmountRiskCode12: excelParser.trim(input.insuranceAmountRiskCode12),
        insuranceAmount12: excelParser.trim(input.insuranceAmount12),
        insurancePremium12: excelParser.trim(input.insurancePremium12),
        directRate12: excelParser.trim(input.directRate12),
        reinsurancePremium12: excelParser.trim(input.reinsurancePremium12),
        reinsuranceRate12: excelParser.trim(input.reinsuranceRate12),
        insuranceAmountRiskCode13: excelParser.trim(input.insuranceAmountRiskCode13),
        insuranceAmount13: excelParser.trim(input.insuranceAmount13),
        insurancePremium13: excelParser.trim(input.insurancePremium13),
        directRate13: excelParser.trim(input.directRate13),
        reinsurancePremium13: excelParser.trim(input.reinsurancePremium13),
        reinsuranceRate13: excelParser.trim(input.reinsuranceRate13),
        insuranceAmountRiskCode14: excelParser.trim(input.insuranceAmountRiskCode14),
        insuranceAmount14: excelParser.trim(input.insuranceAmount14),
        insurancePremium14: excelParser.trim(input.insurancePremium14),
        directRate14: excelParser.trim(input.directRate14),
        reinsurancePremium14: excelParser.trim(input.reinsurancePremium14),
        reinsuranceRate14: excelParser.trim(input.reinsuranceRate14),
        insuranceAmountRiskCode15: excelParser.trim(input.insuranceAmountRiskCode15),
        insuranceAmount15: excelParser.trim(input.insuranceAmount15),
        insurancePremium15: excelParser.trim(input.insurancePremium15),
        directRate15: excelParser.trim(input.directRate15),
        reinsurancePremium15: excelParser.trim(input.reinsurancePremium15),
        reinsuranceRate15: excelParser.trim(input.reinsuranceRate15),
        insuranceAmountRiskCode16: excelParser.trim(input.insuranceAmountRiskCode16),
        insuranceAmount16: excelParser.trim(input.insuranceAmount16),
        insurancePremium16: excelParser.trim(input.insurancePremium16),
        directRate16: excelParser.trim(input.directRate16),
        reinsurancePremium16: excelParser.trim(input.reinsurancePremium16),
        reinsuranceRate16: excelParser.trim(input.reinsuranceRate16),
        insuranceAmountRiskCode17: excelParser.trim(input.insuranceAmountRiskCode17),
        insuranceAmount17: excelParser.trim(input.insuranceAmount17),
        insurancePremium17: excelParser.trim(input.insurancePremium17),
        directRate17: excelParser.trim(input.directRate17),
        reinsurancePremium17: excelParser.trim(input.reinsurancePremium17),
        reinsuranceRate17: excelParser.trim(input.reinsuranceRate17),
        insuranceAmountRiskCode18: excelParser.trim(input.insuranceAmountRiskCode18),
        insuranceAmount18: excelParser.trim(input.insuranceAmount18),
        insurancePremium18: excelParser.trim(input.insurancePremium18),
        directRate18: excelParser.trim(input.directRate18),
        reinsurancePremium18: excelParser.trim(input.reinsurancePremium18),
        reinsuranceRate18: excelParser.trim(input.reinsuranceRate18),
        insuranceAmountRiskCode19: excelParser.trim(input.insuranceAmountRiskCode19),
        insuranceAmount19: excelParser.trim(input.insuranceAmount19),
        insurancePremium19: excelParser.trim(input.insurancePremium19),
        directRate19: excelParser.trim(input.directRate19),
        reinsurancePremium19: excelParser.trim(input.reinsurancePremium19),
        reinsuranceRate19: excelParser.trim(input.reinsuranceRate19),
        insuranceAmountRiskCode20: excelParser.trim(input.insuranceAmountRiskCode20),
        insuranceAmount20: excelParser.trim(input.insuranceAmount20),
        insurancePremium20: excelParser.trim(input.insurancePremium20),
        directRate20: excelParser.trim(input.directRate20),
        reinsurancePremium20: excelParser.trim(input.reinsurancePremium20),
        reinsuranceRate20: excelParser.trim(input.reinsuranceRate20),
        insuranceAmountRiskCode21: excelParser.trim(input.insuranceAmountRiskCode21),
        insuranceAmount21: excelParser.trim(input.insuranceAmount21),
        insurancePremium21: excelParser.trim(input.insurancePremium21),
        directRate21: excelParser.trim(input.directRate21),
        reinsurancePremium21: excelParser.trim(input.reinsurancePremium21),
        reinsuranceRate21: excelParser.trim(input.reinsuranceRate21),
        insuranceAmountRiskCode22: excelParser.trim(input.insuranceAmountRiskCode22),
        insuranceAmount22: excelParser.trim(input.insuranceAmount22),
        insurancePremium22: excelParser.trim(input.insurancePremium22),
        directRate22: excelParser.trim(input.directRate22),
        reinsurancePremium22: excelParser.trim(input.reinsurancePremium22),
        reinsuranceRate22: excelParser.trim(input.reinsuranceRate22),
        insuranceAmountRiskCode23: excelParser.trim(input.insuranceAmountRiskCode23),
        insuranceAmount23: excelParser.trim(input.insuranceAmount23),
        insurancePremium23: excelParser.trim(input.insurancePremium23),
        directRate23: excelParser.trim(input.directRate23),
        reinsurancePremium23: excelParser.trim(input.reinsurancePremium23),
        reinsuranceRate23: excelParser.trim(input.reinsuranceRate23),
        commission: excelParser.trim(input.commission),
        manualExpenses: excelParser.trim(input.manualExpenses),
        manualCommissionNP: excelParser.trim(input.manualCommissionNP),
        manualCommissionSP: excelParser.trim(input.manualCommissionSP),
        reinsurerCode: excelParser.trim(input.reinsurerCode),
        reinsurerShare: excelParser.trim(input.reinsurerShare)
    };

    const ret = {
        data: data,
        $recordKey: `${input.$rowNumber}`
    };

    return ret;
};

function getNames(input) {

    const fullName = excelParser.trim(input.fullName);
    if (fullName) {
        const names = fullName.split(" ");
        const surName = names[0];
        const firstName = names[1];
        const middleName = (names.length > 2) ? names.slice(- (names.length - 2)).join(" ") : " ";

        return {
            surName,
            firstName,
            middleName
        };
    }

    return {};
}
