IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_CANCELLATION_SAT_CANCELLATION_DATE'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_CANCELLATION_SAT') ) BEGIN
	CREATE INDEX IDX_AA_CANCELLATION_SAT_CANCELLATION_DATE ON
PAS_IMPL.AA_CANCELLATION_SAT(CANCELLATION_DATE)
END

------------------
