UPDATE BFX_IMPL.SEND_EVENT_EXCEPTIONS
SET SALES_SEGMENT = p.CODE
FROM BFX_IMPL.SEND_EVENT_EXCEPTIONS see
INNER JOIN BFX_IMPL.PRODUCTS p
	ON p.CODE = see.VALUE
WHERE see.SALES_SEGMENT IS NULL

UPDATE BFX_IMPL.SEND_EVENT_EXCEPTIONS
SET PARTNER_CODE = JSON_VALUE(u.BODY,'$.code')
FROM ORG.ORGANISATION_UNIT u
WHERE JSON_VALUE(u.BODY,'$.code') IN (
	SELECT DISTINCT c.PARTNER_BUSINESS_CODE FROM BFX_IMPL.PRODUCTS p
	LEFT JOIN BFX_IMPL.PRODUCT_CONF c
		ON c.PRODUCT_CODE = p.CODE
	INNER JOIN BFX_IMPL.SEND_EVENT_EXCEPTIONS see
		ON see.VALUE = p.CODE)
AND PARTNER_CODE IS NULL