BEGIN TRY
BEGIN TRAN

UPDATE CLM_IMPL.CLM_SAT 
	SET CONTRACT_INSURED_NAME = psl.INSURED_NAME
FROM CLM_IMPL.CLM_SAT_LATEST csl
	LEFT JOIN PAS_IMPL.POLICY_HUB ph ON ph.CONTRACT_NUMBER = csl.CONTRACT_NUMBER
	LEFT JOIN PAS_IMPL.POLICY_SAT_LATEST psl ON psl.POLICY_HKEY  = ph.POLICY_HKEY

COMMIT TRAN
END TRY

BEGIN CATCH

    ROLLBACK TRAN
    DECLARE @ErrorMessage NVARCHAR(4000); DECLARE @ErrorSeverity INT; DECLARE @ErrorState INT;
    SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = 1;
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);

END CATCH