IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ACC_IMPL].[CRT_SAT]') AND TYPE IN (N'U'))
BEGIN
	IF COL_LENGTH('ACC_IMPL.CRT_SAT','INCOME_SOURCE') IS NOT NULL
	BEGIN
        UPDATE sat
        SET sat.INCOME_SOURCE = '2'
        FROM ACC_IMPL.CRT_SAT sat
        WHERE sat.INCOME_SOURCE IS NULL
    END
END

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ACC_IMPL].[CRT_SAT]') AND TYPE IN (N'U'))
BEGIN
    IF COL_LENGTH('ACC_IMPL.CRT_SAT','INCOME_SOURCE') IS NOT NULL
    BEGIN
        UPDATE sat
        SET sat.INCOME_SOURCE = '1'
        FROM ACC_IMPL.CRT_SAT sat
        WHERE sat.INCOME_SOURCE NOT IN ('1','2','3')
    END
END

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ACC_IMPL].[CRT_SAT]') AND TYPE IN (N'U'))
BEGIN
    IF COL_LENGTH('ACC_IMPL.CRT_SAT','INCOME_SOURCE') IS NOT NULL
    BEGIN
        UPDATE ud
        SET ud.BODY = JSON_MODIFY(ud.BODY, '$.accountingCertificateIncomeSource', CAST(sat.INCOME_SOURCE AS INT))
        FROM
        BFX.UNIVERSAL_DOCUMENT ud
        INNER JOIN ACC_IMPL.CRT_HUB hub
            ON ud.UNIVERSAL_DOCUMENT_NUMBER = hub.CERTIFICATE_NUMBER
        INNER JOIN ACC_IMPL.CRT_SAT sat
            ON hub.CRT_HKEY = sat.CRT_HKEY
        WHERE ud.PUBLISHED_ARTIFACT_ID =
        (
            SELECT PUBLISHED_ARTIFACT_ID
            FROM CFX.PUBLISHED_ARTIFACT
            WHERE CODE_NAME = N'AccountingCertificate'
        )
            AND ud.body LIKE N'%accountingCertificateIncomeSource": "%'
    END
END