INSERT INTO BFX.ACTIVITY
(
	ACTIVITY_ID,
	ACTIVITY_TYPE,
	ENTITY_REF_ID,
	ACTIVITY_STATUS,
	DOCUMENT_STATE,
	SOURCE_ID,
	PARENT_ACTIVITY_ID,
	CLOSE_ON_TRANSITION,
	CLOSE_MANUALLY,
	USER_GROUP_CODE,
	OU_ID,
	SYS_CREATED_ON,
	SYS_UPDATED_ON,
	SYS_CLIENT_ID,
	SYS_VERSION,
	SYS_TENANT_ID,
	SYS_CREATED_BY_ID,
	SYS_UPDATED_BY_ID,
	CREATED_ON,
	CLOSED_ON,
	ASSIGNED_USER_ID,
	CREATED_BY,
	CLOSED_BY,
	DEADLINE,
	COMMENT,
	PREVIOUS_DOCUMENT_STATE,
	PRIORITY_WEIGHT,
	PRIORITY_CODE,
	WAIT_FOR_CHILDREN,
	CLOSE_WHEN_CHILDREN,
	MANUAL_ACTIVITY_TYPE,
	CREATION_CAUSED_BY,
	CLOSING_CAUSED_BY,
	LAST_ASSIGNED_BY,
	LAST_ASSIGNED_ON,
	EFFORT_CODE,
	EFFORT_IN_MINUTES,
	REFERENCE,
	ALLOCATED_BY_SCHEDULE,
	EVENT_CREATED_ON
)
SELECT
	NEWID(),
	'State' AS ACTIVITY_TYPE,
	ud.UNIVERSAL_DOCUMENT_ID AS ENTITY_REF_ID,
	'Open' AS ACTIVITY_STATUS,
	1 AS DOCUMENT_STATE,
	N'00000000-0000-0000-0000-000000000000' AS SOURCE_ID,
	NULL AS PARENT_ACTIVITY_ID,
	1 AS CLOSE_ON_TRANSITION,
	0 AS CLOSE_MANUALLY,
	'UFO' AS USER_GROUP_CODE,
	NULL AS OU_ID,
	GETDATE() AS SYS_CREATED_ON,
	GETDATE() AS SYS_UPDATED_ON,
	'System' AS SYS_CLIENT_ID,
	1 AS SYS_VERSION,
	NULL AS SYS_TENANT_ID,
	N'00000000-0000-0000-0000-000000000000' AS SYS_CREATED_BY_ID,
	N'00000000-0000-0000-0000-000000000000' AS SYS_UPDATED_BY_ID,
	GETDATE() AS CREATED_ON,
	NULL AS CLOSED_ON,
	NULL AS ASSIGNED_USER_ID,
	N'00000000-0000-0000-0000-000000000000' AS CREATED_BY,
	NULL AS CLOSED_BY,
	NULL AS DEADLINE,
	NULL AS COMMENT,
	NULL AS PREVIOUS_DOCUMENT_STATE,
	NULL AS PRIORITY_WEIGHT,
	NULL AS PRIORITY_CODE,
	0 AS WAIT_FOR_CHILDREN,
	0 AS CLOSE_WHEN_CHILDREN,
	NULL AS MANUAL_ACTIVITY_TYPE,
	N'00000000-0000-0000-0000-000000000000' AS CREATION_CAUSED_BY,
	N'00000000-0000-0000-0000-000000000000' AS CLOSING_CAUSED_BY,
	N'00000000-0000-0000-0000-000000000000' AS LAST_ASSIGNED_BY,
	GETDATE() AS LAST_ASSIGNED_ON,
	NULL AS EFFORT_CODE,
	NULL AS EFFORT_IN_MINUTES,
	NULL AS REFERENCE,
	NULL AS ALLOCATED_BY_SCHEDULE,
	GETDATE() AS EVENT_CREATED_ON
FROM BFX.UNIVERSAL_DOCUMENT ud
	JOIN ACC_IMPL.CRT_HUB crtH
		ON crtH.CERTIFICATE_NUMBER = ud.UNIVERSAL_DOCUMENT_NUMBER
	JOIN ACC_IMPL.CRT_SAT_LATEST crtS
		ON crtS.CRT_HKEY = crtH.CRT_HKEY
	JOIN CFG.PROCESS_STATE ps
		ON ps.CODE_NAME = crtS.STATE
	JOIN PAS.CONTRACT c
		ON c.CONTRACT_NUMBER = crtS.CONTRACT_NUMBER
	JOIN CFX.PUBLISHED_ARTIFACT pa
		ON pa.PUBLISHED_ARTIFACT_ID = c.PUBLISHED_ARTIFACT_ID
	LEFT JOIN BFX.ACTIVITY activ
		ON activ.ENTITY_REF_ID = ud.UNIVERSAL_DOCUMENT_ID
WHERE activ.ACTIVITY_ID IS NULL