UPDATE ud
SET VERSION_STATE = NULL
FROM BFX.UNIVERSAL_VERSIONED_DOCUMENT ud
INNER JOIN ACC_IMPL.CRT_HUB hub
	ON hub.CERTIFICATE_NUMBER = ud.UNIVERSAL_VERSIONED_DOCUMENT_NUMBER
WHERE ud.VERSION_STATE = 'DISCARDED'