IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[PRODUCT_CONF]') AND TYPE IN (N'U'))
BEGIN

    update [BFX_IMPL].[PRODUCT_CONF] set [CONSENT_TO_DATA_TRANSFERING_FNS] = 1
    where PRODUCT_CODE in ('EBMGVTB','EBMGNVTB','IDGP5VTB','IDGPN5VTB','IDGP5PPVTB','IDGPN5PPVTB','ECATFPVTB','IBAP5VTB','IBAKVP5PEVTB','IBAKVP5VTB','ECOFPVTB','IBA2P5VTB','EBMGVVTB','IDGV5VTB','IDGVN5VTB','IDGV5PPVTB','IDGVN5PPVTB','ECATFPVVTB','IBAV5VTB','IBAKVVP5PEVTB','IBAKVVP5VTB','ECOFPVVTB','IBA2V5VTB','EBMGRETVTB','EBMGNRETVTB')

    update [BFX_IMPL].[PRODUCT_CONF] set [CONSENT_TO_DATA_TRANSFERING_FNS] = 0
    where PRODUCT_CODE not in ('EBMGVTB','EBMGNVTB','IDGP5VTB','IDGPN5VTB','IDGP5PPVTB','IDGPN5PPVTB','ECATFPVTB','IBAP5VTB','IBAKVP5PEVTB','IBAKVP5VTB','ECOFPVTB','IBA2P5VTB','EBMGVVTB','IDGV5VTB','IDGVN5VTB','IDGV5PPVTB','IDGVN5PPVTB','ECATFPVVTB','IBAV5VTB','IBAKVVP5PEVTB','IBAKVVP5VTB','ECOFPVVTB','IBA2V5VTB','EBMGRETVTB','EBMGNRETVTB')

END
GO