UPDATE ud SET COMMON_BODY = JSON_MODIFY(ud.COMMON_BODY, '$.attributes.contract.configurationVersion', '1')
FROM bfx.UNIVERSAL_DOCUMENT ud
LEFT JOIN cfx.PUBLISHED_ARTIFACT pa ON pa.PUBLISHED_ARTIFACT_ID = ud.PUBLISHED_ARTIFACT_ID
WHERE pa.CODE_NAME = 'InsuredEvent';