CREATE TABLE BFX_IMPL.ADIRGSLSUPP_1050_BACKUP (
DOC_ID UNIQUEIDENTIFIER,
DOC_NUMBER NVARCHAR(255) NOT NULL,
BODY NVARCHAR(MAX) NOT NULL
)

INSERT INTO BFX_IMPL.ADIRGSLSUPP_1050_BACKUP (DOC_ID, DOC_NUMBER, BODY)
SELECT doc.UNIVERSAL_DOCUMENT_ID, doc.UNIVERSAL_DOCUMENT_NUMBER, doc.BODY
FROM BFX.UNIVERSAL_DOCUMENT doc
JOIN cfx.PUBLISHED_ARTIFACT art on art.PUBLISHED_ARTIFACT_ID = doc.PUBLISHED_ARTIFACT_ID
WHERE art.CODE_NAME in ('EndowmentInquiry', 'LifeInsuranceInquiry', 'CancellationInquiry', 'LifeInsurancePolicyInquiry')