IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX].[UNIVERSAL_DOCUMENT]') AND TYPE IN (N'U'))
BEGIN

	IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX].[UNIVERSAL_DOCUMENT_PARTNER_BACKUP]') AND TYPE IN (N'U'))
	BEGIN
		DROP TABLE BFX.UNIVERSAL_DOCUMENT_PARTNER_BACKUP
	END

	SELECT 
		UNIVERSAL_DOCUMENT_NUMBER,
		BODY, 
		COMMON_BODY
	INTO BFX.UNIVERSAL_DOCUMENT_PARTNER_BACKUP
	FROM BFX.UNIVERSAL_DOCUMENT ud
	LEFT JOIN CFX.PUBLISHED_ARTIFACT pa ON pa.PUBLISHED_ARTIFACT_ID = ud.PUBLISHED_ARTIFACT_ID
	WHERE pa.CODE_NAME = 'LifeInsuranceRequest';

END
