SELECT DISTINCT pdi.PARTY_CODE, pdi.DEDUPL_NUMBER
INTO #tempPolicyHolderCodesToUpdate
FROM PTY_IMPL.PARTY_DEDUP_INFO pdi
LEFT JOIN PAS_IMPL.POLICY_SAT ps ON ps.HOLDER_CODE = pdi.PARTY_CODE
WHERE pdi.IS_PROCESSED = 1 AND ps.HOLDER_CODE != pdi.DEDUPL_NUMBER

UPDATE ps
SET HOLDER_CODE = t1.DEDUPL_NUMBER
FROM PAS_IMPL.POLICY_SAT ps
LEFT JOIN #tempPolicyHolderCodesToUpdate t1 ON t1.PARTY_CODE = ps.HOLDER_CODE
WHERE t1.PARTY_CODE = ps.HOLDER_CODE

DROP TABLE #tempPolicyHolderCodesToUpdate
