IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_SAT]') AND TYPE IN (N'U'))
BEGIN

	IF COL_LENGTH('PAS_IMPL.POLICY_SAT','GUARANTEE_INCOME_CODE') IS NOT NULL
	BEGIN

		UPDATE ps
		SET ps.GUARANTEE_INCOME_CODE = JSON_VALUE(c.body, '$.basicConditions.guaranteedIncome.guaranteedIncomeCode')
		FROM PAS_IMPL.POLICY_SAT ps
		JOIN PAS_IMPL.POLICY_HUB qh on qh.POLICY_HKEY = ps.POLICY_HKEY
		JOIN PAS.CONTRACT c on c.CONTRACT_NUMBER = qh.CONTRACT_NUMBER

	END

END
GO
