UPDATE bSat SET BANK_ACCOUNT_NUMBER = r.BANK_ACCOUNT_NUMBER
FROM EWT_IMPL.EWT_HUB eHub
INNER JOIN BFX.UNIVERSAL_DOCUMENT doc ON doc.UNIVERSAL_DOCUMENT_NUMBER = eHub.ENDOWMENT_NUMBER
INNER JOIN EWT_IMPL.EWT_BENEFICIARY_LINK bLink on bLink.EWT_HKEY = eHub.EWT_HKEY
INNER JOIN PTY_IMPL.PARTY_HUB pHub on pHub.PARTY_HKEY = bLink.PARTY_HKEY
INNER JOIN EWT_IMPL.EWT_BENEFICIARY_SAT_LATEST bSat on bSat.EWT_BENEFICIARY_HKEY = bLink.EWT_BENEFICIARY_HKEY
CROSS APPLY OPENJSON(doc.BODY,'$.endowmentBeneficiaries')
 with  
 (    
     BENEFICIARY_PARTY_CODE NVARCHAR(50) N'lax $.partyCode',
	 AMOUNT_TO_PAY_DOC_CURR DECIMAL(15,7) N'lax $.amountToPay',
	 AMOUNT_TO_PAY_RUB_CURR DECIMAL(15,7) N'lax $.amountToPayInRubCurrency',
	 BANK_ACCOUNT_NUMBER NVARCHAR(100) N'lax $.bankAccount.number',
	 ASSIGNED_PO_NUMBER NVARCHAR(255) N'lax $.assignedPaymentOrderNumber'
 ) r
WHERE 
pHub.PARTY_CODE = r.BENEFICIARY_PARTY_CODE 
AND r.ASSIGNED_PO_NUMBER = bSat.ASSIGNED_PO_NUMBER
AND bSat.IS_DELETED = 0