UPDATE PAS_IMPL.AMENDMENT_LINES_SAT SET SUM_IN_RUB = SUM

INSERT INTO PAS_IMPL.CNL_AMENDMENT_SAT (
	CNL_AMENDMENT_HKEY,
	LOAD_DATE,
	RECORD_SOURCE,
	HASH_DIFF,
	AMENDMENT_SUBTYPE,
	SHOULD_USE_NETTING
)
SELECT s.AMENDMENT_HKEY,
	   s.LOAD_DATE,
	   s.RECORD_SOURCE,
	   CONVERT(CHAR(32), HashBytes('MD5', CAST(newid() AS varbinary(max))), 2) AS HASH_DIFF,
	   s.AMEDNMENT_SUBTYPE,
	   s.SHOULD_USE_NETTING
FROM
(SELECT hub.AMENDMENT_HKEY,
	   GETDATE() AS LOAD_DATE,
	   N'ADINSURE' AS RECORD_SOURCE,
	   JSON_VALUE(ctr.BODY, '$.basicAmendmentConditions.amendmentSubType') AS AMEDNMENT_SUBTYPE,
	   COALESCE(JSON_VALUE(ctr.BODY, '$.paymentAmendmentConditions.shouldUseNetting'), 0) AS SHOULD_USE_NETTING
FROM PAS_IMPL.AMENDMENT_HUB hub
JOIN PAS.CONTRACT ctr ON ctr.CONTRACT_NUMBER = hub.AMENDMENT_NUMBER
JOIN CFX.PUBLISHED_ARTIFACT art on ctr.PUBLISHED_ARTIFACT_ID = art.PUBLISHED_ARTIFACT_ID
WHERE art.CODE_NAME IN ('AccumulatedLifeInsuranceCancellation', 'InvestmentLifeInsuranceCancellation', 'CreditLifeInsuranceCancellation',
'RiskLifeInsuranceCancellation', 'MedLifeInsuranceCancellation')) s



INSERT INTO PAS_IMPL.CNL_RECIPIENT_LINK (
	CNL_RECIPIENT_HKEY,
	LOAD_DATE,
	RECORD_SOURCE,
	AMENDMENT_HKEY,
	PARTY_HKEY
)
SELECT CONVERT(CHAR(32), HashBytes('MD5', CONVERT(VARBINARY(MAX), sys_impl.NCharToUTF8Binary(CONCAT_WS(':', s.AMENDMENT_NUMBER, s.PARTY_CODE ), NULL))), 2) AS CNL_RECIPIENT_HKEY,
	   s.LOAD_DATE,
	   s.RECORD_SOURCE,
	   s.AMENDMENT_HKEY,
	   s.PARTY_HKEY
FROM
(SELECT GETDATE() AS LOAD_DATE,
	   N'ADINSURE' AS RECORD_SOURCE,
	   hub.AMENDMENT_HKEY,
	   hub.AMENDMENT_NUMBER,
	   pHub.PARTY_HKEY,
	   pHub.PARTY_CODE
FROM PAS_IMPL.AMENDMENT_HUB hub
JOIN PAS.CONTRACT ctr ON ctr.CONTRACT_NUMBER = hub.AMENDMENT_NUMBER
JOIN CFX.PUBLISHED_ARTIFACT art on ctr.PUBLISHED_ARTIFACT_ID = art.PUBLISHED_ARTIFACT_ID
CROSS APPLY OPENJSON(ctr.BODY,'$.paymentAmendmentConditions.canellationRecipients')
 with  
 (    
     RECIPIENT_CODE NVARCHAR(50) N'$.partyCode'
 ) r 
 JOIN PTY_IMPL.PARTY_HUB pHub ON pHub.PARTY_CODE = r.RECIPIENT_CODE
WHERE art.CODE_NAME IN ('AccumulatedLifeInsuranceCancellation', 'InvestmentLifeInsuranceCancellation', 'CreditLifeInsuranceCancellation',
'RiskLifeInsuranceCancellation', 'MedLifeInsuranceCancellation')) s



INSERT INTO PAS_IMPL.CNL_RECIPIENT_SAT (
	CNL_RECIPIENT_HKEY,
	LOAD_DATE,
	RECORD_SOURCE,
	HASH_DIFF,
	REASON_CODE,
	REASON_DESCRIPTION,
	PAYMENT_TYPE_CODE,
	PAYMENT_TYPE_DESCRIPTION,
	AMOUNT_TO_PAY_PERCENTAGE,
	AMOUNT_TO_PAY,
	AMOUNT_TO_PAY_RUB_CUR,
	PIT_AMOUNT,
	PIT_AMOUNT_RUB_CUR,
	BANK_ACCOUNT_NUMBER,
	IS_PAID,
	IS_DELETED
)
SELECT s.CNL_RECIPIENT_HKEY,
	   s.LOAD_DATE,
	   s.RECORD_SOURCE,
	   CONVERT(CHAR(32), HashBytes('MD5', CAST(newid() AS varbinary(max))), 2) AS HASH_DIFF,
		s.REASON_CODE, 
		s.REASON_DESCRIPTION, 
		s.PAYMENT_TYPE_CODE,
		s.PAYMENT_TYPE_DESCRIPTION,
		s.AMOUNT_TO_PAY_PERCENTAGE,
		s.AMOUNT_TO_PAY,
		s.AMOUNT_TO_PAY_RUB_CUR,
		s.PIT_AMOUNT,
		s.PIT_AMOUNT_RUB_CUR,
		s.BANK_ACCOUNT_NUMBER,
		s.IS_PAID,
		s.IS_DELETED
FROM
(SELECT rLink.CNL_RECIPIENT_HKEY,
	   GETDATE() AS LOAD_DATE,
	   N'ADINSURE' AS RECORD_SOURCE,
	   r.REASON_CODE AS REASON_CODE,
	   r.REASON_DESCRIPTION AS REASON_DESCRIPTION,
	   r.PAYMENT_TYPE_CODE AS PAYMENT_TYPE_CODE,
	   r.PAYMENT_TYPE_DESCRIPTION AS PAYMENT_TYPE_DESCRIPTION,
	   r.AMOUNT_TO_PAY_PERCENTAGE AS AMOUNT_TO_PAY_PERCENTAGE,
	   r.AMOUNT_TO_PAY AS AMOUNT_TO_PAY,
	   r.AMOUNT_TO_PAY_RUB_CUR AS AMOUNT_TO_PAY_RUB_CUR,
	   r.PIT_AMOUNT AS PIT_AMOUNT,
	   r.PIT_AMOUNT_RUB_CUR AS PIT_AMOUNT_RUB_CUR,
	   r.BANK_ACCOUNT_NUMBER AS BANK_ACCOUNT_NUMBER,
	   COALESCE(r.IS_PAID, 0) AS IS_PAID,
	   0 AS IS_DELETED
FROM PAS_IMPL.AMENDMENT_HUB hub
JOIN PAS.CONTRACT ctr ON ctr.CONTRACT_NUMBER = hub.AMENDMENT_NUMBER
JOIN CFX.PUBLISHED_ARTIFACT art on ctr.PUBLISHED_ARTIFACT_ID = art.PUBLISHED_ARTIFACT_ID
CROSS APPLY OPENJSON(ctr.BODY,'$.paymentAmendmentConditions.canellationRecipients')
 with  
 (    
     RECIPIENT_CODE NVARCHAR(50) N'$.partyCode',
	 REASON_CODE NVARCHAR(50) N'$.recipientReason.code',
	 REASON_DESCRIPTION NVARCHAR(250) N'$.recipientReason.description',
	 PAYMENT_TYPE_CODE NVARCHAR(50) N'$.recipientPaymentType.code',
	 PAYMENT_TYPE_DESCRIPTION NVARCHAR(250) N'$.recipientPaymentType.description',
	 AMOUNT_TO_PAY_PERCENTAGE DECIMAL(15,2) N'$.amountToPayPercetage',
	 AMOUNT_TO_PAY DECIMAL(15,2) N'$.amountToPay',
	 AMOUNT_TO_PAY_RUB_CUR DECIMAL(15,2) N'$.amountToPayInRubCurrency',
	 PIT_AMOUNT DECIMAL(15,2) N'$.pitAmount',
	 PIT_AMOUNT_RUB_CUR DECIMAL(15,2) N'$.pitAmountInRubCurrency',
	 BANK_ACCOUNT_NUMBER NVARCHAR(256) N'$.bankAccount.number',
	 IS_PAID BIT N'$.isPaid'
 ) r 
 JOIN PTY_IMPL.PARTY_HUB pHub ON pHub.PARTY_CODE = r.RECIPIENT_CODE
 JOIN PAS_IMPL.CNL_RECIPIENT_LINK rLink ON rLink.AMENDMENT_HKEY = hub.AMENDMENT_HKEY AND rLink.PARTY_HKEY = pHub.PARTY_HKEY
WHERE art.CODE_NAME IN ('AccumulatedLifeInsuranceCancellation', 'InvestmentLifeInsuranceCancellation', 'CreditLifeInsuranceCancellation',
'RiskLifeInsuranceCancellation', 'MedLifeInsuranceCancellation')) s



INSERT INTO PAS_IMPL.CNL_APPLICANT_LINK (
	CNL_APPLICANT_HKEY,
	LOAD_DATE,
	RECORD_SOURCE,
	AMENDMENT_HKEY,
	PARTY_HKEY
)
SELECT CONVERT(CHAR(32), HashBytes('MD5', CONVERT(VARBINARY(MAX), sys_impl.NCharToUTF8Binary(CONCAT_WS(':', s.AMENDMENT_NUMBER, pHub.PARTY_CODE ), NULL))), 2) AS CNL_APPLICANT_HKEY,
	   s.LOAD_DATE,
	   s.RECORD_SOURCE,
	   s.AMENDMENT_HKEY,
	   pHub.PARTY_HKEY
FROM
(SELECT GETDATE() AS LOAD_DATE,
	   N'ADINSURE' AS RECORD_SOURCE,
	   hub.AMENDMENT_HKEY,
	   hub.AMENDMENT_NUMBER,
	   JSON_VALUE(ctr.BODY, '$.basicAmendmentConditions.applicant.partyCode') AS APPLICANT_CODE
FROM PAS_IMPL.AMENDMENT_HUB hub
JOIN PAS.CONTRACT ctr ON ctr.CONTRACT_NUMBER = hub.AMENDMENT_NUMBER
JOIN CFX.PUBLISHED_ARTIFACT art on ctr.PUBLISHED_ARTIFACT_ID = art.PUBLISHED_ARTIFACT_ID
WHERE art.CODE_NAME IN ('AccumulatedLifeInsuranceCancellation', 'InvestmentLifeInsuranceCancellation', 'CreditLifeInsuranceCancellation',
'RiskLifeInsuranceCancellation', 'MedLifeInsuranceCancellation')) s
JOIN PTY_IMPL.PARTY_HUB pHub ON pHub.PARTY_CODE = s.APPLICANT_CODE



INSERT INTO PAS_IMPL.CNL_APPLICANT_SAT (
	CNL_APPLICANT_HKEY,
	LOAD_DATE,
	RECORD_SOURCE,
	HASH_DIFF,
	RECEIVE_METHOD,
	RECEIVE_DATE,
	SIGN_DATE,
	IS_DELETED
)
SELECT rLink.CNL_APPLICANT_HKEY,
	   s.LOAD_DATE,
	   s.RECORD_SOURCE,
	   CONVERT(CHAR(32), HashBytes('MD5', CAST(newid() AS varbinary(max))), 2) AS HASH_DIFF,
	   s.RECEIVE_METHOD,
	   s.RECEIVE_DATE,
	   s.SIGN_DATE,
	   s.IS_DELETED
FROM
(SELECT GETDATE() AS LOAD_DATE,
	   N'ADINSURE' AS RECORD_SOURCE,
	   hub.AMENDMENT_HKEY,
	   JSON_VALUE(ctr.BODY, '$.basicAmendmentConditions.applicant.partyCode') AS APPLICANT_CODE,
	   JSON_VALUE(ctr.BODY, '$.basicAmendmentConditions.receiveMethod') AS RECEIVE_METHOD,
	   JSON_VALUE(ctr.BODY, '$.basicAmendmentConditions.applicationReceiveDate') AS RECEIVE_DATE,
	   JSON_VALUE(ctr.BODY, '$.basicAmendmentConditions.applicationSignDate') AS SIGN_DATE,
	   0 AS IS_DELETED
FROM PAS_IMPL.AMENDMENT_HUB hub
JOIN PAS.CONTRACT ctr ON ctr.CONTRACT_NUMBER = hub.AMENDMENT_NUMBER
JOIN CFX.PUBLISHED_ARTIFACT art on ctr.PUBLISHED_ARTIFACT_ID = art.PUBLISHED_ARTIFACT_ID
WHERE art.CODE_NAME IN ('AccumulatedLifeInsuranceCancellation', 'InvestmentLifeInsuranceCancellation', 'CreditLifeInsuranceCancellation',
'RiskLifeInsuranceCancellation', 'MedLifeInsuranceCancellation')) s
JOIN PTY_IMPL.PARTY_HUB pHub ON pHub.PARTY_CODE = s.APPLICANT_CODE
JOIN PAS_IMPL.CNL_APPLICANT_LINK rLink ON rLink.AMENDMENT_HKEY = s.AMENDMENT_HKEY AND rLink.PARTY_HKEY = pHub.PARTY_HKEY