BEGIN TRY
BEGIN TRAN

INSERT INTO UNI_IMPL.RQT_CHANGE_TYPE_SAT (
	RQT_CHANGE_TYPE_HKEY,
	LOAD_DATE,
	RECORD_SOURCE,
	HASH_DIFF,
	CODE
)
SELECT DISTINCT 
	rqtHub.RQT_HKEY,
	GETDATE() AS LOAD_DATE,
	N'ADINSURE' AS RECORD_SOURCE,
		CONVERT(
		CHAR(32),
		HashBytes('MD5', CAST(newid() AS varbinary(max))),
		2
	) AS HASH_DIFF,
	changeCodes.VALUE AS CODE
FROM 
	UNI_IMPL.RQT_HUB requestHub,
	bfx.UNIVERSAL_DOCUMENT ud
CROSS APPLY OPENJSON(
	JSON_QUERY(ud.body, '$.changeType')
) changeCodes
LEFT JOIN CFX.PUBLISHED_ARTIFACT pa ON pa.PUBLISHED_ARTIFACT_ID = ud.PUBLISHED_ARTIFACT_ID
LEFT JOIN UNI_IMPL.RQT_HUB rqtHub ON rqtHub.REQUEST_NUMBER = ud.UNIVERSAL_DOCUMENT_NUMBER
LEFT JOIN CFG.PROCESS_STATE ps ON ps.PROCESS_STATE_ID = ud.STATE_ID
WHERE ud.UNIVERSAL_DOCUMENT_NUMBER = requestHub.REQUEST_NUMBER
AND rqtHub.RQT_HKEY NOT IN (SELECT RQT_CHANGE_TYPE_HKEY FROM UNI_IMPL.RQT_CHANGE_TYPE_SAT)
AND pa.CODE_NAME = 'LifeInsuranceRequest'
ORDER BY rqtHub.RQT_HKEY

INSERT INTO UNI_IMPL.RQT_CHANGE_SUB_TYPE_SAT (
	RQT_CHANGE_SUB_TYPE_HKEY,
	LOAD_DATE,
	RECORD_SOURCE,
	HASH_DIFF,
	CODE
)
SELECT DISTINCT 
	rqtHub.RQT_HKEY,
	GETDATE() AS LOAD_DATE,
	N'ADINSURE' AS RECORD_SOURCE,
		CONVERT(
		CHAR(32),
		HashBytes('MD5', CAST(newid() AS varbinary(max))),
		2
	) AS HASH_DIFF,
	changeCodes.VALUE AS CODE
FROM 
	UNI_IMPL.RQT_HUB requestHub,
	bfx.UNIVERSAL_DOCUMENT ud
CROSS APPLY OPENJSON(
	JSON_QUERY(ud.body, '$.changeSubtype')
) changeCodes
LEFT JOIN CFX.PUBLISHED_ARTIFACT pa ON pa.PUBLISHED_ARTIFACT_ID = ud.PUBLISHED_ARTIFACT_ID
LEFT JOIN UNI_IMPL.RQT_HUB rqtHub ON rqtHub.REQUEST_NUMBER = ud.UNIVERSAL_DOCUMENT_NUMBER
LEFT JOIN CFG.PROCESS_STATE ps ON ps.PROCESS_STATE_ID = ud.STATE_ID
WHERE ud.UNIVERSAL_DOCUMENT_NUMBER = requestHub.REQUEST_NUMBER
AND rqtHub.RQT_HKEY NOT IN (SELECT RQT_CHANGE_SUB_TYPE_HKEY FROM UNI_IMPL.RQT_CHANGE_SUB_TYPE_SAT)
AND pa.CODE_NAME = 'LifeInsuranceRequest'
ORDER BY rqtHub.RQT_HKEY

INSERT INTO UNI_IMPL.RQT_CHANGE_CLASS_SAT (
	RQT_CHANGE_CLASS_HKEY,
	LOAD_DATE,
	RECORD_SOURCE,
	HASH_DIFF,
	CODE
)
SELECT DISTINCT 
	rqtHub.RQT_HKEY,
	GETDATE() AS LOAD_DATE,
	N'ADINSURE' AS RECORD_SOURCE,
		CONVERT(
		CHAR(32),
		HashBytes('MD5', CAST(newid() AS varbinary(max))),
		2
	) AS HASH_DIFF,
	changeCodes.VALUE AS CODE
FROM 
	UNI_IMPL.RQT_HUB requestHub,
	bfx.UNIVERSAL_DOCUMENT ud
CROSS APPLY OPENJSON(
	JSON_QUERY(ud.body, '$.changeClass')
) changeCodes
LEFT JOIN CFX.PUBLISHED_ARTIFACT pa ON pa.PUBLISHED_ARTIFACT_ID = ud.PUBLISHED_ARTIFACT_ID
LEFT JOIN UNI_IMPL.RQT_HUB rqtHub ON rqtHub.REQUEST_NUMBER = ud.UNIVERSAL_DOCUMENT_NUMBER
LEFT JOIN CFG.PROCESS_STATE ps ON ps.PROCESS_STATE_ID = ud.STATE_ID
WHERE ud.UNIVERSAL_DOCUMENT_NUMBER = requestHub.REQUEST_NUMBER
AND rqtHub.RQT_HKEY NOT IN (SELECT RQT_CHANGE_CLASS_HKEY FROM UNI_IMPL.RQT_CHANGE_CLASS_SAT)
AND pa.CODE_NAME = 'LifeInsuranceRequest'
ORDER BY rqtHub.RQT_HKEY

COMMIT TRAN
END TRY

BEGIN CATCH

    ROLLBACK TRAN
    DECLARE @ErrorMessage NVARCHAR(4000); DECLARE @ErrorSeverity INT; DECLARE @ErrorState INT;
    SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = 1;
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);

END CATCH
