CREATE TABLE PAS_IMPL.ADIRGSLSUPP_406_CNL_BACKUP (
DOC_ID UNIQUEIDENTIFIER,
DOC_NUMBER NVARCHAR(255) NOT NULL,
BODY NVARCHAR(MAX) NOT NULL,
CONSTRAINT ADIRGSLSUPP_406_BACKUP PRIMARY KEY (DOC_ID)
)


INSERT INTO PAS_IMPL.ADIRGSLSUPP_406_CNL_BACKUP(DOC_ID, DOC_NUMBER, BODY)
SELECT doc.CONTRACT_ID, doc.CONTRACT_NUMBER, doc.BODY
FROM PAS.CONTRACT doc
JOIN CFX.PUBLISHED_ARTIFACT art ON art.PUBLISHED_ARTIFACT_ID = doc.PUBLISHED_ARTIFACT_ID
WHERE art.CODE_NAME IN ('AccumulatedLifeInsuranceCancellation', 'CreditLifeInsuranceCancellation', 'EquityLifeInsuranceCancellation', 
'InvestmentLifeInsuranceCancellation', 'MedLifeInsuranceCancellation', 'RiskLifeInsuranceCancellation')