UPDATE bSat SET BANK_ACCOUNT_NUMBER = r.BANK_ACCOUNT_NUMBER
FROM CLM_IMPL.CLM_HUB cHub
INNER JOIN CLM.CLAIM clm ON clm.CLAIM_NUMBER = cHub.CLAIM_NUMBER
INNER JOIN CLM_IMPL.CLM_BENEFICIARY_LINK bLink on bLink.CLM_HKEY = cHub.CLM_HKEY
INNER JOIN PTY_IMPL.PARTY_HUB pHub on pHub.PARTY_HKEY = bLink.PARTY_HKEY
INNER JOIN CLM_IMPL.CLM_BENEFICIARY_SAT_LATEST bSat on bSat.CLM_BENEFICIARY_HKEY = bLink.CLM_BENEFICIARY_HKEY
CROSS APPLY OPENJSON(clm.BODY,'$.claimBeneficiaries')
 with  
 (    
     BENEFICIARY_PARTY_CODE NVARCHAR(50) N'lax $.partyCode',
	 AMOUNT_TO_PAY_DOC_CURR DECIMAL(15,7) N'lax $.amountToPay',
	 AMOUNT_TO_PAY_RUB_CURR DECIMAL(15,7) N'lax $.amountToPayInRubCurrency',
	 BANK_ACCOUNT_NUMBER NVARCHAR(100) N'lax $.bankAccount.number',
	 ASSIGNED_PO_NUMBER NVARCHAR(255) N'lax $.assignedPaymentOrderNumber'
 ) r
WHERE 
pHub.PARTY_CODE = r.BENEFICIARY_PARTY_CODE 
AND r.ASSIGNED_PO_NUMBER = bSat.ASSIGNED_PO_NUMBER
AND bSat.IS_DELETED = 0