IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[AA_BACKUP]') AND TYPE IN (N'U'))
BEGIN
	CREATE TABLE [PAS_IMPL].[AA_BACKUP](
	[AGENT_AGREEMENT_ID] [UNIQUEIDENTIFIER] NOT NULL,
	[BODY] [NVARCHAR](MAX) NOT NULL,
	[COMMON_BODY] [NVARCHAR](MAX) NOT NULL,
	[SNAPSHOT_BODY] [NVARCHAR](MAX) NOT NULL
)
END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[AA_BACKUP]') AND TYPE IN (N'U'))
BEGIN
	INSERT INTO [PAS_IMPL].[AA_BACKUP] ([AGENT_AGREEMENT_ID], [BODY], [COMMON_BODY], [SNAPSHOT_BODY])
	SELECT aa.AGENT_AGREEMENT_ID, aa.BODY, aa.COMMON_BODY, aa.SNAPSHOT_BODY
	FROM PAS.AGENT_AGREEMENT aa
END
GO
