BEGIN TRY
BEGIN TRAN

UPDATE EWT_IMPL.EWT_SAT
SET CONTRACT_NUMBER = c.CONTRACT_NUMBER,
	CONTRACT_HOLDER_NAME = psl.HOLDER_NAME,
	CONTRACT_CONF_CODE_NAME = pa.CODE_NAME
FROM EWT_IMPL.EWT_SAT ewtSat
LEFT JOIN EWT_IMPL.EWT_HUB ewtHub ON ewtHub.EWT_HKEY = ewtSat.EWT_HKEY
LEFT JOIN BFX.UNIVERSAL_DOCUMENT ud ON ud.UNIVERSAL_DOCUMENT_NUMBER = ewtHub.ENDOWMENT_NUMBER
LEFT JOIN PAS.CONTRACT c ON c.CONTRACT_NUMBER = JSON_VALUE(ud.BODY, '$.mainAttributes.contract.number')
LEFT JOIN CFX.PUBLISHED_ARTIFACT pa on pa.PUBLISHED_ARTIFACT_ID = c.PUBLISHED_ARTIFACT_ID
LEFT JOIN PAS_IMPL.POLICY_HUB ph ON ph.CONTRACT_NUMBER = c.CONTRACT_NUMBER
LEFT JOIN PAS_IMPL.POLICY_SAT_LATEST psl ON psl.POLICY_HKEY = ph.POLICY_HKEY

COMMIT TRAN
END TRY

BEGIN CATCH

    ROLLBACK TRAN
    DECLARE @ErrorMessage NVARCHAR(4000); DECLARE @ErrorSeverity INT; DECLARE @ErrorState INT;
    SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = 1;
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);

END CATCH
