IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS].[CONTRACT_PARTNER_BACKUP]') AND TYPE IN (N'U'))
BEGIN
	DROP TABLE PAS.CONTRACT_PARTNER_BACKUP
END

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX].[UNIVERSAL_DOCUMENT_PARTNER_BACKUP]') AND TYPE IN (N'U'))
BEGIN
	DROP TABLE BFX.UNIVERSAL_DOCUMENT_PARTNER_BACKUP
END