IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS].[CONTRACT]') AND TYPE IN (N'U'))
BEGIN

	IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[CONTRACT_SAD_ADDING_BACKUP]') AND TYPE IN (N'U'))
	BEGIN
		DROP TABLE PAS_IMPL.CONTRACT_SAD_ADDING_BACKUP
	END

	SELECT CONTRACT_NUMBER, BODY, COMMON_BODY
	INTO PAS_IMPL.CONTRACT_SAD_ADDING_BACKUP
	FROM PAS.CONTRACT;

END;
GO
