IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ARCHIVE_ETL_EXECUTION_STATUS]') AND type IN (N'P', N'RF', N'PC'))
BEGIN
DROP PROCEDURE dbo.ARCHIVE_ETL_EXECUTION_STATUS;
END
GO

CREATE PROCEDURE ARCHIVE_ETL_EXECUTION_STATUS
AS
BEGIN TRY
begin tran

	INSERT INTO BFX_IMPL.ETL_EXECUTION_STATUS_ARCH
	SELECT * FROM BFX.ETL_EXECUTION_STATUS
	WHERE STATUS = 2 and SYS_CREATED_ON < dateadd(month, -1, getdate())

    DELETE FROM BFX.ETL_EXECUTION_STATUS
	WHERE STATUS = 2 and SYS_CREATED_ON < dateadd(month, -1, getdate())

commit tran
END TRY
BEGIN CATCH
    ROLLBACK tran
    DECLARE @ErrorMessage NVARCHAR(4000); DECLARE @ErrorSeverity INT; DECLARE @ErrorState INT;
    SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = 1;
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState );
END CATCH;
GO