UPDATE c
SET c.BODY= JSON_MODIFY(c.BODY, '$.initiator.sadNumber', agl.SAD_NUMBER)
FROM pas.CONTRACT c
	INNER JOIN ORG.SERVICE_PROVIDER sp ON JSON_VALUE(c.body, '$.initiator.employeeCode') = sp.SERVICE_PROVIDER_CODE
	INNER JOIN ORG_IMPL.SERVICE_PROVIDER_HUB ph ON sp.SERVICE_PROVIDER_CODE= ph.SERVICE_PROVIDER_CODE
	INNER JOIN ORG_IMPL.SP_SUB_AGENT_SAT_LATEST agl ON agl.SP_SUB_AGENT_HKEY = ph.SERVICE_PROVIDER_HKEY
WHERE JSON_VALUE(c.body, '$.initiator.employeeCode') IS NOT NULL;
GO
