BEGIN TRY
BEGIN TRAN

DECLARE @CurrentAttrValues TABLE
(
   COMM_TYPE_ID NVARCHAR(500),
   ATTR_VALUE NVARCHAR(150),
   RULE_NUM INT,
   LOAD_DATE DATETIME2
);


INSERT INTO @CurrentAttrValues

SELECT comm.AA_BASE_COMM_HKEY, comm.PREMIUM_PERIOD_TYPE, comm.RULE_NUM, comm.LOAD_DATE 
FROM pas.AA_HUB hub
JOIN pas.AA_COMM_LINK link ON hub.AA_HKEY = link.AA_HKEY
JOIN pas_impl.AA_BASE_COMM_SAT comm ON link.AA_COMM_HKEY = comm.AA_BASE_COMM_HKEY
WHERE comm.PREMIUM_PERIOD_TYPE IS NOT NULL AND comm.PREM_PERIOD_VALUE_REF_ID IS NULL

DECLARE @CommTypeId NVARCHAR(500), @AttrValue BIGINT, @RefId BIGINT, @RuleNumber INT, @RuleDate DATETIME2

DECLARE AA_CURSOR CURSOR LOCAL READ_ONLY FORWARD_ONLY
FOR 

SELECT COMM_TYPE_ID,
	   ATTR_VALUE,
	   RULE_NUM,
	   LOAD_DATE
FROM @CurrentAttrValues

OPEN AA_CURSOR
FETCH NEXT FROM AA_CURSOR INTO @CommTypeId, @AttrValue, @RuleNumber, @RuleDate
WHILE @@FETCH_STATUS = 0

BEGIN 

	EXEC dbo.SEQ_BIG_NEXTVAL @SEQ = 'PAS_IMPL.AA_EVAL_ATTR_VALUE', @SEQ_ID = @RefId OUTPUT

	UPDATE pas_impl.AA_BASE_COMM_SAT SET PREM_PERIOD_VALUE_REF_ID = @RefId WHERE AA_BASE_COMM_HKEY =  @CommTypeId AND RULE_NUM = @RuleNumber AND LOAD_DATE = @RuleDate
	INSERT INTO PAS_IMPL.AA_EVAL_ATTR_VALUE (EVAL_ATTR_VALUE_ID, VALUE_REF_ID, STRING_VALUE) VALUES (NEWID(), @RefId, @AttrValue)

	FETCH NEXT FROM AA_CURSOR INTO @CommTypeId, @AttrValue, @RuleNumber, @RuleDate

END

CLOSE AA_CURSOR
DEALLOCATE AA_CURSOR

COMMIT TRAN

END TRY

BEGIN CATCH

    ROLLBACK TRAN
    DECLARE @ErrorMessage NVARCHAR(4000); DECLARE @ErrorSeverity INT; DECLARE @ErrorState INT;
    SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = 1;
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);

END CATCH