IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[UNI_IMPL].[RQT_CONTRACT_LINK]') AND TYPE IN (N'U'))
BEGIN
DELETE FROM UNI_IMPL.RQT_CONTRACT_LINK
END
GO

BEGIN TRY
BEGIN TRAN

INSERT INTO UNI_IMPL.RQT_CONTRACT_LINK (
	RQT_CONTRACT_HKEY,
	LOAD_DATE,
	RECORD_SOURCE,
	RQT_HKEY,
	POLICY_HKEY
)
SELECT DISTINCT 
	CONVERT(CHAR(32), HashBytes('MD5', sys_impl.NCharToUTF8Binary(CONCAT_WS(':', rqtHub.REQUEST_NUMBER, policyHub.CONTRACT_NUMBER ), null)), 2)  AS RQT_APPLICANT_HKEY,
	GETDATE() AS LOAD_DATE,
	N'ADINSURE' AS RECORD_SOURCE,
	rqtHub.RQT_HKEY AS RQT_HKEY,
	policyHub.POLICY_HKEY AS POLICY_HKEY
FROM UNI_IMPL.RQT_HUB rqtHub
LEFT JOIN UNI_IMPL.RQT_SAT rqtSat ON rqtSat.RQT_HKEY = rqtHub.RQT_HKEY
LEFT JOIN PAS_IMPL.POLICY_HUB policyHub ON policyHub.CONTRACT_NUMBER = rqtSat.CONTRACT_NUMBER
WHERE policyHub.POLICY_HKEY IS NOT NULL AND rqtHub.RQT_HKEY IS NOT NULL
AND rqtHub.RQT_HKEY NOT IN (SELECT RQT_HKEY FROM UNI_IMPL.RQT_CONTRACT_LINK)

COMMIT TRAN
END TRY

BEGIN CATCH

    ROLLBACK TRAN
    DECLARE @ErrorMessage NVARCHAR(4000); DECLARE @ErrorSeverity INT; DECLARE @ErrorState INT;
    SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = 1;
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);

END CATCH
