insert into PAS_IMPL.POLICY_INVESTMENT_SAT
(
    POLICY_INVESTMENT_HKEY,
    RECORD_SOURCE,
    HASH_DIFF,
    LOAD_DATE,
    STRATEGY_CODE,
    STRATEGY_DESCRIPTION,
    RATE_OF_RETURN,
    RATE_OF_RETURN_MANUAL_RATE,
    VARIANT_CODE,
    VARIANT_DESCRIPTION,
    STRATEGY_DESCRIPTION_FULL,
    CASHBACK,
    PAYOFF_DESCRIPTION,
    IS_MANUAL_SET_INV_PARAMS,
    BASE_ACTIVE_DESCRIPTION,
    PARTICIPATION_COEFF,
    OPTION_PRICE,
    BARRIER,
    BARRIER_AUTO_CALL,
    PARTICIPATION_COEFF_BY_PERIODS,
    PURCHASE_DATE,
    EMITENT,
    FIX_RATE,
    INITIAL_SHARE,
    HEDGE_COST,
    SPREAD_BA,
    PAY_OFF_SHORT_DESCRIPTION,
    TOOL_TYPE,
    MEASURE_TOOL_NOMINAL,
    CALCULATING_AGENT,
    PRICE_OF_MEASURE_TOOL,
    PART_OF_PREMIUM_FOR_TOOL,
    DISCOUNT,
    DISCHARGE_DATE,
    DID_BEGIN_DATE,
    DID_END_DATE,
    WINDOW_START_DATE,
    WINDOW_START_END,
    FUTURE_CONTRACT_NUMBER
)
select
    ph.POLICY_HKEY,
    N'ADINSURE' AS RECORD_SOURCE,
    CONVERT(
		CHAR(32),
		HashBytes('MD5', CAST(newid() AS varbinary(max))),
		2
	) AS HASH_DIFF,
    GETDATE() AS LOAD_DATE,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.investmentStrategy.investmentStrategyCode') investmentStrategyCode,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.investmentStrategy.investmentStrategyDescription') investmentStrategyDescription,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.rateOfReturn') rateOfReturn,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.rateOfReturnManualRate') rateOfReturnManualRate,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.variant.variantCode') variantCode,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.variant.variantDescription') variantDescription,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.investmentStrategyDescriptionFull') investmentStrategyDescriptionFull,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.cashback') cashback,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.payOffDescription') payOffDescription,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.isManualSetInvestmentParams') isManualSetInvestmentParams,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.baseActiveDescription') baseActiveDescription,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.participationCoeff') participationCoeff,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.optionPrice') optionPrice,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.barrier') barrier,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.barrierAutoCall') barrierAutoCall,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.participationCoeffByPeriods') participationCoeffByPeriods,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.purchaseDate') purchaseDate,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.emitent') emitent,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.fixRate') fixRate,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.intialShare') intialShare,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.hedgeCost') hedgeCost,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.spreadBA') spreadBA,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.payOffShortDescription') payOffShortDescription,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.toolType') toolType,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.measureToolNominal') measureToolNominal,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.calculatingAgent') calculatingAgent,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.priceOfMeasureTool') priceOfMeasureTool,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.partOfPremiumForTool') partOfPremiumForTool,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.discount') discount,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.dischargeDate') dischargeDate,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.didBeginDate') didBeginDate,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.didEndDate') didEndDate,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.windowStartDate') windowStartDate,
    JSON_VALUE(c.BODY, '$.basicInvestmentParameters.windowEndDate') windowEndDate,
    JSON_VALUE(c.BODY, '$.technicalInformation.futureContractNumber') futureContractNumber
from
  PAS.CONTRACT c,
  CFX.PUBLISHED_ARTIFACT art,
  PAS_IMPL.POLICY_HUB ph
where c.PUBLISHED_ARTIFACT_ID = art.PUBLISHED_ARTIFACT_ID
  and c.CONTRACT_NUMBER = ph.CONTRACT_NUMBER