IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[QUOTE_SAT]') AND TYPE IN (N'U'))
BEGIN

	IF COL_LENGTH('PAS_IMPL.QUOTE_SAT','GUARANTEE_INCOME_CODE') IS NOT NULL
	BEGIN

		UPDATE qs
		SET qs.GUARANTEE_INCOME_CODE = JSON_VALUE(c.body, '$.basicConditions.guaranteedIncome.guaranteedIncomeCode')
		FROM PAS_IMPL.QUOTE_SAT qs
		JOIN PAS_IMPL.QUOTE_HUB qh on qh.QUOTE_HKEY = qs.QUOTE_HKEY
		JOIN PAS.CONTRACT c on c.CONTRACT_NUMBER = qh.CONTRACT_NUMBER

	END

END
GO
