---Создание таблицы бэкапа убытков
CREATE TABLE CLM_IMPL.ADIRGSL_2922_CLM_BACKUP (
CLAIM_ID UNIQUEIDENTIFIER,
CLAIM_NUMBER NVARCHAR(255) NOT NULL,
BODY NVARCHAR(MAX) NOT NULL,
COMMON_BODY NVARCHAR(MAX) NOT NULL,
CONSTRAINT ADIRGSL_3043_BCKUP PRIMARY KEY (CLAIM_ID)
)

--Заполнение таблицы бэкапов убытков
INSERT INTO CLM_IMPL.ADIRGSL_2922_CLM_BACKUP(CLAIM_ID, CLAIM_NUMBER, BODY, COMMON_BODY)
SELECT clm.CLAIM_ID, clm.CLAIM_NUMBER, clm.BODY, clm.COMMON_BODY
FROM CLM.CLAIM clm