UPDATE sat set sat.EXCHANGE_RATE = JSON_VALUE(ctr.BODY, '$.basicConditions.exchangeRate')
FROM PAS.CONTRACT ctr
JOIN CFX.PUBLISHED_ARTIFACT art ON art.PUBLISHED_ARTIFACT_ID = ctr.PUBLISHED_ARTIFACT_ID AND art.CODE_NAME = 'CollectiveLifeInsurancePolicy'
JOIN PAS_IMPL.POLICY_HUB hub ON hub.CONTRACT_NUMBER = ctr.CONTRACT_NUMBER
JOIN PAS_IMPL.POLICY_SAT_LATEST sat ON sat.POLICY_HKEY = hub.POLICY_HKEY
WHERE sat.EXCHANGE_RATE IS NULL AND JSON_VALUE(ctr.BODY, '$.basicConditions.exchangeRate') IS NOT NULL