IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[CONTRACT_EMPTY_BODY_UPDATE_INFO]') AND TYPE IN (N'U'))
BEGIN
	CREATE TABLE PAS_IMPL.CONTRACT_EMPTY_BODY_UPDATE_INFO
	(
		[ID] [int] IDENTITY(1,1) PRIMARY KEY,
		[CONTRACT_NUMBER] [nvarchar](64) NOT NULL,
		[IS_UPDATED] [bit] NOT NULL,
		[INFO] [nvarchar](MAX) NULL,
		[DATE] datetime NOT NULL
	)

	CREATE INDEX IX_CONTRACT_EMPTY_BODY_UPDATE_INFO_CONTRACT_NUMBER
	ON PAS_IMPL.CONTRACT_EMPTY_BODY_UPDATE_INFO
	(CONTRACT_NUMBER)
END

DROP INDEX IF EXISTS IX_CEBTU_CONTRACT_NUMBER ON #CONTRACT_EMPTY_BODY_TO_UPDATE;
DROP TABLE IF EXISTS #CONTRACT_EMPTY_BODY_TO_UPDATE

SELECT
	c.CONTRACT_NUMBER
INTO #CONTRACT_EMPTY_BODY_TO_UPDATE
FROM PAS.CONTRACT c
LEFT JOIN PAS_IMPL.CONTRACT_EMPTY_BODY_UPDATE_INFO cbui ON cbui.CONTRACT_NUMBER = c.CONTRACT_NUMBER
WHERE BODY = '{}'

CREATE INDEX IX_CEBTU_CONTRACT_NUMBER ON #CONTRACT_EMPTY_BODY_TO_UPDATE(CONTRACT_NUMBER);

DECLARE @originalBody NVARCHAR(MAX)
DECLARE @contractNumber NVARCHAR(255)

DECLARE cur CURSOR FORWARD_ONLY FOR
SELECT cebtu.CONTRACT_NUMBER
FROM #CONTRACT_EMPTY_BODY_TO_UPDATE cebtu

OPEN cur
FETCH NEXT FROM cur INTO @contractNumber
WHILE @@fetch_status = 0

BEGIN

	BEGIN TRY
		BEGIN TRAN

			SET @originalBody = (
				SELECT
					BODY
				FROM PAS.CONTRACT
				WHERE CONTRACT_ID = (SELECT ORIGINAL_DOCUMENT_ID FROM PAS.CONTRACT WHERE CONTRACT_NUMBER = @contractNumber)
			);

			UPDATE PAS.CONTRACT
			SET BODY = JSON_QUERY(@originalBody),
				SNAPSHOT_BODY = JSON_QUERY(@originalBody)
			WHERE CONTRACT_NUMBER = @contractNumber

			INSERT INTO PAS_IMPL.CONTRACT_EMPTY_BODY_UPDATE_INFO (CONTRACT_NUMBER, IS_UPDATED, INFO, DATE)
				SELECT
					@contractNumber,
					1,
					NULL,
					GETDATE()

		COMMIT TRAN
	END TRY

	BEGIN CATCH
    ROLLBACK TRAN
    PRINT @contractNumber
    DECLARE @ErrorMessage NVARCHAR(4000); DECLARE @ErrorSeverity INT; DECLARE @ErrorState INT;
    SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = 1;

    UPDATE PAS_IMPL.CONTRACT_EMPTY_BODY_UPDATE_INFO
    SET INFO = CONCAT('ErrorMessage:',@ErrorMessage, ' ErrorSeverity:', @ErrorSeverity, '. ErrorState:', @ErrorState, '.'),
		IS_UPDATED = NULL
    WHERE CONTRACT_NUMBER = @contractNumber

    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
	END CATCH;

	FETCH NEXT FROM cur INTO @contractNumber

END
CLOSE cur
DEALLOCATE cur

DROP INDEX IF EXISTS IX_CEBTU_CONTRACT_NUMBER ON #CONTRACT_EMPTY_BODY_TO_UPDATE;
DROP TABLE IF EXISTS #CONTRACT_EMPTY_BODY_TO_UPDATE
