IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[CONTRACT_INVESTMENT_BACKUP]') AND TYPE IN (N'U'))
BEGIN
	UPDATE c
	SET c.BODY = JSON_MODIFY(c.BODY, '$.basicInvestmentParameters.barrierAutoCall', JSON_VALUE(b.BODY, '$.basicInvestmentParameters.barrierAutoCall'))
	FROM PAS.CONTRACT c
	INNER JOIN [PAS_IMPL].[CONTRACT_INVESTMENT_BACKUP] b 
		ON c.CONTRACT_ID = b.CONTRACT_ID
END
GO
