-- Clean list of economic parameters (ASS)
DROP TABLE UNIV_IMPL.PRODUCT_CONF_HUB
DROP TABLE UNIV_IMPL.PRODUCT_CONF_SAT
DROP VIEW UNIV_IMPL.PRODUCT_CONF_SAT_LATEST

DROP TABLE UNIV_IMPL.ECONOMIC_PARAMETER_HUB
DROP TABLE UNIV_IMPL.ECONOMIC_PARAMETER_SAT
DROP VIEW UNIV_IMPL.ECONOMIC_PARAMETER_SAT_LATEST

-- Clean additional parameters for contracts (ASS)
DROP TABLE BFX_IMPL.ADDITIONAL_PARAMETERS_HUB
DROP TABLE BFX_IMPL.ADDITIONAL_PARAMETERS_SAT
DROP TABLE BFX_IMPL.ADDITIONAL_PARAMETERS_POLICY_LINK
DROP TABLE BFX_IMPL.ADDITIONAL_PARAMETERS_QUOTE_LINK
DROP VIEW BFX_IMPL.ADDITIONAL_PARAMETERS_SAT_LATEST