IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ARCHIVE_NOTIFICATION_MAILBOX]') AND type IN (N'P', N'RF', N'PC'))
BEGIN
DROP PROCEDURE dbo.ARCHIVE_NOTIFICATION_MAILBOX;
END
GO

CREATE PROCEDURE ARCHIVE_NOTIFICATION_MAILBOX
AS
BEGIN TRY
begin tran

	INSERT INTO BFX_IMPL.NOTIFICATION_MAILBOX_ARCH
	SELECT * FROM BFX.NOTIFICATION_MAILBOX 
	WHERE (IS_SYSTEM_NOTIFICATION = 1 and NOTIFICATION_END_TIME < getdate()) 
	   OR (IS_SYSTEM_NOTIFICATION = 0 and NOTIFICATION_STATE = 'Read' and NOTIFICATION_CREATED_ON < dateadd(month, -1, getdate()))

	DELETE FROM BFX.NOTIFICATION_MAILBOX 
	WHERE (IS_SYSTEM_NOTIFICATION = 1 and NOTIFICATION_END_TIME < getdate()) 
	   OR (IS_SYSTEM_NOTIFICATION = 0 and NOTIFICATION_STATE = 'Read' and NOTIFICATION_CREATED_ON < dateadd(month, -1, getdate()))

commit tran
END TRY
BEGIN CATCH
    ROLLBACK tran
    DECLARE @ErrorMessage NVARCHAR(4000); DECLARE @ErrorSeverity INT; DECLARE @ErrorState INT;
    SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = 1;
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState );
END CATCH;
GO