SELECT DISTINCT pdi.PARTY_CODE, pdi.DEDUPL_NUMBER
INTO #tempQouteInsuredCodesToUpdate
FROM PTY_IMPL.PARTY_DEDUP_INFO pdi
LEFT JOIN PAS_IMPL.QUOTE_SAT qs ON qs.INSURED_CODE = pdi.PARTY_CODE
WHERE pdi.IS_PROCESSED = 1 AND qs.INSURED_CODE != pdi.DEDUPL_NUMBER

UPDATE qs
SET INSURED_CODE = t1.DEDUPL_NUMBER
FROM PAS_IMPL.QUOTE_SAT qs
LEFT JOIN #tempQouteInsuredCodesToUpdate t1 ON t1.PARTY_CODE = qs.INSURED_CODE
WHERE t1.PARTY_CODE = qs.INSURED_CODE

DROP TABLE #tempQouteInsuredCodesToUpdate
