UPDATE PAS_IMPL.QUOTE_RISKS_SAT
SET INSURED_SUM_WITHOUT_CASHBACK = INSURED_SUM
WHERE INSURED_SUM_WITHOUT_CASHBACK IS NULL

UPDATE PAS_IMPL.POLICY_RISKS_SAT
SET INSURED_SUM_WITHOUT_CASHBACK = INSURED_SUM
WHERE INSURED_SUM_WITHOUT_CASHBACK IS NULL
