DECLARE @CTE_TABLE TABLE(
    CONTRACT_NUMBER NVARCHAR(50),
    CONSENT_FNS BIT
)

;WITH UD_CTE(CONTRACT_NUMBER, CONSENT_FNS) AS(
	select DISTINCT c.CONTRACT_NUMBER, cast(JSON_VALUE(c.BODY, '$.consent.consentToDataTransferingFNS') as bit) as CONSENT_FNS
	from [PAS].[CONTRACT] C
	  JOIN [PAS_IMPL].[POLICY_HUB] PH ON C.CONTRACT_NUMBER = PH.CONTRACT_NUMBER
	  JOIN [PAS_IMPL].[POLICY_SAT_LATEST] PSL ON PH.[POLICY_HKEY] = PSL.POLICY_HKEY
	  JOIN BFX.UNIVERSAL_VERSIONED_DOCUMENT ud on JSON_VALUE(ud.BODY, '$.contract.number') = C.CONTRACT_NUMBER
	  AND ud.STATE_ID = 1
	  WHERE (PSL.STATE = 'Activated'
		OR PSL.STATE = 'Active')
		AND psl.START_DATE >= '2024-10-10'
		AND psl.INSURANCE_TERMS >= 5
		AND psl.PRODUCT_CODE in (select PRODUCT_CODE FROM [BFX_IMPL].[PRODUCT_CONF] WHERE [CONSENT_TO_DATA_TRANSFERING_FNS] = 1)
	  )

INSERT INTO @CTE_TABLE
SELECT CONTRACT_NUMBER, CONSENT_FNS
FROM UD_CTE

UPDATE BFX.UNIVERSAL_VERSIONED_DOCUMENT
SET BODY = JSON_MODIFY(ud.BODY, '$.contract.isInsurerSendDataToFns', cast(1 as bit))
FROM BFX.UNIVERSAL_VERSIONED_DOCUMENT ud
INNER JOIN CFG.PROCESS_STATE ps
	ON ps.PROCESS_STATE_ID = ud.STATE_ID
WHERE JSON_VALUE(ud.BODY, '$.contract.number') IN (
		SELECT CONTRACT_NUMBER
		FROM @CTE_TABLE
		WHERE CONSENT_FNS = 1)
	AND ps.CODE_NAME = 'Draft'

UPDATE BFX.UNIVERSAL_VERSIONED_DOCUMENT
SET ud.SNAPSHOT_BODY = JSON_MODIFY(ud.SNAPSHOT_BODY, '$.contract.isInsurerSendDataToFns', cast(1 as bit))
FROM BFX.UNIVERSAL_VERSIONED_DOCUMENT ud
INNER JOIN CFG.PROCESS_STATE ps
	ON ps.PROCESS_STATE_ID = ud.STATE_ID
WHERE JSON_VALUE(ud.SNAPSHOT_BODY, '$.contract.number') IN (
		SELECT CONTRACT_NUMBER
		FROM @CTE_TABLE
		WHERE CONSENT_FNS = 1)
	AND ps.CODE_NAME = 'Draft'

UPDATE ACC_IMPL.CRT_SAT
SET IS_INSURER_SEND_DATA_TO_FNS = CAST(1 as bit)
FROM ACC_IMPL.CRT_SAT sat
INNER JOIN ACC_IMPL.CRT_HUB hub
	ON hub.CRT_HKEY = sat.CRT_HKEY
INNER JOIN ACC_IMPL.CRT_SAT_LATEST satl
	ON satl.CRT_HKEY = sat.CRT_HKEY
INNER JOIN bfx.UNIVERSAL_VERSIONED_DOCUMENT ud
	ON ud.UNIVERSAL_VERSIONED_DOCUMENT_NUMBER = hub.CERTIFICATE_NUMBER
INNER JOIN CFG.PROCESS_STATE ps
	ON ps.PROCESS_STATE_ID = ud.STATE_ID
WHERE sat.CONTRACT_NUMBER IN (
		SELECT CONTRACT_NUMBER
		FROM @CTE_TABLE
		WHERE CONSENT_FNS = 1)
	AND ps.CODE_NAME = 'Draft'
GO