IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_CLM_APPLICANT_SAT_STATEMENT_RECEIVED_DATE'
	AND object_id = OBJECT_ID('CLM_IMPL.CLM_APPLICANT_SAT') ) BEGIN
	CREATE INDEX IDX_CLM_APPLICANT_SAT_STATEMENT_RECEIVED_DATE ON
CLM_IMPL.CLM_APPLICANT_SAT(STATEMENT_RECEIVED_DATE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_CLM_APPLICANT_SAT_STATEMENT_APPLICATION_DATE'
	AND object_id = OBJECT_ID('CLM_IMPL.CLM_APPLICANT_SAT') ) BEGIN
	CREATE INDEX IDX_CLM_APPLICANT_SAT_STATEMENT_APPLICATION_DATE ON
CLM_IMPL.CLM_APPLICANT_SAT(STATEMENT_APPLICATION_DATE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_CLM_APPLICANT_SAT_IS_DELETED'
	AND object_id = OBJECT_ID('CLM_IMPL.CLM_APPLICANT_SAT') ) BEGIN
	CREATE INDEX IDX_CLM_APPLICANT_SAT_IS_DELETED ON
CLM_IMPL.CLM_APPLICANT_SAT(IS_DELETED)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_CLM_BENEFICIARY_SAT_SAT_REASON_CODE'
	AND object_id = OBJECT_ID('CLM_IMPL.CLM_BENEFICIARY_SAT') ) BEGIN
	CREATE INDEX IDX_CLM_CLM_BENEFICIARY_SAT_REASON_CODE ON
CLM_IMPL.CLM_BENEFICIARY_SAT(REASON_CODE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_CLM_BENEFICIARY_SAT_PAYMENT_TYPE_CODE'
	AND object_id = OBJECT_ID('CLM_IMPL.CLM_BENEFICIARY_SAT') ) BEGIN
	CREATE INDEX IDX_CLM_BENEFICIARY_SAT_PAYMENT_TYPE_CODE ON
CLM_IMPL.CLM_BENEFICIARY_SAT(PAYMENT_TYPE_CODE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_CLM_BENEFICIARY_SAT_IS_DELETED'
	AND object_id = OBJECT_ID('CLM_IMPL.CLM_BENEFICIARY_SAT') ) BEGIN
	CREATE INDEX IDX_CLM_BENEFICIARY_SAT_IS_DELETED ON
CLM_IMPL.CLM_BENEFICIARY_SAT(IS_DELETED)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_CLM_IE_SAT_CONTRACT_CURRENCY'
	AND object_id = OBJECT_ID('CLM_IMPL.CLM_IE_SAT') ) BEGIN
	CREATE INDEX IDX_CLM_IE_SAT_CONTRACT_CURRENCY ON
CLM_IMPL.CLM_IE_SAT(CONTRACT_CURRENCY)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_CLM_IE_SAT_IS_DELETED'
	AND object_id = OBJECT_ID('CLM_IMPL.CLM_IE_SAT') ) BEGIN
	CREATE INDEX IDX_CLM_IE_SAT_IS_DELETED ON
CLM_IMPL.CLM_IE_SAT(IS_DELETED)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_CLM_INJURY_SAT_CODE'
	AND object_id = OBJECT_ID('CLM_IMPL.CLM_INJURY_SAT') ) BEGIN
	CREATE INDEX IDX_CLM_INJURY_SAT_CODE ON
CLM_IMPL.CLM_INJURY_SAT(CODE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_CLM_INJURY_SAT_GROUP_CODE'
	AND object_id = OBJECT_ID('CLM_IMPL.CLM_INJURY_SAT') ) BEGIN
	CREATE INDEX IDX_CLM_INJURY_SAT_GROUP_CODE ON
CLM_IMPL.CLM_INJURY_SAT(GROUP_CODE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_CLM_INJURY_SAT_SUBGROUP_CODE'
	AND object_id = OBJECT_ID('CLM_IMPL.CLM_INJURY_SAT') ) BEGIN
	CREATE INDEX IDX_CLM_INJURY_SAT_SUBGROUP_CODE ON
CLM_IMPL.CLM_INJURY_SAT(SUBGROUP_CODE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_CLM_INJURY_SAT_IS_DELETED'
	AND object_id = OBJECT_ID('CLM_IMPL.CLM_INJURY_SAT') ) BEGIN
	CREATE INDEX IDX_CLM_INJURY_SAT_IS_DELETED ON
CLM_IMPL.CLM_INJURY_SAT(IS_DELETED)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_IE_CONTRACT_SAT_IS_DELETED'
	AND object_id = OBJECT_ID('CLM_IMPL.IE_CONTRACT_SAT') ) BEGIN
	CREATE INDEX IDX_IE_CONTRACT_SAT_IS_DELETED ON
CLM_IMPL.IE_CONTRACT_SAT(IS_DELETED)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_CLM_RISK_SAT_CODE'
	AND object_id = OBJECT_ID('CLM_IMPL.CLM_RISK_SAT') ) BEGIN
	CREATE INDEX IDX_CLM_RISK_SAT_CODE ON
CLM_IMPL.CLM_RISK_SAT(CODE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_CLM_RISK_SAT_BUSINESS_LINE'
	AND object_id = OBJECT_ID('CLM_IMPL.CLM_RISK_SAT') ) BEGIN
	CREATE INDEX IDX_CLM_RISK_SAT_BUSINESS_LINE ON
CLM_IMPL.CLM_RISK_SAT(BUSINESS_LINE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_CLM_RISK_SAT_DISABILITY_GROUP'
	AND object_id = OBJECT_ID('CLM_IMPL.CLM_RISK_SAT') ) BEGIN
	CREATE INDEX IDX_CLM_RISK_SAT_DISABILITY_GROUP ON
CLM_IMPL.CLM_RISK_SAT(DISABILITY_GROUP)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_CLM_SAT_CLAIM_STATE'
	AND object_id = OBJECT_ID('CLM_IMPL.CLM_SAT') ) BEGIN
	CREATE INDEX IDX_CLM_SAT_CLAIM_STATE ON
CLM_IMPL.CLM_SAT(CLAIM_STATE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_CLM_SAT_REJECTION_REASON_CODE'
	AND object_id = OBJECT_ID('CLM_IMPL.CLM_SAT') ) BEGIN
	CREATE INDEX IDX_CLM_SAT_REJECTION_REASON_CODE ON
CLM_IMPL.CLM_SAT(REJECTION_REASON_CODE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_CLM_SAT_NUM_OF_NON_ACCEPTANCE_PAYMENT'
	AND object_id = OBJECT_ID('CLM_IMPL.CLM_SAT') ) BEGIN
	CREATE INDEX IDX_CLM_SAT_NUM_OF_NON_ACCEPTANCE_PAYMENT ON
CLM_IMPL.CLM_SAT(NUM_OF_NON_ACCEPTANCE_PAYMENT)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_IE_SAT_YEAR_QUARTER'
	AND object_id = OBJECT_ID('CLM_IMPL.IE_SAT') ) BEGIN
	CREATE INDEX IDX_IE_SAT_YEAR_QUARTER ON
CLM_IMPL.IE_SAT(YEAR_QUARTER)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_IE_SAT_TYPE_CODE'
	AND object_id = OBJECT_ID('CLM_IMPL.IE_SAT') ) BEGIN
	CREATE INDEX IDX_IE_SAT_TYPE_CODE ON
CLM_IMPL.IE_SAT(TYPE_CODE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_IE_SAT_REASON_CODE'
	AND object_id = OBJECT_ID('CLM_IMPL.IE_SAT') ) BEGIN
	CREATE INDEX IDX_IE_SAT_REASON_CODE ON
CLM_IMPL.IE_SAT(REASON_CODE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_IE_SAT_DIAGNOSIS_CODE'
	AND object_id = OBJECT_ID('CLM_IMPL.IE_SAT') ) BEGIN
	CREATE INDEX IDX_IE_SAT_DIAGNOSIS_CODE ON
CLM_IMPL.IE_SAT(DIAGNOSIS_CODE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_IE_SAT_STATE'
	AND object_id = OBJECT_ID('CLM_IMPL.IE_SAT') ) BEGIN
	CREATE INDEX IDX_IE_SAT_STATE ON
CLM_IMPL.IE_SAT(STATE)
END

------------------