BEGIN TRY
BEGIN TRAN

INSERT INTO UNI_IMPL.RQT_HUB (
	RQT_HKEY,
	LOAD_DATE,
	RECORD_SOURCE,
	REQUEST_NUMBER
)
SELECT DISTINCT 
	CONVERT(CHAR(32), HashBytes('MD5', cast(newid() as varbinary(max))), 2) AS RQT_HKEY,
	GETDATE() AS LOAD_DATE,
	N'ADINSURE' AS RECORD_SOURCE,
    ud.UNIVERSAL_DOCUMENT_NUMBER
FROM BFX.UNIVERSAL_DOCUMENT ud
LEFT JOIN CFX.PUBLISHED_ARTIFACT pa ON pa.PUBLISHED_ARTIFACT_ID = ud.PUBLISHED_ARTIFACT_ID
WHERE pa.CODE_NAME = 'LifeInsuranceRequest'
AND NOT EXISTS
(
  SELECT REQUEST_NUMBER FROM UNI_IMPL.RQT_HUB rqtHub
  WHERE rqtHub.REQUEST_NUMBER = ud.UNIVERSAL_DOCUMENT_NUMBER
);

COMMIT TRAN
END TRY

BEGIN CATCH

    ROLLBACK TRAN
    DECLARE @ErrorMessage NVARCHAR(4000); DECLARE @ErrorSeverity INT; DECLARE @ErrorState INT;
    SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = 1;
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);

END CATCH
