INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЦЕНТРАЛЬНАЯ И ПЕРИФЕРИЧЕСКАЯ НЕРВНАЯ СИСТЕМА',N'1',N'Перелом костей черепа (за исключением перелома орбиты, костей носа, скуловой кости, верхней и нижней челюстей, зубов, подъязычной кости):',N'1.1',NULL,NULL,NULL,NULL,N'перелом наружной пластинки костей свода черепа',0.05,N'В случае открытого перелома дополнительно выплачивается 5% от страховой суммы. Страховая выплата согласно п.1 определяется по одному из подпунктов (1.1 – 1.4), учитывающему наибольший размер выплаты.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЦЕНТРАЛЬНАЯ И ПЕРИФЕРИЧЕСКАЯ НЕРВНАЯ СИСТЕМА',N'1',N'Перелом костей черепа (за исключением перелома орбиты, костей носа, скуловой кости, верхней и нижней челюстей, зубов, подъязычной кости):',N'1.2',NULL,NULL,NULL,NULL,N'перелом свода черепа',0.15,N'В случае открытого перелома дополнительно выплачивается 5% от страховой суммы. Страховая выплата согласно п.1 определяется по одному из подпунктов (1.1 – 1.4), учитывающему наибольший размер выплаты.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЦЕНТРАЛЬНАЯ И ПЕРИФЕРИЧЕСКАЯ НЕРВНАЯ СИСТЕМА',N'1',N'Перелом костей черепа (за исключением перелома орбиты, костей носа, скуловой кости, верхней и нижней челюстей, зубов, подъязычной кости):',N'1.3',NULL,NULL,NULL,NULL,N'перелом основания черепа',0.2,N'В случае открытого перелома дополнительно выплачивается 5% от страховой суммы. Страховая выплата согласно п.1 определяется по одному из подпунктов (1.1 – 1.4), учитывающему наибольший размер выплаты.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЦЕНТРАЛЬНАЯ И ПЕРИФЕРИЧЕСКАЯ НЕРВНАЯ СИСТЕМА',N'1',N'Перелом костей черепа (за исключением перелома орбиты, костей носа, скуловой кости, верхней и нижней челюстей, зубов, подъязычной кости):',N'1.4',NULL,NULL,NULL,NULL,N'перелом свода и основания черепа',0.25,N'В случае открытого перелома дополнительно выплачивается 5% от страховой суммы. Страховая выплата согласно п.1 определяется по одному из подпунктов (1.1 – 1.4), учитывающему наибольший размер выплаты.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЦЕНТРАЛЬНАЯ И ПЕРИФЕРИЧЕСКАЯ НЕРВНАЯ СИСТЕМА',N'2',N'Повреждение спинного мозга на любом уровне, а также конского хвоста:',N'2.1',NULL,NULL,NULL,NULL,N'частичный разрыв',0.6,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЦЕНТРАЛЬНАЯ И ПЕРИФЕРИЧЕСКАЯ НЕРВНАЯ СИСТЕМА',N'2',N'Повреждение спинного мозга на любом уровне, а также конского хвоста:',N'2.2',NULL,NULL,NULL,NULL,N'полный разрыв ',1,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЦЕНТРАЛЬНАЯ И ПЕРИФЕРИЧЕСКАЯ НЕРВНАЯ СИСТЕМА',N'3',N'Повреждение сплетений:',N'3.1',NULL,NULL,NULL,NULL,N'частичный разрыв сплетений',0.4,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЦЕНТРАЛЬНАЯ И ПЕРИФЕРИЧЕСКАЯ НЕРВНАЯ СИСТЕМА',N'3',N'Повреждение сплетений:',N'3.2',NULL,NULL,NULL,NULL,N'полный разрыв сплетений',0.7,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ДЫХАТЕЛЬНАЯ СИСТЕМА',N'4',NULL,NULL,NULL,NULL,NULL,NULL,N'Перелом грудины',0.05,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ДЫХАТЕЛЬНАЯ СИСТЕМА',N'5',N'Переломы ребер:',N'5.1',NULL,NULL,NULL,NULL,N'одного ребра',0.01,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ДЫХАТЕЛЬНАЯ СИСТЕМА',N'5',N'Переломы ребер:',N'5.2',NULL,NULL,NULL,NULL,N'двух ребер',0.02,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ДЫХАТЕЛЬНАЯ СИСТЕМА',N'5',N'Переломы ребер:',N'5.3',NULL,NULL,NULL,NULL,N'трех и более ребер',0.05,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ДЫХАТЕЛЬНАЯ СИСТЕМА',N'6',NULL,NULL,NULL,NULL,NULL,NULL,N'Перелом подъязычной кости',0.15,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ДЫХАТЕЛЬНАЯ СИСТЕМА',N'7',NULL,NULL,NULL,NULL,NULL,NULL,N'Перелом кости (костей), не предусмотренный данным разделом',0.01,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ОРГАНЫ ПИЩЕВАРЕНИЯ',N'8',N'Перелом верхней или нижней челюсти, скуловой кости, повреждения зубов в результате травмы:',N'8.1',NULL,NULL,NULL,NULL,N'перелом одной кости',0.05,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ОРГАНЫ ПИЩЕВАРЕНИЯ',N'8',N'Перелом верхней или нижней челюсти, скуловой кости, повреждения зубов в результате травмы:',N'8.2',NULL,NULL,NULL,NULL,N'перелом двух и более костей, двойной перелом одной кости',0.1,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ПОЗВОНОЧНИК',N'9',N'Перелом тел позвонков (за исключением крестца и копчика)',N'9.1',NULL,NULL,NULL,NULL,N'одного позвонка',0.05,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ПОЗВОНОЧНИК',N'9',N'Перелом тел позвонков (за исключением крестца и копчика)',N'9.2',NULL,NULL,NULL,NULL,N'двух позвонков',0.1,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ПОЗВОНОЧНИК',N'9',N'Перелом тел позвонков (за исключением крестца и копчика)',N'9.3',NULL,NULL,NULL,NULL,N'трех или более позвонков',0.2,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ПОЗВОНОЧНИК',N'10',NULL,NULL,NULL,NULL,NULL,NULL,N'Перелом поперечных или остистых отростков трех и более позвонков',0.1,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ПОЗВОНОЧНИК',N'11',NULL,NULL,NULL,NULL,NULL,NULL,N'перелом крестца',0.05,N'Страховая выплата согласно п.11 определяется по одному из подпунктов (11.1, 11.2), учитывающему наибольший размер выплаты.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ПОЗВОНОЧНИК',N'11',NULL,NULL,NULL,NULL,NULL,NULL,N'перелом копчика',0.03,N'Страховая выплата согласно п.11 определяется по одному из подпунктов (11.1, 11.2), учитывающему наибольший размер выплаты.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЛОПАТКА И КЛЮЧИЦА',N'12',N'Перелом тела лопатки, ключицы: ',N'12.1',NULL,NULL,NULL,NULL,N'перелом одной кости',0.03,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЛОПАТКА И КЛЮЧИЦА',N'12',N'Перелом тела лопатки, ключицы: ',N'12.2',NULL,NULL,NULL,NULL,N'перелом двух костей',0.05,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЛОПАТКА И КЛЮЧИЦА',N'12',N'Перелом тела лопатки, ключицы: ',N'12.3',NULL,NULL,NULL,NULL,N'несросшийся перелом, ложный сустав (выплата производится не ранее, чем через 6 (шесть) месяцев после травмы, произошедшей в период страхования)',0.15,N'Если были произведены выплаты по п.п.12.1, 12.2, выплаты по п.12.3 производятся за вычетом ранее произведенных выплат по п.п.12.1 и 12.2.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ПЛЕЧО',N'13',N'Перелом плечевой кости: ',N'13.1',NULL,NULL,NULL,NULL,N'на любом уровне',0.1,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ПЛЕЧО',N'13',N'Перелом плечевой кости: ',N'13.2',NULL,NULL,NULL,NULL,N'двойной перелом',0.15,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ПЛЕЧО',N'14',NULL,NULL,NULL,NULL,NULL,NULL,N'Травматическая ампутация верхней конечности на любом уровне',0.4,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЛОКТЕВОЙ СУСТАВ И ПРЕДПЛЕЧЬЕ',N'15',N'Перелом костей на уровне верхней трети или средней трети костей предплечья:',N'15.1',NULL,NULL,NULL,NULL,N'перелом одной кости',0.05,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЛОКТЕВОЙ СУСТАВ И ПРЕДПЛЕЧЬЕ',N'15',N'Перелом костей на уровне верхней трети или средней трети костей предплечья:',N'15.2',NULL,NULL,NULL,NULL,N'перелом двух костей ',0.1,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЛУЧЕЗАПЯСТНЫЙ СУСТАВ, КИСТЬ',N'16',N'Перелом костей предплечья на уровне нижней трети, внутрисуставные переломы, разрыв связок лучезапястного сустава:',N'16.1',NULL,NULL,NULL,NULL,N'перелом кости ',0.03,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЛУЧЕЗАПЯСТНЫЙ СУСТАВ, КИСТЬ',N'16',N'Перелом костей предплечья на уровне нижней трети, внутрисуставные переломы, разрыв связок лучезапястного сустава:',N'16.2',NULL,NULL,NULL,NULL,N'отрыв, перелом шиловидного отростка(отростков)',0.01,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЛУЧЕЗАПЯСТНЫЙ СУСТАВ, КИСТЬ',N'17',N'Перелом костей запястья, пясти:',N'17.1',NULL,NULL,NULL,NULL,N'одной кости',0.03,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЛУЧЕЗАПЯСТНЫЙ СУСТАВ, КИСТЬ',N'17',N'Перелом костей запястья, пясти:',N'17.2',NULL,NULL,NULL,NULL,N'двух и более костей',0.05,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЛУЧЕЗАПЯСТНЫЙ СУСТАВ, КИСТЬ',N'18',NULL,NULL,NULL,NULL,NULL,NULL,N'Перелом большого пальца',0.03,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЛУЧЕЗАПЯСТНЫЙ СУСТАВ, КИСТЬ',N'19',NULL,NULL,NULL,NULL,NULL,NULL,N'Потеря большого пальца',0.1,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЛУЧЕЗАПЯСТНЫЙ СУСТАВ, КИСТЬ',N'20',NULL,NULL,NULL,NULL,NULL,NULL,N'Потеря любого другого пальца',0.05,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЛУЧЕЗАПЯСТНЫЙ СУСТАВ, КИСТЬ',N'21',NULL,NULL,NULL,NULL,NULL,NULL,N'Травматическая ампутация или повреждение, повлекшее за собой ампутацию на уровне пальцев всех пальцев одной кисти',0.2,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ЛУЧЕЗАПЯСТНЫЙ СУСТАВ, КИСТЬ',N'22',NULL,NULL,NULL,NULL,NULL,NULL,N'Перелом кости (костей), не предусмотренный данным разделом',0.01,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'НИЖНЯЯ КОНЕЧНОСТЬ ',N'23',N'Перелом костей таза:',N'23.1',NULL,NULL,NULL,NULL,N'перелом одной кости',0.05,N'Если в результате травмы возникли повреждения, указанные в п.п.23-24, то выплата осуществляется по пункту с наибольшим размером выплаты.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'НИЖНЯЯ КОНЕЧНОСТЬ ',N'23',N'Перелом костей таза:',N'23.2',NULL,NULL,NULL,NULL,N'перелом двух костей',0.1,N'Если в результате травмы возникли повреждения, указанные в п.п.23-24, то выплата осуществляется по пункту с наибольшим размером выплаты.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'НИЖНЯЯ КОНЕЧНОСТЬ ',N'23',N'Перелом костей таза:',N'23.3',NULL,NULL,NULL,NULL,N'перелом трех и более костей',0.15,N'Если в результате травмы возникли повреждения, указанные в п.п.23-24, то выплата осуществляется по пункту с наибольшим размером выплаты.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'НИЖНЯЯ КОНЕЧНОСТЬ ',N'24',N'Разрыв лонного, крестцово-подвздошного сочленения:',N'24.1',NULL,NULL,NULL,NULL,N'одного сочленения',0.1,N'Если в результате травмы возникли повреждения, указанные в п.п.23-24, то выплата осуществляется по пункту с наибольшим размером выплаты.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'НИЖНЯЯ КОНЕЧНОСТЬ ',N'24',N'Разрыв лонного, крестцово-подвздошного сочленения:',N'24.2',NULL,NULL,NULL,NULL,N'двух и более сочленений',0.15,N'Если в результате травмы возникли повреждения, указанные в п.п.23-24, то выплата осуществляется по пункту с наибольшим размером выплаты.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'НИЖНЯЯ КОНЕЧНОСТЬ ',N'25',NULL,NULL,NULL,NULL,NULL,NULL,N'Перелом верхней трети головки, шейки бедра',0.4,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'БЕДРО',N'26',N'Диафизарный перелом бедра на любом уровне (за исключением области суставов):',N'26.1',NULL,NULL,NULL,NULL,N'без смещения отломков',0.15,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'БЕДРО',N'26',N'Диафизарный перелом бедра на любом уровне (за исключением области суставов):',N'26.2',NULL,NULL,NULL,NULL,N'со смещением отломков',0.2,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'КОЛЕННЫЙ СУСТАВ',N'27',N'Перелом костей, составляющих коленный сустав:',N'27.1',NULL,NULL,NULL,NULL,N'разрыв мениска (менисков)',0.02,N'При сочетании различных видов повреждений области коленного сустава выплата производится однократно в соответствии с одним из п.27, предусматривающим наибольший размер страховой выплаты.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'КОЛЕННЫЙ СУСТАВ',N'27',N'Перелом костей, составляющих коленный сустав:',N'27.2',NULL,NULL,NULL,NULL,N'перелом надмыщелка (надмыщелков) бедренной кости',0.02,N'При сочетании различных видов повреждений области коленного сустава выплата производится однократно в соответствии с одним из п.27, предусматривающим наибольший размер страховой выплаты.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'КОЛЕННЫЙ СУСТАВ',N'27',N'Перелом костей, составляющих коленный сустав:',N'27.3',NULL,NULL,NULL,NULL,N'перелом головки малоберцовой кости',0.05,N'При сочетании различных видов повреждений области коленного сустава выплата производится однократно в соответствии с одним из п.27, предусматривающим наибольший размер страховой выплаты.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'КОЛЕННЫЙ СУСТАВ',N'27',N'Перелом костей, составляющих коленный сустав:',N'27.4',NULL,NULL,NULL,NULL,N'перелом надколенника',0.05,N'При сочетании различных видов повреждений области коленного сустава выплата производится однократно в соответствии с одним из п.27, предусматривающим наибольший размер страховой выплаты.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'КОЛЕННЫЙ СУСТАВ',N'27',N'Перелом костей, составляющих коленный сустав:',N'27.5',NULL,NULL,NULL,NULL,N'перелом дистального эпифиза бедра и проксимального эпифиза большеберцовой кости',0.2,N'При сочетании различных видов повреждений области коленного сустава выплата производится однократно в соответствии с одним из п.27, предусматривающим наибольший размер страховой выплаты.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ГОЛЕНЬ',N'28',N'Перелом костей голени на уровне средней трети (за исключением области суставов)',N'28.1',NULL,NULL,NULL,NULL,N'одной кости',0.1,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ГОЛЕНЬ',N'28',N'Перелом костей голени на уровне средней трети (за исключением области суставов)',N'28.2',NULL,NULL,NULL,NULL,N'двух костей',0.15,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ГОЛЕНЬ',N'29',N'Перелом костей голени, повлекший за собой несросшийся перелом, ложный сустав (за исключением костных фрагментов):',N'29.1',NULL,NULL,NULL,NULL,N'большеберцовой кости. Выплата не ранее, чем через 3 (три) месяца со дня травмы, при условии подтверждения диагноза',0.1,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ГОЛЕНЬ',N'29',N'Перелом костей голени, повлекший за собой несросшийся перелом, ложный сустав (за исключением костных фрагментов):',N'29.2',NULL,NULL,NULL,NULL,N'обеих костей. Выплата не ранее, чем через 3 (три) месяца со дня травмы, при условии подтверждения диагноза',0.15,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ГОЛЕНОСТОПНЫЙ СУСТАВ',N'30',N'Перелом костей голени и разрыв связок на уровне нижней трети:',N'30.1',NULL,NULL,NULL,NULL,N'перелом одной лодыжки',0.05,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ГОЛЕНОСТОПНЫЙ СУСТАВ',N'30',N'Перелом костей голени и разрыв связок на уровне нижней трети:',N'30.2',NULL,NULL,NULL,NULL,N'перелом одной лодыжки с краем большеберцовой кости',0.05,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ГОЛЕНОСТОПНЫЙ СУСТАВ',N'30',N'Перелом костей голени и разрыв связок на уровне нижней трети:',N'30.3',NULL,NULL,NULL,NULL,N'перелом обеих лодыжек',0.1,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ГОЛЕНОСТОПНЫЙ СУСТАВ',N'30',N'Перелом костей голени и разрыв связок на уровне нижней трети:',N'30.4',NULL,NULL,NULL,NULL,N'перелом обеих лодыжек с краем большеберцовой кости',0.1,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ГОЛЕНОСТОПНЫЙ СУСТАВ',N'30',N'Перелом костей голени и разрыв связок на уровне нижней трети:',N'30.5',NULL,NULL,NULL,NULL,N'разрыв межберцового синдесмоза',0.05,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ГОЛЕНОСТОПНЫЙ СУСТАВ',N'30',N'Перелом костей голени и разрыв связок на уровне нижней трети:',N'30.6',NULL,NULL,NULL,NULL,N'разрыв связок или сухожилия (кроме ахиллова сухожилия) голеностопного сустава',0.02,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ГОЛЕНОСТОПНЫЙ СУСТАВ',N'30',N'Перелом костей голени и разрыв связок на уровне нижней трети:',N'30.7',NULL,NULL,NULL,NULL,N'частичный разрыв ахиллова сухожилия',0.02,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'ГОЛЕНОСТОПНЫЙ СУСТАВ',N'30',N'Перелом костей голени и разрыв связок на уровне нижней трети:',N'30.8',NULL,NULL,NULL,NULL,N'полный разрыв ахиллова сухожилия',0.04,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'31',N'Перелом кости (костей) стопы:',N'31.1',NULL,NULL,NULL,NULL,N'перелом одной, двух костей (кроме пяточной кости)',0.05,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'31',N'Перелом кости (костей) стопы:',N'31.2',NULL,NULL,NULL,NULL,N'перелом трех и более костей, пяточной кости',0.1,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'32',NULL,NULL,NULL,NULL,NULL,NULL,N'Травматическая ампутация нижней конечности на любом уровне:',0.3,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'33',NULL,NULL,NULL,NULL,NULL,NULL,N'перелом большого пальца стопы',0.03,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'34',N'Травматическая ампутация или повреждение, повлекшее за собой ампутацию:',N'34.1',NULL,NULL,NULL,NULL,N'большого пальца ноги ',0.05,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'34',N'Травматическая ампутация или повреждение, повлекшее за собой ампутацию:',N'34.2',NULL,NULL,NULL,NULL,N'другого пальца ноги',0.03,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'35',N'',N'35.1',N'Монопарез всей конечности, в зависимости от тяжести поражения:',N'35.1.1',NULL,NULL,N'легкая степень (4 -4,5 балла)',0.1,N'Страховая выплата в связи с последствиями травмы нервной системы, указанными в п.35 производится по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата производится дополнительно к страховой выплате, ранее произведенной в связи со страховыми событиями, приведшими к поражению нервной системы. Общая сумма выплат не может превышать 100%.',N'Решение о страховой выплате в связи с последствиями травмы нервной системы, указанными в п.35, принимается по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата осуществляется дополнительно к страховой сумме, выплаченной в связи со страховыми событиями, приведшими к повреждению нервной системы. Общая сумма выплат не может превышать 100% страховой суммы.
Таблица «Степени пареза»
0 баллов «силы мышц» – нет произвольных движений. Паралич.
1 балл – едва заметные сокращения мышц, без движений в суставах
2 балла – объём движений в суставе значительно снижен, движения возможны без преодоления силы тяжести по плоскости
3 балла – значительное сокращение объёма движений в суставе, мышцы способны преодолеть силу тяжести, трения (возможность отрыва конечности от поверхности)
4 балла – легкое снижение силы мышц, при полном объёме движения
5 баллов – нормальная сила мышц, полный объём движений
',NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'35',N'',N'35.1',N'Монопарез всей конечности, в зависимости от тяжести поражения:',N'35.1.2',NULL,NULL,N'умеренная степень (3-3,5 балла)',0.16,N'Страховая выплата в связи с последствиями травмы нервной системы, указанными в п.35 производится по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата производится дополнительно к страховой выплате, ранее произведенной в связи со страховыми событиями, приведшими к поражению нервной системы. Общая сумма выплат не может превышать 100%.',N'Решение о страховой выплате в связи с последствиями травмы нервной системы, указанными в п.35, принимается по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата осуществляется дополнительно к страховой сумме, выплаченной в связи со страховыми событиями, приведшими к повреждению нервной системы. Общая сумма выплат не может превышать 100% страховой суммы.
Таблица «Степени пареза»
0 баллов «силы мышц» – нет произвольных движений. Паралич.
1 балл – едва заметные сокращения мышц, без движений в суставах
2 балла – объём движений в суставе значительно снижен, движения возможны без преодоления силы тяжести по плоскости
3 балла – значительное сокращение объёма движений в суставе, мышцы способны преодолеть силу тяжести, трения (возможность отрыва конечности от поверхности)
4 балла – легкое снижение силы мышц, при полном объёме движения
5 баллов – нормальная сила мышц, полный объём движений
',NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'35',N'',N'35.1',N'Монопарез всей конечности, в зависимости от тяжести поражения:',N'35.1.3',NULL,NULL,N'глубокая степень (0,5- 2,5 балла)',0.2,N'Страховая выплата в связи с последствиями травмы нервной системы, указанными в п.35 производится по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата производится дополнительно к страховой выплате, ранее произведенной в связи со страховыми событиями, приведшими к поражению нервной системы. Общая сумма выплат не может превышать 100%.',N'Решение о страховой выплате в связи с последствиями травмы нервной системы, указанными в п.35, принимается по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата осуществляется дополнительно к страховой сумме, выплаченной в связи со страховыми событиями, приведшими к повреждению нервной системы. Общая сумма выплат не может превышать 100% страховой суммы.
Таблица «Степени пареза»
0 баллов «силы мышц» – нет произвольных движений. Паралич.
1 балл – едва заметные сокращения мышц, без движений в суставах
2 балла – объём движений в суставе значительно снижен, движения возможны без преодоления силы тяжести по плоскости
3 балла – значительное сокращение объёма движений в суставе, мышцы способны преодолеть силу тяжести, трения (возможность отрыва конечности от поверхности)
4 балла – легкое снижение силы мышц, при полном объёме движения
5 баллов – нормальная сила мышц, полный объём движений
',NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'35',N'',N'35.2',N'Монопарез по уровню поражения:',N'35.2.1',N'Проксимальная часть верхней конечности (от плечевого сустава до локтевого сустава включительно)',N'35.2.1.1',N'легкая степень',0.06,N'Страховая выплата в связи с последствиями травмы нервной системы, указанными в п.35 производится по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата производится дополнительно к страховой выплате, ранее произведенной в связи со страховыми событиями, приведшими к поражению нервной системы. Общая сумма выплат не может превышать 100%.',N'Решение о страховой выплате в связи с последствиями травмы нервной системы, указанными в п.35, принимается по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата осуществляется дополнительно к страховой сумме, выплаченной в связи со страховыми событиями, приведшими к повреждению нервной системы. Общая сумма выплат не может превышать 100% страховой суммы.
Таблица «Степени пареза»
0 баллов «силы мышц» – нет произвольных движений. Паралич.
1 балл – едва заметные сокращения мышц, без движений в суставах
2 балла – объём движений в суставе значительно снижен, движения возможны без преодоления силы тяжести по плоскости
3 балла – значительное сокращение объёма движений в суставе, мышцы способны преодолеть силу тяжести, трения (возможность отрыва конечности от поверхности)
4 балла – легкое снижение силы мышц, при полном объёме движения
5 баллов – нормальная сила мышц, полный объём движений
',NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'35',N'',N'35.2',N'Монопарез по уровню поражения:',N'35.2.1',N'Проксимальная часть верхней конечности (от плечевого сустава до локтевого сустава включительно)',N'35.2.1.2',N'умеренная степень',0.1,N'Страховая выплата в связи с последствиями травмы нервной системы, указанными в п.35 производится по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата производится дополнительно к страховой выплате, ранее произведенной в связи со страховыми событиями, приведшими к поражению нервной системы. Общая сумма выплат не может превышать 100%.',N'Решение о страховой выплате в связи с последствиями травмы нервной системы, указанными в п.35, принимается по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата осуществляется дополнительно к страховой сумме, выплаченной в связи со страховыми событиями, приведшими к повреждению нервной системы. Общая сумма выплат не может превышать 100% страховой суммы.
Таблица «Степени пареза»
0 баллов «силы мышц» – нет произвольных движений. Паралич.
1 балл – едва заметные сокращения мышц, без движений в суставах
2 балла – объём движений в суставе значительно снижен, движения возможны без преодоления силы тяжести по плоскости
3 балла – значительное сокращение объёма движений в суставе, мышцы способны преодолеть силу тяжести, трения (возможность отрыва конечности от поверхности)
4 балла – легкое снижение силы мышц, при полном объёме движения
5 баллов – нормальная сила мышц, полный объём движений
',NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'35',N'',N'35.2',N'Монопарез по уровню поражения:',N'35.2.1',N'Проксимальная часть верхней конечности (от плечевого сустава до локтевого сустава включительно)',N'35.2.1.3',N'глубокая степень',0.12,N'Страховая выплата в связи с последствиями травмы нервной системы, указанными в п.35 производится по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата производится дополнительно к страховой выплате, ранее произведенной в связи со страховыми событиями, приведшими к поражению нервной системы. Общая сумма выплат не может превышать 100%.',N'Решение о страховой выплате в связи с последствиями травмы нервной системы, указанными в п.35, принимается по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата осуществляется дополнительно к страховой сумме, выплаченной в связи со страховыми событиями, приведшими к повреждению нервной системы. Общая сумма выплат не может превышать 100% страховой суммы.
Таблица «Степени пареза»
0 баллов «силы мышц» – нет произвольных движений. Паралич.
1 балл – едва заметные сокращения мышц, без движений в суставах
2 балла – объём движений в суставе значительно снижен, движения возможны без преодоления силы тяжести по плоскости
3 балла – значительное сокращение объёма движений в суставе, мышцы способны преодолеть силу тяжести, трения (возможность отрыва конечности от поверхности)
4 балла – легкое снижение силы мышц, при полном объёме движения
5 баллов – нормальная сила мышц, полный объём движений
',NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'35',N'',N'35.2',N'Монопарез по уровню поражения:',N'35.2.2',N'Дистальная часть верхней конечности  (от локтевого сустава до кисти - включительно)',N'35.2.2.1',N'легкая степень',0.04,N'Страховая выплата в связи с последствиями травмы нервной системы, указанными в п.35 производится по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата производится дополнительно к страховой выплате, ранее произведенной в связи со страховыми событиями, приведшими к поражению нервной системы. Общая сумма выплат не может превышать 100%.',N'Решение о страховой выплате в связи с последствиями травмы нервной системы, указанными в п.35, принимается по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата осуществляется дополнительно к страховой сумме, выплаченной в связи со страховыми событиями, приведшими к повреждению нервной системы. Общая сумма выплат не может превышать 100% страховой суммы.
Таблица «Степени пареза»
0 баллов «силы мышц» – нет произвольных движений. Паралич.
1 балл – едва заметные сокращения мышц, без движений в суставах
2 балла – объём движений в суставе значительно снижен, движения возможны без преодоления силы тяжести по плоскости
3 балла – значительное сокращение объёма движений в суставе, мышцы способны преодолеть силу тяжести, трения (возможность отрыва конечности от поверхности)
4 балла – легкое снижение силы мышц, при полном объёме движения
5 баллов – нормальная сила мышц, полный объём движений
',NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'35',N'',N'35.2',N'Монопарез по уровню поражения:',N'35.2.2',N'Дистальная часть верхней конечности  (от локтевого сустава до кисти - включительно)',N'35.2.2.2',N'умеренная степень',0.06,N'Страховая выплата в связи с последствиями травмы нервной системы, указанными в п.35 производится по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата производится дополнительно к страховой выплате, ранее произведенной в связи со страховыми событиями, приведшими к поражению нервной системы. Общая сумма выплат не может превышать 100%.',N'Решение о страховой выплате в связи с последствиями травмы нервной системы, указанными в п.35, принимается по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата осуществляется дополнительно к страховой сумме, выплаченной в связи со страховыми событиями, приведшими к повреждению нервной системы. Общая сумма выплат не может превышать 100% страховой суммы.
Таблица «Степени пареза»
0 баллов «силы мышц» – нет произвольных движений. Паралич.
1 балл – едва заметные сокращения мышц, без движений в суставах
2 балла – объём движений в суставе значительно снижен, движения возможны без преодоления силы тяжести по плоскости
3 балла – значительное сокращение объёма движений в суставе, мышцы способны преодолеть силу тяжести, трения (возможность отрыва конечности от поверхности)
4 балла – легкое снижение силы мышц, при полном объёме движения
5 баллов – нормальная сила мышц, полный объём движений
',NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'35',N'',N'35.2',N'Монопарез по уровню поражения:',N'35.2.2',N'Дистальная часть верхней конечности  (от локтевого сустава до кисти - включительно)',N'35.2.2.3',N'глубокая степень',0.08,N'Страховая выплата в связи с последствиями травмы нервной системы, указанными в п.35 производится по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата производится дополнительно к страховой выплате, ранее произведенной в связи со страховыми событиями, приведшими к поражению нервной системы. Общая сумма выплат не может превышать 100%.',N'Решение о страховой выплате в связи с последствиями травмы нервной системы, указанными в п.35, принимается по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата осуществляется дополнительно к страховой сумме, выплаченной в связи со страховыми событиями, приведшими к повреждению нервной системы. Общая сумма выплат не может превышать 100% страховой суммы.
Таблица «Степени пареза»
0 баллов «силы мышц» – нет произвольных движений. Паралич.
1 балл – едва заметные сокращения мышц, без движений в суставах
2 балла – объём движений в суставе значительно снижен, движения возможны без преодоления силы тяжести по плоскости
3 балла – значительное сокращение объёма движений в суставе, мышцы способны преодолеть силу тяжести, трения (возможность отрыва конечности от поверхности)
4 балла – легкое снижение силы мышц, при полном объёме движения
5 баллов – нормальная сила мышц, полный объём движений
',NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'35',N'',N'35.2',N'Монопарез по уровню поражения:',N'35.2.3',N'Проксимальная часть нижней конечности (от бедренного сустава до коленного сустава включительно)',N'35.2.3.1',N'легкая степень',0.06,N'Страховая выплата в связи с последствиями травмы нервной системы, указанными в п.35 производится по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата производится дополнительно к страховой выплате, ранее произведенной в связи со страховыми событиями, приведшими к поражению нервной системы. Общая сумма выплат не может превышать 100%.',N'Решение о страховой выплате в связи с последствиями травмы нервной системы, указанными в п.35, принимается по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата осуществляется дополнительно к страховой сумме, выплаченной в связи со страховыми событиями, приведшими к повреждению нервной системы. Общая сумма выплат не может превышать 100% страховой суммы.
Таблица «Степени пареза»
0 баллов «силы мышц» – нет произвольных движений. Паралич.
1 балл – едва заметные сокращения мышц, без движений в суставах
2 балла – объём движений в суставе значительно снижен, движения возможны без преодоления силы тяжести по плоскости
3 балла – значительное сокращение объёма движений в суставе, мышцы способны преодолеть силу тяжести, трения (возможность отрыва конечности от поверхности)
4 балла – легкое снижение силы мышц, при полном объёме движения
5 баллов – нормальная сила мышц, полный объём движений
',NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'35',N'',N'35.2',N'Монопарез по уровню поражения:',N'35.2.3',N'Проксимальная часть нижней конечности (от бедренного сустава до коленного сустава включительно)',N'35.2.3.2',N'умеренная степень',0.1,N'Страховая выплата в связи с последствиями травмы нервной системы, указанными в п.35 производится по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата производится дополнительно к страховой выплате, ранее произведенной в связи со страховыми событиями, приведшими к поражению нервной системы. Общая сумма выплат не может превышать 100%.',N'Решение о страховой выплате в связи с последствиями травмы нервной системы, указанными в п.35, принимается по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата осуществляется дополнительно к страховой сумме, выплаченной в связи со страховыми событиями, приведшими к повреждению нервной системы. Общая сумма выплат не может превышать 100% страховой суммы.
Таблица «Степени пареза»
0 баллов «силы мышц» – нет произвольных движений. Паралич.
1 балл – едва заметные сокращения мышц, без движений в суставах
2 балла – объём движений в суставе значительно снижен, движения возможны без преодоления силы тяжести по плоскости
3 балла – значительное сокращение объёма движений в суставе, мышцы способны преодолеть силу тяжести, трения (возможность отрыва конечности от поверхности)
4 балла – легкое снижение силы мышц, при полном объёме движения
5 баллов – нормальная сила мышц, полный объём движений
',NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'35',N'',N'35.2',N'Монопарез по уровню поражения:',N'35.2.3',N'Проксимальная часть нижней конечности (от бедренного сустава до коленного сустава включительно)',N'35.2.3.3',N'глубокая степень',0.12,N'Страховая выплата в связи с последствиями травмы нервной системы, указанными в п.35 производится по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата производится дополнительно к страховой выплате, ранее произведенной в связи со страховыми событиями, приведшими к поражению нервной системы. Общая сумма выплат не может превышать 100%.',N'Решение о страховой выплате в связи с последствиями травмы нервной системы, указанными в п.35, принимается по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата осуществляется дополнительно к страховой сумме, выплаченной в связи со страховыми событиями, приведшими к повреждению нервной системы. Общая сумма выплат не может превышать 100% страховой суммы.
Таблица «Степени пареза»
0 баллов «силы мышц» – нет произвольных движений. Паралич.
1 балл – едва заметные сокращения мышц, без движений в суставах
2 балла – объём движений в суставе значительно снижен, движения возможны без преодоления силы тяжести по плоскости
3 балла – значительное сокращение объёма движений в суставе, мышцы способны преодолеть силу тяжести, трения (возможность отрыва конечности от поверхности)
4 балла – легкое снижение силы мышц, при полном объёме движения
5 баллов – нормальная сила мышц, полный объём движений
',NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'35',N'',N'35.2',N'Монопарез по уровню поражения:',N'35.2.4',N'Дистальная часть нижней конечности (от коленного сустава до и стопы включительно)',N'35.2.4.1',N'легкая степень',0.04,N'Страховая выплата в связи с последствиями травмы нервной системы, указанными в п.35 производится по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата производится дополнительно к страховой выплате, ранее произведенной в связи со страховыми событиями, приведшими к поражению нервной системы. Общая сумма выплат не может превышать 100%.',N'Решение о страховой выплате в связи с последствиями травмы нервной системы, указанными в п.35, принимается по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата осуществляется дополнительно к страховой сумме, выплаченной в связи со страховыми событиями, приведшими к повреждению нервной системы. Общая сумма выплат не может превышать 100% страховой суммы.
Таблица «Степени пареза»
0 баллов «силы мышц» – нет произвольных движений. Паралич.
1 балл – едва заметные сокращения мышц, без движений в суставах
2 балла – объём движений в суставе значительно снижен, движения возможны без преодоления силы тяжести по плоскости
3 балла – значительное сокращение объёма движений в суставе, мышцы способны преодолеть силу тяжести, трения (возможность отрыва конечности от поверхности)
4 балла – легкое снижение силы мышц, при полном объёме движения
5 баллов – нормальная сила мышц, полный объём движений
',NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'35',N'',N'35.2',N'Монопарез по уровню поражения:',N'35.2.4',N'Дистальная часть нижней конечности (от коленного сустава до и стопы включительно)',N'35.2.4.2',N'умеренная степень',0.06,N'Страховая выплата в связи с последствиями травмы нервной системы, указанными в п.35 производится по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата производится дополнительно к страховой выплате, ранее произведенной в связи со страховыми событиями, приведшими к поражению нервной системы. Общая сумма выплат не может превышать 100%.',N'Решение о страховой выплате в связи с последствиями травмы нервной системы, указанными в п.35, принимается по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата осуществляется дополнительно к страховой сумме, выплаченной в связи со страховыми событиями, приведшими к повреждению нервной системы. Общая сумма выплат не может превышать 100% страховой суммы.
Таблица «Степени пареза»
0 баллов «силы мышц» – нет произвольных движений. Паралич.
1 балл – едва заметные сокращения мышц, без движений в суставах
2 балла – объём движений в суставе значительно снижен, движения возможны без преодоления силы тяжести по плоскости
3 балла – значительное сокращение объёма движений в суставе, мышцы способны преодолеть силу тяжести, трения (возможность отрыва конечности от поверхности)
4 балла – легкое снижение силы мышц, при полном объёме движения
5 баллов – нормальная сила мышц, полный объём движений
',NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'35',N'',N'35.2',N'Монопарез по уровню поражения:',N'35.2.4',N'Дистальная часть нижней конечности (от коленного сустава до и стопы включительно)',N'35.2.4.3',N'глубокая степень',0.08,N'Страховая выплата в связи с последствиями травмы нервной системы, указанными в п.35 производится по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата производится дополнительно к страховой выплате, ранее произведенной в связи со страховыми событиями, приведшими к поражению нервной системы. Общая сумма выплат не может превышать 100%.',N'Решение о страховой выплате в связи с последствиями травмы нервной системы, указанными в п.35, принимается по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата осуществляется дополнительно к страховой сумме, выплаченной в связи со страховыми событиями, приведшими к повреждению нервной системы. Общая сумма выплат не может превышать 100% страховой суммы.
Таблица «Степени пареза»
0 баллов «силы мышц» – нет произвольных движений. Паралич.
1 балл – едва заметные сокращения мышц, без движений в суставах
2 балла – объём движений в суставе значительно снижен, движения возможны без преодоления силы тяжести по плоскости
3 балла – значительное сокращение объёма движений в суставе, мышцы способны преодолеть силу тяжести, трения (возможность отрыва конечности от поверхности)
4 балла – легкое снижение силы мышц, при полном объёме движения
5 баллов – нормальная сила мышц, полный объём движений
',NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'35',N'',N'35.3',NULL,NULL,NULL,NULL,N'Гемипарез или парапарез (снижение силы в 2 конечностях), расчет за каждую конечность в зависимости от тяжести поражения (максимально суммарно – 40%) смотреть в таблице монопарезов',NULL,N'Страховая выплата в связи с последствиями травмы нервной системы, указанными в п.35 производится по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата производится дополнительно к страховой выплате, ранее произведенной в связи со страховыми событиями, приведшими к поражению нервной системы. Общая сумма выплат не может превышать 100%.',N'Решение о страховой выплате в связи с последствиями травмы нервной системы, указанными в п.35, принимается по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата осуществляется дополнительно к страховой сумме, выплаченной в связи со страховыми событиями, приведшими к повреждению нервной системы. Общая сумма выплат не может превышать 100% страховой суммы.
Таблица «Степени пареза»
0 баллов «силы мышц» – нет произвольных движений. Паралич.
1 балл – едва заметные сокращения мышц, без движений в суставах
2 балла – объём движений в суставе значительно снижен, движения возможны без преодоления силы тяжести по плоскости
3 балла – значительное сокращение объёма движений в суставе, мышцы способны преодолеть силу тяжести, трения (возможность отрыва конечности от поверхности)
4 балла – легкое снижение силы мышц, при полном объёме движения
5 баллов – нормальная сила мышц, полный объём движений
',NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'35',N'',N'35.4',NULL,NULL,NULL,NULL,N'Тетрапарез (снижение силы во всех 4 конечностях) расчет за каждую конечность в зависимости от тяжести поражения (максимально суммарно – 80%) смотреть в таблице монопарезов',NULL,N'Страховая выплата в связи с последствиями травмы нервной системы, указанными в п.35 производится по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата производится дополнительно к страховой выплате, ранее произведенной в связи со страховыми событиями, приведшими к поражению нервной системы. Общая сумма выплат не может превышать 100%.',N'Решение о страховой выплате в связи с последствиями травмы нервной системы, указанными в п.35, принимается по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата осуществляется дополнительно к страховой сумме, выплаченной в связи со страховыми событиями, приведшими к повреждению нервной системы. Общая сумма выплат не может превышать 100% страховой суммы.
Таблица «Степени пареза»
0 баллов «силы мышц» – нет произвольных движений. Паралич.
1 балл – едва заметные сокращения мышц, без движений в суставах
2 балла – объём движений в суставе значительно снижен, движения возможны без преодоления силы тяжести по плоскости
3 балла – значительное сокращение объёма движений в суставе, мышцы способны преодолеть силу тяжести, трения (возможность отрыва конечности от поверхности)
4 балла – легкое снижение силы мышц, при полном объёме движения
5 баллов – нормальная сила мышц, полный объём движений
',NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'35',N'',N'35.5',NULL,NULL,NULL,NULL,N'Моноплегия (отсутствие движений в 1 конечности), нарушение функции тазовых органов, потеря речи (понимание речи (сенсорная афазия), воспроизведение речи (моторная афазия), а также смешанная форма (сенсо-моторная афазия)',0.4,N'Страховая выплата в связи с последствиями травмы нервной системы, указанными в п.35 производится по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата производится дополнительно к страховой выплате, ранее произведенной в связи со страховыми событиями, приведшими к поражению нервной системы. Общая сумма выплат не может превышать 100%.',N'Решение о страховой выплате в связи с последствиями травмы нервной системы, указанными в п.35, принимается по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата осуществляется дополнительно к страховой сумме, выплаченной в связи со страховыми событиями, приведшими к повреждению нервной системы. Общая сумма выплат не может превышать 100% страховой суммы.
Таблица «Степени пареза»
0 баллов «силы мышц» – нет произвольных движений. Паралич.
1 балл – едва заметные сокращения мышц, без движений в суставах
2 балла – объём движений в суставе значительно снижен, движения возможны без преодоления силы тяжести по плоскости
3 балла – значительное сокращение объёма движений в суставе, мышцы способны преодолеть силу тяжести, трения (возможность отрыва конечности от поверхности)
4 балла – легкое снижение силы мышц, при полном объёме движения
5 баллов – нормальная сила мышц, полный объём движений
',N'Выплата по п.35.5 возможна только за один из видов нарушения функции.',NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'35',N'',N'35.6',NULL,NULL,NULL,NULL,N'Гемиплегия или параплегия отсутствие движений в 2 конечностях, слабоумие (деменция)',0.8,N'Страховая выплата в связи с последствиями травмы нервной системы, указанными в п.35 производится по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата производится дополнительно к страховой выплате, ранее произведенной в связи со страховыми событиями, приведшими к поражению нервной системы. Общая сумма выплат не может превышать 100%.',N'Решение о страховой выплате в связи с последствиями травмы нервной системы, указанными в п.35, принимается по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата осуществляется дополнительно к страховой сумме, выплаченной в связи со страховыми событиями, приведшими к повреждению нервной системы. Общая сумма выплат не может превышать 100% страховой суммы.
Таблица «Степени пареза»
0 баллов «силы мышц» – нет произвольных движений. Паралич.
1 балл – едва заметные сокращения мышц, без движений в суставах
2 балла – объём движений в суставе значительно снижен, движения возможны без преодоления силы тяжести по плоскости
3 балла – значительное сокращение объёма движений в суставе, мышцы способны преодолеть силу тяжести, трения (возможность отрыва конечности от поверхности)
4 балла – легкое снижение силы мышц, при полном объёме движения
5 баллов – нормальная сила мышц, полный объём движений
',N'Выплата по п.35.6 возможна только за один из видов нарушения функции',NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('UNL_1_20230401',N'СТОПА, ПАЛЬЦЫ СТОПЫ',N'35',N'',N'35.7',NULL,NULL,NULL,NULL,N'Тетраплегия отсутствие движений в 4 конечностях',1,N'Страховая выплата в связи с последствиями травмы нервной системы, указанными в п.35 производится по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата производится дополнительно к страховой выплате, ранее произведенной в связи со страховыми событиями, приведшими к поражению нервной системы. Общая сумма выплат не может превышать 100%.',N'Решение о страховой выплате в связи с последствиями травмы нервной системы, указанными в п.35, принимается по одному из подпунктов, учитывающему наиболее тяжелые последствия травмы, в том случае, если они установлены лечебно-профилактическим учреждением не ранее 3 (трех) месяцев со дня травмы и подтверждены справкой этого учреждения. При этом страховая выплата осуществляется дополнительно к страховой сумме, выплаченной в связи со страховыми событиями, приведшими к повреждению нервной системы. Общая сумма выплат не может превышать 100% страховой суммы.
Таблица «Степени пареза»
0 баллов «силы мышц» – нет произвольных движений. Паралич.
1 балл – едва заметные сокращения мышц, без движений в суставах
2 балла – объём движений в суставе значительно снижен, движения возможны без преодоления силы тяжести по плоскости
3 балла – значительное сокращение объёма движений в суставе, мышцы способны преодолеть силу тяжести, трения (возможность отрыва конечности от поверхности)
4 балла – легкое снижение силы мышц, при полном объёме движения
5 баллов – нормальная сила мышц, полный объём движений
',NULL,NULL); 
 GO 

