IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ARCHIVE_DOCUMENT_SYNC_BATCH]') AND type IN (N'P', N'RF', N'PC'))
BEGIN
DROP PROCEDURE dbo.ARCHIVE_DOCUMENT_SYNC_BATCH;
END
GO

CREATE PROCEDURE ARCHIVE_DOCUMENT_SYNC_BATCH
AS
BEGIN TRY
begin tran

	INSERT INTO BFX_IMPL.DOCUMENT_SYNC_BATCH_ARCH
	SELECT * FROM BFX.DOCUMENT_SYNC_BATCH
	WHERE STATUS = 2

    DELETE FROM BFX.DOCUMENT_SYNC_BATCH
	WHERE STATUS = 2

commit tran
END TRY
BEGIN CATCH
    ROLLBACK tran
    DECLARE @ErrorMessage NVARCHAR(4000); DECLARE @ErrorSeverity INT; DECLARE @ErrorState INT;
    SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = 1;
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState );
END CATCH;
GO