IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ARCHIVE_SERVICE_PROVIDER_HISTORY]') AND type IN (N'P', N'RF', N'PC'))
BEGIN
DROP PROCEDURE dbo.ARCHIVE_SERVICE_PROVIDER_HISTORY;
END
GO

CREATE PROCEDURE ARCHIVE_SERVICE_PROVIDER_HISTORY
AS
BEGIN TRY
begin tran

	INSERT INTO ORG_IMPL.SERVICE_PROVIDER_HISTORY_ARCH
	SELECT * FROM ORG.SERVICE_PROVIDER_HISTORY 
	WHERE SYS_CREATED_ON < dateadd(month, -1, getdate())

	DELETE FROM ORG.SERVICE_PROVIDER_HISTORY 
	WHERE SYS_CREATED_ON < dateadd(month, -1, getdate())

commit tran
END TRY
BEGIN CATCH
    ROLLBACK tran
    DECLARE @ErrorMessage NVARCHAR(4000); DECLARE @ErrorSeverity INT; DECLARE @ErrorState INT;
    SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = 1;
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState );
END CATCH;
GO