IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ARCHIVE_ATTACHMENT_RELATED_ENTITY]') AND type IN (N'P', N'RF', N'PC'))
BEGIN
DROP PROCEDURE dbo.ARCHIVE_ATTACHMENT_RELATED_ENTITY;
END
GO

CREATE PROCEDURE ARCHIVE_ATTACHMENT_RELATED_ENTITY
AS
BEGIN TRY
begin tran

	INSERT INTO BFX_IMPL.ATTACHMENT_RELATED_ENTITY_ARCH
	SELECT * FROM BFX.ATTACHMENT_RELATED_ENTITY 
	WHERE ATTACHMENT_ID IN (
		SELECT ATTACHMENT_ID FROM BFX.ATTACHMENT a
		WHERE UPLOAD_STATUS IN (3, 4)
	)

	DELETE FROM BFX.ATTACHMENT_RELATED_ENTITY 
	WHERE ATTACHMENT_ID IN (
		SELECT ATTACHMENT_ID FROM BFX.ATTACHMENT a
		WHERE UPLOAD_STATUS IN (3, 4)
	)

commit tran
END TRY
BEGIN CATCH
    ROLLBACK tran
    DECLARE @ErrorMessage NVARCHAR(4000); DECLARE @ErrorSeverity INT; DECLARE @ErrorState INT;
    SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = 1;
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState );
END CATCH;
GO