DROP VIEW IF EXISTS PAS_IMPL.CUMULATION_SAT_LATEST
GO
DROP VIEW IF EXISTS PAS_IMPL.CUMULATION_DOCUMENTS_SAT_LATEST
GO
DROP VIEW IF EXISTS PAS_IMPL.CUMULATION_RISKS_SAT_LATEST
GO
DROP TABLE IF EXISTS PAS_IMPL.CUMULATION_HUB
GO
DROP TABLE IF EXISTS PAS_IMPL.CUMULATION_SAT
GO
DROP TABLE IF EXISTS PAS_IMPL.CUMULATION_DOCUMENTS_SAT
GO
DROP TABLE IF EXISTS PAS_IMPL.CUMULATION_RISKS_SAT
GO
DROP TABLE IF EXISTS PAS_IMPL.CUMULATION_QUOTE_LINK
GO