DELETE FROM BFX.INTEGRATION_MESSAGE_ERROR
WHERE INTEGRATION_MESSAGE_ID IN (
	SELECT INTEGRATION_MESSAGE_ID FROM BFX_IMPL.INTEGRATION_MESSAGE_ERROR_ARCH
	WHERE INTEGRATION_MESSAGE_ID IN (
		SELECT INTEGRATION_MESSAGE_ID FROM BFX.INTEGRATION_MESSAGE_ERROR
	)
)