IF EXISTS (
SELECT *
  FROM SYS.INDEXES
 WHERE NAME = 'IDX_PARTY_DEDUP_INFO_IS_PROCESSED'
   AND OBJECT_ID = OBJECT_ID('PTY_IMPL.PARTY_DEDUP_INFO')
)
BEGIN
  DROP INDEX IDX_PARTY_DEDUP_INFO_IS_PROCESSED ON PTY_IMPL.PARTY_DEDUP_INFO
END
GO

CREATE NONCLUSTERED INDEX IDX_PARTY_DEDUP_INFO_IS_PROCESSED
ON PTY_IMPL.PARTY_DEDUP_INFO (IS_PROCESSED)
GO