-- Обновление даты окончания действия продукта PRODUCT_ACTIVE_TO в таблице PAS_IMPL.EFR_PRODUCT_RISK
-- датой действия продукта ACTIVE_TO из конфигурационного файла продуктов 
-- (configuration\@config-rgsl\life-insurance\lib\productConfiguration.xlsx)

-- Пример установки даты окончания действия продукта: 
-- UPDATE PAS_IMPL.EFR_PRODUCT_RISK 
-- SET PRODUCT_ACTIVE_TO = '2023-01-26'
-- WHERE PRODUCT_CODE = N'EBMBFKO' and PRODUCT_DESCRIPTION = N'Стратегия на пять'

-- Пример открытия продукта: 
-- UPDATE PAS_IMPL.EFR_PRODUCT_RISK 
-- SET PRODUCT_ACTIVE_TO = NULL
-- WHERE PRODUCT_CODE = N'EBMBFKO' and PRODUCT_DESCRIPTION = N'Стратегия на пять'

UPDATE PAS_IMPL.EFR_PRODUCT_RISK 
SET PRODUCT_ACTIVE_TO = NULL
WHERE PRODUCT_CODE = N'EBMBFKO' and PRODUCT_DESCRIPTION = N'Стратегия на пять'

UPDATE PAS_IMPL.EFR_PRODUCT_RISK 
SET PRODUCT_ACTIVE_TO = NULL
WHERE PRODUCT_CODE = N'EFRBFKO' and PRODUCT_DESCRIPTION = N'Финансовый резерв'

UPDATE PAS_IMPL.EFR_PRODUCT_RISK 
SET PRODUCT_ACTIVE_TO = NULL
WHERE PRODUCT_CODE = N'IBA3BFKO' and PRODUCT_DESCRIPTION = N'Базис Актив (3 года)'

UPDATE PAS_IMPL.EFR_PRODUCT_RISK 
SET PRODUCT_ACTIVE_TO = NULL
WHERE PRODUCT_CODE = N'IBA5BFKO' and PRODUCT_DESCRIPTION = N'Базис Актив (5 лет)'

UPDATE PAS_IMPL.EFR_PRODUCT_RISK 
SET PRODUCT_ACTIVE_TO = NULL
WHERE PRODUCT_CODE = N'IBG3BFKO' and PRODUCT_DESCRIPTION = N'Базис Гарант (3 года)'

UPDATE PAS_IMPL.EFR_PRODUCT_RISK 
SET PRODUCT_ACTIVE_TO = NULL
WHERE PRODUCT_CODE = N'IBG5BFKO' and PRODUCT_DESCRIPTION = N'Базис Гарант (5 лет)'

UPDATE PAS_IMPL.EFR_PRODUCT_RISK 
SET PRODUCT_ACTIVE_TO = NULL
WHERE PRODUCT_CODE = N'IBI3BFKO' and PRODUCT_DESCRIPTION = N'Базис Инвест (3 года)'

UPDATE PAS_IMPL.EFR_PRODUCT_RISK 
SET PRODUCT_ACTIVE_TO = NULL
WHERE PRODUCT_CODE = N'IBI5BFKO' and PRODUCT_DESCRIPTION = N'Базис Инвест (5 лет)'