IF EXISTS (select * from sys.objects where object_id = object_id(N'[ACC_IMPL].[CRT_SAT]') and type in (N'U'))
BEGIN
    IF COL_LENGTH('ACC_IMPL.CRT_SAT','IS_INSURER_SEND_DATA_TO_FNS') IS NOT NULL
    BEGIN
		WITH DIFF AS(
			SELECT CS.CRT_HKEY AS CRT_HKEY
			FROM ACC_IMPL.CRT_SAT_LATEST CS 
			JOIN ACC_IMPL.CRT_HUB CH ON CS.CRT_HKEY = CH.CRT_HKEY
			JOIN BFX.UNIVERSAL_DOCUMENT UD ON CH.CERTIFICATE_NUMBER = UD.UNIVERSAL_DOCUMENT_NUMBER
			WHERE JSON_VALUE(BODY, '$.contract.isInsurerSendDataToFns') = 'true'
			AND CS.IS_INSURER_SEND_DATA_TO_FNS <> 1
		)
        UPDATE ACC_IMPL.CRT_SAT
        SET IS_INSURER_SEND_DATA_TO_FNS = 1
		WHERE ACC_IMPL.CRT_SAT.CRT_HKEY IN (SELECT CRT_HKEY FROM DIFF)
    END
END
GO