IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[RECOMMENDED_STRATEGIES_BACKUP]') AND TYPE IN (N'U'))
BEGIN

	SELECT *
	INTO PAS_IMPL.RECOMMENDED_STRATEGIES_BACKUP
	FROM PAS_IMPL.RECOMMENDED_STRATEGIES;

END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[RECOMMENDED_STRATEGIES_BACKUP]') AND TYPE IN (N'U'))
BEGIN

	DROP TABLE PAS_IMPL.RECOMMENDED_STRATEGIES

END
GO
