UPDATE ud
SET BODY = JSON_MODIFY(BODY, '$.lastFundStatus', NULL)
FROM BFX.UNIVERSAL_DOCUMENT ud
LEFT JOIN CFX.PUBLISHED_ARTIFACT pa ON pa.PUBLISHED_ARTIFACT_ID = ud.PUBLISHED_ARTIFACT_ID
WHERE pa.CODE_NAME = 'LifeInsuranceRequest'
AND JSON_VALUE(BODY, '$.lastFundStatus') IS NOT NULL
