UPDATE inqSat SET TEXT_OF_ANSWER = JSON_VALUE(inqDoc.BODY, '$.textOfAnswer'), TEXT_OF_COMMENT = JSON_VALUE(inqDoc.BODY, '$.textOfComment'), TEXT_OF_INQUIRY = JSON_VALUE(inqDoc.BODY, '$.textOfInquiry') 
FROM
PAS_IMPL.INQUIRY_HUB inqHub
JOIN PAS_IMPL.INQUIRY_SAT inqSat ON inqSat.INQUIRY_HKEY = inqHub.INQUIRY_HKEY
JOIN BFX.UNIVERSAL_DOCUMENT inqDoc ON inqDoc.UNIVERSAL_DOCUMENT_NUMBER = inqHub.INQUIRY_NUMBER


UPDATE inqSat SET TEXT_OF_ANSWER = JSON_VALUE(inqDoc.BODY, '$.textOfAnswer'), TEXT_OF_COMMENT = JSON_VALUE(inqDoc.BODY, '$.textOfComment'), TEXT_OF_INQUIRY = JSON_VALUE(inqDoc.BODY, '$.textOfInquiry') 
FROM
EWT_IMPL.ENDOWMENT_INQUIRY_HUB inqHub
JOIN EWT_IMPL.ENDOWMENT_INQUIRY_SAT inqSat ON inqSat.ENDOWMENT_INQUIRY_HKEY = inqHub.ENDOWMENT_INQUIRY_HKEY
JOIN BFX.UNIVERSAL_DOCUMENT inqDoc ON inqDoc.UNIVERSAL_DOCUMENT_NUMBER = inqHub.INQUIRY_NUMBER