-- Backup reinsurance --
SELECT *
INTO PAS_IMPL.REINSURANCE_BACKUP
FROM PAS_IMPL.REINSURANCE;

-- Clean reinsurance --
DELETE r
FROM PAS_IMPL.REINSURANCE r
LEFT JOIN ORG_IMPL.SERVICE_PROVIDER_INFO_SAT_LATEST spis on spis.PARTNER_CODE = CAST(r.REINSURER_CODE as nvarchar)
WHERE spis.PARTNER_CODE IS NULL