IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = N'API_SENDER'
          AND Object_ID = OBJECT_ID(N'BFX_IMPL.SEND_EVENT_CONFIGURATION'))
BEGIN
	PRINT('Adding API_SENDER column')
    ALTER TABLE BFX_IMPL.SEND_EVENT_CONFIGURATION
	ADD API_SENDER NVARCHAR(50)
END
GO

BEGIN
	UPDATE BFX_IMPL.SEND_EVENT_CONFIGURATION
	SET API_SENDER = 'API_EFR'
	WHERE SUBSCRIBER = 'EFR' 
		AND API_SENDER IS NULL
END
GO