INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НЕРВНАЯ СИСТЕМА',N'1',NULL,NULL,NULL,NULL,NULL,NULL,N'Сдавление субдуральной и эпидуаральной (внутримозговой) травматической гематомой',0.2,N'Страховая выплата в соответствии со п. 01 производится при условии подтверждения установленного диагноза методами КТ и/или МРТ, при лечении в условиях стационара не менее 10 дней.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НЕРВНАЯ СИСТЕМА',N'2',NULL,NULL,NULL,NULL,NULL,NULL,N'Размозжение вещества головного мозга (без указания симптоматики)',0.5,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НЕРВНАЯ СИСТЕМА',N'3',N'Повреждение нервной системы (травматическое, токсическое, гипоксическое), повлекшее за собой:',N'а)',NULL,NULL,NULL,NULL,N'моноплегию (паралич одной конечности)',0.6,N'Страховая выплата в соответствии с п. 03 производится при условии установления диагноза лечебно-профилактическим учреждением не ранее чем через 3 месяца со дня травмы и подтверждения диагноза справкой этого учреждения.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НЕРВНАЯ СИСТЕМА',N'3',N'Повреждение нервной системы (травматическое, токсическое, гипоксическое), повлекшее за собой:',N'б)',NULL,NULL,NULL,NULL,N'тетрапарез (парез верхних и нижних конечностей), нарушение координации движений, слабоумие (деменцию)',0.7,N'Страховая выплата в соответствии с п. 03 производится при условии установления диагноза лечебно-профилактическим учреждением не ранее чем через 3 месяца со дня травмы и подтверждения диагноза справкой этого учреждения.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НЕРВНАЯ СИСТЕМА',N'3',N'Повреждение нервной системы (травматическое, токсическое, гипоксическое), повлекшее за собой:',N'в)',NULL,NULL,NULL,NULL,N'геми-, пара- или тетраплегию, афазию, потерю речи, декортикацию, нарушение функции тазовых органов',1,N'Страховая выплата в соответствии с п. 03 производится при условии установления диагноза лечебно-профилактическим учреждением не ранее чем через 3 месяца со дня травмы и подтверждения диагноза справкой этого учреждения.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НЕРВНАЯ СИСТЕМА',N'4',N'Повреждение спинного мозга на любом уровне, конского хвоста, полиомиелит, без указания симптомов:',N'а)',NULL,NULL,NULL,NULL,N'частичный разрыв',0.5,N'Страховая выплата в соответствии со п. 04 производится при условии подтверждения установленного диагноза методами КТ и/или МРТ, при лечении в условиях стационара не менее 10 дней.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НЕРВНАЯ СИСТЕМА',N'4',N'Повреждение спинного мозга на любом уровне, конского хвоста, полиомиелит, без указания симптомов:',N'б)',NULL,NULL,NULL,NULL,N'полный перерыв спинного мозга',1,N'Страховая выплата в соответствии со п. 04 производится при условии подтверждения установленного диагноза методами КТ и/или МРТ, при лечении в условиях стационара не менее 10 дней.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НЕРВНАЯ СИСТЕМА',N'5',N'Повреждение (перерыв, ранение) шейного, плечевого, поясничного, крестцового сплетений:',N'а)',NULL,NULL,NULL,NULL,N'частичный разрыв сплетения',0.4,N'Невралгии, невропатии, возникшие в связи с травмой, не дают основания для осуществления страховой выплаты.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НЕРВНАЯ СИСТЕМА',N'5',N'Повреждение (перерыв, ранение) шейного, плечевого, поясничного, крестцового сплетений:',N'б)',NULL,NULL,NULL,NULL,N'перерыв сплетения',0.7,N'Невралгии, невропатии, возникшие в связи с травмой, не дают основания для осуществления страховой выплаты.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НЕРВНАЯ СИСТЕМА',N'6',NULL,NULL,NULL,NULL,NULL,NULL,N'Перерыв двух и более нервов: подмышечного, лучевого, локтевого, срединного – на уровне локтевого сустава и плеча, седалищного и бедренного',0.4,N'Страховая выплата в соответствии со п.п. 05-06 производится при условии подтверждения установленного диагноза методом электронейромиографии.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОРГАНЫ ЗРЕНИЯ',N'7',NULL,NULL,NULL,NULL,NULL,NULL,N'Повреждение глаза (глаз), повлекшее за собой полную потерю зрения единственного глаза или обоих глаз, обладавших зрением не ниже 0,01',1,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОРГАНЫ СЛУХА',N'8',N'Повреждение центральной и/или периферической части слухового анализатора, повлекшее за собой полную глухоту (разговорная речь – 0)',N'а)',NULL,NULL,NULL,NULL,N'на одно ',0.5,N'Решение о выплате страховой суммы в связи со снижением в результате травмы слуха принимается после окончания лечения, но не ранее 3 месяцев со дня травмы на основании заключения ЛОР-специалиста и результатами аудиометрии.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОРГАНЫ СЛУХА',N'8',N'Повреждение центральной и/или периферической части слухового анализатора, повлекшее за собой полную глухоту (разговорная речь – 0)',N'б)',NULL,NULL,NULL,NULL,N'оба уха',1,N'Решение о выплате страховой суммы в связи со снижением в результате травмы слуха принимается после окончания лечения, но не ранее 3 месяцев со дня травмы на основании заключения ЛОР-специалиста и результатами аудиометрии.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ДЫХАТЕЛЬНАЯ СИСТЕМА',N'9',NULL,NULL,NULL,NULL,NULL,NULL,N'Повреждение грудной клетки и ее органов, повлекшее за собой удаление одного легкого.',0.6,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ДЫХАТЕЛЬНАЯ СИСТЕМА',N'10',NULL,NULL,NULL,NULL,NULL,NULL,N'Проникающее ранение грудной клетки, торакотомия, произведенная в связи с травмой при повреждении органов грудной полости.',0.15,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'СЕРДЕЧНО-СОСУДИСТАЯ СИСТЕМА',N'11',NULL,NULL,NULL,NULL,NULL,NULL,N'Повреждение сердца, его оболочек и крупных магистральных сосудов, повлекшее за собой сердечно-сосудистую недостаточность II – III степени.',0.25,N'Если в справке не указана степень сердечно-сосудистой недостаточности, страховая выплата не производится.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОРГАНЫ ПИЩЕВАРЕНИЯ',N'12',NULL,NULL,NULL,NULL,NULL,NULL,N'Повреждение челюсти, повлекшее за собой полное отсутствие челюсти.',0.8,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОРГАНЫ ПИЩЕВАРЕНИЯ',N'13',NULL,NULL,NULL,NULL,NULL,NULL,N'Повреждение языка, повлекшее за собой отсутствие языка на уровне корня или полное отсутствие языка.',0.6,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОРГАНЫ ПИЩЕВАРЕНИЯ',N'14',N' Повреждение (разрыв, ожог, ранение) органов пищеварения, случайное острое отравление, повлекшее за собой:',N'а)',NULL,NULL,NULL,NULL,N'кишечный свищ, кишечно-влагалищный свищ, свищ поджелудочной железы',0.5,N'При осложнениях травмы, предусмотренных в п.п. 14 а), 14 б) по истечении 6 месяцев после травмы. Указанные осложнения травмы признаются только в том случае, если они подтверждены справкой лечебно-профилактического учреждения.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОРГАНЫ ПИЩЕВАРЕНИЯ',N'14',N' Повреждение (разрыв, ожог, ранение) органов пищеварения, случайное острое отравление, повлекшее за собой:',N'б)',NULL,NULL,NULL,NULL,N'противоестественный задний проход (колостома)',1,N'При осложнениях травмы, предусмотренных в п.п. 14 а), 14 б) по истечении 6 месяцев после травмы. Указанные осложнения травмы признаются только в том случае, если они подтверждены справкой лечебно-профилактического учреждения.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОРГАНЫ ПИЩЕВАРЕНИЯ',N'15',N'Повреждение печени, желчного пузыря, повлекшие за собой:',N'а)',NULL,NULL,NULL,NULL,N'удаление части печени',0.25,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОРГАНЫ ПИЩЕВАРЕНИЯ',N'15',N'Повреждение печени, желчного пузыря, повлекшие за собой:',N'б)',NULL,NULL,NULL,NULL,N'удаление части печени и желчного пузыря',0.35,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОРГАНЫ ПИЩЕВАРЕНИЯ',N'16',NULL,NULL,NULL,NULL,NULL,NULL,N'Повреждение желудка, повлекшее за собой удаление желудка.',0.6,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'МОЧЕВЫДЕЛИТЕЛЬНАЯ И ПОЛОВАЯ СИСТЕМЫ',N'17',NULL,NULL,NULL,NULL,NULL,NULL,N'Повреждение почки, повлекшее за собой удаление почки.',0.6,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'МОЧЕВЫДЕЛИТЕЛЬНАЯ И ПОЛОВАЯ СИСТЕМЫ',N'18',NULL,NULL,NULL,NULL,NULL,NULL,N'Повреждение органов мочевыделительной системы (почек, мочеточников, мочевого пузыря, мочеиспускательного канала), повлекшее за собой синдром длительного раздавливания (травматический токсикоз, краш-синдром, синдром размозжения), хроническую почечную недостаточность.',0.3,N'Страховая выплата по п. 18 в связи с последствиями травмы производится только в том случае, если указанные осложнения имеются по истечении 3 месяцев после травмы. Ранее этого срока страховая выплата производится по п. 17 и размер выплаты, произведенной по данной статье, не учитывается при выплате по п. 18.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'МОЧЕВЫДЕЛИТЕЛЬНАЯ И ПОЛОВАЯ СИСТЕМЫ',N'19',N'Повреждение половой системы, повлекшее за собой:',N'а)',N'потерю матки у женщин в возрасте:',NULL,NULL,NULL,N'до 39 лет включительно',0.5,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'МОЧЕВЫДЕЛИТЕЛЬНАЯ И ПОЛОВАЯ СИСТЕМЫ',N'19',N'Повреждение половой системы, повлекшее за собой:',N'а)',N'потерю матки у женщин в возрасте:',NULL,NULL,NULL,N'с 40 до 49 лет включительно',0.3,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'МОЧЕВЫДЕЛИТЕЛЬНАЯ И ПОЛОВАЯ СИСТЕМЫ',N'19',N'Повреждение половой системы, повлекшее за собой:',N'а)',N'потерю матки у женщин в возрасте:',NULL,NULL,NULL,N'50 лет и старше',0.15,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'МОЧЕВЫДЕЛИТЕЛЬНАЯ И ПОЛОВАЯ СИСТЕМЫ',N'19',N'Повреждение половой системы, повлекшее за собой:',N'б)',NULL,NULL,NULL,NULL,N'потерю полового члена и обоих яичек',0.5,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ПОЗВОНОЧНИК',N'20',NULL,NULL,NULL,NULL,NULL,NULL,N'Перелом или переломо-вывих 6 и более тел, дужек и суставных отростков позвонков (за исключением крестца и копчика)',0.4,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ВЕРХНЯЯ КОНЕЧНОСТЬ. ПЛЕЧЕВОЙ СУСТАВ',N'21',N'Повреждения плечевого пояса, повлекшие за собой:',N'а)',NULL,NULL,NULL,NULL,N'отсутствие движений в суставе (анкилоз)',0.2,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ВЕРХНЯЯ КОНЕЧНОСТЬ. ПЛЕЧЕВОЙ СУСТАВ',N'21',N'Повреждения плечевого пояса, повлекшие за собой:',N'б)',NULL,NULL,NULL,NULL,N'«болтающийся» плечевой сустав в результате резекции суставных поверхностей составляющих его костей',0.4,N'Страховая выплата по п. 21 производится с том случае, если перечисленные в этой статье осложнения будут установлены лечебно-профилактическим учреждением по истечении 6 месяцев после травмы и подтверждены справкой этого учреждения.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ВЕРХНЯЯ КОНЕЧНОСТЬ. ПЛЕЧО',N'22',N'Травматическая ампутация верхней конечности или тяжелое повреждение, приведшее к ампутации:',N'а)',NULL,NULL,NULL,NULL,N'с лопаткой, ключицей или их частью',0.8,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ВЕРХНЯЯ КОНЕЧНОСТЬ. ПЛЕЧО',N'22',N'Травматическая ампутация верхней конечности или тяжелое повреждение, приведшее к ампутации:',N'б)',NULL,NULL,NULL,NULL,N'плеча на любом уровне',0.75,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ВЕРХНЯЯ КОНЕЧНОСТЬ. ПЛЕЧО',N'22',N'Травматическая ампутация верхней конечности или тяжелое повреждение, приведшее к ампутации:',N'в)',NULL,NULL,NULL,NULL,N'единственной конечности на уровне плеча',1,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ВЕРХНЯЯ КОНЕЧНОСТЬ. ЛОКТЕВОЙ СУСТАВ',N'23',N'Повреждение области локтевого сустава, повлекшее за собой:',N'а)',NULL,NULL,NULL,NULL,N'отсутствие движений в суставе (анкилоз)',0.2,N'Страховая выплата по п. 23 производится в том случае, если нарушение движений в этом суставе будет установлено лечебно-профилактическим учреждением по истечении 6 месяцев после травмы и подтверждено справкой этого учреждения.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ВЕРХНЯЯ КОНЕЧНОСТЬ. ЛОКТЕВОЙ СУСТАВ',N'23',N'Повреждение области локтевого сустава, повлекшее за собой:',N'б)',NULL,NULL,NULL,NULL,N'«болтающийся» локтевой сустав (в результате резекции суставных поверхностей составляющих его костей)',0.3,N'Страховая выплата по п. 23 производится в том случае, если нарушение движений в этом суставе будет установлено лечебно-профилактическим учреждением по истечении 6 месяцев после травмы и подтверждено справкой этого учреждения.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ВЕРХНЯЯ КОНЕЧНОСТЬ. ПРЕДПЛЕЧЬЕ',N'24',N'Тяжелое повреждение, приведшее: ',N'а)',NULL,NULL,NULL,NULL,N'к ампутации предплечья на любом уровне',0.65,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ВЕРХНЯЯ КОНЕЧНОСТЬ. ПРЕДПЛЕЧЬЕ',N'24',N'Тяжелое повреждение, приведшее: ',N'б)',NULL,NULL,NULL,NULL,N'к экзартикуляции в локтевом суставе',0.7,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ВЕРХНЯЯ КОНЕЧНОСТЬ. ПРЕДПЛЕЧЬЕ',N'24',N'Тяжелое повреждение, приведшее: ',N'в)',NULL,NULL,NULL,NULL,N'к ампутации единственной конечности на уровне предплечья',1,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ВЕРХНЯЯ КОНЕЧНОСТЬ. КИСТЬ',N'25',N'Повреждение кисти, повлекшее за собой:',N'а)',NULL,NULL,NULL,NULL,N'потерю всех пальцев, ампутацию на уровне пястных костей запястья или лучезапястного сустава',0.65,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ВЕРХНЯЯ КОНЕЧНОСТЬ. КИСТЬ',N'25',N'Повреждение кисти, повлекшее за собой:',N'б)',NULL,NULL,NULL,NULL,N'бампутацию единственной кисти',1,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ТАЗ',N'26',NULL,NULL,NULL,NULL,NULL,NULL,N'Повреждения таза в двух суставах, повлекшие за собой отсутствие движений в тазобедренных суставах.',0.4,N'Страховая выплата в связи с нарушением функции тазобедренных суставов выплачивается по п. 26 в том случае, если отсутствие движений в суставе будет установлено лечебно-профилактическим учреждением через 6 месяцев после травмы и подтверждено справкой этого учреждения.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НИЖНЯЯ КОНЕЧНОСТЬ. ТАЗОБЕДРЕННЫЙ СУСТАВ',N'27',N'Повреждения тазобедренного сустава, повлекшие за собой:',N'а)',NULL,NULL,NULL,NULL,N'отсутствие движений (анкилоз)',0.2,N'Страховая сумма по п.п. 27 а), 27 б), 27 г) выплачивается в том случае, если это осложнение травмы будет установлено в лечебно-профилактическом учреждении по истечении 6 месяцев после травмы и подтверждено справкой этого учреждения.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НИЖНЯЯ КОНЕЧНОСТЬ. ТАЗОБЕДРЕННЫЙ СУСТАВ',N'27',N'Повреждения тазобедренного сустава, повлекшие за собой:',N'б)',NULL,NULL,NULL,NULL,N'несросшийся перелом (ложный сустав) шейки бедра',0.3,N'Страховая сумма по п.п. 27 а), 27 б), 27 г) выплачивается в том случае, если это осложнение травмы будет установлено в лечебно-профилактическом учреждении по истечении 6 месяцев после травмы и подтверждено справкой этого учреждения.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НИЖНЯЯ КОНЕЧНОСТЬ. ТАЗОБЕДРЕННЫЙ СУСТАВ',N'27',N'Повреждения тазобедренного сустава, повлекшие за собой:',N'в)',NULL,NULL,NULL,NULL,N'эндопротезирование',0.4,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НИЖНЯЯ КОНЕЧНОСТЬ. ТАЗОБЕДРЕННЫЙ СУСТАВ',N'27',N'Повреждения тазобедренного сустава, повлекшие за собой:',N'г)',NULL,NULL,NULL,NULL,N'“болтающийся” сустав в результате резекции головки бедра',0.45,N'Страховая сумма по п.п. 27 а), 27 б), 27 г) выплачивается в том случае, если это осложнение травмы будет установлено в лечебно-профилактическом учреждении по истечении 6 месяцев после травмы и подтверждено справкой этого учреждения.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НИЖНЯЯ КОНЕЧНОСТЬ. ТАЗОБЕДРЕННЫЙ СУСТАВ',N'27',N'Повреждения тазобедренного сустава, повлекшие за собой:',N'д)',NULL,NULL,NULL,NULL,N'Травматическую ампутацию бедра ',0.65,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НИЖНЯЯ КОНЕЧНОСТЬ. ТАЗОБЕДРЕННЫЙ СУСТАВ',N'27',N'Повреждения тазобедренного сустава, повлекшие за собой:',N'е)',NULL,NULL,NULL,NULL,N'Травматическую ампутацию бедра единственного ',0.75,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НИЖНЯЯ КОНЕЧНОСТЬ. КОЛЕННЫЙ СУСТАВ',N'28',N'Повреждения области коленного сустава, повлекшие за собой:',N'а)',NULL,NULL,NULL,NULL,N'отсутствие движений в суставе',0.2,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НИЖНЯЯ КОНЕЧНОСТЬ. КОЛЕННЫЙ СУСТАВ',N'28',N'Повреждения области коленного сустава, повлекшие за собой:',N'б)',NULL,NULL,NULL,NULL,N'«болтающийся» коленный сустав в результате резекции суставных поверхностей составляющих его костей',0.3,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НИЖНЯЯ КОНЕЧНОСТЬ. КОЛЕННЫЙ СУСТАВ',N'28',N'Повреждения области коленного сустава, повлекшие за собой:',N'в)',NULL,NULL,NULL,NULL,N'эндопротезирование в течении 3 месяцев с момента получения травмы',0.4,NULL,NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НИЖНЯЯ КОНЕЧНОСТЬ. ГОЛЕНЬ',N'29',N'Тяжелое повреждение, повлекшее за собой:',N'а)',NULL,NULL,NULL,NULL,N'ампутацию голени на любом уровне',0.6,N'Страховая выплата в связи с осложнениями, предусмотренными п.п. 29 – 31 а) в том случае, если они будут установлены лечебно-профилактическим учреждением по истечении 6 месяцев после травмы и подтверждены справкой этого учреждения, а по п.п. 31 б), 31 в), 31 г) – независимо от срока, прошедшего со дня травмы.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НИЖНЯЯ КОНЕЧНОСТЬ. ГОЛЕНЬ',N'29',N'Тяжелое повреждение, повлекшее за собой:',N'б)',NULL,NULL,NULL,NULL,N'экзартикуляцию в коленном суставе',0.7,N'Страховая выплата в связи с осложнениями, предусмотренными п.п. 29 – 31 а) в том случае, если они будут установлены лечебно-профилактическим учреждением по истечении 6 месяцев после травмы и подтверждены справкой этого учреждения, а по п.п. 31 б), 31 в), 31 г) – независимо от срока, прошедшего со дня травмы.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НИЖНЯЯ КОНЕЧНОСТЬ. ГОЛЕНЬ',N'29',N'Тяжелое повреждение, повлекшее за собой:',N'в)',NULL,NULL,NULL,NULL,N'ампутацию единственной конечности на любом уровне голени',1,N'Страховая выплата в связи с осложнениями, предусмотренными п.п. 29 – 31 а) в том случае, если они будут установлены лечебно-профилактическим учреждением по истечении 6 месяцев после травмы и подтверждены справкой этого учреждения, а по п.п. 31 б), 31 в), 31 г) – независимо от срока, прошедшего со дня травмы.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НИЖНЯЯ КОНЕЧНОСТЬ. ГОЛЕНОСТОПНЫЙ СУСТАВ',N'30',N'Повреждение области голеностопного сустава, повлекшее за собой:',N'а)',NULL,NULL,NULL,NULL,N'отсутствие движений в голеностопном суставе',0.2,N'Страховая выплата в связи с осложнениями, предусмотренными п.п. 29 – 31 а) в том случае, если они будут установлены лечебно-профилактическим учреждением по истечении 6 месяцев после травмы и подтверждены справкой этого учреждения, а по п.п. 31 б), 31 в), 31 г) – независимо от срока, прошедшего со дня травмы.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НИЖНЯЯ КОНЕЧНОСТЬ. ГОЛЕНОСТОПНЫЙ СУСТАВ',N'30',N'Повреждение области голеностопного сустава, повлекшее за собой:',N'б)',NULL,NULL,NULL,NULL,N'болтающийся голеностопный сустав (в результате резекции суставных поверхностей составляющих его костей)',0.4,N'Страховая выплата в связи с осложнениями, предусмотренными п.п. 29 – 31 а) в том случае, если они будут установлены лечебно-профилактическим учреждением по истечении 6 месяцев после травмы и подтверждены справкой этого учреждения, а по п.п. 31 б), 31 в), 31 г) – независимо от срока, прошедшего со дня травмы.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НИЖНЯЯ КОНЕЧНОСТЬ. ГОЛЕНОСТОПНЫЙ СУСТАВ',N'30',N'Повреждение области голеностопного сустава, повлекшее за собой:',N'в)',NULL,NULL,NULL,NULL,N'экзартикуляцию в голеностопном суставе',0.5,N'Страховая выплата в связи с осложнениями, предусмотренными п.п. 29 – 31 а) в том случае, если они будут установлены лечебно-профилактическим учреждением по истечении 6 месяцев после травмы и подтверждены справкой этого учреждения, а по п.п. 31 б), 31 в), 31 г) – независимо от срока, прошедшего со дня травмы.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НИЖНЯЯ КОНЕЧНОСТЬ. СТОПА',N'31',N'Повреждения стопы, повлекшие за собой:',N'а)',NULL,NULL,NULL,NULL,N'артродез подтаранного сустава, поперечного сустава предплюсны (Шопара) или предплюсне-плюсневого (Лисфранка)',0.2,N'Страховая выплата в связи с осложнениями, предусмотренными п.п. 29 – 31 а) в том случае, если они будут установлены лечебно-профилактическим учреждением по истечении 6 месяцев после травмы и подтверждены справкой этого учреждения, а по п.п. 31 б), 31 в), 31 г) – независимо от срока, прошедшего со дня травмы.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НИЖНЯЯ КОНЕЧНОСТЬ. СТОПА',N'31',N'Повреждения стопы, повлекшие за собой:',N'б)',NULL,NULL,NULL,NULL,N'плюснефаланговых суставов (отсутствие всех пальцев стопы)',0.3,N'Страховая выплата в связи с осложнениями, предусмотренными п.п. 29 – 31 а) в том случае, если они будут установлены лечебно-профилактическим учреждением по истечении 6 месяцев после травмы и подтверждены справкой этого учреждения, а по п.п. 31 б), 31 в), 31 г) – независимо от срока, прошедшего со дня травмы.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НИЖНЯЯ КОНЕЧНОСТЬ. СТОПА',N'31',N'Повреждения стопы, повлекшие за собой:',N'в)',NULL,NULL,NULL,NULL,N'плюсневых костей или предплюсны',0.4,N'Страховая выплата в связи с осложнениями, предусмотренными п.п. 29 – 31 а) в том случае, если они будут установлены лечебно-профилактическим учреждением по истечении 6 месяцев после травмы и подтверждены справкой этого учреждения, а по п.п. 31 б), 31 в), 31 г) – независимо от срока, прошедшего со дня травмы.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'НИЖНЯЯ КОНЕЧНОСТЬ. СТОПА',N'31',N'Повреждения стопы, повлекшие за собой:',N'г)',NULL,NULL,NULL,NULL,N'таранной, пяточной костей (потеря стопы)',0.5,N'Страховая выплата в связи с осложнениями, предусмотренными п.п. 29 – 31 а) в том случае, если они будут установлены лечебно-профилактическим учреждением по истечении 6 месяцев после травмы и подтверждены справкой этого учреждения, а по п.п. 31 б), 31 в), 31 г) – независимо от срока, прошедшего со дня травмы.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОГНЕСТРЕЛЬНЫЕ РАНЕНИЯ',N'32',NULL,NULL,NULL,NULL,NULL,NULL,N'Сквозные множественные ранения без повреждения костей, сосудов, внутренних органов:',0.3,N'При инфицированном ранении размер страховой выплаты по п. 32 увеличивается на 10%.',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОГНЕСТРЕЛЬНЫЕ РАНЕНИЯ',N'33',NULL,NULL,NULL,NULL,NULL,NULL,N'Слепое ранение без повреждения костей, сосудов, внутренних органов',0.25,N'При множественных ранениях, каждая рана, начиная со второй, увеличивает размер страховой выплаты по п. 33 на 10%, максимальный размер выплаты в связи с множественными ранениями составляет 40% от страховой суммы по данному риску.',N'При инфицированном ранении размер страховой выплаты по п. 33 увеличивается на 10%.',NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 5 до 10 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IIIА',0,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 5 до 10 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IIIБ',0.17,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 5 до 10 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IV',0.2,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 11 до 20 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IIIА',0.2,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 11 до 20 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IIIБ',0.25,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 11 до 20 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IV',0.35,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 21 до 30 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IIIА',0.25,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 21 до 30 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IIIБ',0.45,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 21 до 30 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IV',0.55,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 31 до 40 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IIIА',0.3,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 31 до 40 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IIIБ',0.7,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 31 до 40 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IV',0.8,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 41 до 50 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IIIА',0.4,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 41 до 50 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IIIБ',0.85,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 41 до 50 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IV',0.95,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 51 до 60 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IIIА',0.5,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 51 до 60 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IIIБ',0.95,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 51 до 60 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IV',1,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 71 до 80 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IIIА',0.6,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 71 до 80 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IIIБ',1,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 71 до 80 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IV',1,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 81 до 90 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IIIА',0.7,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 81 до 90 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IIIБ',1,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'от 81 до 90 включительно',NULL,N'Степень ожога/обморожения',NULL,N'IV',1,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'более 91',NULL,N'Степень ожога/обморожения',NULL,N'IIIА',0.8,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'более 91',NULL,N'Степень ожога/обморожения',NULL,N'IIIБ',1,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'ОЖОГИ, ОБМОРОЖЕНИЯ',N'34',N'Площадь ожога/обморожения (в % от поверхности тела)',NULL,N'более 91',NULL,N'Степень ожога/обморожения',NULL,N'IV',1,N'1% поверхности тела принимается равным площади ладонной поверхности его кисти и пальцев',NULL,NULL,NULL); 
 GO 

INSERT INTO BFX_IMPL.INJURY_GENERAL (RULE_CODE,INJURY_GROUP,SUBGROUP_CODE_LEVEL_1,SUBGROUP_DESCRIPTION_LEVEL_1,SUBGROUP_CODE_LEVEL_2,SUBGROUP_DESCRIPTION_LEVEL_2,SUBGROUP_CODE_LEVEL_3,SUBGROUP_DESCRIPTION_LEVEL_3,SUBGROUP_CODE_LEVEL_4,INJURY_DESCRIPTION,INSURANCE_SUM_RATE,NOTE1,NOTE2,NOTE3,NOTE4) VALUES ('AL_1_20210701',N'Ожоги дыхательных путей',N'35',NULL,NULL,NULL,NULL,NULL,NULL,N'Ожоги дыхательных путей',0.3,NULL,NULL,NULL,NULL); 
 GO 

