INSERT INTO PAS_IMPL.AA_HUB (AA_HKEY, LOAD_DATE, RECORD_SOURCE, AA_NUMBER) SELECT AA_HKEY, LOAD_DATE, RECORD_SOURCE, AA_NUMBER FROM PAS.AA_HUB

INSERT INTO PAS_IMPL.AA_BASE_SAT (AA_BASE_HKEY, LOAD_DATE, RECORD_SOURCE, HASH_DIFF, TITLE, AGENT, START_DATE, END_DATE) SELECT AA_HKEY,  LOAD_DATE, RECORD_SOURCE, HASH_DIFF, TITLE, AGENT, START_DATE, END_DATE FROM PAS.AA_SAT

INSERT INTO PAS_IMPL.AA_COMM_LINK (AA_COMM_HKEY, LOAD_DATE, RECORD_SOURCE, AA_HKEY, AA_COMM_TYPE_HKEY) SELECT AA_COMM_HKEY, LOAD_DATE, RECORD_SOURCE, AA_HKEY, AA_COMM_TYPE_HKEY FROM PAS.AA_COMM_LINK

INSERT INTO PAS_IMPL.AA_COMM_TYPE_HUB (AA_COMM_TYPE_HKEY, LOAD_DATE, RECORD_SOURCE, COMMISSION_TYPE) SELECT AA_COMM_TYPE_HKEY, LOAD_DATE, RECORD_SOURCE, COMMISSION_TYPE FROM PAS.AA_COMM_TYPE_HUB

INSERT INTO PAS_IMPL.AA_ORGANISATION_UNIT_SAT (AA_ORGANISATION_UNIT_HKEY, LOAD_DATE, RECORD_SOURCE, HASH_DIFF, CODE) SELECT AA_ORGANISATION_UNIT_HKEY, LOAD_DATE, RECORD_SOURCE,HASH_DIFF, CODE FROM PAS.AA_ORGANISATION_UNIT_SAT

INSERT INTO PAS_IMPL.AA_SALES_CHANNEL_SAT (AA_SALES_CHANNEL_HKEY, LOAD_DATE, RECORD_SOURCE, HASH_DIFF, CODE) SELECT AA_SALES_CHANNEL_HKEY, LOAD_DATE, RECORD_SOURCE,HASH_DIFF, CODE FROM PAS.AA_SALES_CHANNEL_SAT