BEGIN TRAN

DECLARE @roleId NVARCHAR(100)
DECLARE @groupId NVARCHAR(100)

SELECT @roleId = APPLICATION_ROLE_ID FROM CFG.APPLICATION_ROLE WHERE CODE_NAME = 'ClaimSecondLine'
SELECT @groupId = APPLICATION_USER_GROUP_ID FROM ORG.APPLICATION_USER_GROUP WHERE APPLICATION_USER_GROUP_CODE = 'claimSecondLine'

DELETE FROM CFX.USER_GROUP_APPLICATION_ROLE_HISTORY WHERE APPLICATION_ROLE_ID = @roleId OR APPLICATION_USER_GROUP_ID = @groupId
DELETE FROM CFX.CONCEPT_PERMISSION_HISTORY WHERE APPLICATION_ROLE_ID = @roleId
DELETE FROM CFX.CONCEPT_PERMISSION WHERE APPLICATION_ROLE_ID = @roleId
DELETE FROM CFX.USER_APPLICATION_ROLE WHERE APPLICATION_ROLE_ID = @roleId
DELETE FROM CFX.USER_GROUP_APPLICATION_ROLE WHERE APPLICATION_ROLE_ID = @roleId OR APPLICATION_USER_GROUP_ID = @groupId
DELETE FROM CFG.APPLICATION_ROLE WHERE APPLICATION_ROLE_ID = @roleId
DELETE FROM CFX.USER_GROUP_APPLICATION_ROLE_HISTORY WHERE APPLICATION_USER_GROUP_ID = @groupId OR APPLICATION_ROLE_ID = @roleId
DELETE FROM ORG.APPLICATION_USER_GROUP_ASSIGNMENT_HISTORY WHERE APPLICATION_USER_GROUP_ID = @groupId
DELETE FROM ORG.APPLICATION_USER_GROUP_ASSIGNMENT WHERE APPLICATION_USER_GROUP_ID = @groupId
DELETE FROM ORG.APPLICATION_USER_GROUP WHERE APPLICATION_USER_GROUP_ID = @groupId

COMMIT TRAN