select
  ppl.POLICY_HKEY POLICY_HKEY,
  sum(pps.AMOUNT) AMOUNT
into PAS_IMPL.SK2703
from
  PAS_IMPL.P_PAYMENT_PLAN_SAT_LATEST pps,
  PAS_IMPL.P_PAYMENT_PLAN_LINK ppl,
  PAS_IMPL.POLICY_SAT_LATEST psl
where pps.P_PAYMENT_PLAN_HKEY = ppl.P_PAYMENT_PLAN_HKEY
  and pps.INSURANCE_YEAR = 1
  and ppl.POLICY_HKEY = psl.POLICY_HKEY
  and psl.PRODUCT_CODE = 'EBMIBFKO'
group by
  ppl.POLICY_HKEY

update
  PAS_IMPL.POLICY_SAT_LATEST
set
  RISK_PREMIUM_ALL = b.AMOUNT
from 
  PAS_IMPL.SK2703 b
where PAS_IMPL.POLICY_SAT_LATEST.POLICY_HKEY = b.POLICY_HKEY
  and b.AMOUNT != 0

drop table PAS_IMPL.SK2703

update
  PAS_IMPL.POLICY_SAT_LATEST
set 
  RISK_PREMIUM = RISK_PREMIUM_ALL
where isnull(RISK_PREMIUM, 0) = 0