UPDATE c
SET BODY = JSON_MODIFY(BODY, '$.productConfiguration', NULL),
	SNAPSHOT_BODY = JSON_MODIFY(SNAPSHOT_BODY, '$.productConfiguration', NULL),
	COMMON_BODY = JSON_MODIFY(COMMON_BODY, '$.attributes.productConfigurationData', NULL)
FROM PAS.CONTRACT c
LEFT JOIN CFX.PUBLISHED_ARTIFACT pa ON pa.PUBLISHED_ARTIFACT_ID = c.PUBLISHED_ARTIFACT_ID
WHERE pa.CODE_NAME = 'CollectiveLifeInsurancePolicy'