IF COL_LENGTH('PAS_IMPL.VERIFICATION_SAT','SELLER_COMMENT') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.VERIFICATION_SAT ADD SELLER_COMMENT nvarchar(max)
END
GO

IF COL_LENGTH('PAS_IMPL.VERIFICATION_SAT','OPERATIONS_COMMENT') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.VERIFICATION_SAT ADD OPERATIONS_COMMENT nvarchar(max)
END
GO