CREATE TABLE PAS_IMPL.ADIRGSL_3043_CL_BACKUP (
CONTRACT_ID UNIQUEIDENTIFIER,
CONTRACT_NUMBER NVARCHAR(255) NOT NULL,
BODY NVARCHAR(MAX) NOT NULL,
COMMON_BODY NVARCHAR(MAX) NOT NULL,
SNAPSHOT_BODY NVARCHAR(MAX) NOT NULL,
CONSTRAINT ADIRGSL_3043_BCKUP PRIMARY KEY (CONTRACT_ID)
)