IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS].[CONTRACT]') AND TYPE IN (N'U'))
BEGIN

	IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS].[CONTRACT_PARTNER_BACKUP]') AND TYPE IN (N'U'))
	BEGIN
		DROP TABLE PAS.CONTRACT_PARTNER_BACKUP
	END

	SELECT CONTRACT_NUMBER, COMMON_BODY
	INTO PAS.CONTRACT_PARTNER_BACKUP
	FROM PAS.CONTRACT;

END