
CREATE TABLE EWT_IMPL.ADIRGSL_3612_EWT_BACKUP (
ENDOWMENT_ID UNIQUEIDENTIFIER,
ENDOWMENT_NUMBER NVARCHAR(255) NOT NULL,
BODY NVARCHAR(MAX) NOT NULL,
COMMON_BODY NVARCHAR(MAX) NOT NULL,
CONSTRAINT ADIRGSL_3612_BCKUP PRIMARY KEY (ENDOWMENT_ID)
)


INSERT INTO EWT_IMPL.ADIRGSL_3612_EWT_BACKUP(ENDOWMENT_ID, ENDOWMENT_NUMBER, BODY, COMMON_BODY)
SELECT doc.UNIVERSAL_DOCUMENT_ID, doc.UNIVERSAL_DOCUMENT_NUMBER, doc.BODY, doc.COMMON_BODY
FROM BFX.UNIVERSAL_DOCUMENT doc
JOIN CFX.PUBLISHED_ARTIFACT art ON art.PUBLISHED_ARTIFACT_ID = doc.PUBLISHED_ARTIFACT_ID
WHERE art.CODE_NAME = 'Endowment'