IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ACC_IMPL].[CRT_SAT]') AND TYPE IN (N'U'))
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ACC_IMPL].[CRT_HUB]') AND TYPE IN (N'U'))
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ACC_IMPL].[CRT_ATTACHMENT_TYPE_SAT]') AND TYPE IN (N'U'))
BEGIN
    insert into ACC_IMPL.CRT_ATTACHMENT_TYPE_SAT (CRT_ATTACHMENT_TYPE_HKEY, LOAD_DATE, RECORD_SOURCE, HASH_DIFF, ATTACHMENT_TYPE)
    SELECT cs.CRT_HKEY, GETDATE() as LOAD_DATE, 'ADINSURE' as RECORD_SOURCE, CONVERT(CHAR(32), HAShBytes('MD5', CAST(newid() AS varbinary(max))), 2) AS HASH_DIFF, 'PDF' as ATTACHMENT_TYPE
        from BFX.UNIVERSAL_VERSIONED_DOCUMENT  ud
		inner join ACC_IMPL.CRT_HUB ch on ud.UNIVERSAL_VERSIONED_DOCUMENT_NUMBER = ch.CERTIFICATE_NUMBER
		inner join ACC_IMPL.CRT_SAT cs on cs.CRT_HKEY = ch.CRT_HKEY
		inner join CFG.PROCESS_STATE ps on ps.PROCESS_STATE_ID = ud.STATE_ID
        left join BFX.ATTACHMENT_RELATED_ENTITY are on are.ENTITY_REF_ID = ud.UNIVERSAL_VERSIONED_DOCUMENT_ID
        where ATTACHMENT_ID is not null and ps.CODE_NAME = 'Issued'
		GROUP BY cs.CRT_HKEY
END