SELECT DISTINCT pdi.PARTY_CODE, pdi.DEDUPL_NUMBER
INTO #tempPolicyInsuredCodesToUpdate
FROM PTY_IMPL.PARTY_DEDUP_INFO pdi
LEFT JOIN PAS_IMPL.POLICY_SAT ps ON ps.INSURED_CODE = pdi.PARTY_CODE
WHERE pdi.IS_PROCESSED = 1 AND ps.INSURED_CODE != pdi.DEDUPL_NUMBER

UPDATE ps
SET INSURED_CODE = t1.DEDUPL_NUMBER
FROM PAS_IMPL.POLICY_SAT ps
LEFT JOIN #tempPolicyInsuredCodesToUpdate t1 ON t1.PARTY_CODE = ps.INSURED_CODE
WHERE t1.PARTY_CODE = ps.INSURED_CODE

DROP TABLE #tempPolicyInsuredCodesToUpdate
