SELECT DISTINCT pdi.PARTY_CODE, pdi.DEDUPL_NUMBER
INTO #tempQouteHolderCodesToUpdate
FROM PTY_IMPL.PARTY_DEDUP_INFO pdi
LEFT JOIN PAS_IMPL.QUOTE_SAT qs ON qs.HOLDER_CODE = pdi.PARTY_CODE
WHERE pdi.IS_PROCESSED = 1 AND qs.HOLDER_CODE != pdi.DEDUPL_NUMBER

UPDATE qs
SET HOLDER_CODE = t1.DEDUPL_NUMBER
FROM PAS_IMPL.QUOTE_SAT qs
LEFT JOIN #tempQouteHolderCodesToUpdate t1 ON t1.PARTY_CODE = qs.HOLDER_CODE
WHERE t1.PARTY_CODE = qs.HOLDER_CODE

DROP TABLE #tempQouteHolderCodesToUpdate
