BEGIN TRY
BEGIN TRAN

UPDATE PAS_IMPL.INQUIRY_SAT
SET CONTRACT_NUMBER = c.CONTRACT_NUMBER,
	CONTRACT_HOLDER_NAME = qs.HOLDER_NAME,
	CONTRACT_CONF_CODE_NAME = pa.CODE_NAME
FROM PAS_IMPL.INQUIRY_SAT inqSat
LEFT JOIN PAS_IMPL.INQUIRY_HUB inqHub ON inqHub.INQUIRY_HKEY = inqSat.INQUIRY_HKEY
LEFT JOIN PAS_IMPL.QUOTE_INQUIRY_LINK inqLink ON inqLink.INQUIRY_HKEY = inqHub.INQUIRY_HKEY
LEFT JOIN PAS_IMPL.QUOTE_HUB qh ON qh.QUOTE_HKEY = inqLink.QUOTE_HKEY
LEFT JOIN PAS_IMPL.QUOTE_SAT_LATEST qs ON qs.QUOTE_HKEY = qh.QUOTE_HKEY
LEFT JOIN PAS.CONTRACT c ON c.CONTRACT_NUMBER = qh.CONTRACT_NUMBER
LEFT JOIN CFX.PUBLISHED_ARTIFACT pa on pa.PUBLISHED_ARTIFACT_ID = c.PUBLISHED_ARTIFACT_ID

COMMIT TRAN
END TRY

BEGIN CATCH

    ROLLBACK TRAN
    DECLARE @ErrorMessage NVARCHAR(4000); DECLARE @ErrorSeverity INT; DECLARE @ErrorState INT;
    SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = 1;
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);

END CATCH