IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PTY_IMPL].[PARTY_DEDUP_INFO]') AND TYPE IN (N'U'))
BEGIN

DROP TABLE PTY_IMPL.PARTY_DEDUP_INFO

END
GO

create table [PTY_IMPL].[PARTY_DEDUP_INFO]
(
	[ID] [int] IDENTITY(1,1) PRIMARY KEY,
	[PARTY_CODE] [nvarchar](64) NOT NULL,
	[DEDUPL_NUMBER] [nvarchar](64) NOT NULL,
	[UPDATE_ORDER] [int] NOT NULL,
	[IS_PROCESSED] [bit] NOT NULL,
	[UPDATED_DOCUMENTS] [nvarchar](MAX) NULL,
	[ERROR] [nvarchar](MAX) NULL,
	[DATE] datetime NOT NULL
)