UPDATE PTY.PARTY 
SET BODY = JSON_MODIFY(JSON_MODIFY(BODY, '$.finKnowledgeQuestionnaire2023', NULL), '$.finKnowledgeQuestionnaire', NULL)
FROM PTY.PARTY p 
LEFT JOIN CFX.PUBLISHED_ARTIFACT pa ON pa.PUBLISHED_ARTIFACT_ID = p.PUBLISHED_ARTIFACT_ID
WHERE CODE_NAME = 'LegalEntity'
--AND PARTY_CODE = 'PARTY_CODE_NUMBER'