BEGIN TRY
BEGIN TRAN

DECLARE @CurrentAttrValues TABLE
(
   CODE NVARCHAR(50),
   IS_NON_RESIDENT BIT
);

INSERT INTO @CurrentAttrValues

SELECT	r.PARTY_CODE,
		r.IS_NON_RESIDENT
FROM
(SELECT	p.PARTY_CODE,
		JSON_VALUE(p.BODY, N'lax $.partyGeneralData.isNonResident') AS IS_NON_RESIDENT
FROM 
PTY.PARTY p) r
WHERE r.IS_NON_RESIDENT IS NOT NULL

DECLARE @PartyCode NVARCHAR(50), @IsNonResident BIT

DECLARE PARTY_CURSOR CURSOR LOCAL READ_ONLY FORWARD_ONLY
FOR 

SELECT CODE,
	   IS_NON_RESIDENT
FROM @CurrentAttrValues

OPEN PARTY_CURSOR
FETCH NEXT FROM PARTY_CURSOR INTO @PartyCode, @IsNonResident
WHILE @@FETCH_STATUS = 0

BEGIN 
	
	UPDATE PTY.PARTY set COMMON_BODY = JSON_MODIFY(COMMON_BODY, '$.attributes.isNonResident', @IsNonResident)
		WHERE PARTY_CODE = @PartyCode
	
	FETCH NEXT FROM PARTY_CURSOR INTO @PartyCode, @IsNonResident

END

CLOSE PARTY_CURSOR
DEALLOCATE PARTY_CURSOR

COMMIT TRAN

END TRY

BEGIN CATCH

    ROLLBACK TRAN
    DECLARE @ErrorMessage NVARCHAR(4000); DECLARE @ErrorSeverity INT; DECLARE @ErrorState INT;
    SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = 1;
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);

END CATCH