IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ARCHIVE_AUDIT_TRAIL]') AND type IN (N'P', N'RF', N'PC'))
BEGIN
DROP PROCEDURE dbo.ARCHIVE_AUDIT_TRAIL;
END
GO

CREATE PROCEDURE ARCHIVE_AUDIT_TRAIL
AS
BEGIN TRY
begin tran

	INSERT INTO BFX_IMPL.AUDIT_TRAIL_ARCH
	SELECT * FROM BFX.AUDIT_TRAIL 
	WHERE SYS_CREATED_ON < dateadd(month, -1, getdate())

	DELETE FROM BFX.AUDIT_TRAIL 
	WHERE SYS_CREATED_ON < dateadd(month, -1, getdate())

commit tran
END TRY
BEGIN CATCH
    ROLLBACK tran
    DECLARE @ErrorMessage NVARCHAR(4000); DECLARE @ErrorSeverity INT; DECLARE @ErrorState INT;
    SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = 1;
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState );
END CATCH;
GO