INSERT INTO PTY_IMPL.PARTY_EMAILS_SAT
(PARTY_EMAILS_HKEY, LOAD_DATE, RECORD_SOURCE, HASH_DIFF, EMAIL_ID, EMAIL, IS_PREFERABLE, IS_FOR_NEWSLETTERS, IS_DELETED)
SELECT DISTINCT partyHub.PARTY_HKEY AS PARTY_EMAILS_HKEY,
       GETDATE() AS LOAD_DATE,
       N'ADINSURE' AS RECORD_SOURCE,
       CONVERT(CHAR(32), HAShBytes('MD5', CAST(newid() AS varbinary(max))), 2) AS HASH_DIFF,
       ROW_NUMBER() OVER (PARTITION BY partyHub.PARTY_HKEY ORDER BY partyHub.LOAD_DATE DESC) EMAIL_ID,
	   JSON_VALUE(partyEmails.value, '$.email') EMAIL,
	   CASE WHEN JSON_VALUE(partyEmails.value, '$.isPreferable') IN (NULL, 'false', 'FALSE', '0') THEN 0 ELSE 1 END IS_PREFERABLE,
	   CASE WHEN JSON_VALUE(partyEmails.value, '$.isForNewsletters') IN (NULL, 'false', 'FALSE', '0') THEN 0 ELSE 1 END IS_FOR_NEWSLETTERS,
       0 AS IS_DELETED
FROM PTY_IMPL.PARTY_HUB partyHub,
       PTY.PARTY party
CROSS APPLY OPENJSON(JSON_QUERY(party.body, '$.partyEmails')) partyEmails 
WHERE party.PARTY_CODE = partyHub.PARTY_CODE