DROP TABLE IF EXISTS BFX_IMPL.INJURY_GENERAL
GO

CREATE TABLE BFX_IMPL.INJURY_GENERAL
(
    ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    RULE_CODE NVARCHAR(256) NOT NULL,
    INJURY_GROUP NVARCHAR(1024),
    SUBGROUP_CODE_LEVEL_1 NVARCHAR(16),
    SUBGROUP_DESCRIPTION_LEVEL_1 NVARCHAR(1024),
    SUBGROUP_CODE_LEVEL_2 NVARCHAR(16),
    SUBGROUP_DESCRIPTION_LEVEL_2 NVARCHAR(1024),
    SUBGROUP_CODE_LEVEL_3 NVARCHAR(16),
    SUBGROUP_DESCRIPTION_LEVEL_3 NVARCHAR(1024),
    SUBGROUP_CODE_LEVEL_4 NVARCHAR(16),
    INJURY_DESCRIPTION NVARCHAR(1024),
    INSURANCE_SUM_RATE DECIMAL(4,2),
    NOTE1 NVARCHAR(MAX),
    NOTE2 NVARCHAR(MAX),
    NOTE3 NVARCHAR(MAX),
    NOTE4 NVARCHAR(MAX)
)