IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ARCHIVE_CONTRACT_HISTORY]') AND type IN (N'P', N'RF', N'PC'))
BEGIN
DROP PROCEDURE dbo.ARCHIVE_CONTRACT_HISTORY;
END
GO

CREATE PROCEDURE ARCHIVE_CONTRACT_HISTORY
AS
BEGIN TRY
begin tran

	DECLARE @contractToArchTable TABLE (CONTRACT_HISTORY_ID NVARCHAR(36));
	INSERT INTO @contractToArchTable (CONTRACT_HISTORY_ID)
	SELECT 
		-- TOP NUMBER_OF_CONTRACTS_TO_SELECT
		cHist.CONTRACT_HISTORY_ID 
		FROM PAS.CONTRACT_HISTORY cHist
		INNER JOIN (
			SELECT CONTRACT_ID, MAX(SYS_VERSION) MAX_SYS_VERSION
			FROM PAS.CONTRACT_HISTORY
			GROUP BY CONTRACT_ID
		) cHistIn ON cHistIn.CONTRACT_ID = cHist.CONTRACT_ID AND cHist.SYS_VERSION != cHistIn.MAX_SYS_VERSION
	
	INSERT INTO PAS_IMPL.CONTRACT_HISTORY_ARCH
	SELECT cHist.* FROM PAS.CONTRACT_HISTORY cHist
	WHERE CONTRACT_HISTORY_ID IN (SELECT CONTRACT_HISTORY_ID FROM @contractToArchTable)

    DELETE FROM PAS.CONTRACT_HISTORY
	WHERE CONTRACT_HISTORY_ID IN (SELECT CONTRACT_HISTORY_ID FROM @contractToArchTable)

commit tran
END TRY
BEGIN CATCH
    ROLLBACK tran
    DECLARE @ErrorMessage NVARCHAR(4000); DECLARE @ErrorSeverity INT; DECLARE @ErrorState INT;
    SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = 1;
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState );
END CATCH;
GO