IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ARCHIVE_NOTIFICATION_JOURNAL]') AND type IN (N'P', N'RF', N'PC'))
BEGIN
DROP PROCEDURE dbo.ARCHIVE_NOTIFICATION_JOURNAL;
END
GO

CREATE PROCEDURE ARCHIVE_NOTIFICATION_JOURNAL
AS
BEGIN TRY
begin tran

	INSERT INTO BFX_IMPL.NOTIFICATION_JOURNAL_ARCH
	SELECT * FROM BFX.NOTIFICATION_JOURNAL 
	WHERE NOTIFICATION_STATUS = 'Sent'

	DELETE FROM BFX.NOTIFICATION_JOURNAL 
	WHERE NOTIFICATION_STATUS = 'Sent'

commit tran
END TRY
BEGIN CATCH
    ROLLBACK tran
    DECLARE @ErrorMessage NVARCHAR(4000); DECLARE @ErrorSeverity INT; DECLARE @ErrorState INT;
    SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = 1;
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState );
END CATCH;
GO