IF COL_LENGTH('BFX_IMPL.ADDITIONAL_PARAMETERS_SAT','HAS_AMENDMENT') IS NULL
BEGIN
  ALTER TABLE BFX_IMPL.ADDITIONAL_PARAMETERS_SAT ADD HAS_AMENDMENT BIT
END;

GO

IF COL_LENGTH('BFX_IMPL.ADDITIONAL_PARAMETERS_SAT','HAS_AMENDMENT_DATE') IS NULL
BEGIN
  ALTER TABLE BFX_IMPL.ADDITIONAL_PARAMETERS_SAT ADD HAS_AMENDMENT_DATE DATE
END;

GO

IF COL_LENGTH('BFX_IMPL.ADDITIONAL_PARAMETERS_SAT','HAS_PAYMENT_INTERMEDIATE_APPLICATION') IS NULL
BEGIN
  ALTER TABLE BFX_IMPL.ADDITIONAL_PARAMETERS_SAT ADD HAS_PAYMENT_INTERMEDIATE_APPLICATION BIT
END;

GO

IF COL_LENGTH('BFX_IMPL.ADDITIONAL_PARAMETERS_SAT','PAYMENT_INTERMEDIATE_APPLICATION_DATE') IS NULL
BEGIN
  ALTER TABLE BFX_IMPL.ADDITIONAL_PARAMETERS_SAT ADD PAYMENT_INTERMEDIATE_APPLICATION_DATE DATE
END;

GO