-- IMPL_LDWH_PRODUCTS
IF EXISTS (SELECT * FROM SYS.VIEWS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IMPL_LDWH_PRODUCTS]'))
BEGIN
DROP VIEW [DBO].[IMPL_LDWH_PRODUCTS];
END
GO

CREATE VIEW IMPL_LDWH_PRODUCTS
AS
SELECT *
  FROM BFX_IMPL.PRODUCTS
GO

-- EXAMPLES
/*
SELECT * FROM IMPL_LDWH_PRODUCTS
*/