-- IMPL_LDWH_RISKS
IF EXISTS (SELECT * FROM SYS.VIEWS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IMPL_LDWH_RISKS]'))
BEGIN
DROP VIEW [DBO].[IMPL_LDWH_RISKS];
END
GO

CREATE VIEW IMPL_LDWH_RISKS
AS
SELECT *
  FROM BFX_IMPL.RISKS
GO

-- EXAMPLES
/*
SELECT * FROM IMPL_LDWH_RISKS
*/