-- ACC_IMPL.CA_ACT
IF EXISTS (SELECT * FROM SYS.VIEWS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IMPL_LDWH_CA_ACT]'))
BEGIN
DROP VIEW [DBO].[IMPL_LDWH_CA_ACT];
END
GO

CREATE VIEW IMPL_LDWH_CA_ACT
AS
SELECT ACT_ID,
       ACT_NO,
       CAST(ISSUE_DATE AS DATETIME) AS ISSUE_DATE,
       CAST(PAY_DATE AS DATETIME) AS PAY_DATE,
       STATUS_ID,
       AGENT_SERVICE_PROVIDER_CODE AS AGENT_SP_CODE,
       AGENT_AGREEMENT_NUMBER AS AA_NUMBER,
       CAST(PERIOD_FROM AS DATETIME) AS PERIOD_FROM,
       CAST(PERIOD_TO AS DATETIME) AS PERIOD_TO,
       CAST(REPORTING_PERIOD_FROM AS DATETIME) AS REP_PERIOD_FROM,
       CAST(REPORTING_PERIOD_TO AS DATETIME) AS REP_PERIOD_TO,
       COMM_AMOUNT_LC,
       VAT_AMOUNT_LC,
       ITEMS_COUNT,
       NOTES,
       PREMIUM_AMOUNT_LC AS PREM_AMOUNT_LC,
       DBO.IMPL_SAP_DATE(LAST_UPDATED) AS LAST_UPDATED,
       VAT_RATE,
       CAST(ORIGINAL_RECEIPT_DATE AS DATETIME) AS O_RECEIPT_DATE,
       IS_DOC_CORRECT
  FROM ACC_IMPL.CA_ACT
GO

-- ACC_IMPL.CA_ACT_ITEM
IF EXISTS (SELECT * FROM SYS.VIEWS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IMPL_LDWH_CA_ACT_ITEM]'))
BEGIN
DROP VIEW [DBO].[IMPL_LDWH_CA_ACT_ITEM];
END
GO

CREATE VIEW IMPL_LDWH_CA_ACT_ITEM
AS
SELECT ACT_ITEM_ID,
       ACT_ID,
       REFERENCE_NO,
       DOC_CURRENCY_CODE AS DOC_C_CODE,
       SOURCE_LINE_ID,
       CAST(PAYMENT_TRANSACTION_DATE AS DATETIME) AS P_TRAN_DATE,
       CAST(DUE_DATE AS DATETIME) AS DUE_DATE,
       BANK_STATEMENT_ITEM_ID AS BSI_ID,
       INSTALLMENT_DOC_AMOUNT AS I_DOC_AMOUNT,
       INSTALLMENT_LC_AMOUNT AS I_LC_AMOUNT,
       PAYMENT_DOC_AMOUNT AS P_DOC_AMOUNT,
       PAYMENT_LC_AMOUNT AS P_LC_AMOUNT,
       INV_COMM_DOC_AMOUNT AS IC_DOC_AMOUNT,
       INV_COMM_LC_AMOUNT AS IC_LC_AMOUNT,
       AA_COMM_RATE,
       DOC_COMM_RATE,
       COMM_RATE_MANUAL,
       COMM_RATE_FINAL,
       LC_COMM_AMOUNT_CALC AS LC_CA_CALC,
       LC_COMM_AMOUNT_MANUAL AS LC_CA_MANUAL,
       LC_COMM_AMOUNT_FINAL AS LC_CA_FINAL,
       STATUS_ID,
       INV_COMM_FINAL_RATE AS IC_FINAL_RATE
  FROM ACC_IMPL.CA_ACT_ITEM
GO

-- EXAMPLES
/*
SELECT * FROM IMPL_LDWH_CA_ACT
SELECT * FROM IMPL_LDWH_CA_ACT_ITEM
*/