if not exists(select * from sys.indexes i where i.name = 'IX_CFX_USER_APPLICATION_ROLE_HISTORY')
begin
	create nonclustered index IX_CFX_USER_APPLICATION_ROLE_HISTORY
	on CFX.USER_APPLICATION_ROLE_HISTORY(APPLICATION_USER_ROLE_ASSIGNMENT_HISTORY_ID, SYS_VERSION);
end
go

if not exists(select * from sys.indexes i where i.name = 'IX_CFX_USER_GROUP_APPLICATION_ROLE_HISTORY')
begin
	create nonclustered index IX_CFX_USER_GROUP_APPLICATION_ROLE_HISTORY
	on CFX.USER_GROUP_APPLICATION_ROLE_HISTORY(USER_GROUP_ROLE_ASSIGNMENT_HISTORY_ID, SYS_VERSION);
end
go

if not exists(select * from sys.indexes i where i.name = 'IX_ORG_APPLICATION_USER_GROUP_ASSIGNMENT_HISTORY')
begin
	create nonclustered index IX_ORG_APPLICATION_USER_GROUP_ASSIGNMENT_HISTORY
	on ORG.APPLICATION_USER_GROUP_ASSIGNMENT_HISTORY(APPLICATION_USER_GROUP_ASSIGNMENT_HISTORY_ID, SYS_VERSION);
end
go