update CFX.PUBLISHED_ARTIFACT
set STATUS = 'Active'
where CONCEPT_TYPE_ID = 47
go

if not exists(select * from sys.indexes i where i.name = 'IX_BFX_UNIVERSAL_MASTER_ENTITY_HISTORY')
begin
   create nonclustered index IX_BFX_UNIVERSAL_MASTER_ENTITY_HISTORY
	on BFX.UNIVERSAL_MASTER_ENTITY_HISTORY(UNIVERSAL_MASTER_ENTITY_ID, SYS_VERSION);
end
go

if not exists(select * from sys.indexes i where i.name = 'IX_CLM_CLAIM_HANDLING_HISTORY')
begin
	create nonclustered index IX_CLM_CLAIM_HANDLING_HISTORY
	on CLM.CLAIM_HANDLING_HISTORY(CLAIM_HANDLING_ID, SYS_VERSION);
end
go

-- CLM.ANNUITY_AGREEMENT
IF NOT EXISTS (SELECT NAME FROM SYS.indexes WHERE NAME = 'IX_CLM_ANNUITY_AGREEMENT_SYS_UPDATED_ON')
BEGIN
    CREATE INDEX IX_CLM_ANNUITY_AGREEMENT_SYS_UPDATED_ON ON CLM.ANNUITY_AGREEMENT (SYS_UPDATED_ON);
END

-- CLM.CLAIM_HANDLING
IF NOT EXISTS (SELECT NAME FROM SYS.indexes WHERE NAME = 'IX_CLM_CLAIM_HANDLING_SYS_UPDATED_ON')
BEGIN
    CREATE INDEX IX_CLM_CLAIM_HANDLING_SYS_UPDATED_ON ON CLM.CLAIM_HANDLING (SYS_UPDATED_ON);
END

-- BFX.UNIVERSAL_MASTER_ENTITY
IF NOT EXISTS (SELECT NAME FROM SYS.indexes WHERE NAME = 'IX_BFX_UNIVERSAL_MASTER_ENTITY_SYS_UPDATED_ON')
BEGIN
    CREATE INDEX IX_BFX_UNIVERSAL_MASTER_ENTITY_SYS_UPDATED_ON ON BFX.UNIVERSAL_MASTER_ENTITY (SYS_UPDATED_ON);
END

