BEGIN
	IF EXISTS(
		SELECT *
		FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_SCHEMA = 'BFX' 
		AND TABLE_NAME = 'INTEGRATION_MESSAGE_GROUP'
		AND COLUMN_NAME = 'TIMESTAMP'
		AND DATA_TYPE = 'datetime'
	)
	BEGIN
		ALTER TABLE BFX.INTEGRATION_MESSAGE_GROUP ALTER COLUMN [TIMESTAMP] datetime2 not null;
	END
	
	IF EXISTS(
		SELECT *
		FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_SCHEMA = 'BFX' 
		AND TABLE_NAME = 'INTEGRATION_MESSAGE_ERROR'
		AND COLUMN_NAME = 'TIMESTAMP'
		AND DATA_TYPE = 'datetime'
	)
	BEGIN
		DECLARE @messageErrorTimestampIndexExisted bit;
		SELECT @messageErrorTimestampIndexExisted = 1 FROM sys.indexes i WHERE i.name = 'IX_BFX_INTEGRATION_MESSAGE_ERROR_TIMESTAMP_AND_SYS_CREATED_ON';
		
		IF(@messageErrorTimestampIndexExisted = 1)
		BEGIN
			DROP INDEX IX_BFX_INTEGRATION_MESSAGE_ERROR_TIMESTAMP_AND_SYS_CREATED_ON
			ON BFX.INTEGRATION_MESSAGE_ERROR;
		END

		ALTER TABLE BFX.INTEGRATION_MESSAGE_ERROR ALTER COLUMN [TIMESTAMP] datetime2 null;
	
		IF(@messageErrorTimestampIndexExisted = 1)
		BEGIN
			CREATE NONCLUSTERED INDEX IX_BFX_INTEGRATION_MESSAGE_ERROR_TIMESTAMP_AND_SYS_CREATED_ON
			ON BFX.INTEGRATION_MESSAGE_ERROR([TIMESTAMP], SYS_CREATED_ON);
		END
	END
	
	IF EXISTS(
		SELECT *
		FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_SCHEMA = 'BFX' 
		AND TABLE_NAME = 'MESSAGE_OUTBOX'
		AND COLUMN_NAME = 'TIMESTAMP_UTC'
		AND DATA_TYPE = 'datetime'
	)
	BEGIN
		DECLARE @messageOutboxTimestampIndexExisted bit;
		DECLARE @messageOutboxStatusIndexExisted bit;
		SELECT @messageOutboxTimestampIndexExisted = 1 FROM sys.indexes i WHERE i.name = 'BFX_IX_BFX_MESSAGE_OUTBOX_TS_UTC';
		SELECT @messageOutboxStatusIndexExisted = 1 FROM sys.indexes i WHERE i.name = 'BFX_IX_BFX_MESSAGE_OUTBOX_STATUS';
		
		IF(@messageOutboxTimestampIndexExisted = 1)
		BEGIN
			DROP INDEX BFX_IX_BFX_MESSAGE_OUTBOX_TS_UTC ON BFX.MESSAGE_OUTBOX;
		END
		
		IF(@messageOutboxStatusIndexExisted = 1)
		BEGIN
			DROP INDEX BFX_IX_BFX_MESSAGE_OUTBOX_STATUS ON BFX.MESSAGE_OUTBOX;
		END

		ALTER TABLE BFX.MESSAGE_OUTBOX ALTER COLUMN TIMESTAMP_UTC datetime2 not null;

		IF EXISTS(
			SELECT *
			FROM INFORMATION_SCHEMA.COLUMNS
			WHERE TABLE_SCHEMA = 'BFX'
			AND TABLE_NAME = 'MESSAGE_OUTBOX'
			AND COLUMN_NAME = 'RETRY_AFTER_TIMESTAMP_UTC'
			AND DATA_TYPE = 'datetime'
		)
		BEGIN
			ALTER TABLE BFX.MESSAGE_OUTBOX ALTER COLUMN RETRY_AFTER_TIMESTAMP_UTC datetime2 not null;
		END
	
		IF(@messageOutboxTimestampIndexExisted = 1)
		BEGIN
			CREATE INDEX BFX_IX_BFX_MESSAGE_OUTBOX_TS_UTC ON BFX.MESSAGE_OUTBOX (TIMESTAMP_UTC ASC);
		END
		
		IF(@messageOutboxStatusIndexExisted = 1)
		BEGIN
			CREATE INDEX BFX_IX_BFX_MESSAGE_OUTBOX_STATUS ON BFX.MESSAGE_OUTBOX (STATUS_ID) INCLUDE (MESSAGE_ID, RETRY_AFTER_TIMESTAMP_UTC, GROUP_ID, DESTINATION, TIMESTAMP_UTC);
		END
	END
END
GO