update CFX.PUBLISHED_ARTIFACT_ITEM
set BODY = FORMATMESSAGE('// Generated by publishing procedure
const ConfigurationName = ''%s'';
const ConfigurationVersion = ''%s'';
const ConfigurationId = ''%s'';

const { createConfigurationObjectById } = require(''@adinsure/platform-framework/lib/config/search-engines'');

var configObject = createConfigurationObjectById(ConfigurationName, ConfigurationVersion, ConfigurationId);

configObject.invalidateConfiguration = function invalidateConfiguration() {
    // invalidation function generated by publishing
    // this should invalidate (remove from cache) all JS modules related to this published artefact
};

module.exports = configObject;', pa.CODE_NAME, pa.PUBLISHED_VERSION, convert(nvarchar(36), pa.PUBLISHED_ARTIFACT_ID))
from CFX.PUBLISHED_ARTIFACT_ITEM pai
  inner join CFX.PUBLISHED_ARTIFACT pa on pai.PUBLISHED_ARTIFACT_ID = pa.PUBLISHED_ARTIFACT_ID
where pa.CONCEPT_TYPE_ID = 47 --search engine data provider
and pai.CONCEPT_TYPE_ID = 50 --root script module