ALTER TABLE BFX.EXECUTED_DDL_SCRIPT DROP CONSTRAINT IF EXISTS UQ_BFX_EXECUTED_DDL_SCRIPT_TN_TD;
GO

ALTER TABLE CFG.CONFIG_TABLE_INDEXES DROP CONSTRAINT IF EXISTS UQ_BFX_CONFIG_TABLE_INDEXES_IX_TN_TD;
GO
