if not exists(select * from sys.indexes i where i.name = 'IX_CFX_CONCEPT_PERMISSION_HISTORY_ASSIGNMENT_DATES')
begin
	create nonclustered index IX_CFX_CONCEPT_PERMISSION_HISTORY_ASSIGNMENT_DATES 
	on CFX.CONCEPT_PERMISSION_HISTORY(ASSIGNMENT_CREATED_DATE, ASSIGNMENT_DELETED_DATE, APPLICATION_ROLE_ID);
end
go

if not exists(select * from sys.indexes i where i.name = 'IX_CFX_SECURITY_SCOPE_ROLE_HISTORY_ASSIGNMENT_DATES')
begin
	create nonclustered index IX_CFX_SECURITY_SCOPE_ROLE_HISTORY_ASSIGNMENT_DATES 
	on CFX.SECURITY_SCOPE_ROLE_HISTORY(ASSIGNMENT_CREATED_DATE, ASSIGNMENT_DELETED_DATE, APPLICATION_ROLE_ID);
end
go

if not exists(select * from sys.indexes i where i.name = 'IX_CFX_CONSTRAINT_PERMISSION_HISTORY_ASSIGNMENT_DATES')
begin
	create nonclustered index IX_CFX_CONSTRAINT_PERMISSION_HISTORY_ASSIGNMENT_DATES 
	on CFX.CONSTRAINT_PERMISSION_HISTORY(ASSIGNMENT_CREATED_DATE, ASSIGNMENT_DELETED_DATE, APPLICATION_ROLE_ID);
end
go