IF NOT EXISTS (SELECT * FROM sys.indexes i WHERE i.name = 'IX_BFX_ATTACHMENT_FILE_METADATA_ID')
BEGIN
    CREATE NONCLUSTERED INDEX IX_BFX_ATTACHMENT_FILE_METADATA_ID
    ON BFX.ATTACHMENT (FILE_METADATA_ID);
END
GO

INSERT INTO BFX.DB_SCHEMA_VERSION (DB_VERSION_ID, SCRIPT, VERSION_DATE, DESCRIPTION, STATEMENT_INDEX, REMARK, CHECKSUM, ELAPSED_TIME, STATUS)
VALUES('7.10_041.000.000_012', '7.10_041.000.000_012.sql', getdate(), null, 0, null, null, 0, 0);
GO