IF EXISTS (SELECT NAME FROM SYS.KEY_CONSTRAINTS WHERE NAME = 'UC_BFX_ENTITY_HISTORY_EID_ETID_HISTORY_VERSION')
BEGIN
    ALTER TABLE BFX.ENTITY_HISTORY DROP CONSTRAINT UC_BFX_ENTITY_HISTORY_EID_ETID_HISTORY_VERSION;
    ALTER TABLE BFX.ENTITY_HISTORY ADD CONSTRAINT UC_BFX_ENTITY_HISTORY_ETID_HISTORY_VERSION UNIQUE NONCLUSTERED (ENTITY_ID, HISTORY_VERSION);
END