IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_SAT_PAYMENT_ORDER_TYPE'
	AND object_id = OBJECT_ID('ACC_IMPL.PAYMENT_ORDER_SAT') ) BEGIN
	CREATE INDEX IDX_PO_SAT_PAYMENT_ORDER_TYPE ON
ACC_IMPL.PAYMENT_ORDER_SAT(PAYMENT_ORDER_TYPE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_SAT_PAYMENT_ORDER_SUBTYPE'
	AND object_id = OBJECT_ID('ACC_IMPL.PAYMENT_ORDER_SAT') ) BEGIN
	CREATE INDEX IDX_PO_SAT_PAYMENT_ORDER_SUBTYPE ON
ACC_IMPL.PAYMENT_ORDER_SAT(PAYMENT_ORDER_SUBTYPE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_SAT_REFERENCE_NUMBER'
	AND object_id = OBJECT_ID('ACC_IMPL.PAYMENT_ORDER_SAT') ) BEGIN
	CREATE INDEX IDX_PO_SAT_REFERENCE_NUMBER ON
ACC_IMPL.PAYMENT_ORDER_SAT(REFERENCE_NUMBER)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_SAT_PAYMENT_ORDER_DATE'
	AND object_id = OBJECT_ID('ACC_IMPL.PAYMENT_ORDER_SAT') ) BEGIN
	CREATE INDEX IDX_PO_SAT_PAYMENT_ORDER_DATE ON
ACC_IMPL.PAYMENT_ORDER_SAT(PAYMENT_ORDER_DATE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_SAT_PAYMENT_METHOD'
	AND object_id = OBJECT_ID('ACC_IMPL.PAYMENT_ORDER_SAT') ) BEGIN
	CREATE INDEX IDX_PO_SAT_PAYMENT_METHOD ON
ACC_IMPL.PAYMENT_ORDER_SAT(PAYMENT_METHOD)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_SAT_CONTRACT_NUMBER'
	AND object_id = OBJECT_ID('ACC_IMPL.PAYMENT_ORDER_SAT') ) BEGIN
	CREATE INDEX IDX_PO_SAT_CONTRACT_NUMBER ON
ACC_IMPL.PAYMENT_ORDER_SAT(CONTRACT_NUMBER)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_SAT_CONTRACT_AMENDMENT_NUMBER'
	AND object_id = OBJECT_ID('ACC_IMPL.PAYMENT_ORDER_SAT') ) BEGIN
	CREATE INDEX IDX_PO_SAT_CONTRACT_AMENDMENT_NUMBER ON
ACC_IMPL.PAYMENT_ORDER_SAT(CONTRACT_AMENDMENT_NUMBER)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_SAT_RECIPIENT_NAME'
	AND object_id = OBJECT_ID('ACC_IMPL.PAYMENT_ORDER_SAT') ) BEGIN
	CREATE INDEX IDX_PO_SAT_RECIPIENT_NAME ON
ACC_IMPL.PAYMENT_ORDER_SAT(BASE_DOC_RECIPIENT_NAME)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_SAT_BANK_ACCOUNT_NUMBER'
	AND object_id = OBJECT_ID('ACC_IMPL.PAYMENT_ORDER_SAT') ) BEGIN
	CREATE INDEX IDX_PO_SAT_BANK_ACCOUNT_NUMBER ON
ACC_IMPL.PAYMENT_ORDER_SAT(BANK_ACCOUNT_NUMBER)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_SAT_NON_ACCEPTANCE_NUMBER'
	AND object_id = OBJECT_ID('ACC_IMPL.PAYMENT_ORDER_SAT') ) BEGIN
	CREATE INDEX IDX_PO_SAT_NON_ACCEPTANCE_NUMBER ON
ACC_IMPL.PAYMENT_ORDER_SAT(NON_ACCEPTANCE_NUMBER)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_SAT_PO_CURRENCY_CODE'
	AND object_id = OBJECT_ID('ACC_IMPL.PAYMENT_ORDER_SAT') ) BEGIN
	CREATE INDEX IDX_PO_SAT_PO_CURRENCY_CODE ON
ACC_IMPL.PAYMENT_ORDER_SAT(PO_CURRENCY_CODE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_SAT_PAYMENT_CURRENCY_CODE'
	AND object_id = OBJECT_ID('ACC_IMPL.PAYMENT_ORDER_SAT') ) BEGIN
	CREATE INDEX IDX_PO_SAT_PAYMENT_CURRENCY_CODE ON
ACC_IMPL.PAYMENT_ORDER_SAT(PAYMENT_CURRENCY_CODE)
END

------------------
