ARG platform_version=latest
FROM registryru.adacta-fintech.ru/adinsure/mono/client:${platform_version}
COPY ./html /usr/share/nginx/html
COPY ./conf /usr/share/nginx/html/conf

COPY ./os-release /usr/lib/os-release

COPY ./certs/life-ca.crt /usr/share/ca-certificates/
RUN echo life-ca.crt >> /etc/ca-certificates.conf

COPY ./certs/rgsl-ru.crt /usr/share/ca-certificates/
RUN echo rgsl-ru.crt >> /etc/ca-certificates.conf

RUN update-ca-certificates