ARG platform_version=latest
FROM registryru.adacta-fintech.ru/adinsure/mono/server:${platform_version}
COPY ./plugins /app/extensions/plugins
COPY ./conf /app/conf

COPY ./os-release /usr/lib/os-release

COPY ./certs/life-ca.crt /usr/share/ca-certificates/
RUN echo life-ca.crt >> /etc/ca-certificates.conf

COPY ./certs/rgsl-ru.crt /usr/share/ca-certificates/
RUN echo rgsl-ru.crt >> /etc/ca-certificates.conf

RUN update-ca-certificates