IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_PARTICIPANT_SAT_NAME'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_PARTICIPANT_SAT') ) BEGIN
	CREATE INDEX IDX_AA_PARTICIPANT_SAT_NAME ON
PAS_IMPL.AA_PARTICIPANT_SAT(NAME)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_PARTICIPANT_SAT_ROLE'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_PARTICIPANT_SAT') ) BEGIN
	CREATE INDEX IDX_AA_PARTICIPANT_SAT_ROLE ON
PAS_IMPL.AA_PARTICIPANT_SAT(ROLE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_PARTICIPANT_SAT_FIXED_COMM'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_PARTICIPANT_SAT') ) BEGIN
	CREATE INDEX IDX_AA_PARTICIPANT_SAT_FIXED_COMM ON
PAS_IMPL.AA_PARTICIPANT_SAT(FIXED_COMMISSION)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_PARTICIPANT_SAT_FIXED_COMM_FREQ'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_PARTICIPANT_SAT') ) BEGIN
	CREATE INDEX IDX_AA_PARTICIPANT_SAT_FIXED_COMM_FREQ ON
PAS_IMPL.AA_PARTICIPANT_SAT(FIXED_COMMISSION_FREQUENCY)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_PARTICIPANT_SAT_FIXED_COMM_VALID_FROM'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_PARTICIPANT_SAT') ) BEGIN
	CREATE INDEX IDX_AA_PARTICIPANT_SAT_FIXED_COMM_VALID_FROM ON
PAS_IMPL.AA_PARTICIPANT_SAT(FIXED_COMMISSION_VALID_FROM)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_PARTICIPANT_SAT_FIXED_COMM_VALID_TO'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_PARTICIPANT_SAT') ) BEGIN
	CREATE INDEX IDX_AA_PARTICIPANT_SAT_FIXED_COMM_VALID_TO ON
PAS_IMPL.AA_PARTICIPANT_SAT(FIXED_COMMISSION_VALID_TO)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_PARTICIPANT_SAT_CURRENCY'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_PARTICIPANT_SAT') ) BEGIN
	CREATE INDEX IDX_AA_PARTICIPANT_SAT_CURRENCY ON
PAS_IMPL.AA_PARTICIPANT_SAT(CURRENCY)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_PARTICIPANT_SAT_SPLIT_COMM_RATE'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_PARTICIPANT_SAT') ) BEGIN
	CREATE INDEX IDX_AA_PARTICIPANT_SAT_SPLIT_COMM_RATE ON
PAS_IMPL.AA_PARTICIPANT_SAT(SPLIT_COMMISSION_RATE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_PARTICIPANT_SAT_START_DATE'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_PARTICIPANT_SAT') ) BEGIN
	CREATE INDEX IDX_AA_PARTICIPANT_SAT_START_DATE ON
PAS_IMPL.AA_PARTICIPANT_SAT(START_DATE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_PARTICIPANT_SAT_END_DATE'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_PARTICIPANT_SAT') ) BEGIN
	CREATE INDEX IDX_AA_PARTICIPANT_SAT_END_DATE ON
PAS_IMPL.AA_PARTICIPANT_SAT(END_DATE)
END

------------------
