IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ACC_IMPL].[PAYMENT_ORDER_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('ACC_IMPL.PAYMENT_ORDER_SAT','FIXED_EXCH_RATE') IS NULL
BEGIN
ALTER TABLE ACC_IMPL.PAYMENT_ORDER_SAT ADD FIXED_EXCH_RATE decimal(15,7)
END

IF COL_LENGTH('ACC_IMPL.PAYMENT_ORDER_SAT','USE_FIXED_EXCH_RATE') IS NULL
BEGIN
ALTER TABLE ACC_IMPL.PAYMENT_ORDER_SAT ADD USE_FIXED_EXCH_RATE bit
END

END