IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_SAT_MANUAL_NUMBER'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_SAT') ) BEGIN
	CREATE INDEX IDX_AA_SAT_MANUAL_NUMBER ON
PAS_IMPL.AA_SAT(MANUAL_NUMBER)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_SAT_EXTERNAL_NUMBER'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_SAT') ) BEGIN
	CREATE INDEX IDX_AA_SAT_EXTERNAL_NUMBER ON
PAS_IMPL.AA_SAT(EXTERNAL_NUMBER)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_SAT_CONCLUSION_DATE'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_SAT') ) BEGIN
	CREATE INDEX IDX_AA_SAT_CONCLUSION_DATE ON
PAS_IMPL.AA_SAT(CONCLUSION_DATE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_SAT_RGS_CHANNEL'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_SAT') ) BEGIN
	CREATE INDEX IDX_AA_SAT_RGS_CHANNEL ON
PAS_IMPL.AA_SAT(RGS_CHANNEL_CODE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_SAT_RGS_CHANNEL_CODE'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_SAT') ) BEGIN
	CREATE INDEX IDX_AA_SAT_RGS_CHANNEL_CODE ON
PAS_IMPL.AA_SAT(CB_AGENT_TYPE_CODE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_SAT_CURRENCY_CODE'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_SAT') ) BEGIN
	CREATE INDEX IDX_AA_SAT_CURRENCY_CODE ON
PAS_IMPL.AA_SAT(CURRENCY_CODE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_SAT_AGENCY_CODE'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_SAT') ) BEGIN
	CREATE INDEX IDX_AA_SAT_AGENCY_CODE ON
PAS_IMPL.AA_SAT(AGENCY_CODE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_SAT_ORDER_NUMBER'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_SAT') ) BEGIN
	CREATE INDEX IDX_AA_SAT_ORDER_NUMBER ON
PAS_IMPL.AA_SAT(ORDER_NUMBER)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_SAT_IS_PER_BUS'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_SAT') ) BEGIN
	CREATE INDEX IDX_AA_SAT_IS_PER_BUS ON
PAS_IMPL.AA_SAT(IS_PERSONAL_BUSINESS)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_SAT_USE_NDS'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_SAT') ) BEGIN
	CREATE INDEX IDX_AA_SAT_USE_NDS ON
PAS_IMPL.AA_SAT(USE_NDS)
END

------------------
