module.exports = {

    groups: [
        'salesPSB',
        'salesAKCEPT',
        'salesAKBARS',
        'salesBFKO',
        'salesZENIT',
        'salesBFKOAuto',
        'salesPSBVIP',
        'salesOAS',
        'salesMINBANK',
        'salesSMP',
        'salesVTB',
        'salesREINVEST',
        'salesVTBMass',
        'salesLIFEINVEST',
        'salesUBRR',
        'salesEKSPO',
        'salesVTBVIP',
        'salesVTBVIPNT',
        'salesVTBPremium',
        'salesVTBPremiumNT',
        'salesVTBMassProducts',
        'salesVTBMassINV',
        'salesVTBMassNT',
        'salesPSBProducts',
        'salesPSBNT',
        'salesPSBAffluentNT',
        'salesPSBAffluent',
        'salesPSBMIMO'
    ],

    groupsDesc: [
        'Продавец ПСБ',
        'Продавец АКЦЕПТ',
        'Продавец АКБАРС',
        'Продавец БФКО',
        'Продавец ЗЕНИТ',
        'Продавец БФКОАВТО',
        'Продавец ПСБ Прайвет',
        'Продавец ОАС',
        'Продавец МИНБАНК',
        'Продавец СМП',
        'Продавец ВТБ',
        'Продавец ИННОВАЦИОННЫЕ РЕШЕНИЯ',
        'Продавец ВТБ РОЗНИЦА',
        'Продавец ЛАЙФ ИНВЕСТ',
        'Продавец ПОЧТА БАНК',
        'Продавец УБРИР',
        'Продавец ЭКСПО БАНК',
        'Продавец ВТБ Прайм',
        'Продавец ВТБ Привилегия',
        'Продавец ВТБ Привилегия НТ',
        'Продавец ВТБ РОЗНИЦА Продукты',
        'Продавец ВТБ РОЗНИЦА ИСЖ',
        'Продавец ВТБ РОЗНИЦА НТ',
        'Продавец ПСБ Продукты',
        'Продавец ПСБ НТ',
        'Продавец ПСБ Премиум НТ',
        'Продавец ПСБ Премиум',
        'Продавец ПСБ МиМО'
    ],

    additionalroles: [
        'InvestmentLifePSBAffluent',
        'AccumulatedLifePSBAffluent',
        'InvestmentLifePSBMass',
        'AccumulatedLifePSBMass',
        'InvestmentLifeSMPMass',
        'AccumulatedLifeSMPMass',
        'CreditLifeBFKOMass',
        'AccumulatedLifeBFKOMass',
        'InvestmentLifeBFKOMass',
        'AccumulatedLifeAKCEPTMass',
        'InvestmentLifeAKCEPTMass',
        'AccumulatedLifeAKBARSMass',
        'InvestmentLifeAKBARSMass',
        'ExcludeERCP2',
        'ExcludeEBMP',
        'ExcludeEBMG',
        'ExcludeNOTE',
        'ExcludeREINVEST',
        'ExcludeEBMOPTIMA',
        'ExcludeEBMGVVTB',
        'ExcludeEBMGVNVTB',
        'ExcludeEBMMGREINVEST',
        'ExcludeIDGREINVEST',
        'ExcludeIDGRETVTB',
        'AccumulatedLifeZENITMass',
        'InvestmentLifeZENITMass',
        'CreditLifeBFKOAuto',
        'InvestmentLifePSBVIP',
        'AccumulatedLifeOASMass',
        'InvestmentLifeOASMass',
        'MedLifeOASMass',
        'AccumulatedLifeMINBANK',
        'InvestmentLifeMINBANK',
        'MedLifeBFKOMass',
        'InvestmentLifeVTBPremium',
        'AccumulatedLifeVTBPremium',
        'EquityLifeVTBPremium',
        'EquityLifeOASMass',
        'InvestmentLifeVTBVIP',
        'EquityLifeVTBVIP',
        'AccumulatedLifeVTBVIP',
        'AllowInitiatorChange',
        'AllowInitiatorChangeOAS',
        'AccumulatedLifeREINVESTMass',
        'InvestmentLifeREINVESTMass',
        'RisklifeVTBVIP',
        'RisklifeOAS',
        'InvestmentLifeVTBMass',
        'AccumulatedLifeVTBMass',
        'AccumulatedLifeLIFEINVESTMass',
        'InvestmentLifeLIFEINVESTMass',
        'AccumulatedLifePBMass',
        'InvestmentLifePBMass',
        'InvestmentLifePSBAffluentNT',
        'AccumulatedLifePSBAffluentNT',
        'InvestmentLifeVTBPremiumNT',
        'AccumulatedLifeVTBPremiumNT',
        'AccumulatedLifeVTBMassNT',
        'InvestmentLifeVTBMassNT',
        'InvestmentLifePSBMassNT',
        'AccumulatedLifePSBMassNT',
        'InvestmentLifeUBRRMass',
        'AccumulatedLifeUBRRMass',
        'AccumulatedLifeEKSPOMass',
        'InvestmentLifeEKSPOMass',
        "AccidentLifeDummyRGSL",
        "ServiceProviderOwnOU",
        "ServiceProviderOwnAndSubordinateOU",
        "ServiceProviderAll"
    ],

    countryCodeRus: {
        countryCode: "643",
        alfa2: "RU",
        countryShortName: "РОССИЯ",
        countryPhoneCode: "+7"
    },

    phoneTypeMobile: {
        phoneTypeCode: "mobile",
        phoneTypeDesc: "Мобильный"
    },
};
