IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[CNL_RECIPIENT_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PAS_IMPL.CNL_RECIPIENT_SAT','ASSIGNED_PO_NUMBER') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.CNL_RECIPIENT_SAT ADD ASSIGNED_PO_NUMBER nvarchar(255)
CREATE INDEX IDX_CNL_REC_SAT_PO_NUMBER ON PAS_IMPL.CNL_RECIPIENT_SAT(ASSIGNED_PO_NUMBER);
END

IF COL_LENGTH('PAS_IMPL.CNL_RECIPIENT_SAT','ASSIGNED_PIT_PO_NUMBER') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.CNL_RECIPIENT_SAT ADD ASSIGNED_PIT_PO_NUMBER nvarchar(255)
CREATE INDEX IDX_CNL_REC_SAT_PIT_PO_NUMBER ON PAS_IMPL.CNL_RECIPIENT_SAT(ASSIGNED_PIT_PO_NUMBER);
END

IF COL_LENGTH('PAS_IMPL.CNL_RECIPIENT_SAT','RECORD_ID') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.CNL_RECIPIENT_SAT ADD RECORD_ID uniqueidentifier NOT NULL DEFAULT NEWID()
END

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME ='PK_PAS_IMPL_CNL_RECIPIENT_SAT')
BEGIN
ALTER TABLE PAS_IMPL.CNL_RECIPIENT_SAT DROP [PK_PAS_IMPL_CNL_RECIPIENT_SAT]
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME ='PK_PAS_IMPL_CNL_RECIPIENT_SAT')
BEGIN

ALTER TABLE PAS_IMPL.CNL_RECIPIENT_SAT ADD CONSTRAINT [PK_PAS_IMPL_CNL_RECIPIENT_SAT] PRIMARY KEY NONCLUSTERED
(
	[CNL_RECIPIENT_HKEY] ASC,
	[LOAD_DATE] ASC,
	[RECORD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]

END

END