IF
	EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[AA_SAT]') AND TYPE IN (N'U'))
	AND
	NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'MVZ_NUMBER' AND Object_ID = Object_ID(N'[PAS_IMPL].[AA_SAT]'))
BEGIN
	ALTER TABLE PAS_IMPL.AA_SAT ADD MVZ_NUMBER NVARCHAR(50)
END
GO

IF
	EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[AA_SAT]') AND TYPE IN (N'U'))
	AND
	NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'SKK_NUMBER' AND Object_ID = Object_ID(N'[PAS_IMPL].[AA_SAT]'))
BEGIN
	ALTER TABLE PAS_IMPL.AA_SAT ADD SKK_NUMBER NVARCHAR(50)
END
GO

GO

IF 
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[AA_SAT]') AND TYPE IN (N'U'))
AND
EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'MVZ_NUMBER' AND Object_ID = Object_ID(N'[PAS_IMPL].[AA_SAT]'))
AND
NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AA_SAT_MVZ_NUMBER' AND object_id = OBJECT_ID('PAS_IMPL.AA_SAT')) 
BEGIN
	CREATE INDEX IDX_AA_SAT_MVZ_NUMBER ON PAS_IMPL.AA_SAT(MVZ_NUMBER)
END
GO

IF 
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[AA_SAT]') AND TYPE IN (N'U'))
AND
EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'SKK_NUMBER' AND Object_ID = Object_ID(N'[PAS_IMPL].[AA_SAT]'))
AND
NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AA_SAT_SKK_NUMBER' AND object_id = OBJECT_ID('PAS_IMPL.AA_SAT')) 
BEGIN
	CREATE INDEX IDX_AA_SAT_SKK_NUMBER ON PAS_IMPL.AA_SAT(SKK_NUMBER)
END
GO