IF 
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[AA_SAT]') AND TYPE IN (N'U'))
AND
EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_AA_SAT_CANCELLATION_DATE' AND object_id = OBJECT_ID('PAS_IMPL.AA_SAT')) 
BEGIN
	DROP INDEX PAS_IMPL.AA_SAT.IDX_AA_SAT_CANCELLATION_DATE
END
GO

IF 
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[AA_SAT]') AND TYPE IN (N'U'))
AND
EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'CANCELLATION_DATE' AND Object_ID = Object_ID(N'[PAS_IMPL].[AA_SAT]')) 
BEGIN
	ALTER TABLE PAS_IMPL.AA_SAT DROP COLUMN CANCELLATION_DATE
END
GO