IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[AA_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PAS_IMPL.AA_SAT','IS_TECHNICAL') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.AA_SAT ADD IS_TECHNICAL bit NOT NULL DEFAULT 0
END

END
GO