IF 
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[AA_BASE_COMM_SAT]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'EXPENSES_RATE' AND OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[AA_BASE_COMM_SAT]')) 
BEGIN
	ALTER TABLE PAS_IMPL.AA_BASE_COMM_SAT ADD EXPENSES_RATE decimal(15,7)
END
GO

IF 
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[AA_BASE_COMM_SAT]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'NATURAL_PERSON_RATE' AND OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[AA_BASE_COMM_SAT]')) 
BEGIN
	ALTER TABLE PAS_IMPL.AA_BASE_COMM_SAT ADD NATURAL_PERSON_RATE decimal(15,7)
END
GO

IF 
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[AA_BASE_COMM_SAT]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'SOLE_PROPRIATOR_RATE' AND OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[AA_BASE_COMM_SAT]')) 
BEGIN
	ALTER TABLE PAS_IMPL.AA_BASE_COMM_SAT ADD SOLE_PROPRIATOR_RATE decimal(15,7)
END
GO

IF 
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[COM_CALC_SAT]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'EXPENSES_RATE' AND OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[COM_CALC_SAT]')) 
BEGIN
	ALTER TABLE PAS_IMPL.COM_CALC_SAT ADD EXPENSES_RATE decimal(15,7)
END
GO

IF 
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[COM_CALC_SAT]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'NATURAL_PERSON_RATE' AND OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[COM_CALC_SAT]')) 
BEGIN
	ALTER TABLE PAS_IMPL.COM_CALC_SAT ADD NATURAL_PERSON_RATE decimal(15,7)
END
GO

IF 
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[COM_CALC_SAT]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'SOLE_PROPRIATOR_RATE' AND OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[COM_CALC_SAT]')) 
BEGIN
	ALTER TABLE PAS_IMPL.COM_CALC_SAT ADD SOLE_PROPRIATOR_RATE decimal(15,7)
END
GO

IF 
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_COMMISSION_SAT]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'CALCULATED_EXPENSES_RATE' AND OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_COMMISSION_SAT]')) 
BEGIN
	ALTER TABLE PAS_IMPL.POLICY_COMMISSION_SAT ADD CALCULATED_EXPENSES_RATE decimal(15,7)
END
GO

IF 
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_COMMISSION_SAT]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'CALCULATED_NATURAL_PERSON_RATE' AND OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_COMMISSION_SAT]')) 
BEGIN
	ALTER TABLE PAS_IMPL.POLICY_COMMISSION_SAT ADD CALCULATED_NP_RATE decimal(15,7)
END
GO

IF 
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_COMMISSION_SAT]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'CALCULATED_SOLE_PROPRIATOR_RATE' AND OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_COMMISSION_SAT]')) 
BEGIN
	ALTER TABLE PAS_IMPL.POLICY_COMMISSION_SAT ADD CALCULATED_SP_RATE decimal(15,7)
END
GO

IF 
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_COMMISSION_SAT]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'MANUAL_EXPENSES_RATE' AND OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_COMMISSION_SAT]')) 
BEGIN
	ALTER TABLE PAS_IMPL.POLICY_COMMISSION_SAT ADD MANUAL_EXPENSES_RATE decimal(15,7)
END
GO

IF 
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_COMMISSION_SAT]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'MANUAL_NATURAL_PERSON_RATE' AND OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_COMMISSION_SAT]')) 
BEGIN
	ALTER TABLE PAS_IMPL.POLICY_COMMISSION_SAT ADD MANUAL_NP_RATE decimal(15,7)
END
GO

IF 
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_COMMISSION_SAT]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'MANUAL_SOLE_PROPRIATOR_RATE' AND OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_COMMISSION_SAT]')) 
BEGIN
	ALTER TABLE PAS_IMPL.POLICY_COMMISSION_SAT ADD MANUAL_SP_RATE decimal(15,7)
END
GO

