IF EXISTS
    (SELECT * FROM sys.columns
     WHERE Name = N'VERSION'
     AND Object_ID = Object_ID(N'[BFX_IMPL].[PRODUCT_CONF]'))
BEGIN
EXEC SP_RENAME 'BFX_IMPL.PRODUCT_CONF.VERSION', 'CONF_VERSION', 'COLUMN';
END;

IF EXISTS
    (SELECT * FROM sys.columns
     WHERE Name = N'VERSION'
     AND Object_ID = Object_ID(N'[BFX_IMPL].[RATE_OF_RETURN]'))
BEGIN
EXEC SP_RENAME 'BFX_IMPL.RATE_OF_RETURN.VERSION', 'CONF_VERSION', 'COLUMN';
END;

IF EXISTS
    (SELECT * FROM sys.columns
     WHERE Name = N'VERSION'
     AND Object_ID = Object_ID(N'[BFX_IMPL].[STRATEGY_CONF]'))
BEGIN
EXEC SP_RENAME 'BFX_IMPL.STRATEGY_CONF.VERSION', 'CONF_VERSION', 'COLUMN';
END;

IF EXISTS
    (SELECT * FROM sys.columns
     WHERE Name = N'VERSION'
     AND Object_ID = Object_ID(N'[BFX_IMPL].[STRATEGY_INSTRUMENTS]'))
BEGIN
EXEC SP_RENAME 'BFX_IMPL.STRATEGY_INSTRUMENTS.VERSION', 'CONF_VERSION', 'COLUMN';
END;