IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[INQUIRY_SAT]') AND TYPE IN (N'U'))
BEGIN

    IF COL_LENGTH('PAS_IMPL.INQUIRY_SAT','TEXT_OF_ANSWER') IS NULL
    BEGIN
    ALTER TABLE PAS_IMPL.INQUIRY_SAT ADD TEXT_OF_ANSWER nvarchar(max)
    END

	IF COL_LENGTH('PAS_IMPL.INQUIRY_SAT','TEXT_OF_COMMENT') IS NULL
    BEGIN
    ALTER TABLE PAS_IMPL.INQUIRY_SAT ADD TEXT_OF_COMMENT nvarchar(max)
    END

END
GO