IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[CNL_RECIPIENT_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PAS_IMPL.CNL_RECIPIENT_SAT','IS_MANUAL_PIT') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.CNL_RECIPIENT_SAT ADD IS_MANUAL_PIT bit
END

END
GO