IF
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[PRODUCT_CONF]') AND TYPE IN (N'U'))
AND
COL_LENGTH('BFX_IMPL.PRODUCT_CONF','MF') IS NOT NULL
    BEGIN
        ALTER TABLE BFX_IMPL.PRODUCT_CONF DROP COLUMN MF
    END
GO

IF
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[PRODUCT_CONF]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'MF' AND OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[PRODUCT_CONF]'))
    BEGIN
        ALTER TABLE BFX_IMPL.PRODUCT_CONF ADD MF DECIMAL(15, 7) NULL
    END
GO