IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'PAS_IMPL.QUOTE_INVESTMENT_SAT') AND TYPE IN (N'U'))
BEGIN

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','PURCHASE_DATE') IS NOT NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		DROP COLUMN PURCHASE_DATE
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','PURCHASE_DATE') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD PURCHASE_DATE DATE
	END

END
GO