IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ACC_IMPL].[CRT_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('ACC_IMPL.CRT_SAT','TAX_CERTIFICATE_FORMAT') IS NULL
BEGIN
ALTER TABLE ACC_IMPL.CRT_SAT
ADD TAX_CERTIFICATE_FORMAT nvarchar(100)
END

END
GO