IF
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[RISKS]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'IS_CONTRIBUTION_REFUND' AND OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[RISKS]'))
BEGIN
	ALTER TABLE BFX_IMPL.RISKS ADD IS_CONTRIBUTION_REFUND BIT NOT NULL DEFAULT 0
END
GO