IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[PRODUCT_CONF]') AND TYPE IN (N'U'))
IF COL_LENGTH('BFX_IMPL.PRODUCT_CONF','CONSENT_TO_DATA_TRANSFERING_FNS') IS NULL
BEGIN
alter table [BFX_IMPL].[PRODUCT_CONF] add [CONSENT_TO_DATA_TRANSFERING_FNS] bit null
end
go