IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'BFX_IMPL.SEND_EVENT_CONFIGURATION') AND TYPE IN (N'U'))
BEGIN

	IF COL_LENGTH('BFX_IMPL.SEND_EVENT_CONFIGURATION','IS_RECORD_DISABLED') IS NULL
	BEGIN
		alter table BFX_IMPL.SEND_EVENT_CONFIGURATION
		add IS_RECORD_DISABLED bit null
	END

END

GO