IF EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[PRODUCTS]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'MAIN_LLOB' AND OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[PRODUCTS]'))
BEGIN
	ALTER TABLE BFX_IMPL.PRODUCTS ADD MAIN_LLOB [nvarchar](255)
END