IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'PAS_IMPL.QUOTE_SAT') AND TYPE IN (N'U'))
BEGIN

	IF COL_LENGTH('PAS_IMPL.QUOTE_SAT','GUARANTEE_INCOME_CODE') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_SAT
		ADD GUARANTEE_INCOME_CODE NVARCHAR(100)
	END

END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'PAS_IMPL.POLICY_SAT') AND TYPE IN (N'U'))
BEGIN

	IF COL_LENGTH('PAS_IMPL.POLICY_SAT','GUARANTEE_INCOME_CODE') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.POLICY_SAT
		ADD GUARANTEE_INCOME_CODE NVARCHAR(100)
	END

END
GO