IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'PAS_IMPL.REPORT_CONTRACT') AND TYPE IN (N'U'))
BEGIN
    IF COL_LENGTH('PAS_IMPL.REPORT_CONTRACT', 'CALCULATED_RATE') IS NULL
    BEGIN
        ALTER TABLE PAS_IMPL.REPORT_CONTRACT
        ADD CALCULATED_RATE DECIMAL(15,7)
    END
    
    IF COL_LENGTH('PAS_IMPL.REPORT_CONTRACT', 'MANUAL_RATE') IS NULL
    BEGIN
        ALTER TABLE PAS_IMPL.REPORT_CONTRACT
        ADD MANUAL_RATE DECIMAL(15,7)
    END
END
GO