IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[AA_PARTICIPANT_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PAS_IMPL.AA_PARTICIPANT_SAT','BANK_ACCOUNT_NUMBER') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.AA_PARTICIPANT_SAT
ADD BANK_ACCOUNT_NUMBER nvarchar(256)
END

END
GO