IF
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[CUMULATION_SAT]') AND TYPE IN (N'U'))
AND
EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'CUMULATION_RULE_ID' AND OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[CUMULATION_SAT]'))
BEGIN
	ALTER TABLE PAS_IMPL.CUMULATION_SAT
	ALTER COLUMN CUMULATION_RULE_ID NVARCHAR(255) NOT NULL
END
GO

IF
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[CUMULATION_SAT]') AND TYPE IN (N'U'))
AND
EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME ='PK_PAS_IMPL_CUMULATION_SAT')
BEGIN
	ALTER TABLE [PAS_IMPL].[CUMULATION_SAT] DROP CONSTRAINT [PK_PAS_IMPL_CUMULATION_SAT]
END
GO

IF
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[CUMULATION_SAT]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME ='PK_PAS_IMPL_CUMULATION_SAT')
BEGIN
ALTER TABLE [PAS_IMPL].[CUMULATION_SAT] ADD CONSTRAINT [PK_PAS_IMPL_CUMULATION_SAT] PRIMARY KEY NONCLUSTERED
(
    [CUMULATION_HKEY] ASC,
	[CUMULATION_RULE_ID] ASC,
	[RISK_GROUP_CODE] ASC,
	[PARTY_TYPE] ASC,
	[LOAD_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
END
GO

IF
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[CUMULATION_RISK_GROUP]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'MRC_ALGORITHM' AND OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[CUMULATION_RISK_GROUP]'))
BEGIN
	ALTER TABLE PAS_IMPL.CUMULATION_RISK_GROUP ADD MRC_ALGORITHM NVARCHAR(MAX) NULL
END
GO

IF
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[CUMULATION_RISK_GROUP]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'MRC_ALGORITHM_PRODUCT_CODES' AND OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[CUMULATION_RISK_GROUP]'))
BEGIN
	ALTER TABLE PAS_IMPL.CUMULATION_RISK_GROUP ADD MRC_ALGORITHM_PRODUCT_CODES NVARCHAR(MAX) NULL
END
GO