IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[CUMULATION_RISKS_SAT]') AND TYPE IN (N'U'))
BEGIN

	IF COL_LENGTH('PAS_IMPL.CUMULATION_RISKS_SAT','RISK_INSURED_SUM') IS NOT NULL
	BEGIN
	    ALTER TABLE [PAS_IMPL].[CUMULATION_RISKS_SAT] ALTER COLUMN RISK_INSURED_SUM DECIMAL(15,2) NOT NULL
	END

	IF COL_LENGTH('PAS_IMPL.CUMULATION_RISKS_SAT','RISK_CURRENCY_CODE') IS NOT NULL
	BEGIN
	    ALTER TABLE [PAS_IMPL].[CUMULATION_RISKS_SAT] ALTER COLUMN RISK_CURRENCY_CODE NVARCHAR(64) NOT NULL
	END

	IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME ='PK_PAS_IMPL_CUMULATION_RISKS_SAT')
	BEGIN
	    ALTER TABLE [PAS_IMPL].[CUMULATION_RISKS_SAT] DROP CONSTRAINT [PK_PAS_IMPL_CUMULATION_RISKS_SAT]
	END

	IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME ='PK_PAS_IMPL_CUMULATION_RISKS_SAT')
	BEGIN
        ALTER TABLE [PAS_IMPL].[CUMULATION_RISKS_SAT] ADD CONSTRAINT [PK_PAS_IMPL_CUMULATION_RISKS_SAT] PRIMARY KEY NONCLUSTERED
        (
            [CUMULATION_RISKS_HKEY] ASC,
            [RISK_GROUP_CODE] ASC,
            [DOCUMENT_NUMBER] ASC,
            [PARTY_CODE] ASC,
            [RISK_CODE] ASC,
            [RISK_INSURED_SUM] ASC,
            [RISK_CURRENCY_CODE] ASC,
            [LOAD_DATE] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	END

END