IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[INVESTMENT_PROFIT]') AND TYPE IN (N'U'))
BEGIN

DROP TABLE PAS_IMPL.INVESTMENT_PROFIT

END

----------------------------------------------------------------------------

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[INVESTMENT_PROFIT]') AND TYPE IN (N'U'))
BEGIN

CREATE TABLE PAS_IMPL.INVESTMENT_PROFIT (
    INV_PROFIT_ROW_ID UNIQUEIDENTIFIER,
    IMPORT_DOCUMENT_ID UNIQUEIDENTIFIER NOT NULL,
	CONTRACT_NUMBER NVARCHAR(64) NOT NULL,
	INV_PROFIT_CALC_DATE DATE NOT NULL,
	INV_PROFIT_RATE DECIMAL (15, 2) NOT NULL,
	INV_PROFIT_PAY_TYPE_CODE INT NOT NULL,
	LOAD_DATE DATETIME2 NOT NULL,
	CONSTRAINT [PK_INV_PROFIT_RECORD]
	PRIMARY KEY CLUSTERED (INV_PROFIT_ROW_ID ASC)
)

END


IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_INV_PROFIT_CONTRACT_NUMBER'
	AND object_id = OBJECT_ID('PAS_IMPL.INVESTMENT_PROFIT') ) BEGIN
	CREATE INDEX IDX_INV_PROFIT_CONTRACT_NUMBER ON
PAS_IMPL.INVESTMENT_PROFIT(CONTRACT_NUMBER)
END

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_INV_PROFIT_CALC_DATE'
	AND object_id = OBJECT_ID('PAS_IMPL.INVESTMENT_PROFIT') ) BEGIN
	CREATE INDEX IDX_INV_PROFIT_CALC_DATE ON
PAS_IMPL.INVESTMENT_PROFIT(INV_PROFIT_CALC_DATE)
END

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_INV_PROFIT_TYPE_CODE'
	AND object_id = OBJECT_ID('PAS_IMPL.INVESTMENT_PROFIT') ) BEGIN
	CREATE INDEX IDX_INV_PROFIT_TYPE_CODE ON
PAS_IMPL.INVESTMENT_PROFIT(INV_PROFIT_PAY_TYPE_CODE)
END

-----------------------------------------------------------------------------------------

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[INVEST_PROFIT_ALLOCATION]') AND TYPE IN (N'U'))
BEGIN

CREATE TABLE PAS_IMPL.INVEST_PROFIT_ALLOCATION (
    ALLOCATION_ID UNIQUEIDENTIFIER,
    INV_PROFIT_ROW_ID UNIQUEIDENTIFIER NOT NULL,
	REFERENCE_NUMBER NVARCHAR(64) NOT NULL,
	REFERENCE_CONF NVARCHAR(256) NOT NULL,
	IS_CANCELLED BIT NOT NULL,
	IS_PAID BIT NOT NULL,
	LOAD_DATE DATETIME2 NOT NULL,
	CONSTRAINT [PK_INV_PROFIT_ALLOCATION]
	PRIMARY KEY CLUSTERED (ALLOCATION_ID ASC),
    FOREIGN KEY (INV_PROFIT_ROW_ID) REFERENCES PAS_IMPL.INVESTMENT_PROFIT(INV_PROFIT_ROW_ID)
)

END

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_INV_PROF_ALLOC_INV_PROFIT_ROW_ID'
	AND object_id = OBJECT_ID('PAS_IMPL.INVEST_PROFIT_ALLOCATION') ) BEGIN
	CREATE INDEX IDX_INV_PROF_ALLOC_INV_PROFIT_ROW_ID ON
PAS_IMPL.INVEST_PROFIT_ALLOCATION(INV_PROFIT_ROW_ID)
END

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_INV_PROF_ALLOC_REF_NUMBER'
	AND object_id = OBJECT_ID('PAS_IMPL.INVEST_PROFIT_ALLOCATION') ) BEGIN
	CREATE INDEX IDX_INV_PROF_ALLOC_REF_NUMBER ON
PAS_IMPL.INVEST_PROFIT_ALLOCATION(REFERENCE_NUMBER)
END

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_INV_PROF_ALLOC_REF_CONF'
	AND object_id = OBJECT_ID('PAS_IMPL.INVEST_PROFIT_ALLOCATION') ) BEGIN
	CREATE INDEX IDX_INV_PROF_ALLOC_REF_CONF ON
PAS_IMPL.INVEST_PROFIT_ALLOCATION(REFERENCE_CONF)
END

----------------------------------------------------------------------------------------
