IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'PAS_IMPL.REPORT_CONTRACT') AND TYPE IN (N'U'))
BEGIN
    IF COL_LENGTH('PAS_IMPL.REPORT_CONTRACT', 'INITIATOR_TAB_NUMBER') IS NULL
    BEGIN
        ALTER TABLE PAS_IMPL.REPORT_CONTRACT
        ADD INITIATOR_TAB_NUMBER NVARCHAR(256) NULL
    END
END
GO