IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[QUOTE_SAT]') AND TYPE IN (N'U'))
BEGIN

    IF COL_LENGTH('PAS_IMPL.QUOTE_SAT','VARIANT_CODE') IS NULL
    BEGIN
    ALTER TABLE PAS_IMPL.QUOTE_SAT ADD VARIANT_CODE nvarchar(100)
    END

    IF COL_LENGTH('PAS_IMPL.QUOTE_SAT','RATE_OF_RETURN') IS NULL
    BEGIN
    ALTER TABLE PAS_IMPL.QUOTE_SAT ADD RATE_OF_RETURN decimal(15,7)
    END

    IF COL_LENGTH('PAS_IMPL.QUOTE_SAT','CASHBACK') IS NULL
    BEGIN
    ALTER TABLE PAS_IMPL.QUOTE_SAT ADD CASHBACK decimal(15,7)
    END

END

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_SAT]') AND TYPE IN (N'U'))
BEGIN

    IF COL_LENGTH('PAS_IMPL.POLICY_SAT','VARIANT_CODE') IS NULL
    BEGIN
    ALTER TABLE PAS_IMPL.POLICY_SAT ADD VARIANT_CODE nvarchar(100)
    END

    IF COL_LENGTH('PAS_IMPL.POLICY_SAT','RATE_OF_RETURN') IS NULL
    BEGIN
    ALTER TABLE PAS_IMPL.POLICY_SAT ADD RATE_OF_RETURN decimal(15,7)
    END

    IF COL_LENGTH('PAS_IMPL.POLICY_SAT','CASHBACK') IS NULL
    BEGIN
    ALTER TABLE PAS_IMPL.POLICY_SAT ADD CASHBACK decimal(15,7)
    END

END
