-- Добавление столбцов DIRECT_RATE в таблицу PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE1 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE2 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE3 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE4 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE5 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE6 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE7 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE8 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE9 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE10 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE11 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE12 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE13 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE14 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE15 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE16 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE17 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE18 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE19 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE20 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE21 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE22 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD DIRECT_RATE23 DECIMAL(15, 2)
GO

-- Добавление столбцов REINSURANCE_RATE в таблицу PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE1 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE2 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE3 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE4 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE5 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE6 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE7 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE8 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE9 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE10 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE11 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE12 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE13 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE14 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE15 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE16 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE17 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE18 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE19 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE20 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE21 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE22 DECIMAL(15, 2)
GO

ALTER TABLE PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
ADD REINSURANCE_RATE23 DECIMAL(15, 2)
GO