-- 6. Валюта
CREATE TABLE [PAS_IMPL].[CUMULATION_CURRENCY_RATE](
	[ID] [uniqueidentifier] NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[CURRENCY_CODE] [nchar](3) NOT NULL,
	[CURRENCY_RATE]  money NOT NULL,
	[ACTIVE_FROM] datetime NOT NULL,
	[ACTIVE_TO] datetime NOT NULL
)
GO

ALTER TABLE PAS_IMPL.CUMULATION_CURRENCY_RATE WITH CHECK ADD CONSTRAINT FK_PAS_IMPL_CUMULATION_CURRENCY_RATE_CURRENCY_CODE FOREIGN KEY(CURRENCY_CODE)
REFERENCES BFX.CURRENCY_REF(CURRENCY_CODE)
GO