
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[AA_BASE_COMM_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PAS_IMPL.AA_BASE_COMM_SAT','MANUAL_RULE_DESCRIPTION') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.AA_BASE_COMM_SAT
ADD MANUAL_RULE_DESCRIPTION nvarchar(1024)
END

END
GO