-- 1.1. Описание групп продуктов
CREATE TABLE [PAS_IMPL].[CUMULATION_PRODUCT_GROUP](
	[CODE] [nvarchar](255) PRIMARY KEY,
	[CODE_DESCRIPTION] [nvarchar](max) NOT NULL
)
GO

-- 1.2. Связь группы продуктов с кодами продуктов
CREATE TABLE [PAS_IMPL].[CUMULATION_PRODUCT_GROUP_RELATION](
	[ID] [uniqueidentifier] NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[PRODUCT_GROUP_CODE] [nvarchar](255) NOT NULL,
	[PRODUCT_CODE] [nvarchar](255) NOT NULL
)
GO

ALTER TABLE PAS_IMPL.CUMULATION_PRODUCT_GROUP_RELATION WITH CHECK ADD CONSTRAINT FK_PAS_IMPL_CUMULATION_PRODUCT_GROUP_RELATION_PRODUCT_GROUP_CODE FOREIGN KEY(PRODUCT_GROUP_CODE)
REFERENCES PAS_IMPL.CUMULATION_PRODUCT_GROUP(CODE)
GO

-- 2.1. Описание группы рисков
CREATE TABLE [PAS_IMPL].[CUMULATION_RISK_GROUP](
	[CODE] [nvarchar](255) PRIMARY KEY,
	[CODE_DESCRIPTION] [nvarchar](max) NOT NULL
)
GO

-- 2.2. Связь группы рисков с кодами рисков
CREATE TABLE [PAS_IMPL].[CUMULATION_RISK_GROUP_RELATION](
	[ID] [uniqueidentifier] NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[GROUP_CODE] [nvarchar](255) NOT NULL,
	[RISK_CODE] [nvarchar](255) NOT NULL
)
GO

ALTER TABLE PAS_IMPL.CUMULATION_RISK_GROUP_RELATION WITH CHECK ADD CONSTRAINT FK_PAS_IMPL_CUMULATION_RISK_GROUP_RELATION_RISK_CODE FOREIGN KEY(RISK_CODE)
REFERENCES BFX_IMPL.RISKS(CODE)

ALTER TABLE PAS_IMPL.CUMULATION_RISK_GROUP_RELATION WITH CHECK ADD CONSTRAINT FK_PAS_IMPL_CUMULATION_RISK_GROUP_RELATION_GROUP_CODE FOREIGN KEY(GROUP_CODE)
REFERENCES PAS_IMPL.CUMULATION_RISK_GROUP(CODE)

-- 3.1. Лимиты по возрасту контрагента
CREATE TABLE [PAS_IMPL].[CUMULATION_LIMIT_AGE](
	[CODE] [nvarchar](255) PRIMARY KEY,
	[AGE_FROM] int NULL,
	[AGE_TO] int NULL
)
GO

-- 3.2. Лимиты по страховой сумме
CREATE TABLE [PAS_IMPL].[CUMULATION_LIMIT_AMOUNT](
	[CODE] [nvarchar](255) PRIMARY KEY,
	[AMOUNT_FROM] money NULL,
	[AMOUNT_TO] money NULL
)
GO

-- 3.3. Лимиты период действия
CREATE TABLE [PAS_IMPL].[CUMULATION_LIMIT_ACTIVE_PERIOD](
	[CODE] [nvarchar](255) PRIMARY KEY,
	[ACTIVE_FROM] datetime NOT NULL,
	[ACTIVE_TO] datetime NOT NULL
)
GO

-- 4. Триггеры
CREATE TABLE [PAS_IMPL].[CUMULATION_TRIGGER](
	[CODE] [nvarchar](255) PRIMARY KEY,
	[DESCRIPTION] [nvarchar](max)
)
GO

-- 5. Кумуляция
CREATE TABLE [PAS_IMPL].[CUMULATION](
	[ID] [uniqueidentifier] NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[PRODUCT_GROUP_CODE] [nvarchar](255) NOT NULL,
	[PRODUCT_CODE] [nvarchar](255) NOT NULL,
	[RISK_GROUP_CODE] [nvarchar](255) NOT NULL,
	[LIMIT_AGE_CODE] [nvarchar](255) NOT NULL,
	[LIMIT_AMOUNT_CODE] [nvarchar](255) NOT NULL,
	[TRIGGER_CODE] [nvarchar](255) NOT NULL,
	[ACTIVE_PERIOD_CODE] [nvarchar](255) NOT NULL
)
GO

ALTER TABLE PAS_IMPL.CUMULATION WITH CHECK ADD CONSTRAINT FK_PAS_IMPL_CUMULATION_PRODUCT_GROUP_CODE FOREIGN KEY(PRODUCT_GROUP_CODE)
REFERENCES PAS_IMPL.CUMULATION_PRODUCT_GROUP(CODE)

ALTER TABLE PAS_IMPL.CUMULATION WITH CHECK ADD CONSTRAINT FK_PAS_IMPL_CUMULATION_RISK_GROUP_CODE FOREIGN KEY(RISK_GROUP_CODE)
REFERENCES PAS_IMPL.CUMULATION_RISK_GROUP(CODE)

ALTER TABLE PAS_IMPL.CUMULATION WITH CHECK ADD CONSTRAINT FK_PAS_IMPL_LIMIT_AGE_CODE FOREIGN KEY(LIMIT_AGE_CODE)
REFERENCES PAS_IMPL.CUMULATION_LIMIT_AGE(CODE)

ALTER TABLE PAS_IMPL.CUMULATION WITH CHECK ADD CONSTRAINT FK_PAS_IMPL_LIMIT_AMOUNT_CODE FOREIGN KEY(LIMIT_AMOUNT_CODE)
REFERENCES PAS_IMPL.CUMULATION_LIMIT_AMOUNT(CODE)

ALTER TABLE PAS_IMPL.CUMULATION WITH CHECK ADD CONSTRAINT FK_PAS_IMPL_TRIGGER_CODE FOREIGN KEY(TRIGGER_CODE)
REFERENCES PAS_IMPL.CUMULATION_TRIGGER(CODE)

ALTER TABLE PAS_IMPL.CUMULATION WITH CHECK ADD CONSTRAINT FK_PAS_IMPL_CUMULATION_ACTIVE_PERIOD_CODE FOREIGN KEY(ACTIVE_PERIOD_CODE)
REFERENCES PAS_IMPL.CUMULATION_LIMIT_ACTIVE_PERIOD(CODE)