IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'PAS_IMPL.QUOTE_INVESTMENT_SAT') AND TYPE IN (N'U'))
BEGIN

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','RATE_OF_RETURN') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD RATE_OF_RETURN DECIMAL(15, 4)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','RATE_OF_RETURN_MANUAL_RATE') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD RATE_OF_RETURN_MANUAL_RATE DECIMAL(15, 4)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','VARIANT_CODE') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD VARIANT_CODE NVARCHAR(255)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','VARIANT_DESCRIPTION') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD VARIANT_DESCRIPTION NVARCHAR(MAX)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','STRATEGY_DESCRIPTION_FULL') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD STRATEGY_DESCRIPTION_FULL NVARCHAR(MAX)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','CASHBACK') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD CASHBACK DECIMAL(15, 4)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','PAYOFF_DESCRIPTION') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD PAYOFF_DESCRIPTION NVARCHAR(MAX)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','IS_MANUAL_SET_INV_PARAMS') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD IS_MANUAL_SET_INV_PARAMS BIT
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','BASE_ACTIVE_DESCRIPTION') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD BASE_ACTIVE_DESCRIPTION NVARCHAR(MAX)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','PARTICIPATION_COEFF') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD PARTICIPATION_COEFF DECIMAL(15, 4)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','OPTION_PRICE') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD OPTION_PRICE DECIMAL(15, 4)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','BARRIER') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD BARRIER NVARCHAR(255)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','BARRIER_AUTO_CALL') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD BARRIER_AUTO_CALL NVARCHAR(255)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','PARTICIPATION_COEFF_BY_PERIODS') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD PARTICIPATION_COEFF_BY_PERIODS NVARCHAR(255)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','PURCHASE_DATE') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD PURCHASE_DATE DATE
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','EMITENT') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD EMITENT NVARCHAR(255)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','FIX_RATE') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD FIX_RATE DECIMAL(15, 4)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','INITIAL_SHARE') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD INITIAL_SHARE DECIMAL(15, 4)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','HEDGE_COST') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD HEDGE_COST DECIMAL(15, 4)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','SPREAD_BA') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD SPREAD_BA DECIMAL(15, 4)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','PAY_OFF_SHORT_DESCRIPTION') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD PAY_OFF_SHORT_DESCRIPTION NVARCHAR(MAX)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','TOOL_TYPE') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD TOOL_TYPE NVARCHAR(255)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','MEASURE_TOOL_NOMINAL') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD MEASURE_TOOL_NOMINAL DECIMAL(15, 4)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','CALCULATING_AGENT') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD CALCULATING_AGENT NVARCHAR(255)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','PRICE_OF_MEASURE_TOOL') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD PRICE_OF_MEASURE_TOOL DECIMAL(15, 4)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','PART_OF_PREMIUM_FOR_TOOL') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD PART_OF_PREMIUM_FOR_TOOL DECIMAL(15, 4)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','DISCOUNT') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD DISCOUNT DECIMAL(15, 4)
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','DISCHARGE_DATE') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD DISCHARGE_DATE DATE
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','DID_BEGIN_DATE') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD DID_BEGIN_DATE DATE
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','DID_END_DATE') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD DID_END_DATE DATE
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','WINDOW_START_DATE') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD WINDOW_START_DATE DATE
	END

	IF COL_LENGTH('PAS_IMPL.QUOTE_INVESTMENT_SAT','WINDOW_START_END') IS NULL
	BEGIN
		ALTER TABLE PAS_IMPL.QUOTE_INVESTMENT_SAT
		ADD WINDOW_START_END DATE
	END

END
GO