IF
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[PRODUCT_CONF]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'COOL_OFF_DID_RATE' AND OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[PRODUCT_CONF]'))
BEGIN
	ALTER TABLE BFX_IMPL.PRODUCT_CONF ADD COOL_OFF_DID_RATE DECIMAL(15, 4) NULL
END
GO