IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[CNL_AMENDMENT_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PAS_IMPL.CNL_AMENDMENT_SAT','FIXED_EXCH_RATE') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.CNL_AMENDMENT_SAT ADD FIXED_EXCH_RATE decimal(15,7)
END

IF COL_LENGTH('PAS_IMPL.CNL_AMENDMENT_SAT','USE_FIXED_EXCH_RATE') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.CNL_AMENDMENT_SAT ADD USE_FIXED_EXCH_RATE bit
END

END