ALTER TABLE BFX_IMPL.PRODUCTS
WITH CHECK ADD CONSTRAINT UQ_PRODUCTS_PRODUCT_CODE UNIQUE(CODE)
GO

CREATE TABLE BFX_IMPL.AA_VARIANT
(
	[CODE] NVARCHAR(255) PRIMARY KEY,
	[CODE_DESCRIPTION] [nvarchar](max) NOT NULL
)
GO

CREATE TABLE BFX_IMPL.AA_PRODUCT_VARIANT
(
	[PRODUCT_CODE] NVARCHAR(255) NOT NULL,
	[VARIANT_CODE] NVARCHAR(255) NOT NULL,
	CONSTRAINT UC_BFX_IMPL_AA_PRODUCT_VARIANT UNIQUE (PRODUCT_CODE, VARIANT_CODE),
	CONSTRAINT FK_BFX_IMPL_AA_PRODUCT_VARIANT_PRODUCT FOREIGN KEY(PRODUCT_CODE) REFERENCES BFX_IMPL.PRODUCTS(CODE),
	CONSTRAINT FK_BFX_IMPL_AA_PRODUCT_VARIANT_VARIANT FOREIGN KEY(VARIANT_CODE) REFERENCES BFX_IMPL.AA_VARIANT(CODE)
);
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[AA_BASE_COMM_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PAS_IMPL.AA_BASE_COMM_SAT','VARIANT_VALUE_REF_ID') IS NULL
BEGIN

ALTER TABLE pas_impl.AA_BASE_COMM_SAT ADD VARIANT_VALUE_REF_ID BIGINT NULL
CREATE INDEX IDX_AA_BASE_COMM_SAT_VARIANT_CODE ON PAS_IMPL.AA_BASE_COMM_SAT(VARIANT_VALUE_REF_ID)

END

IF COL_LENGTH('PAS_IMPL.AA_BASE_COMM_SAT','VARIANT_INVERSION') IS NULL
BEGIN

ALTER TABLE pas_impl.AA_BASE_COMM_SAT ADD VARIANT_INVERSION BIT NULL

END

END
GO
