
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[PRODUCTS]') AND TYPE IN (N'U'))
BEGIN

    IF COL_LENGTH('BFX_IMPL.PRODUCTS','SALES_SEGMENT') IS NULL
    BEGIN
    ALTER TABLE BFX_IMPL.PRODUCTS ADD SALES_SEGMENT nvarchar (255) NULL
    END

END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[REPORT_CONTRACT]') AND TYPE IN (N'U'))
BEGIN

    IF COL_LENGTH('PAS_IMPL.REPORT_CONTRACT','PRODUCT_SALES_SEGMENT') IS NULL
    BEGIN
    ALTER TABLE PAS_IMPL.REPORT_CONTRACT ADD PRODUCT_SALES_SEGMENT nvarchar (255) NULL
    END

END
GO