IF
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[PRODUCT_CONF]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'NUM_OF_WORKING_DAYS_TO_INVEST' AND OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[PRODUCT_CONF]'))
BEGIN
	ALTER TABLE BFX_IMPL.PRODUCT_CONF ADD NUM_OF_WORKING_DAYS_TO_INVEST INT NULL
END
GO

IF
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[PRODUCT_CONF]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'MF' AND OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[PRODUCT_CONF]'))
BEGIN
	ALTER TABLE BFX_IMPL.PRODUCT_CONF ADD MF DECIMAL(15, 7) NULL
END
GO