IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[FUND_STATUS]') AND TYPE IN (N'U'))
BEGIN
    DROP TABLE BFX_IMPL.FUND_STATUS
END
GO

CREATE TABLE BFX_IMPL.FUND_STATUS (
    [ID] INT IDENTITY(1,1) PRIMARY KEY,
	[CODE] NVARCHAR(255) NOT NULL,
	[DESCRIPTION] NVARCHAR(MAX) NOT NULL
)
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[FUND_ALLOW_IMPORT]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE BFX_IMPL.FUND_ALLOW_IMPORT
END
GO

CREATE TABLE BFX_IMPL.FUND_ALLOW_IMPORT (
    [ID] INT IDENTITY(1,1) PRIMARY KEY,
	[CODE] NVARCHAR(255) NOT NULL,
	[DESCRIPTION] NVARCHAR(MAX) NOT NULL
);
GO