/**
* Description: Create 3 tables for Risks, Insurance Program and Products
* Auth: IvanM
*/

-- [BFX_IMPL].[RISKS]
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[RISKS]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[RISKS]
END
GO

CREATE TABLE [BFX_IMPL].[RISKS] (
[ID] [UNIQUEIDENTIFIER] NOT NULL,
[CODE] NVARCHAR(255) NOT NULL,
[TYPE] NVARCHAR(255) NOT NULL,
[SHORT_DESCRIPTION] NVARCHAR(MAX) NOT NULL,
[FULL_DESCRIPTION] NVARCHAR(MAX) NOT NULL,
CONSTRAINT [PK_CT_RISKS] PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO


-- [BFX_IMPL].[INSURANCE_PROGRAMS]
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[INSURANCE_PROGRAMS]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[INSURANCE_PROGRAMS]
END
GO

CREATE TABLE [BFX_IMPL].[INSURANCE_PROGRAMS] (
[ID] [UNIQUEIDENTIFIER] NOT NULL,
[CODE] NVARCHAR(255) NOT NULL,
[DESCRIPTION] NVARCHAR(MAX) NOT NULL,
CONSTRAINT [PK_CT_INSURANCE_PROGRAMS] PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO


-- [BFX_IMPL].[PRODUCTS]
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[PRODUCTS]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[PRODUCTS]
END
GO

CREATE TABLE [BFX_IMPL].[PRODUCTS] (
[ID] [UNIQUEIDENTIFIER] NOT NULL,
[CODE] NVARCHAR(255) NOT NULL,
[PRODUCT_GROUP] NVARCHAR(255) NOT NULL,
[DESCRIPTION] NVARCHAR(MAX) NOT NULL,
CONSTRAINT [PK_CT_PRODUCTS] PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO