-- Add new table
-- [BFX_IMPL].[GIFT_SERVICE]
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[GIFT_SERVICE]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[GIFT_SERVICE]
END
GO

CREATE TABLE [BFX_IMPL].[GIFT_SERVICE] (
[ID] INT NOT NULL,
[NAME] NVARCHAR(255) NOT NULL,
[CODE] NVARCHAR(255) NOT NULL,
[DESCRIPTION] NVARCHAR(255) NOT NULL,
CONSTRAINT [PK_CT_GIFT_SERVICE] PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO