IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[SEGMENT]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[SEGMENT] 
END
GO

CREATE TABLE [BFX_IMPL].[SEGMENT] (
[CODE] NVARCHAR(255) NOT NULL,
[DESCRIPTION] NVARCHAR(255) NOT NULL,
CONSTRAINT [PK_SEGMENT]
PRIMARY KEY CLUSTERED ([CODE] ASC)
)
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[BENEFICIARY_OWNER]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[BENEFICIARY_OWNER] 
END
GO

CREATE TABLE [BFX_IMPL].[BENEFICIARY_OWNER] (
[CODE] NVARCHAR(255) NOT NULL,
[DESCRIPTION] NVARCHAR(255) NOT NULL,
CONSTRAINT [PK_BENEFICIARY_OWNER]
PRIMARY KEY CLUSTERED ([CODE] ASC)
)
GO