ALTER TABLE acc_impl.BANK_STATEMENT_ITEM ALTER COLUMN TOLERANCE int not null
GO
EXEC sp_rename 'acc_impl.BANK_STATEMENT_ITEM.TOLERANCE', 'TOLERANCE_TYPE', 'COLUMN'
GO
EXEC sp_rename 'acc_impl.ALLOCATION.DOCUMENT_NO', 'REFERENCE_NO', 'COLUMN'
GO
EXEC sp_rename 'acc_impl.ALLOCATION.MATCHING_TYPE', 'DOCUMENT_TYPE_ID', 'COLUMN'
GO
ALTER TABLE acc_impl.MATCHING DROP COLUMN pay_amount;
GO
ALTER TABLE acc_impl.ALLOCATION DROP COLUMN ALLOCATION_STATUS_ID
GO

-- create tables for a policy strategy
CREATE TABLE [ACC_IMPL].[ALLOCATION_POLICY](
	[ALLOCATION_ID] [bigint] NOT NULL,
	[DUE_DATE] [date] NOT NULL,

	CONSTRAINT [PK_ACC_IMPL_ALLOCATION_POLICY_ALLOCATION_ID] PRIMARY KEY CLUSTERED
	(
		[ALLOCATION_ID] ASC
	)
)
GO

ALTER TABLE [ACC_IMPL].[ALLOCATION_POLICY]  WITH CHECK ADD CONSTRAINT [FK_ACC_IMPL_ALLOCATION_POLICY_BASE_ALLOCATION_ID] FOREIGN KEY([ALLOCATION_ID])
REFERENCES [ACC_IMPL].[ALLOCATION] ([ALLOCATION_ID])
GO

ALTER TABLE [ACC_IMPL].[ALLOCATION_POLICY] CHECK CONSTRAINT [FK_ACC_IMPL_ALLOCATION_POLICY_BASE_ALLOCATION_ID]
GO

CREATE TABLE [ACC_IMPL].[MATCHING_POLICY](
	[MATCHING_ID] [bigint] NOT NULL,
	[PAYER_CODE] [nvarchar](128) NOT NULL,
	[SOURCE_LINE_ID] [nvarchar](50) NOT NULL,
	[IS_LIFE] [bit] NOT NULL,

	CONSTRAINT [PK_ACC_IMPL_MATCHING_POLICY_MATCHING_ID] PRIMARY KEY CLUSTERED
	(
		[MATCHING_ID] ASC
	)
)
GO

ALTER TABLE [ACC_IMPL].[MATCHING_POLICY]  WITH CHECK ADD CONSTRAINT [FK_ACC_IMPL_MATCHING_POLICY_BASE_MATCHING_ID] FOREIGN KEY([MATCHING_ID])
REFERENCES [ACC_IMPL].[MATCHING] ([MATCHING_ID])
GO

ALTER TABLE [ACC_IMPL].[MATCHING_POLICY] CHECK CONSTRAINT [FK_ACC_IMPL_MATCHING_POLICY_BASE_MATCHING_ID]
GO
