IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[PAYMENT_FREQUENCY]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[PAYMENT_FREQUENCY]
END
GO

CREATE TABLE [BFX_IMPL].[PAYMENT_FREQUENCY] (
[ID] [UNIQUEIDENTIFIER] NOT NULL,
[CODE] NVARCHAR(255) NOT NULL,
[DESCRIPTION] NVARCHAR(MAX) NOT NULL,
PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[PAYMENT_VARIANT]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[PAYMENT_VARIANT]
END
GO

CREATE TABLE [BFX_IMPL].[PAYMENT_VARIANT] (
[ID] [UNIQUEIDENTIFIER] NOT NULL,
[CODE] NVARCHAR(255) NOT NULL,
[DESCRIPTION] NVARCHAR(MAX) NOT NULL,
PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[ISSUE_FORM]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[ISSUE_FORM]
END
GO

CREATE TABLE [BFX_IMPL].[ISSUE_FORM] (
[ID] [UNIQUEIDENTIFIER] NOT NULL,
[CODE] NVARCHAR(255) NOT NULL,
[DESCRIPTION] NVARCHAR(MAX) NOT NULL,
PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO