/**
* Description: Add table for CBR key rates 
* Auth: IvanM
*/

-- [BFX_IMPL].[BANK_KEY_RATE]
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[BANK_KEY_RATE]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[BANK_KEY_RATE]
END
GO

CREATE TABLE [BFX_IMPL].[BANK_KEY_RATE] (
[RATE_DATE] DATE,
[RATE] FLOAT,
CONSTRAINT [PK_BANK_KEY_RATE] PRIMARY KEY CLUSTERED ([RATE_DATE] ASC)
)
GO