IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[P_PAYMENT_PLAN_SAT]') AND TYPE IN (N'U'))
BEGIN
	ALTER TABLE pas_impl.P_PAYMENT_PLAN_SAT DROP COLUMN ADDITIONAL_ATTRIBUTES;
	ALTER TABLE pas_impl.P_PAYMENT_PLAN_SAT DROP COLUMN ADDITIONAL_ATTRIBUTES_HKEY;
END
GO

