-- create table for country (OKSM)
IF NOT EXISTS (SELECT * FROM SYS.SCHEMAS WHERE [NAME] = N'BFX_IMPL')
EXEC('CREATE SCHEMA [BFX_IMPL]')
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[COUNTRY_REF]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[COUNTRY_REF]
END
GO

CREATE TABLE [BFX_IMPL].[COUNTRY_REF] (
[COUNTRY_CODE] NVARCHAR(3) NOT NULL,
[COUNTRY_SHORT_NAME] NVARCHAR(255) NOT NULL,
[COUNTRY_FULL_NAME] NVARCHAR(255) NULL,
[ALFA_2] NVARCHAR(2) NOT NULL,
[ALFA_3] NVARCHAR(3) NOT NULL
)
GO