CREATE TABLE [BFX_IMPL].[VAT](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[RATE] [decimal](12,6) NOT NULL,
	[VALID_FROM] [date] NOT NULL,
	[VALID_TO] [date] NOT NULL,
CONSTRAINT [PK_CT_VAT] PRIMARY KEY CLUSTERED ([ID] ASC) ON [PRIMARY]
)
GO

INSERT INTO [BFX_IMPL].[VAT] ([RATE],[VALID_FROM],[VALID_TO])
VALUES (18, '2004-01-01', '2019-01-01')
GO

INSERT INTO [BFX_IMPL].[VAT] ([RATE],[VALID_FROM],[VALID_TO])
VALUES (20, '2019-01-01', '3000-01-01')
GO