IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PTY_IMPL].[PARTY_INFO_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PTY_IMPL.PARTY_INFO_SAT','ADDRES_NUMBER_SAPALICE') IS NOT NULL
BEGIN
ALTER TABLE PTY_IMPL.PARTY_INFO_SAT DROP COLUMN ADDRES_NUMBER_SAPALICE
END

IF COL_LENGTH('PTY_IMPL.PARTY_INFO_SAT','ADDRES_NUMBER_SAPALICE_R') IS NULL
BEGIN
ALTER TABLE PTY_IMPL.PARTY_INFO_SAT ADD ADDRES_NUMBER_SAPALICE_R int
END

IF COL_LENGTH('PTY_IMPL.PARTY_INFO_SAT','ADDRES_NUMBER_SAPALICE_F') IS NULL
BEGIN
ALTER TABLE PTY_IMPL.PARTY_INFO_SAT ADD ADDRES_NUMBER_SAPALICE_F int
END

IF COL_LENGTH('PTY_IMPL.PARTY_INFO_SAT','ADDRES_NUMBER_SAPALICE_P') IS NULL
BEGIN
ALTER TABLE PTY_IMPL.PARTY_INFO_SAT ADD ADDRES_NUMBER_SAPALICE_P int
END

END
GO