IF
	EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[EFR_PRODUCT_RISK]') AND TYPE IN (N'U'))
	AND
	NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'PRODUCT_ACTIVE_TO' AND Object_ID = Object_ID(N'[PAS_IMPL].[EFR_PRODUCT_RISK]'))
BEGIN
	ALTER TABLE PAS_IMPL.EFR_PRODUCT_RISK ADD PRODUCT_ACTIVE_TO nvarchar(max) NULL;
END
GO