IF
	EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ACC_IMPL].[ALLOCATION]') AND TYPE IN (N'U'))
	and
	EXISTS (SELECT * FROM SYS.COLUMNS WHERE NAME = N'REFERENCE_NO' AND OBJECT_ID = OBJECT_ID(N'[ACC_IMPL].[ALLOCATION]'))
BEGIN
	exec sp_rename 'ACC_IMPL.ALLOCATION.REFERENCE_NO', 'DOCUMENT_NO', 'COLUMN';
END
GO

IF
	EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ACC_IMPL].[PENDING_PAYMENT_ETL_LOG]') AND TYPE IN (N'U'))
	and
	EXISTS (SELECT * FROM SYS.COLUMNS WHERE NAME = N'REFERENCE_NO' AND OBJECT_ID = OBJECT_ID(N'[ACC_IMPL].[PENDING_PAYMENT_ETL_LOG]'))
BEGIN
	exec sp_rename 'ACC_IMPL.PENDING_PAYMENT_ETL_LOG.REFERENCE_NO', 'DOCUMENT_NO', 'COLUMN';
END
GO