IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[OKOPF]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[OKOPF]
END
GO
CREATE TABLE [BFX_IMPL].[OKOPF] (
[NUMBER] NVARCHAR(3) NOT NULL,
[CODE] NVARCHAR(5) NOT NULL,
[DESCRIPTION] NVARCHAR(255) NOT NULL
CONSTRAINT [PK_OKOPF]
PRIMARY KEY CLUSTERED ([NUMBER] ASC)
)
GO