IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[REPORT_CONTRACT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PAS_IMPL.REPORT_CONTRACT','IS_PERSONAL_MANAGER') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.REPORT_CONTRACT ADD IS_PERSONAL_MANAGER BIT
END

END
GO