-- ass tables update schema
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[QUOTE_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PAS_IMPL.QUOTE_SAT','CREDIT_SUM') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.QUOTE_SAT ADD CREDIT_SUM DECIMAL(15,2) NULL
END

IF COL_LENGTH('PAS_IMPL.QUOTE_SAT','CREDIT_SUM_NET') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.QUOTE_SAT ADD CREDIT_SUM_NET DECIMAL(15,2) NULL
END

IF COL_LENGTH('PAS_IMPL.QUOTE_SAT','CREDIT_RATE') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.QUOTE_SAT ADD CREDIT_RATE DECIMAL(15,4) NULL
END

IF COL_LENGTH('PAS_IMPL.QUOTE_SAT','ANNUITY_PAYMENT_SUM') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.QUOTE_SAT ADD ANNUITY_PAYMENT_SUM DECIMAL(15,2) NULL
END

IF COL_LENGTH('PAS_IMPL.QUOTE_SAT','CREDIT_PROGRAM_ID') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.QUOTE_SAT ADD CREDIT_PROGRAM_ID nvarchar(max) NULL
END

END
GO



IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PAS_IMPL.POLICY_SAT','CREDIT_SUM') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.POLICY_SAT ADD CREDIT_SUM DECIMAL(15,2) NULL
END

IF COL_LENGTH('PAS_IMPL.POLICY_SAT','CREDIT_SUM_NET') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.POLICY_SAT ADD CREDIT_SUM_NET DECIMAL(15,2) NULL
END

IF COL_LENGTH('PAS_IMPL.POLICY_SAT','CREDIT_RATE') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.POLICY_SAT ADD CREDIT_RATE DECIMAL(15,4) NULL
END

IF COL_LENGTH('PAS_IMPL.POLICY_SAT','ANNUITY_PAYMENT_SUM') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.POLICY_SAT ADD ANNUITY_PAYMENT_SUM DECIMAL(15,2) NULL
END

IF COL_LENGTH('PAS_IMPL.POLICY_SAT','CREDIT_PROGRAM_ID') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.POLICY_SAT ADD CREDIT_PROGRAM_ID nvarchar(max) NULL
END

END
GO