IF
	exists (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'PTY_IMPL.PARTY_INFO_SAT') AND TYPE IN (N'U'))
	and
	not exists (SELECT * FROM sys.columns WHERE Name = N'SHORT_NAME' AND Object_ID = Object_ID(N'PTY_IMPL.PARTY_INFO_SAT'))
BEGIN
	ALTER TABLE PTY_IMPL.PARTY_INFO_SAT ADD SHORT_NAME NVARCHAR(500) NULL;

	EXEC(N'
	UPDATE PTY_IMPL.PARTY_INFO_SAT
	SET
		SHORT_NAME = JSON_VALUE(p.COMMON_BODY, ''$.attributes.shortOrgName'')
	FROM
		PTY_IMPL.PARTY_INFO_SAT pis
		join PTY_IMPL.PARTY_HUB ph on ph.PARTY_HKEY = pis.PARTY_INFO_HKEY
		join PTY.PARTY p on p.PARTY_CODE = ph.PARTY_CODE
	WHERE
		PARTY_INFO_HKEY = pis.PARTY_INFO_HKEY');
END
GO