IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[QUOTE_SAT]') AND TYPE IN (N'U'))
BEGIN

    IF COL_LENGTH('PAS_IMPL.QUOTE_SAT','INITIATOR_IS_DBO') IS NULL
    BEGIN
    ALTER TABLE PAS_IMPL.QUOTE_SAT ADD INITIATOR_IS_DBO BIT
    END

END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_SAT]') AND TYPE IN (N'U'))
BEGIN

    IF COL_LENGTH('PAS_IMPL.POLICY_SAT','INITIATOR_IS_DBO') IS NULL
    BEGIN
    ALTER TABLE PAS_IMPL.POLICY_SAT ADD INITIATOR_IS_DBO BIT
    END

END
GO