create table BFX_IMPL.GET_PH_CUSTOM_SERVICE_USERS
(
  ID int identity(1, 1),
  USERNAME nvarchar(64) not null,
  AGENT_AGREEMENT_NUMBERS nvarchar(max) not null,
  CONSTRAINT PK_GET_PH_CUSTOM_SERVICE_USERS PRIMARY KEY (ID),
  CONSTRAINT UK_USERNAME UNIQUE(USERNAME),
  CONSTRAINT FK_GET_PH_CUSTOM_SERVICE_USERS FOREIGN KEY (USERNAME) REFERENCES ORG.APPLICATION_USER (USERNAME)
)