CREATE TABLE BFX_IMPL.INJURY_GROUP
(
	CODE bigint PRIMARY KEY,
	DESCRIPTION nvarchar(500) NOT NULL,
	INDEX IDX_BFX_IMPL_INJURY_GROUP NONCLUSTERED (DESCRIPTION)
)
go

CREATE TABLE BFX_IMPL.INJURY_SUBGROUP
(
	CODE nvarchar(150) PRIMARY KEY,
	DESCRIPTION nvarchar(500) NOT NULL,
	GROUP_CODE bigint NOT NULL FOREIGN KEY REFERENCES BFX_IMPL.INJURY_GROUP(CODE),
	INDEX IDX_INJ_GROUP_SUBGROUP NONCLUSTERED (GROUP_CODE),
	INDEX IDX_INJURY_SUBGROUP_DESCRIPTION NONCLUSTERED (DESCRIPTION)
)
go


CREATE TABLE BFX_IMPL.INJURY 
(
	CODE nvarchar(150) PRIMARY KEY,
	DESCRIPTION nvarchar(500) NOT NULL,
	PAYMENT_PERCENTAGE decimal(15,7) NOT NULL,
	SUBGROUP_CODE nvarchar(150) NOT NULL FOREIGN KEY REFERENCES BFX_IMPL.INJURY_SUBGROUP(CODE),
	INDEX IDX_INJ_COEFF_SUBGROUP NONCLUSTERED (SUBGROUP_CODE), 
	INDEX IDX_INJURY_COEFF_DESCRIPTION NONCLUSTERED (DESCRIPTION)
)
go