IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ACC_IMPL].[PAYMENT_ORDER_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('ACC_IMPL.PAYMENT_ORDER_SAT','IS_CNL_NETTING') IS NULL
BEGIN
ALTER TABLE ACC_IMPL.PAYMENT_ORDER_SAT ADD IS_CNL_NETTING bit
CREATE INDEX IDX_PO_SAT_IS_CNL_NETTING ON ACC_IMPL.PAYMENT_ORDER_SAT(IS_CNL_NETTING);
END

IF COL_LENGTH('ACC_IMPL.PAYMENT_ORDER_SAT','IS_CRT_FROM_NETTING') IS NULL
BEGIN
ALTER TABLE ACC_IMPL.PAYMENT_ORDER_SAT ADD IS_CRT_FROM_NETTING bit
CREATE INDEX IDX_PO_SAT_IS_CRT_NETTING ON ACC_IMPL.PAYMENT_ORDER_SAT(IS_CRT_FROM_NETTING);
END

IF COL_LENGTH('ACC_IMPL.PAYMENT_ORDER_SAT','ORIGINAL_PO_NUMBER') IS NULL
BEGIN
ALTER TABLE ACC_IMPL.PAYMENT_ORDER_SAT ADD ORIGINAL_PO_NUMBER nvarchar(128)
CREATE INDEX IDX_PO_SAT_ORIG_PO_NUMBER ON ACC_IMPL.PAYMENT_ORDER_SAT(ORIGINAL_PO_NUMBER);
END

IF COL_LENGTH('ACC_IMPL.PAYMENT_ORDER_SAT','PARENT_PO_NUMBER') IS NULL
BEGIN
ALTER TABLE ACC_IMPL.PAYMENT_ORDER_SAT ADD PARENT_PO_NUMBER nvarchar(128)
CREATE INDEX IDX_PO_SAT_PRNT_PO_NUMBER ON ACC_IMPL.PAYMENT_ORDER_SAT(PARENT_PO_NUMBER);
END

END