create table BFX_IMPL.SEND_EVENT_TYPE
(
  SEND_EVENT_TYPE_ID int identity(1, 1) primary key,
  SEND_EVENT_TYPE_NAME NVARCHAR(32) not null
)

create table BFX_IMPL.SEND_EVENT_CONFIGURATION
(
  SEND_EVENT_CONFIGURATION_ID int identity(1, 1) primary key,
  SEND_EVENT_TYPE_ID int not null FOREIGN KEY REFERENCES BFX_IMPL.SEND_EVENT_TYPE(SEND_EVENT_TYPE_ID),
  SUBSCRIBER NVARCHAR(32) not null,
  ENTITY_CODE NVARCHAR(16) not null,
  EVENT_CODE NVARCHAR(16) not null,
  BEGIN_DATE DATE not null,
  END_DATE DATE not null
)