IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[PHONE_TYPE]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[PHONE_TYPE]
END
GO

CREATE TABLE [BFX_IMPL].[PHONE_TYPE] (
[CODE] NVARCHAR(255) NOT NULL,
[DESCRIPTION] NVARCHAR(MAX) NOT NULL,
CONSTRAINT [PK_CT_PHONE_TYPE]
PRIMARY KEY CLUSTERED ([CODE] ASC)
)
GO