IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[QUOTE_SAT]') AND TYPE IN (N'U'))
BEGIN

    IF COL_LENGTH('PAS_IMPL.QUOTE_SAT','IS_HERITORS') IS NULL
    BEGIN
    ALTER TABLE PAS_IMPL.QUOTE_SAT ADD IS_HERITORS BIT
    END

    IF COL_LENGTH('PAS_IMPL.QUOTE_SAT','IS_NOT_HERITORS') IS NULL
    BEGIN
    ALTER TABLE PAS_IMPL.QUOTE_SAT ADD IS_NOT_HERITORS BIT
    END

    IF COL_LENGTH('PAS_IMPL.QUOTE_SAT','BENEFICIARY_SPEC_CONDITIONS') IS NULL
    BEGIN
    ALTER TABLE PAS_IMPL.QUOTE_SAT ADD BENEFICIARY_SPEC_CONDITIONS nvarchar(max)
    END

END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_SAT]') AND TYPE IN (N'U'))
BEGIN

    IF COL_LENGTH('PAS_IMPL.POLICY_SAT','IS_HERITORS') IS NULL
    BEGIN
    ALTER TABLE PAS_IMPL.POLICY_SAT ADD IS_HERITORS BIT
    END

    IF COL_LENGTH('PAS_IMPL.POLICY_SAT','IS_NOT_HERITORS') IS NULL
    BEGIN
    ALTER TABLE PAS_IMPL.POLICY_SAT ADD IS_NOT_HERITORS BIT
    END

    IF COL_LENGTH('PAS_IMPL.POLICY_SAT','BENEFICIARY_SPEC_CONDITIONS') IS NULL
    BEGIN
    ALTER TABLE PAS_IMPL.POLICY_SAT ADD BENEFICIARY_SPEC_CONDITIONS nvarchar(max)
    END

END
GO