-- create code table RISK_PROGRAM
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[BFX_IMPL].[RISK_PROGRAM]'))
BEGIN
DROP TABLE [BFX_IMPL].[RISK_PROGRAM];
END
GO

CREATE TABLE [BFX_IMPL].[RISK_PROGRAM] (
[ID] uniqueidentifier NOT NULL,
[RISK_PROGRAM_CODE] nvarchar(max) NOT NULL,
[RISK_PROGRAM_DESCRIPTION] nvarchar(max) NOT NULL,
CONSTRAINT [PK_CT_RISK_PROGRAM]
PRIMARY KEY CLUSTERED ([ID] ASC)
ON [PRIMARY]
)
ON [PRIMARY];
GO


-- create code table RISK_PERSON
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[BFX_IMPL].[RISK_PERSON]'))
BEGIN
DROP TABLE [BFX_IMPL].[RISK_PERSON];
END
GO

CREATE TABLE [BFX_IMPL].[RISK_PERSON] (
[ID] uniqueidentifier NOT NULL,
[RISK_PERSON_CODE] nvarchar(max) NOT NULL,
[RISK_PERSON_DESCRIPTION] nvarchar(max) NOT NULL,
CONSTRAINT [PK_CT_RISK_PERSON]
PRIMARY KEY CLUSTERED ([ID] ASC)
ON [PRIMARY]
)
ON [PRIMARY];
GO


-- add new columns to table RISK_PRODUCT_RELATION
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[RISK_PRODUCT_RELATION]'))
BEGIN

IF COL_LENGTH('BFX_IMPL.RISK_PRODUCT_RELATION','RISK_PROGRAM') IS NULL
BEGIN
ALTER TABLE BFX_IMPL.RISK_PRODUCT_RELATION ADD RISK_PROGRAM NVARCHAR(MAX)
END

IF COL_LENGTH('BFX_IMPL.RISK_PRODUCT_RELATION','RISK_PERSON') IS NULL
BEGIN
ALTER TABLE BFX_IMPL.RISK_PRODUCT_RELATION ADD RISK_PERSON NVARCHAR(MAX)
END

END
GO