
--region SCHEME

alter table acc.ATTRIBUTE_VALUE_SET drop column DOCUMENT_NO;
alter table acc.ATTRIBUTE_VALUE_SET add IS_LIFE bit null;

create table ACC_IMPL.CT_OFR
(
    OFR_ID [int] NOT NULL PRIMARY KEY,
    OFR_CODE NVARCHAR(50) not null unique,
    DESCRIPTION NVARCHAR(250) not null
);

create table ACC_IMPL.CT_TRANSACTION_DOCUMENT_TYPE
(
    TRANSACTION_DOCUMENT_TYPE_ID [int] NOT NULL PRIMARY KEY,
    TRANSACTION_DOCUMENT_TYPE_CODE NVARCHAR(50) not null,
    DESCRIPTION NVARCHAR(250) not null
);

 create table ACC_IMPL.CT_LOCAL_DIMENSION_3
(
    LOCAL_DIMENSION_3_ID [int] NOT NULL PRIMARY KEY,
    LOCAL_DIMENSION_3_CODE NVARCHAR(50) not null,
    DESCRIPTION NVARCHAR(250) not null
);

create table ACC_IMPL.CT_TRANSACTION_CODE_1
(
    TRANSACTION_CODE_1_ID [int] NOT NULL PRIMARY KEY,
    TRANSACTION_CODE NVARCHAR(50) not null unique,
    DESCRIPTION NVARCHAR(250) not null
);

create table ACC_IMPL.CT_PERSON_TYPE
(
    PERSON_TYPE_ID [int] NOT NULL PRIMARY KEY,
    DESCRIPTION NVARCHAR(50) not null
);

create table ACC_IMPL.SAP_GL_ACCOUNT
(
    SAP_GL_ACCOUNT_ID [int] primary key identity,
    SAP_GL_ACCOUNT_NO [nvarchar](64) not null unique,
    DESCRIPTION        nvarchar(250) null,
    ATTRIBUTE_SET_ID [bigint] not null
);

create table ACC_IMPL.TRANSACTION_TYPE
(
    TRANSACTION_TYPE_ID  [int]  NOT NULL PRIMARY KEY,
    DESCRIPTION NVARCHAR(250) NOT NULL,
    TRANSACTION_DOCUMENT_TYPE_ID [int] NOT NULL FOREIGN KEY REFERENCES ACC_IMPL.CT_TRANSACTION_DOCUMENT_TYPE(TRANSACTION_DOCUMENT_TYPE_ID),
    LOCAL_DIMENSION_3_ID [int] NOT NULL FOREIGN KEY REFERENCES ACC_IMPL.CT_LOCAL_DIMENSION_3(LOCAL_DIMENSION_3_ID)
);

create table ACC_IMPL.OFR_RULE
(
    OFR_RULE_ID [int] NOT NULL PRIMARY KEY IDENTITY,
    GL_ACCOUNT_ID [bigint] not null,
    PREVIOUS_PERIOD [bit] null,
    DOCUMENT_TYPE_ID [int] null references ACC.CT_DOCUMENT_TYPE(DOCUMENT_TYPE_ID),
    OFR_ID [int] not null references  ACC_IMPL.CT_OFR(OFR_ID)
);

create table ACC_IMPL.SAP_GL_ACCOUNT_RULE
(
    SAP_GL_ACCOUNT_RULE_ID [int] primary key identity,
    GL_ACCOUNT_ID [bigint] not null references ACC.GL_ACCOUNT(GL_ACCOUNT_ID),
    OFR_ID         [int] null references ACC_IMPL.CT_OFR(OFR_ID),
    PREVIOUS_PERIOD [bit] null,
    PERSON_TYPE_ID [int] null references ACC_IMPL.CT_PERSON_TYPE(PERSON_TYPE_ID),
    SAP_GL_ACCOUNT_ID [int] not null references ACC_IMPL.SAP_GL_ACCOUNT(SAP_GL_ACCOUNT_ID)
);


--region GL & JR ADDITIONAL_ATTRIBUTES

alter table ACC.GL_ADDITIONAL_ATTRIBUTES add BALANCE_UNIT [int] null;
alter table ACC.GL_ADDITIONAL_ATTRIBUTES add TRANSACTION_CODE_1 [int] null constraint FK_GL_ADD_ATTR_TRANS_CODE_1 foreign key references ACC_IMPL.CT_TRANSACTION_CODE_1 (TRANSACTION_CODE_1_ID);
alter table ACC.GL_ADDITIONAL_ATTRIBUTES add TRANSACTION_CODE_2 [int] null;
alter table ACC.GL_ADDITIONAL_ATTRIBUTES add TRANSACTION_TYPE_ID [int] null constraint FK_GL_ADD_ATTR_TRANS_TYPE_ID foreign key references ACC_IMPL.TRANSACTION_TYPE (TRANSACTION_TYPE_ID);
alter table ACC.GL_ADDITIONAL_ATTRIBUTES add OFR_ID [int] null constraint FK_GL_ADD_ATTR_OFR_ID foreign key references ACC_IMPL.CT_OFR (OFR_ID);
alter table ACC.GL_ADDITIONAL_ATTRIBUTES add SAP_GL_ACCOUNT_ID [int] null constraint FK_GL_ADD_ATTR_SAP_GL_ACC_ID foreign key references ACC_IMPL.SAP_GL_ACCOUNT (SAP_GL_ACCOUNT_ID);
alter table ACC.GL_ADDITIONAL_ATTRIBUTES add REGISTER [nvarchar](64) null;
alter table ACC.GL_ADDITIONAL_ATTRIBUTES add COST_CENTER [nvarchar](50) null; --МВЗ
alter table ACC.GL_ADDITIONAL_ATTRIBUTES add TRADING_PARTNER [nvarchar](64) null;
alter table ACC.GL_ADDITIONAL_ATTRIBUTES add CONTRACT_NO [nvarchar](64) null;
alter table ACC.GL_ADDITIONAL_ATTRIBUTES add AA_ORDER_NO [nvarchar](50) null;
alter table ACC.GL_ADDITIONAL_ATTRIBUTES add XREF2 [nvarchar](10) null;
alter table ACC.GL_ADDITIONAL_ATTRIBUTES add PERSONAL_ACCOUNT_NUMBER [nvarchar](32) null;
alter table ACC.GL_ADDITIONAL_ATTRIBUTES add BUSINESS_LINE [nvarchar](6) null;
alter table ACC.GL_ADDITIONAL_ATTRIBUTES add CEDENTS_COUNTRY [nvarchar](3) null;
alter table ACC.GL_ADDITIONAL_ATTRIBUTES add LOCAL_DIMENSION_1 [nvarchar](4) null;
alter table ACC.GL_ADDITIONAL_ATTRIBUTES add LOCAL_DIMENSION_2 [nvarchar](4) null;
alter table ACC.GL_ADDITIONAL_ATTRIBUTES add LOCAL_DIMENSION_3_ID [int] null constraint FK_GL_ADD_ATTR_LD3_ID foreign key references ACC_IMPL.CT_LOCAL_DIMENSION_3(LOCAL_DIMENSION_3_ID);
alter table ACC.GL_ADDITIONAL_ATTRIBUTES add PARTY_CODE [nvarchar](50) null;
alter table ACC.GL_ADDITIONAL_ATTRIBUTES add TRANSACTION_DOCUMENT_TYPE_ID [int] null constraint FK_GL_ADD_ATTR_TRANS_DOC_TYPE_ID foreign key references ACC_IMPL.CT_TRANSACTION_DOCUMENT_TYPE(TRANSACTION_DOCUMENT_TYPE_ID);



alter table ACC.JR_ADDITIONAL_ATTRIBUTES add BALANCE_UNIT [int] null;
alter table ACC.JR_ADDITIONAL_ATTRIBUTES add TRANSACTION_CODE_1 [int] null constraint FK_JR_ADD_ATTR_TRANS_CODE_1 foreign key references ACC_IMPL.CT_TRANSACTION_CODE_1 (TRANSACTION_CODE_1_ID);
alter table ACC.JR_ADDITIONAL_ATTRIBUTES add TRANSACTION_CODE_2 [int] null;
alter table ACC.JR_ADDITIONAL_ATTRIBUTES add TRANSACTION_TYPE_ID [int] null constraint FK_JR_ADD_ATTR_TRANS_TYPE_ID foreign key references ACC_IMPL.TRANSACTION_TYPE (TRANSACTION_TYPE_ID);
alter table ACC.JR_ADDITIONAL_ATTRIBUTES add OFR_ID [int] null constraint FK_JR_ADD_ATTR_OFR_ID foreign key references ACC_IMPL.CT_OFR (OFR_ID);
alter table ACC.JR_ADDITIONAL_ATTRIBUTES add IS_REVALUATION [bit] null;
alter table ACC.JR_ADDITIONAL_ATTRIBUTES add PERSON_TYPE_ID [int] null constraint FK_JR_ADD_ATTR_PERSON_TYPE_ID foreign key references ACC_IMPL.CT_PERSON_TYPE(PERSON_TYPE_ID);
alter table ACC.JR_ADDITIONAL_ATTRIBUTES add SAP_GL_ACCOUNT_ID [int] null constraint FK_JR_ADD_ATTR_SAP_GL_ACC_ID foreign key references ACC_IMPL.SAP_GL_ACCOUNT (SAP_GL_ACCOUNT_ID);
alter table ACC.JR_ADDITIONAL_ATTRIBUTES add REGISTER [nvarchar](64) null;
alter table ACC.JR_ADDITIONAL_ATTRIBUTES add COST_CENTER [nvarchar](50) null; --МВЗ
alter table ACC.JR_ADDITIONAL_ATTRIBUTES add TRADING_PARTNER [nvarchar](64) null;
alter table ACC.JR_ADDITIONAL_ATTRIBUTES add CONTRACT_NO [nvarchar](64) null;
alter table ACC.JR_ADDITIONAL_ATTRIBUTES add AA_ORDER_NO [nvarchar](50) null;
alter table ACC.JR_ADDITIONAL_ATTRIBUTES add XREF2 [nvarchar](10) null;
alter table ACC.JR_ADDITIONAL_ATTRIBUTES add PERSONAL_ACCOUNT_NUMBER [nvarchar](32) null;
alter table ACC.JR_ADDITIONAL_ATTRIBUTES add BUSINESS_LINE [nvarchar](6) null;
alter table ACC.JR_ADDITIONAL_ATTRIBUTES add CEDENTS_COUNTRY [nvarchar](3) null;
alter table ACC.JR_ADDITIONAL_ATTRIBUTES add LOCAL_DIMENSION_1 [nvarchar](4) null;
alter table ACC.JR_ADDITIONAL_ATTRIBUTES add LOCAL_DIMENSION_2 [nvarchar](4) null;
alter table ACC.JR_ADDITIONAL_ATTRIBUTES add LOCAL_DIMENSION_3_ID [int] null constraint FK_JR_ADD_ATTR_LD3_ID foreign key references ACC_IMPL.CT_LOCAL_DIMENSION_3(LOCAL_DIMENSION_3_ID);
alter table ACC.JR_ADDITIONAL_ATTRIBUTES add PARTY_CODE [nvarchar](50) null;
alter table ACC.JR_ADDITIONAL_ATTRIBUTES add TRANSACTION_DOCUMENT_TYPE_ID [int] null constraint FK_JR_ADD_ATTR_TRANS_DOC_TYPE_ID foreign key references ACC_IMPL.CT_TRANSACTION_DOCUMENT_TYPE(TRANSACTION_DOCUMENT_TYPE_ID);

--endregion

--endregion