IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ORG_IMPL].[ORGANISATION_UNIT_INFO_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('ORG_IMPL.ORGANISATION_UNIT_INFO_SAT','COACH_CODE') IS NULL
BEGIN
ALTER TABLE ORG_IMPL.ORGANISATION_UNIT_INFO_SAT ADD COACH_CODE nvarchar(250)
END

IF COL_LENGTH('ORG_IMPL.ORGANISATION_UNIT_INFO_SAT','TERRITORIAL_CHIEF_CODE') IS NULL
BEGIN
ALTER TABLE ORG_IMPL.ORGANISATION_UNIT_INFO_SAT ADD TERRITORIAL_CHIEF_CODE nvarchar(250)
END

IF COL_LENGTH('ORG_IMPL.ORGANISATION_UNIT_INFO_SAT','REGIONAL_CHIEF_CODE') IS NULL
BEGIN
ALTER TABLE ORG_IMPL.ORGANISATION_UNIT_INFO_SAT ADD REGIONAL_CHIEF_CODE nvarchar(250)
END

END
GO