IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PTY_IMPL].[PARTY_INFO_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PTY_IMPL.PARTY_INFO_SAT','IS_MIGRATED') IS NULL
BEGIN
ALTER TABLE PTY_IMPL.PARTY_INFO_SAT ADD IS_MIGRATED bit
END

IF COL_LENGTH('PTY_IMPL.PARTY_INFO_SAT','ADDRES_NUMBER_SAPALICE') IS NULL
BEGIN
ALTER TABLE PTY_IMPL.PARTY_INFO_SAT ADD ADDRES_NUMBER_SAPALICE int
END

IF COL_LENGTH('PTY_IMPL.PARTY_INFO_SAT','PARTNER_NUMBER_SAPALICE') IS NULL
BEGIN
ALTER TABLE PTY_IMPL.PARTY_INFO_SAT ADD PARTNER_NUMBER_SAPALICE int
END

END
GO