IF
	EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[AA_SAT]') AND TYPE IN (N'U'))
	AND
	NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'IS_DOC_CORRECT' AND Object_ID = Object_ID(N'[PAS_IMPL].[AA_SAT]'))
BEGIN
	ALTER TABLE PAS_IMPL.AA_SAT ADD IS_DOC_CORRECT bit
END
GO