IF EXISTS (SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[SAP_INTEGRATION_STATUS]'))
BEGIN
DELETE FROM BFX_IMPL.SAP_INTEGRATION_STATUS
DROP TABLE BFX_IMPL.SAP_INTEGRATION_STATUS
END

CREATE TABLE [BFX_IMPL].[SAP_INTEGRATION_STATUS](
	[INTEGRATION_STATUS_ID] [uniqueidentifier] NOT NULL,
	[LOAD_DATE] [DATETIME] NULL,
	[METHOD_NAME] [nvarchar](256) NULL, -- SAP system method name, e.g. 'Zerluapi000000000100' 
	[STATUS] [nvarchar](256) NULL, -- 'Success' or 'Error'
	[ERRORS] [nvarchar](max) NULL, -- All erroe messages from normal response or the whole response body in case of Server Error
	[RESULT_ENTITY_ID] [nvarchar](256) NOT NULL -- SAP system id of created contract or party

	CONSTRAINT [PK_BFX_IMPL_SAP_INTEGRATION_STATUS] PRIMARY KEY NONCLUSTERED 
	(
		[INTEGRATION_STATUS_ID] ASC
	)

);

IF EXISTS (SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[SAP_INTEGRATION_STATUS]') AND NAME = N'IDX_LOAD_DATE')
BEGIN
	DROP INDEX [IDX_LOAD_DATE] ON [BFX_IMPL].[SAP_INTEGRATION_STATUS]
END
GO

CREATE INDEX [IDX_LOAD_DATE] ON [BFX_IMPL].[SAP_INTEGRATION_STATUS] ([LOAD_DATE])
GO