CREATE TABLE [ACC_IMPL].[PERIOD_HISTORY](
	[PERIOD_HISTORY_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PERIOD_ID] [bigint] NOT NULL,
	[PERIOD_STATUS_ID_TO] [int] NOT NULL,
	[CREATE_DATE] [datetime2](7) NOT NULL,
	[USER_ID] [uniqueidentifier] NOT NULL,
	CONSTRAINT [PK_ACC_IMPL_PERIOD_HISTORY] PRIMARY KEY CLUSTERED ([PERIOD_HISTORY_ID])
)
GO

ALTER TABLE [ACC_IMPL].[PERIOD_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_ACC_IMPL_PERIOD_HISTORY_PERIOD_ID] FOREIGN KEY([PERIOD_ID])
REFERENCES [ACC_IMPL].[PERIOD] ([PERIOD_ID])
GO

ALTER TABLE [ACC_IMPL].[PERIOD_HISTORY] CHECK CONSTRAINT [FK_ACC_IMPL_PERIOD_HISTORY_PERIOD_ID]
GO

ALTER TABLE [ACC_IMPL].[PERIOD_HISTORY] WITH CHECK ADD CONSTRAINT [FK_ACC_IMPL_PERIOD_HISTORY_PERIOD_STATUS_ID_TO] FOREIGN KEY([PERIOD_STATUS_ID_TO])
REFERENCES [ACC].[CT_PERIOD_STATUS] ([PERIOD_STATUS_ID])
GO

ALTER TABLE [ACC_IMPL].[PERIOD_HISTORY] CHECK CONSTRAINT [FK_ACC_IMPL_PERIOD_HISTORY_PERIOD_STATUS_ID_TO]
GO