CREATE TABLE [ACC_IMPL].[BANK_STATEMENT_ITEM_HISTORY](
	[BANK_STATEMENT_ITEM_HISTORY_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BANK_STATEMENT_ITEM_ID] [bigint] NOT NULL,
	[STATUS_ID_FROM] [int] NOT NULL,
	[STATUS_ID_TO] [int] NOT NULL,
	[PAYMENT_DESCRIPTION_FROM] [nvarchar](256) NOT NULL,
	[PAYMENT_DESCRIPTION_TO] [nvarchar](256) NOT NULL,
	[CREATE_DATE] [datetime2](7) NOT NULL,
	[USER_ID] [uniqueidentifier] NOT NULL,
CONSTRAINT [PK_ACC_IMPL_BANK_STATEMENT_ITEM_HISTORY_ID] PRIMARY KEY CLUSTERED 
(
	[BANK_STATEMENT_ITEM_ID] ASC,
	[BANK_STATEMENT_ITEM_HISTORY_ID] ASC
))
GO

ALTER TABLE [ACC_IMPL].[BANK_STATEMENT_ITEM_HISTORY] WITH CHECK 
ADD CONSTRAINT [FK_ACC_IMPL_BANK_STATEMENT_ITEM_HISTORY_BANK_STATEMENT_ITEM_ID] FOREIGN KEY([BANK_STATEMENT_ITEM_ID])
REFERENCES [ACC_IMPL].[BANK_STATEMENT_ITEM] ([BANK_STATEMENT_ITEM_ID])
GO