IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[INVESTMENT_STRATEGY]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[INVESTMENT_STRATEGY]
END
GO

CREATE TABLE [BFX_IMPL].[INVESTMENT_STRATEGY] (
[ID] [UNIQUEIDENTIFIER] NOT NULL,
[CODE] NVARCHAR(255) NOT NULL,
[DESCRIPTION] NVARCHAR(MAX) NOT NULL,
PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO