IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[PAYMENT_FORM]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[PAYMENT_FORM]
END
GO

CREATE TABLE [BFX_IMPL].[PAYMENT_FORM] (
[ID] [UNIQUEIDENTIFIER] NOT NULL,
[CODE] NVARCHAR(255) NOT NULL,
[DESCRIPTION] NVARCHAR(MAX) NOT NULL,
PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO



IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[RISKS_GROUP]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[RISKS_GROUP]
END
GO

CREATE TABLE [BFX_IMPL].[RISKS_GROUP] (
[ID] [UNIQUEIDENTIFIER] NOT NULL,
[CODE] NVARCHAR(255) NOT NULL,
[DESCRIPTION] NVARCHAR(MAX) NOT NULL,
PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO



-- add new columns to table RISKS
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[RISKS]'))
BEGIN

IF COL_LENGTH('BFX_IMPL.RISKS','PAYMENT_FORM') IS NULL
BEGIN
ALTER TABLE BFX_IMPL.RISKS ADD PAYMENT_FORM NVARCHAR(MAX)
END

IF COL_LENGTH('BFX_IMPL.RISKS','RISKS_GROUP') IS NULL
BEGIN
ALTER TABLE BFX_IMPL.RISKS ADD RISKS_GROUP NVARCHAR(MAX)
END

END
GO
