IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[CNL_AMENDMENT_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PAS_IMPL.CNL_AMENDMENT_SAT','CONTRACT_NUMBER') IS NOT NULL
BEGIN
	ALTER TABLE PAS_IMPL.CNL_AMENDMENT_SAT DROP COLUMN CONTRACT_NUMBER
END

IF COL_LENGTH('PAS_IMPL.CNL_AMENDMENT_SAT','CONTRACT_HOLDER_NAME') IS NOT NULL
BEGIN
	ALTER TABLE PAS_IMPL.CNL_AMENDMENT_SAT DROP COLUMN CONTRACT_HOLDER_NAME
END

IF COL_LENGTH('PAS_IMPL.CNL_AMENDMENT_SAT','CONTRACT_CONF_CODE_NAME') IS NOT NULL
BEGIN
	ALTER TABLE PAS_IMPL.CNL_AMENDMENT_SAT DROP COLUMN CONTRACT_CONF_CODE_NAME
END

END
GO