IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[ATTACHMENTS_ERROR]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[ATTACHMENTS_ERROR]
END
GO

CREATE TABLE [BFX_IMPL].[ATTACHMENTS_ERROR] (
[ID] [UNIQUEIDENTIFIER] NOT NULL,
[CODE]  NVARCHAR(3) NOT NULL,
[DESCRIPTION_FULL] NVARCHAR(MAX) NOT NULL,
[DESCRIPTION_SHORT] NVARCHAR(20) NOT NULL,
[TYPE_OF_ERROR] NVARCHAR(20) NOT NULL,
[CLASS_OF_ERROR] NVARCHAR(20) NOT NULL,
PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO