drop table if exists PAS_IMPL.COLLECTIVE_POLICY_RISK_DATA_EXP

create table PAS_IMPL.COLLECTIVE_POLICY_RISK_DATA_EXP
(
  ID bigint identity(1, 1) not null,
  INSURED_ID bigint not null,
  CONTRACT_NUMBER nvarchar(64),
  RISK_CODE nvarchar(255),
  REINS_RATE decimal(15,2),
  REINS_PREMIUM decimal(15,2),
  CONSTRAINT PK_COLLECTIVE_POLICY_RISK_EXP_ID PRIMARY KEY(ID)
)

create index IDX_COLLECTIVE_POLICY_RISK_DATA_EXP_INSURED_ID ON PAS_IMPL.COLLECTIVE_POLICY_RISK_DATA_EXP(INSURED_ID)

create index IDX_COLLECTIVE_POLICY_RISK_DATA_EXP_CONTRACT_NUMBER ON PAS_IMPL.COLLECTIVE_POLICY_RISK_DATA_EXP(CONTRACT_NUMBER)