CREATE TABLE [ACC_IMPL].[ALLOCATION](
	[ALLOCATION_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CANCELLED] [bit] NOT NULL,
	[CANCELLED_ALLOCATION_ID] [bigint] NULL,
	[BANK_STATEMENT_ITEM_ID] [bigint] NOT NULL,
	[PAY_AMOUNT] [decimal](15, 2) NOT NULL,
	[DOC_AMOUNT] [decimal](15, 2) NOT NULL,
	[TOLERANCE_DOC_AMOUNT] [decimal](15, 2) NOT NULL,
	[CURRENCY_CODE] [nvarchar](3) NOT NULL,
	[ALLOCATION_STATUS_ID] [int] NOT NULL,
	[CREATE_DATE] [datetimeoffset] NOT NULL,
	[DOCUMENT_NO] [nvarchar](64) NULL,
	[DOCUMENT_ID] [nvarchar](64) NOT NULL,
	[MATCHING_TYPE] [int] NOT NULL,

	CONSTRAINT [PK_ACC_IMPL_ALLOCATION_ALLOCATION_ID] PRIMARY KEY NONCLUSTERED
	(
		[ALLOCATION_ID] ASC
	)
)
GO

ALTER TABLE [ACC_IMPL].[ALLOCATION]  WITH CHECK ADD  CONSTRAINT [FK_ACC_IMPL_ALLOCATION_CANCELLED_ALLOCATION_ID] FOREIGN KEY([CANCELLED_ALLOCATION_ID])
REFERENCES [ACC_IMPL].[ALLOCATION] ([ALLOCATION_ID])
GO

ALTER TABLE [ACC_IMPL].[ALLOCATION] CHECK CONSTRAINT [FK_ACC_IMPL_ALLOCATION_CANCELLED_ALLOCATION_ID]
GO

CREATE TABLE [ACC_IMPL].[MATCHING](
	[MATCHING_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ALLOCATION_ID] [bigint] NOT NULL,
	[CANCELLED] [bit] NOT NULL,
	[CANCELLED_MATCHING_ID] [bigint] NULL,
	[PAY_AMOUNT] [decimal](15, 2) NOT NULL,
	[DOC_AMOUNT] [decimal](15, 2) NOT NULL,
	[TOLERANCE_DOC_AMOUNT] [decimal](15, 2) NOT NULL,
	[CREATE_DATE] [datetimeoffset] NOT NULL,

	CONSTRAINT [PK_ACC_IMPL_MATCHING_MATCHING_ID] PRIMARY KEY NONCLUSTERED
	(
		[MATCHING_ID] ASC
	)
)
GO

ALTER TABLE [ACC_IMPL].[MATCHING]  WITH CHECK ADD  CONSTRAINT [FK_ACC_IMPL_MATCHING_ALLOCATION_ID] FOREIGN KEY([ALLOCATION_ID])
REFERENCES [ACC_IMPL].[ALLOCATION] ([ALLOCATION_ID])
GO

ALTER TABLE [ACC_IMPL].[MATCHING] CHECK CONSTRAINT [FK_ACC_IMPL_MATCHING_ALLOCATION_ID]
GO


ALTER TABLE [ACC_IMPL].[MATCHING]  WITH CHECK ADD  CONSTRAINT [FK_ACC_IMPL_MATCHING_CANCELLED_MATCHING_ID] FOREIGN KEY([CANCELLED_MATCHING_ID])
REFERENCES [ACC_IMPL].[MATCHING] ([MATCHING_ID])
GO

ALTER TABLE [ACC_IMPL].[MATCHING] CHECK CONSTRAINT [FK_ACC_IMPL_MATCHING_CANCELLED_MATCHING_ID]
GO
