IF (EXISTS 
	(SELECT * 
	FROM INFORMATION_SCHEMA.TABLES 
	WHERE TABLE_SCHEMA = 'BFX_IMPL' 
	AND  TABLE_NAME = 'SEND_EVENT_CONFIGURATION')
)
BEGIN
	IF NOT EXISTS(SELECT 1 FROM sys.columns 
			  WHERE Name = N'API_SENDER'
			  AND Object_ID = OBJECT_ID(N'BFX_IMPL.SEND_EVENT_CONFIGURATION'))
	BEGIN
		PRINT('Adding API_SENDER column')
		ALTER TABLE BFX_IMPL.SEND_EVENT_CONFIGURATION
		ADD API_SENDER NVARCHAR(50)
	END
END
GO