CREATE TABLE [ACC_IMPL].[BOK_MIGRATED_PC]
(
	[CONTRACT_NUMBER] [nvarchar](64) NOT NULL,
	[START_PERIOD_DATE] [date] NOT NULL,
	[END_PERIOD_DATE] [date] NOT NULL,
	[INVOICE] [varchar](12) NOT NULL,
	[MIGRATED_AOEW] [bit] NOT NULL,

	CONSTRAINT [PK_ACC_IMPL_BOK_MIGRATED_PC_CONTRACT_NUMBER] PRIMARY KEY CLUSTERED
	(
		[CONTRACT_NUMBER] ASC
	)
)
GO
