-- ass tables update

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[QUOTE_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PAS_IMPL.QUOTE_SAT','RISK_PREMIUM') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.QUOTE_SAT ADD RISK_PREMIUM DECIMAL(15,2) NULL
END

IF COL_LENGTH('PAS_IMPL.QUOTE_SAT','RISKS_MANUAL_CORRECTION') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.QUOTE_SAT ADD RISKS_MANUAL_CORRECTION nvarchar(100) NULL
END

IF COL_LENGTH('PAS_IMPL.QUOTE_SAT','RISK_PREMIUM_ALL') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.QUOTE_SAT ADD RISK_PREMIUM_ALL DECIMAL(15,2) NULL
END

IF COL_LENGTH('PAS_IMPL.QUOTE_SAT','HOLDER_EMAIL') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.QUOTE_SAT ADD HOLDER_EMAIL nvarchar(max) NULL
END

IF COL_LENGTH('PAS_IMPL.QUOTE_SAT','INSURED_EMAIL') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.QUOTE_SAT ADD INSURED_EMAIL nvarchar(max) NULL
END

END
GO


IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PAS_IMPL.POLICY_SAT','RISKS_MANUAL_CORRECTION') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.POLICY_SAT ADD RISKS_MANUAL_CORRECTION nvarchar(100) NULL
END

IF COL_LENGTH('PAS_IMPL.POLICY_SAT','RISK_PREMIUM_ALL') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.POLICY_SAT ADD RISK_PREMIUM_ALL DECIMAL(15,2) NULL
END

IF COL_LENGTH('PAS_IMPL.POLICY_SAT','HOLDER_EMAIL') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.POLICY_SAT ADD HOLDER_EMAIL nvarchar(max) NULL
END

IF COL_LENGTH('PAS_IMPL.POLICY_SAT','INSURED_EMAIL') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.POLICY_SAT ADD INSURED_EMAIL nvarchar(max) NULL
END

END
GO