IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[DECLARATION_MEDICAL_QUESTIONS]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[DECLARATION_MEDICAL_QUESTIONS]
END
GO

CREATE TABLE [BFX_IMPL].[DECLARATION_MEDICAL_QUESTIONS] (
[ID] [UNIQUEIDENTIFIER] NOT NULL,
[ITEM_TEXT] NVARCHAR(MAX) NOT NULL,
PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[DECLARATION_MEDICAL]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[DECLARATION_MEDICAL]
END
GO

CREATE TABLE [BFX_IMPL].[DECLARATION_MEDICAL] (
[ID] [UNIQUEIDENTIFIER] NOT NULL,
[PRODUCT_CODE] NVARCHAR(6) NOT NULL,
[ITEM_NUMBER] NVARCHAR(2) NOT NULL,
[ITEM_TEXT_ID] NVARCHAR(255) NOT NULL,
[DEPARTAMENT] NVARCHAR(255) NOT NULL,
PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[DECLARATION_MAIN_QUESTIONS]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[DECLARATION_MAIN_QUESTIONS]
END
GO

CREATE TABLE [BFX_IMPL].[DECLARATION_MAIN_QUESTIONS] (
[ID] [UNIQUEIDENTIFIER] NOT NULL,
[ITEM_TEXT] NVARCHAR(MAX) NOT NULL,
PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[DECLARATION_MAIN]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[DECLARATION_MAIN]
END
GO

CREATE TABLE [BFX_IMPL].[DECLARATION_MAIN] (
[ID] [UNIQUEIDENTIFIER] NOT NULL,
[PRODUCT_CODE] NVARCHAR(6) NOT NULL,
[ITEM_NUMBER] NVARCHAR(2) NOT NULL,
[ITEM_TEXT_ID] NVARCHAR(255) NOT NULL,
[DEPARTAMENT] NVARCHAR(255) NOT NULL,
PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO