drop table if exists PAS_IMPL.COLLECTIVE_POLICY

drop table if exists PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST

create table PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST
(
  ID bigint identity(1, 1) not null,
  CONTRACT_NUMBER nvarchar(64),
  PARTY_CODE nvarchar(64),
  SURNAME nvarchar(1024),
  FIRST_NAME nvarchar(1024),
  MIDDLE_NAME nvarchar(1024),
  BIRTHDAY date,
  GENDER bit,
  MOBILE nvarchar(32),
  AMOUNT decimal(15,2),
  PREMIUM decimal(15,2),
  CONSTRAINT PK_COLLECTIVE_POLICY_INSURED_LIST_ID PRIMARY KEY(ID)
)

create index IDX_COLLECTIVE_POLICY_CONTRACT_NUMBER ON PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST (CONTRACT_NUMBER)

drop table if exists PAS_IMPL.COLLECTIVE_POLICY_RISK

drop table if exists PAS_IMPL.COLLECTIVE_POLICY_RISK_DATA

create table PAS_IMPL.COLLECTIVE_POLICY_RISK_DATA
(
  ID bigint identity(1, 1) not null,
  INSURED_ID bigint not null,
  CONTRACT_NUMBER nvarchar(64),
  START_DATE date,
  END_DATE date,
  RISK_CODE nvarchar(255),
  AMOUNT decimal(15,2),
  PREMIUM decimal(15,2),
  CONSTRAINT PK_COLLECTIVE_POLICY_RISK_ID PRIMARY KEY(ID)
)

create index IDX_COLLECTIVE_POLICY_RISK_DATA_INSURED_ID ON PAS_IMPL.COLLECTIVE_POLICY_RISK_DATA(INSURED_ID)

create index IDX_COLLECTIVE_POLICY_RISK_DATA_CONTRACT_NUMBER ON PAS_IMPL.COLLECTIVE_POLICY_RISK_DATA (CONTRACT_NUMBER)