IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[SEND_EVENT]') AND TYPE IN (N'U'))
BEGIN
  IF COL_LENGTH('BFX_IMPL.SEND_EVENT','POLICY_HOLDER_TYPE') IS NULL
  BEGIN
    ALTER TABLE BFX_IMPL.SEND_EVENT ADD POLICY_HOLDER_TYPE nvarchar(128) null
  END

  IF COL_LENGTH('BFX_IMPL.SEND_EVENT','AGENT_AGREEMENT_NUMBER') IS NULL
  BEGIN
    ALTER TABLE BFX_IMPL.SEND_EVENT ADD AGENT_AGREEMENT_NUMBER nvarchar(128) null
  END
END

GO

CREATE TABLE BFX_IMPL.SEND_EVENT_EXCEPTIONS
(
  ID INT IDENTITY(1, 1) not null,
  VALUE NVARCHAR(256) not null,
  VALUE_TYPE NVARCHAR(16) not null,
  SUBSCRIBER NVARCHAR(32) not null,
  CONSTRAINT PK_SEND_EVENT_EXCEPTIONS PRIMARY KEY (ID ASC),
  CHECK(VALUE_TYPE in ('PRODUCT', 'AGENT AGREEMENT')),
  CHECK(SUBSCRIBER in ('AGIMA', 'ELMA', 'EFR'))
)

GO