/*
IF
	EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ACC_IMPL].[BANK_STATEMENT_ITEM]') AND TYPE IN (N'U'))
	and
	not exists (SELECT * FROM sys.columns WHERE Name = N'UNIVERSAL_DOCUMENT_ID' AND Object_ID = Object_ID(N'[ACC_IMPL].[BANK_STATEMENT_ITEM]'))
BEGIN
	if ((select count(*) from ACC_IMPL.BANK_STATEMENT_ITEM) = 0)
	begin
		return;
	end;

	ALTER TABLE [ACC_IMPL].[BANK_STATEMENT_ITEM] DROP CONSTRAINT [PK_ACC_IMPL_BANK_STATEMENT_ITEM];
	ALTER TABLE [ACC_IMPL].[BANK_STATEMENT_ITEM] ADD  CONSTRAINT [PK_ACC_IMPL_BANK_STATEMENT_ITEM] PRIMARY KEY CLUSTERED
	(
		[BANK_STATEMENT_ITEM_ID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];

	ALTER TABLE ACC_IMPL.BANK_STATEMENT_ITEM
	ADD UNIVERSAL_DOCUMENT_ID NVARCHAR(50) null;

	EXEC(N'UPDATE ACC_IMPL.BANK_STATEMENT_ITEM SET UNIVERSAL_DOCUMENT_ID = (select UNIVERSAL_DOCUMENT_ID from BFX.UNIVERSAL_DOCUMENT where JSON_VALUE(body, ''$.bankStatementId'') = bank_statement_id)');
END
GO
*/
