IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[CLM_IMPL].[CLM_RISK_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('CLM_IMPL.CLM_RISK_SAT','PAYMENT_RISK_PERCENTAGE') IS NOT NULL
BEGIN
ALTER TABLE CLM_IMPL.CLM_RISK_SAT DROP COLUMN PAYMENT_RISK_PERCENTAGE
END

END
GO

------------------

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[CLM_IMPL].[CLM_BENEFICIARIES_SAT]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE CLM_IMPL.CLM_BENEFICIARIES_SAT
END
GO

------------------

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[CLM_IMPL].[CLM_INJURIES_SAT]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE CLM_IMPL.CLM_INJURIES_SAT
END
GO

------------------

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[CLM_IMPL].[CLM_BENEFICIARIES_LINK]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE CLM_IMPL.CLM_BENEFICIARIES_LINK
END
GO

------------------
