CREATE TABLE BFX_IMPL.INSURED_EVENT_TYPE
(
	CODE nvarchar(50) PRIMARY KEY,
	DESCRIPTION nvarchar(150) NOT NULL,
	INDEX IDX_INS_EVENT_REASON_TYPE NONCLUSTERED (DESCRIPTION)
)
go

CREATE TABLE BFX_IMPL.INSURED_EVENT_REASON
(
	CODE nvarchar(50) PRIMARY KEY,
	DESCRIPTION nvarchar(150) NOT NULL,
	TYPE_CODE nvarchar(50) NOT NULL FOREIGN KEY REFERENCES BFX_IMPL.INSURED_EVENT_TYPE(CODE),
	INDEX IDX_INS_EVENT_REASON_TYPE NONCLUSTERED (TYPE_CODE),
	INDEX IDX_INS_EVENT_REASON_DESCRIPTION NONCLUSTERED (DESCRIPTION)
)
go

CREATE TABLE BFX_IMPL.INSURED_EVENT_REJECTION
(
	CODE nvarchar(50) PRIMARY KEY,
	DESCRIPTION nvarchar(500) NOT NULL,
	INDEX IDX_INS_EVENT_REASON_TYPE NONCLUSTERED (DESCRIPTION)
)
go

CREATE TABLE BFX_IMPL.DISEASE_CLASS
(
	CODE nvarchar(50) PRIMARY KEY,
	DESCRIPTION nvarchar(500) NOT NULL,
	PARENT_CODE nvarchar(50),
	INDEX IDX_INS_EVENT_REASON_TYPE NONCLUSTERED (DESCRIPTION)
)
go

