ALTER TABLE BFX_IMPL.COUNTRY_REF DROP COLUMN IF EXISTS IS_OBSOLETE
GO

ALTER TABLE BFX_IMPL.COUNTRY_REF ADD IS_OBSOLETE INT
GO

UPDATE BFX_IMPL.COUNTRY_REF
   SET IS_OBSOLETE = 0
GO

ALTER TABLE BFX_IMPL.COUNTRY_REF ALTER COLUMN IS_OBSOLETE INT NOT NULL
GO