IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ORG_IMPL].[SERVICE_PROVIDER_INFO_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('ORG_IMPL.SERVICE_PROVIDER_INFO_SAT','RECEIVE_TYPE') IS NULL
BEGIN
ALTER TABLE ORG_IMPL.SERVICE_PROVIDER_INFO_SAT ADD RECEIVE_TYPE nvarchar(max)
END

END
GO