if exists (select * from sys.tables t
    INNER JOIN sys.partitions p on t.object_id = p.object_id
    WHERE t.object_id = OBJECT_ID(N'[PAS_IMPL].[COM_CALC_SAT]') and p.rows > 0)
BEGIN
	EXEC(N'
		UPDATE PAS_IMPL.COM_CALC_SAT set RULE_NUM = 0 where RULE_NUM is null;
		ALTER TABLE PAS_IMPL.COM_CALC_SAT ALTER COLUMN RULE_NUM int not null;
		ALTER TABLE PAS_IMPL.COM_CALC_SAT DROP CONSTRAINT PK_PAS_IMPL_COM_CALC_SAT;
		ALTER TABLE PAS_IMPL.COM_CALC_SAT ADD CONSTRAINT PK_PAS_IMPL_COM_CALC_SAT PRIMARY KEY NONCLUSTERED (COM_CALC_HKEY, LOAD_DATE, RULE_NUM);
        ');
END
go
