IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ORG_IMPL].[SERVICE_PROVIDER_INFO_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('ORG_IMPL.SERVICE_PROVIDER_INFO_SAT','IS_PERSONAL_MANAGER') IS NULL
BEGIN
ALTER TABLE ORG_IMPL.SERVICE_PROVIDER_INFO_SAT ADD IS_PERSONAL_MANAGER BIT
END

END
GO