IF COL_LENGTH('ACC_IMPL.PAYMENT_ORDER_SAT','IS_MANUAL') IS NULL
AND EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ACC_IMPL].[PAYMENT_ORDER_SAT]') AND TYPE IN (N'U'))
BEGIN
ALTER TABLE ACC_IMPL.PAYMENT_ORDER_SAT ADD IS_MANUAL BIT
END

IF COL_LENGTH('ACC_IMPL.PAYMENT_ORDER_SAT','SHOULD_USE_NETTING') IS NULL
AND EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ACC_IMPL].[PAYMENT_ORDER_SAT]') AND TYPE IN (N'U'))
BEGIN
ALTER TABLE ACC_IMPL.PAYMENT_ORDER_SAT ADD SHOULD_USE_NETTING BIT
END