IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[QUOTE_BENEFICIARY_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PAS_IMPL.QUOTE_BENEFICIARY_SAT', 'BENEFICIARY_ID') IS NOT NULL
BEGIN
ALTER TABLE PAS_IMPL.QUOTE_BENEFICIARY_SAT DROP PK_PAS_IMPL_QUOTE_BENEFICIARY_SAT;

DECLARE @defaultConstraint nvarchar(max) = (SELECT name FROM sysobjects WHERE parent_obj = (SELECT OBJECT_ID(N'PAS_IMPL.QUOTE_BENEFICIARY_SAT') AS 'Object ID'));
DECLARE @dropStatement nvarchar(max);
SET @dropStatement = 'ALTER TABLE PAS_IMPL.QUOTE_BENEFICIARY_SAT DROP ' + @defaultConstraint
EXEC sp_sqlexec @dropStatement

ALTER TABLE PAS_IMPL.QUOTE_BENEFICIARY_SAT DROP COLUMN BENEFICIARY_ID;
END

IF COL_LENGTH('PAS_IMPL.QUOTE_BENEFICIARY_SAT', 'BENEFICIARY_ID') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.QUOTE_BENEFICIARY_SAT ADD BENEFICIARY_ID uniqueidentifier DEFAULT NEWID() NOT NULL;
ALTER TABLE PAS_IMPL.QUOTE_BENEFICIARY_SAT ADD CONSTRAINT PK_PAS_IMPL_QUOTE_BENEFICIARY_SAT PRIMARY KEY NONCLUSTERED 
(
    QUOTE_BENEFICIARY_HKEY ASC,
    LOAD_DATE ASC,
	BENEFICIARY_ID
)

END

END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_BENEFICIARY_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PAS_IMPL.POLICY_BENEFICIARY_SAT', 'BENEFICIARY_ID') IS NOT NULL
BEGIN
ALTER TABLE PAS_IMPL.POLICY_BENEFICIARY_SAT DROP PK_PAS_IMPL_POLICY_BENEFICIARY_SAT;

DECLARE @defaultConstraint nvarchar(max) = (SELECT name FROM sysobjects WHERE parent_obj = (SELECT OBJECT_ID(N'PAS_IMPL.POLICY_BENEFICIARY_SAT') AS 'Object ID'));
DECLARE @dropStatement nvarchar(max);
SET @dropStatement = 'ALTER TABLE PAS_IMPL.POLICY_BENEFICIARY_SAT DROP ' + @defaultConstraint
EXEC sp_sqlexec @dropStatement

ALTER TABLE PAS_IMPL.POLICY_BENEFICIARY_SAT DROP COLUMN BENEFICIARY_ID;
END

IF COL_LENGTH('PAS_IMPL.POLICY_BENEFICIARY_SAT', 'BENEFICIARY_ID') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.POLICY_BENEFICIARY_SAT ADD BENEFICIARY_ID uniqueidentifier DEFAULT NEWID() NOT NULL;
ALTER TABLE PAS_IMPL.POLICY_BENEFICIARY_SAT ADD CONSTRAINT PK_PAS_IMPL_POLICY_BENEFICIARY_SAT PRIMARY KEY NONCLUSTERED 
(
    POLICY_BENEFICIARY_HKEY ASC,
    LOAD_DATE ASC,
	BENEFICIARY_ID
)

END

END
GO