IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[SMS_SECURITY_NOTIFICATION]') AND TYPE IN (N'U'))
BEGIN

CREATE TABLE BFX_IMPL.SMS_SECURITY_NOTIFICATION
(
	NOTIFICATION_ID UNIQUEIDENTIFIER PRIMARY KEY,
	REFERENCE_NUMBER NVARCHAR(500) NOT NULL,
	PARTY_CODE NVARCHAR(100) NOT NULL,
	PHONE_NUMBER NVARCHAR(300),
	SECURITY_CODE NVARCHAR(100) NOT NULL,
	SMS_ID NVARCHAR(100),
	SMS_TYPE_CODE INT,
	NOTIFICATION_DATE datetime2,
	IS_VERIFIED BIT NOT NULL DEFAULT 0,
	INDEX IDX_BFX_IMPL_SMS_SEC_REF_NO NONCLUSTERED (REFERENCE_NUMBER),
	INDEX IDX_BFX_IMPL_SMS_SEC_PARTY_CODE NONCLUSTERED (PARTY_CODE),
	INDEX IDX_BFX_IMPL_SMS_SEC_TYPE_CODE NONCLUSTERED (SMS_TYPE_CODE)
)

END
GO