create table BFX_IMPL.DOCUMENT_SYNC_BATCH_ERROR
(
  ERROR_ID UNIQUEIDENTIFIER not null,
  BATCH_ID UNIQUEIDENTIFIER not null,
  ENTITY_ID UNIQUEIDENTIFIER not null,
  ENTITY_TYPE NVARCHAR(128) not null,
  CONSTRAINT PK_DOCUMENT_SYNC_BATCH_ERROR PRIMARY KEY (ERROR_ID),
  CONSTRAINT FK_DOCUMENT_SYNC_BATCH FOREIGN KEY(BATCH_ID) REFERENCES BFX.DOCUMENT_SYNC_BATCH(BATCH_ID)
)