/**
* Description: Replace table
* Auth: FedorY
*/

-- Replace table
-- [ACC_IMPL].[BANK_STATEMENT_ITEM]

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ACC_IMPL].[BANK_STATEMENT_ITEM]') AND TYPE IN (N'U'))
BEGIN
	EXEC sp_rename N'ACC_IMPL.BANK_STATEMENT_ITEM', N'BANK_STATEMENT_ITEM_OLD2'
	EXEC sp_rename N'ACC_IMPL.PK_ACC_IMPL_BANK_STATEMENT_ITEM', N'PK_ACC_IMPL_BANK_STATEMENT_ITEM_OLD2', N'OBJECT'
END;

CREATE TABLE [ACC_IMPL].[BANK_STATEMENT_ITEM]
(
	[BANK_STATEMENT_ITEM_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[UNIVERSAL_DOCUMENT_ID] [nvarchar](50) NULL,
	[BANK_STATEMENT_ITEM_NO] [nvarchar](64) NOT NULL,
	[INCOME_SOURCE] [nvarchar](64) NULL,
	[DIRECTION] [int] NOT NULL,
	[REFERENCE_NO] [nvarchar](256) NULL,
	[PAYMENT_DESCRIPTION] [nvarchar](256) NULL,
	[CURRENCY_CODE] [nvarchar](3) NOT NULL,
	[STATUS_ID] [int] NOT NULL,
	[AMOUNT] [decimal](15, 2) NOT NULL,
	[OPEN_AMOUNT] [decimal](15, 2) NOT NULL,
	[PAYMENT_DATE] [date] NOT NULL,
	[CREATE_DATE] [datetimeoffset] NOT NULL,
	[TRANSACTION_DATE] [date] NOT NULL,
	[CLIENT_PAY_DATE] [date] NOT NULL,
	[IS_REGISTRY] [bit] NOT NULL,
	[IS_ACQUIRING] [bit] NOT NULL,
	[NON_ACCEPTANCE] [bit] NOT NULL,
	[TOLERANCE] [decimal](15, 2) NULL,
	[POSTING_DATE] [date] NOT NULL,
	[DEBTOR_NAME] [nvarchar](256) NULL,
	[DEBTOR_BANK_ACCOUNT_NO] [nvarchar](64) NULL,
	[CREDITOR_NAME] [nvarchar](256) NULL,
	[CREDITOR_BANK_ACCOUNT_NO] [nvarchar](64) NULL,

	CONSTRAINT [PK_ACC_IMPL_BANK_STATEMENT_ITEM_ID] PRIMARY KEY CLUSTERED
	(
		[BANK_STATEMENT_ITEM_ID] ASC
	)
);

GO