
IF NOT EXISTS
    (SELECT * FROM sys.columns
     WHERE Name = N'DOCUMENT_NO'
       AND Object_ID = Object_ID(N'[acc].[GL_ADDITIONAL_ATTRIBUTES]'))
BEGIN
EXEC SP_RENAME 'acc.GL_ADDITIONAL_ATTRIBUTES.CONTRACT_NO', 'DOCUMENT_NO', 'COLUMN';
END;

IF NOT EXISTS
    (SELECT * FROM sys.columns
     WHERE Name = N'DOCUMENT_NO'
       AND Object_ID = Object_ID(N'[acc].[JR_ADDITIONAL_ATTRIBUTES]'))
BEGIN
EXEC SP_RENAME 'acc.JR_ADDITIONAL_ATTRIBUTES.CONTRACT_NO', 'DOCUMENT_NO', 'COLUMN';
END;

update ACC.ATTRIBUTE_DEFINITION set NAME = 'DocumentNo', DESCRIPTION = 'Document number' where NAME = 'ContractNo';

