/*IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ACC_IMPL].[BANK_STATEMENT_ITEM]') AND TYPE IN (N'U'))
BEGIN
ALTER TABLE ACC_IMPL.BANK_STATEMENT_ITEM ADD REFERENCE_NO nvarchar(256);

EXEC(N'UPDATE ACC_IMPL.BANK_STATEMENT_ITEM SET REFERENCE_NO = PAYMENT_DESCRIPTION');

END
GO
*/