IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[BUDGET_RULE]') AND TYPE IN (N'U'))
BEGIN

CREATE TABLE [BFX_IMPL].[BUDGET_RULE] (
[CODE] NVARCHAR(16) NOT NULL,
[DESCRIPTION] NVARCHAR(300) NOT NULL,
CONSTRAINT [PK_BUDGET_RULE]
PRIMARY KEY CLUSTERED ([CODE] ASC)
)

END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[BUDGET_RULE_ALGORITHM]') AND TYPE IN (N'U'))
BEGIN

CREATE TABLE [BFX_IMPL].[BUDGET_RULE_ALGORITHM] (
[CODE] NVARCHAR(16) NOT NULL,
[DESCRIPTION] NVARCHAR(300) NOT NULL,
CONSTRAINT [PK_BUDGET_RULE_ALGORITHM]
PRIMARY KEY CLUSTERED ([CODE] ASC)
)

END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[AA_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PAS_IMPL.AA_SAT','BUDGET_RULE_CODE') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.AA_SAT ADD BUDGET_RULE_CODE nvarchar(16)
END

IF COL_LENGTH('PAS_IMPL.AA_SAT','BUDGET_ALG_CODE') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.AA_SAT ADD BUDGET_ALG_CODE nvarchar(16)
END

END
GO

