IF EXISTS(
  SELECT * 
  FROM 
    SYS.TABLES tbl,
    SYS.PARTITIONS prt
  WHERE tbl.OBJECT_ID = prt.OBJECT_ID 
    AND tbl.OBJECT_ID = OBJECT_ID(N'[PTY_IMPL].[PARTY_INFO_SAT]'))
BEGIN
  IF COL_LENGTH('PTY_IMPL.PARTY_INFO_SAT','DUPLICATE_MASTER_NUMBER') IS NULL
  BEGIN
    ALTER TABLE PTY_IMPL.PARTY_INFO_SAT ADD DUPLICATE_MASTER_NUMBER NVARCHAR(256) NULL
  END
END

GO