if object_id(N'ACC_IMPL.RSD_HUB', N'U') is not null
	drop table ACC_IMPL.RSD_HUB;
go

if object_id(N'ACC_IMPL.RSD_SAT', N'U') is not null
	drop table ACC_IMPL.RSD_SAT;
go

if object_id(N'ACC_IMPL.RSD_ITEM_LINK', N'U') is not null
	drop table ACC_IMPL.RSD_ITEM_LINK;
go

if object_id(N'ACC_IMPL.RSD_ITEM_SAT', N'U') is not null
	drop table ACC_IMPL.RSD_ITEM_SAT;
go

CREATE TABLE [ACC_IMPL].[RSD_HUB]
(
	[RSD_HKEY] [char](32) NOT NULL,
	[LOAD_DATE] [datetime2](7) NOT NULL,
	[RECORD_SOURCE] [varchar](50) NOT NULL,
	[RSD_NUMBER] [nvarchar](128) NOT NULL,
	CONSTRAINT [PK_ACC_IMPL_RSD_HUB] PRIMARY KEY NONCLUSTERED ([RSD_HKEY] ASC),
	CONSTRAINT [UQ_RSD_HUB] UNIQUE CLUSTERED ([RSD_NUMBER] ASC)
)
GO

CREATE TABLE [ACC_IMPL].[RSD_SAT]
(
	[RSD_HKEY] [char](32) NOT NULL,
	[LOAD_DATE] [datetime2](7) NOT NULL,
	[RECORD_SOURCE] [varchar](50) NOT NULL,
	[HASH_DIFF] [char](32) NOT NULL,
	[CREATED_DATE] [date] NULL,
	[NOTES] [nvarchar](max) NULL,
	CONSTRAINT [PK_ACC_IMPL_RSD_SAT] PRIMARY KEY NONCLUSTERED
	(
		[RSD_HKEY] ASC,
		[LOAD_DATE] ASC
	)
)
GO

CREATE TABLE [ACC_IMPL].[RSD_ITEM_LINK]
(
	[RSD_ITEM_HKEY] [char](32) NOT NULL,
	[LOAD_DATE] [datetime2](7) NOT NULL,
	[RECORD_SOURCE] [varchar](50) NOT NULL,
	[CONTRACT_NUMBER] [nvarchar](50) NOT NULL,
	[DUE_DATE] [date] NOT NULL,
	[OBJECT_CODE] [nvarchar](50) NOT NULL,
	[ITEM_NO] [nvarchar](256) NOT NULL,
	[RSD_HKEY] [char](32) NOT NULL,
	CONSTRAINT [PK_ACC_IMPL_RSD_ITEM_LINK] PRIMARY KEY NONCLUSTERED ([RSD_ITEM_HKEY] ASC),
	CONSTRAINT [UQ_RSD_ITEM_LINK] UNIQUE NONCLUSTERED
	(
		[RSD_HKEY] ASC,
		[CONTRACT_NUMBER] ASC,
		[DUE_DATE] ASC,
		[OBJECT_CODE] ASC,
		[ITEM_NO] ASC
	)
)
GO

CREATE TABLE [ACC_IMPL].[RSD_ITEM_SAT]
(
	[RSD_ITEM_HKEY] [char](32) NOT NULL,
	[LOAD_DATE] [datetime2](7) NOT NULL,
	[RECORD_SOURCE] [varchar](50) NOT NULL,
	[HASH_DIFF] [char](32) NOT NULL,
	[IS_DELETED] [bit] NULL,
	[POSTING_DATE] [date] NOT NULL,
	[DEADLINE_DATE] [date] NOT NULL,
	[OVERDUE_DAYS] [int] NOT NULL,
	[AMOUNT] [decimal](15, 2) NOT NULL,
	[OPEN_AMOUNT] [decimal](15, 2) NOT NULL,
	[RSD_RATE] [decimal](15, 4) NOT NULL,
	[RSD_AMOUNT] [decimal](15, 2) NOT NULL,
	CONSTRAINT [PK_ACC_IMPL_RSD_ITEM_SAT] PRIMARY KEY NONCLUSTERED
	(
		[RSD_ITEM_HKEY] ASC,
		[LOAD_DATE] ASC
	)
)
GO
