-- ass tables update schema
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[REPORT_CONTRACT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PAS_IMPL.REPORT_CONTRACT','CREDIT_SUM') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.REPORT_CONTRACT ADD CREDIT_SUM DECIMAL(15,2) NULL
END

IF COL_LENGTH('PAS_IMPL.REPORT_CONTRACT','CREDIT_RATE') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.REPORT_CONTRACT ADD CREDIT_RATE DECIMAL(15,4) NULL
END

IF COL_LENGTH('PAS_IMPL.REPORT_CONTRACT','ANNUITY_PAYMENT_SUM') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.REPORT_CONTRACT ADD ANNUITY_PAYMENT_SUM DECIMAL(15,2) NULL
END

IF COL_LENGTH('PAS_IMPL.REPORT_CONTRACT','CREDIT_PROGRAM_ID') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.REPORT_CONTRACT ADD CREDIT_PROGRAM_ID nvarchar(max) NULL
END

END
GO