IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[INQUIRY_SAT]') AND TYPE IN (N'U'))
BEGIN

    IF COL_LENGTH('PAS_IMPL.INQUIRY_SAT','TEXT_OF_INQUIRY') IS NULL
    BEGIN
    ALTER TABLE PAS_IMPL.INQUIRY_SAT ADD TEXT_OF_INQUIRY nvarchar(max)
    END

	IF COL_LENGTH('PAS_IMPL.INQUIRY_SAT','INCLUDED_IN_RP_REGISTER') IS NULL
    BEGIN
    ALTER TABLE PAS_IMPL.INQUIRY_SAT ADD INCLUDED_IN_RP_REGISTER bit
    END

	IF COL_LENGTH('PAS_IMPL.INQUIRY_SAT','INCLUSION_DATE_RP_REGISTER') IS NULL
    BEGIN
    ALTER TABLE PAS_IMPL.INQUIRY_SAT ADD INCLUSION_DATE_RP_REGISTER date
    END

END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[EWT_IMPL].[ENDOWMENT_INQUIRY_SAT]') AND TYPE IN (N'U'))
BEGIN

    IF COL_LENGTH('EWT_IMPL.ENDOWMENT_INQUIRY_SAT','TEXT_OF_INQUIRY') IS NULL
    BEGIN
    ALTER TABLE EWT_IMPL.ENDOWMENT_INQUIRY_SAT ADD TEXT_OF_INQUIRY nvarchar(max)
    END

	IF COL_LENGTH('EWT_IMPL.ENDOWMENT_INQUIRY_SAT','INCLUDED_IN_RP_REGISTER') IS NULL
    BEGIN
    ALTER TABLE EWT_IMPL.ENDOWMENT_INQUIRY_SAT ADD INCLUDED_IN_RP_REGISTER bit
    END

	IF COL_LENGTH('EWT_IMPL.ENDOWMENT_INQUIRY_SAT','INCLUSION_DATE_RP_REGISTER') IS NULL
    BEGIN
    ALTER TABLE EWT_IMPL.ENDOWMENT_INQUIRY_SAT ADD INCLUSION_DATE_RP_REGISTER date
    END

END
GO
