/**
* Description: change Product relation table
* Auth: IvanM
*/

-- [BFX_IMPL].[RISK_PRODUCT_RELATION]
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[RISK_PRODUCT_RELATION]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[RISK_PRODUCT_RELATION]
END
GO

CREATE TABLE [BFX_IMPL].[RISK_PRODUCT_RELATION] (
[ID] [UNIQUEIDENTIFIER] NOT NULL,
[RISK_CODE] NVARCHAR(255) NOT NULL,
[PRODUCT_CODE] NVARCHAR(255) NOT NULL,
[RELATION_TYPE] NVARCHAR(255) NOT NULL,
[IS_REPLACEABLE] BIT NULL,
[PARENT_RISK] NVARCHAR(255) NULL,
[CONDITIONS_FUNCTION] NVARCHAR(255) NULL,
CONSTRAINT [PK_CT_RISK_PRODUCT_RELATION] PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO
