CREATE TABLE [ACC_IMPL].[PAYMENT_REFERENCE](
[BANK_STATEMENT_ITEM_ID] [bigint] not null constraint FK_PAY_REF_BANK_STATEMENT_ITEM_ID references [ACC_IMPL].[BANK_STATEMENT_ITEM](BANK_STATEMENT_ITEM_ID),
[REFERENCE_NO] [nvarchar](64) not null,
[ORDER_NO] [int] not null,
[AUTO_ALLOCATION_MESSAGE] [nvarchar](512) null,

CONSTRAINT [PK_ACC_IMPL_PAYMENT_REFERENCE_ID] PRIMARY KEY CLUSTERED
	(
		[BANK_STATEMENT_ITEM_ID], [REFERENCE_NO]
	)
);