CREATE TABLE BFX_IMPL.BENEFICIARY_PAYMENT_TYPE
(
	CODE nvarchar(50) PRIMARY KEY,
	DESCRIPTION nvarchar(500) NOT NULL,
	INDEX IDX_BENEFICIARY_PAYMENT_TYPE_DESCRIPTION NONCLUSTERED (DESCRIPTION)
)
go

CREATE TABLE BFX_IMPL.BENEFICIARY_REASON
(
	CODE nvarchar(50) PRIMARY KEY,
	DESCRIPTION nvarchar(500) NOT NULL,
	INDEX IDX_BENEFICIARY_REASON_DESCRIPTION NONCLUSTERED (DESCRIPTION)
)
go