-- rename INCOME_SOURCE => INCOME_SOURCE_ID
update acc_impl.BANK_STATEMENT_ITEM set INCOME_SOURCE = null
GO
ALTER TABLE acc_impl.BANK_STATEMENT_ITEM
ALTER COLUMN INCOME_SOURCE int null
GO
update acc_impl.BANK_STATEMENT_ITEM set INCOME_SOURCE = 93
GO
ALTER TABLE acc_impl.BANK_STATEMENT_ITEM
ALTER COLUMN INCOME_SOURCE int not null
GO
EXEC sp_rename 'acc_impl.BANK_STATEMENT_ITEM.INCOME_SOURCE', 'INCOME_SOURCE_ID', 'COLUMN'
GO

-- drop CLIENT_PAY_DATE from BSI
ALTER TABLE acc_impl.BANK_STATEMENT_ITEM
DROP COLUMN CLIENT_PAY_DATE
GO

-- rename CLIENT_PAY_DATE in ACC_IMPL.AGGREGATED_PAYMENT_REGISTER
IF
	EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[acc_impl].[AGGREGATED_PAYMENT_REGISTER]') AND TYPE IN (N'U'))
	and
	not exists (SELECT * FROM sys.columns WHERE Name = N'PAYMENT_DATE' AND Object_ID = Object_ID(N'[acc_impl].[AGGREGATED_PAYMENT_REGISTER]'))
BEGIN
	EXEC sp_rename 'acc_impl.AGGREGATED_PAYMENT_REGISTER.CLIENT_PAYMENT_DATE', 'PAYMENT_DATE', 'COLUMN'
END
GO

-- add RGSL_GUID
ALTER TABLE acc_impl.BANK_STATEMENT_ITEM
ADD RGSL_GUID uniqueidentifier null
GO
CREATE UNIQUE INDEX UQ_ACC_IMPL_BSI_RGSL_GUID ON acc_impl.BANK_STATEMENT_ITEM(RGSL_GUID) where RGSL_GUID is not null
GO
