-- create table for banks
IF NOT EXISTS (SELECT * FROM SYS.SCHEMAS WHERE [NAME] = N'ORG_IMPL')
EXEC('CREATE SCHEMA [ORG_IMPL]')
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ORG_IMPL].[BANK]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [ORG_IMPL].[BANK]
END
GO

CREATE TABLE [ORG_IMPL].[BANK] (
[ID] UNIQUEIDENTIFIER NOT NULL,
[BIC] NVARCHAR(9) NOT NULL,
[NAME] NVARCHAR(255) NOT NULL,
[REGISTRATION_NUMBER] NVARCHAR(20) NOT NULL,
[CORRESPONDENT_ACCOUNT] NVARCHAR(30) NOT NULL,
[PARENT_BIC] NVARCHAR(9) NULL,
[ADDRESS_INDEX] NVARCHAR(7) NULL,
[REGION] NVARCHAR(3) NULL,
[AREA_TYPE] NVARCHAR(20) NULL,
[AREA_NAME] NVARCHAR(255) NULL,
[ADDRESS_LINE] NVARCHAR(255) NULL,
CONSTRAINT [PK_BANK]
PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO

IF EXISTS (SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'[ORG_IMPL].[BANK]') AND NAME = N'IDX_BIC')
BEGIN
DROP INDEX [IDX_BIC] ON [ORG_IMPL].[BANK]
END
GO

CREATE INDEX [IDX_BIC] ON [ORG_IMPL].[BANK] ([BIC])
GO