IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[COUNTRY_PHONE_CODE]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[COUNTRY_PHONE_CODE]
END
GO
CREATE TABLE [BFX_IMPL].[COUNTRY_PHONE_CODE] (
[COUNTRY_CODE] [nvarchar](3) NOT NULL,
[PHONE_CODE] NVARCHAR(31) NOT NULL
CONSTRAINT [PK_COUNTRY_PHONE_CODE]
PRIMARY KEY CLUSTERED ([COUNTRY_CODE], [PHONE_CODE] ASC)
)
GO