IF
	exists (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'PTY_IMPL.PARTY_INFO_SAT') AND TYPE IN (N'U'))
	and
	not exists (SELECT * FROM sys.columns WHERE Name = N'CONFIGURATION_CODE_NAME' AND Object_ID = Object_ID(N'PTY_IMPL.PARTY_INFO_SAT'))
	and
	not exists (SELECT * FROM sys.columns WHERE Name = N'NATURAL_PERSON_CATEGORY' AND Object_ID = Object_ID(N'PTY_IMPL.PARTY_INFO_SAT'))
BEGIN
	ALTER TABLE PTY_IMPL.PARTY_INFO_SAT ADD CONFIGURATION_CODE_NAME NVARCHAR(256) NULL;

	ALTER TABLE PTY_IMPL.PARTY_INFO_SAT ADD NATURAL_PERSON_CATEGORY NVARCHAR(256) NULL;

	EXEC(N'
	UPDATE PTY_IMPL.PARTY_INFO_SAT
	SET
		CONFIGURATION_CODE_NAME = pa.CODE_NAME,
		NATURAL_PERSON_CATEGORY = JSON_VALUE(p.BODY, ''$.partyPersonData.naturalPersonCategory'')
	FROM
		PTY_IMPL.PARTY_INFO_SAT pis
		join PTY_IMPL.PARTY_HUB ph on ph.PARTY_HKEY = pis.PARTY_INFO_HKEY
		join PTY.PARTY p on p.PARTY_CODE = ph.PARTY_CODE
		join CFX.PUBLISHED_ARTIFACT pa on pa.PUBLISHED_ARTIFACT_ID = p.PUBLISHED_ARTIFACT_ID
	WHERE
		PARTY_INFO_HKEY = pis.PARTY_INFO_HKEY');
END
GO

IF
	exists (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'ORG_IMPL.SERVICE_PROVIDER_INFO_SAT') AND TYPE IN (N'U'))
	and
	not exists (SELECT * FROM sys.columns WHERE Name = N'CONFIGURATION_CODE_NAME' AND Object_ID = Object_ID(N'ORG_IMPL.SERVICE_PROVIDER_INFO_SAT'))
	and
	not exists (SELECT * FROM sys.columns WHERE Name = N'PARTNER_TYPE' AND Object_ID = Object_ID(N'ORG_IMPL.SERVICE_PROVIDER_INFO_SAT'))
BEGIN
	ALTER TABLE ORG_IMPL.SERVICE_PROVIDER_INFO_SAT ADD CONFIGURATION_CODE_NAME NVARCHAR(256) NULL;

	ALTER TABLE ORG_IMPL.SERVICE_PROVIDER_INFO_SAT ADD PARTNER_TYPE NVARCHAR(256) NULL;

	EXEC(N'
	UPDATE ORG_IMPL.SERVICE_PROVIDER_INFO_SAT
	SET
		CONFIGURATION_CODE_NAME = pa.CODE_NAME,
		PARTNER_TYPE = JSON_VALUE(sp.BODY, ''$.partnerType'')
	FROM
		ORG_IMPL.SERVICE_PROVIDER_INFO_SAT pis
		join ORG_IMPL.SERVICE_PROVIDER_HUB ph on ph.SERVICE_PROVIDER_HKEY = pis.SERVICE_PROVIDER_INFO_HKEY
		join ORG.SERVICE_PROVIDER sp on sp.SERVICE_PROVIDER_CODE = ph.SERVICE_PROVIDER_CODE
		join CFX.PUBLISHED_ARTIFACT pa on pa.PUBLISHED_ARTIFACT_ID = sp.PUBLISHED_ARTIFACT_ID
	WHERE
		SERVICE_PROVIDER_INFO_HKEY = pis.SERVICE_PROVIDER_INFO_HKEY');
END
GO