IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PAS_IMPL.POLICY_SAT','RISK_PREMIUM') IS NOT NULL
BEGIN
ALTER TABLE PAS_IMPL.POLICY_SAT ALTER COLUMN RISK_PREMIUM DECIMAL(15,2) NULL
END

END
GO