IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[PARTY_RELATIONS_TYPE]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[PARTY_RELATIONS_TYPE]
END
GO

CREATE TABLE [BFX_IMPL].[PARTY_RELATIONS_TYPE] (
[ID] [UNIQUEIDENTIFIER] NOT NULL,
[DESCRIPTION] NVARCHAR(MAX) NOT NULL,
PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO