IF NOT EXISTS (SELECT * FROM SYS.SCHEMAS WHERE [NAME] = N'BFX_IMPL')
EXEC('CREATE SCHEMA [BFX_IMPL]')
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[FK_DOCUMENT_TYPE_CLASS]') AND TYPE IN (N'F'))
BEGIN
ALTER TABLE [BFX_IMPL].[DOCUMENT_TYPE] DROP CONSTRAINT [FK_DOCUMENT_TYPE_CLASS]
END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[DOCUMENT_TYPE]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[DOCUMENT_TYPE]
END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[DOCUMENT_TYPE_CLASS]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[DOCUMENT_TYPE_CLASS]
END
GO

CREATE TABLE [BFX_IMPL].[DOCUMENT_TYPE_CLASS] (
[CODE] NVARCHAR(255) NOT NULL,
[DESCRIPTION] NVARCHAR(MAX) NOT NULL,
CONSTRAINT [PK_DOCUMENT_TYPE_CLASS]
PRIMARY KEY CLUSTERED ([CODE] ASC)
)
GO

CREATE TABLE [BFX_IMPL].[DOCUMENT_TYPE] (
[CODE] NVARCHAR(255) NOT NULL,
[DESCRIPTION] NVARCHAR(MAX) NOT NULL,
[CLASS_CODE] NVARCHAR(255) NOT NULL,
CONSTRAINT [PK_DOCUMENT_TYPE]
PRIMARY KEY CLUSTERED ([CODE] ASC)
)
GO

ALTER TABLE [BFX_IMPL].[DOCUMENT_TYPE] ADD CONSTRAINT [FK_DOCUMENT_TYPE_CLASS] FOREIGN KEY([CLASS_CODE])
REFERENCES [BFX_IMPL].[DOCUMENT_TYPE_CLASS] ([CODE])
GO