IF
	EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[acc_impl].[CA_ACT_ITEM]') AND TYPE IN (N'U'))
	and
	not exists (SELECT * FROM sys.columns WHERE Name = N'DOC_CURRENCY_CODE' AND Object_ID = Object_ID(N'[acc_impl].[CA_ACT_ITEM]'))
BEGIN
	ALTER TABLE acc_impl.CA_ACT_ITEM ADD DOC_CURRENCY_CODE NVARCHAR(3) NOT NULL;
END
GO

IF
	EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[acc_impl].[CA_ACT_HISTORY]') AND TYPE IN (N'U'))
	and
	not exists (SELECT * FROM sys.columns WHERE Name = N'CREATE_DATE' AND Object_ID = Object_ID(N'[acc_impl].[CA_ACT_HISTORY]'))
BEGIN
	ALTER TABLE acc_impl.CA_ACT_HISTORY ADD CREATE_DATE datetime2 NOT NULL;
END
GO

ALTER TABLE acc_impl.BANK_STATEMENT_ITEM ALTER COLUMN CREATE_DATE datetime2
GO

ALTER TABLE acc_impl.ALLOCATION ALTER COLUMN CREATE_DATE datetime2
GO

ALTER TABLE acc_impl.MATCHING ALTER COLUMN CREATE_DATE datetime2
GO

