IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[AA_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PAS_IMPL.AA_SAT','SALES_CLASSIFICATION') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.AA_SAT ADD SALES_CLASSIFICATION nvarchar(150)
END

END
GO