/**
* Description: Add relation type table
* Auth: IvanM
*/

-- Add new table
-- [BFX_IMPL].[RISK_RELATION_TYPE]
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[RISK_RELATION_TYPE]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[RISK_RELATION_TYPE]
END
GO

CREATE TABLE [BFX_IMPL].[RISK_RELATION_TYPE] (
[ID] [UNIQUEIDENTIFIER] NOT NULL,
[CODE] NVARCHAR(255) NOT NULL,
[RELATION_TYPE] NVARCHAR(255) NOT NULL,
CONSTRAINT [PK_CT_RISK_RELATION_TYPE] PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO

-- Change column name from RELATION_TYPE to RELATION_TYPE_CODE
DELETE FROM BFX_IMPL.RISK_PRODUCT_RELATION 
ALTER TABLE BFX_IMPL.RISK_PRODUCT_RELATION DROP COLUMN RELATION_TYPE
ALTER TABLE BFX_IMPL.RISK_PRODUCT_RELATION ADD RELATION_TYPE_CODE NVARCHAR(255) NOT NULL
