IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[REINSURANCE]') AND TYPE IN (N'U'))
BEGIN

    IF COL_LENGTH('PAS_IMPL.REINSURANCE','POLICY_YEAR_NUMBER') IS NULL
    BEGIN
    ALTER TABLE PAS_IMPL.REINSURANCE ADD POLICY_YEAR_NUMBER int
    END

END
GO