IF COL_LENGTH('BFX_IMPL.DOCUMENT_TYPE', 'OFFICIAL_CODE') IS NULL
BEGIN
	ALTER TABLE BFX_IMPL.DOCUMENT_TYPE ADD OFFICIAL_CODE nvarchar(255) NULL
END
GO

IF COL_LENGTH('BFX_IMPL.DOCUMENT_TYPE', 'IS_OFFICIAL_OTHER') IS NULL
BEGIN
	ALTER TABLE BFX_IMPL.DOCUMENT_TYPE ADD IS_OFFICIAL_OTHER bit NULL
END
GO