CREATE TABLE [ACC_IMPL].[PAYABLE_COMMISSION]
(
	[PAYABLE_COMMISSION_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[MATCHING_ID] [bigint] NOT NULL,

	[CANCELLED] BIT NOT NULL,
	[CANCELLED_PC_ID] [bigint] NULL,

	[AA_COMM_RATE] [decimal](15, 2) NOT NULL,
	[DOC_COMM_RATE] [decimal](15, 2) NULL,

	[CREATE_DATE] [datetime2] NOT NULL,

	CONSTRAINT [PK_ACC_IMPL_PAYABLE_COMMISSION_ID] PRIMARY KEY CLUSTERED
	(
		[PAYABLE_COMMISSION_ID] ASC
	)
);

GO

ALTER TABLE [ACC_IMPL].[PAYABLE_COMMISSION] WITH CHECK ADD CONSTRAINT [FK_ACC_IMPL_PAYABLE_COMMISSION_MATCHING_ID] FOREIGN KEY([MATCHING_ID])
REFERENCES [ACC_IMPL].[MATCHING] ([MATCHING_ID])
GO

ALTER TABLE [ACC_IMPL].[PAYABLE_COMMISSION] CHECK CONSTRAINT [FK_ACC_IMPL_PAYABLE_COMMISSION_MATCHING_ID]
GO
