/**
* Description: Chage Risks table
* Auth: IvanM
*/

-- [BFX_IMPL].[RISKS]
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[RISKS]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[RISKS]
END
GO

CREATE TABLE [BFX_IMPL].[RISKS] (
[ID] [UNIQUEIDENTIFIER] NOT NULL,
[CODE] NVARCHAR(255) NOT NULL,
[TYPE] NVARCHAR(255) NOT NULL,
[BUSINESS_LINE] NVARCHAR(255) NOT NULL,
[SHORT_DESCRIPTION] NVARCHAR(MAX) NOT NULL,
[FULL_DESCRIPTION] NVARCHAR(MAX) NOT NULL,
CONSTRAINT [PK_CT_RISKS] PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO
