ALTER TABLE acc_impl.CA_ACT ADD PREMIUM_AMOUNT_LC DECIMAL(15,2) NULL
GO
UPDATE acc_impl.CA_ACT SET PREMIUM_AMOUNT_LC = 0
GO
ALTER TABLE acc_impl.CA_ACT ALTER COLUMN PREMIUM_AMOUNT_LC DECIMAL(15,2) NOT NULL
GO