IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[RGS_BRANCHES]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [BFX_IMPL].[RGS_BRANCHES];
END
GO

CREATE TABLE [BFX_IMPL].[RGS_BRANCHES] (
[ID] UNIQUEIDENTIFIER NOT NULL,
[NAME] NVARCHAR(MAX) NULL,
[KSP] NVARCHAR(MAX) NULL,
[REGION] NVARCHAR(MAX) NULL,
PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO