IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[VERIFICATION_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('PAS_IMPL.VERIFICATION_SAT','SELLER_COMMENT') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.VERIFICATION_SAT ADD SELLER_COMMENT nvarchar(max)
END

IF COL_LENGTH('PAS_IMPL.VERIFICATION_SAT','OPERATIONS_COMMENT') IS NULL
BEGIN
ALTER TABLE PAS_IMPL.VERIFICATION_SAT ADD OPERATIONS_COMMENT nvarchar(max)
END

END
GO