IF
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[SEND_EVENT_TYPE]'))
AND
EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'SEND_EVENT_TYPE_NAME' AND OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[SEND_EVENT_TYPE]'))
BEGIN
	ALTER TABLE BFX_IMPL.SEND_EVENT_TYPE
	ALTER COLUMN SEND_EVENT_TYPE_NAME NVARCHAR(64) NOT NULL
END
GO