IF
NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'CFG.CERTIFICATE_DESCRIPTION') AND TYPE IN (N'U'))
BEGIN
    CREATE TABLE CFG.CERTIFICATE_DESCRIPTION (
    	[DESCRIPTION_ID] [int] NOT NULL,
    	[CODE_NAME] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    	[DESCRIPTION] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    	CONSTRAINT [PK_CFG_CERTIFICATE_DESCRIPTION] PRIMARY KEY CLUSTERED
    (
    	[DESCRIPTION_ID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
     CONSTRAINT [UQ_CERTIFICATE_CODE_NAME] UNIQUE NONCLUSTERED
    (
    	[CODE_NAME] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]

END