IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'BFX_IMPL.HISTORY_COMMENT') AND TYPE IN (N'U'))
	BEGIN
		DROP TABLE BFX_IMPL.HISTORY_COMMENT
	END
GO

CREATE TABLE BFX_IMPL.HISTORY_COMMENT(
    COMMENT_ID NVARCHAR(64) NOT NULL,
   	AUTHOR NVARCHAR(64) NOT NULL,
    ORIGINAL_DOCUMENT_NUMBER NVARCHAR(64) NOT NULL,
    AUTHOR_APPLICATION_USER_GROUP NVARCHAR(64) NOT NULL,
    COMMENT NVARCHAR(MAX) NOT NULL,
    CREATED_ON DATETIME NOT NULL,
    MODIFIED_ON DATETIME NULL,
    DELETED BIT NOT NULL,
    SEQ_NUMBER INT NOT NULL,
    ORIGINAL_COMMENT_ID NVARCHAR(64) NULL,
    CONSTRAINT [PK_COMMENT_ID]
	PRIMARY KEY CLUSTERED ([COMMENT_ID] ASC)
    );
GO