IF
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_COMMISSION_SAT]') AND TYPE IN (N'U'))
AND
NOT EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'IS_DELETED' AND OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_COMMISSION_SAT]'))
BEGIN
	ALTER TABLE PAS_IMPL.POLICY_COMMISSION_SAT ADD IS_DELETED bit
END
GO

IF
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_COMMISSION_SAT]') AND TYPE IN (N'U'))
AND
EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'IS_DELETED' AND OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_COMMISSION_SAT]'))
BEGIN
	UPDATE PAS_IMPL.POLICY_COMMISSION_SAT
    SET IS_DELETED = 0
    WHERE IS_DELETED IS NULL
END
GO