IF NOT EXISTS (select * from sys.objects where object_id = object_id(N'[BFX_IMPL].[HISTORY_COMMENT]') and type in (N'U'))
BEGIN
    CREATE TABLE BFX_IMPL.HISTORY_COMMENT(
    	COMMENT_ID BIGINT IDENTITY (1,1),
    	AUTHOR NVARCHAR(64) NOT NULL,
    	ORIGINAL_DOCUMENT_NUMBER NVARCHAR(64) NOT NULL,
    	AUTHOR_APPLICATION_USER_GROUP NVARCHAR(64) NOT NULL,
    	COMMENT NVARCHAR(MAX) NOT NULL,
    	CREATED_ON DATETIME NOT NULL,
    	MODIFIED_ON DATETIME NULL,
    	DELETED BIT NOT NULL,
    	SEQ_NUMBER INT NOT NULL,
    	ORIGINAL_COMMENT_ID BIGINT NULL
    );
END
GO
