IF OBJECT_ID(N'BFX_IMPL.MESSAGE_OUTBOX_ARCH', N'U') IS NOT NULL
	DROP TABLE BFX_IMPL.MESSAGE_OUTBOX_ARCH;
GO

CREATE TABLE [BFX_IMPL].[MESSAGE_OUTBOX_ARCH](
	[MESSAGE_OUTBOX_ITEM_ID] [uniqueidentifier] NOT NULL,
	[MESSAGE_ID] [nvarchar](128) NOT NULL,
	[GROUP_ID] [nvarchar](128) NOT NULL,
	[STATUS_ID] [int] NOT NULL,
	[DEQUEUE_ID] [uniqueidentifier] NULL,
	[RETRY_COUNT] [int] NOT NULL,
	[RETRY_AFTER_TIMESTAMP_UTC] [datetime] NOT NULL,
	[MESSAGE] [nvarchar](max) NOT NULL,
	[TIMESTAMP_UTC] [datetime] NOT NULL,
	[DESTINATION] [nvarchar](256) NOT NULL,
	CONSTRAINT [PK_BFX_IMPL_MESSAGE_OUTBOX_ARCH] PRIMARY KEY NONCLUSTERED 
	(
		[MESSAGE_OUTBOX_ITEM_ID] ASC
	)
)
GO