IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ACC_IMPL].[CRT_EMPLOYEE_LINK]') AND TYPE IN (N'U'))
BEGIN
DROP TABLE [ACC_IMPL].[CRT_EMPLOYEE_LINK]
END
GO

CREATE TABLE [ACC_IMPL].[CRT_EMPLOYEE_LINK](
	[CRT_EMPLOYEE_HKEY] [char](32) NOT NULL,
	[LOAD_DATE] [datetime2](7) NOT NULL,
	[RECORD_SOURCE] [varchar](50) NOT NULL,
	[CRT_HKEY] [char](32) NOT NULL,
	[PARTY_HKEY] [char](32) NOT NULL,
	CONSTRAINT [PK_ACC_IMPL_CRT_EMPLOYEE_LINK] PRIMARY KEY NONCLUSTERED 
	(
		[CRT_EMPLOYEE_HKEY] ASC
	),
	CONSTRAINT [UQ_CRT_EMPLOYEE_LINK] UNIQUE NONCLUSTERED 
	(
		[CRT_HKEY] ASC,
		[PARTY_HKEY] ASC
	)
)
GO