IF NOT EXISTS (SELECT * FROM SYS.SCHEMAS WHERE [NAME] = N'CFX_IMPL')
EXEC('CREATE SCHEMA [CFX_IMPL]')
GO

IF OBJECT_ID(N'CFX_IMPL.USER_APPLICATION_ROLE_HISTORY_ARCH', N'U') IS NOT NULL
	DROP TABLE CFX_IMPL.USER_APPLICATION_ROLE_HISTORY_ARCH;
GO

CREATE TABLE [CFX_IMPL].[USER_APPLICATION_ROLE_HISTORY_ARCH](
	[APPLICATION_USER_ROLE_ASSIGNMENT_HISTORY_ID] [uniqueidentifier] NOT NULL,
	[APPLICATION_ROLE_ID] [uniqueidentifier] NOT NULL,
	[APPLICATION_USER_ID] [uniqueidentifier] NOT NULL,
	[ASSIGNMENT_CREATED_DATE] [datetime] NOT NULL,
	[ASSIGNMENT_DELETED_DATE] [datetime] NULL,
	[SYS_CREATED_ON] [datetime] NOT NULL,
	[SYS_CREATED_BY_ID] [uniqueidentifier] NOT NULL,
	[SYS_UPDATED_ON] [datetime] NOT NULL,
	[SYS_UPDATED_BY_ID] [uniqueidentifier] NOT NULL,
	[SYS_CLIENT_ID] [nvarchar](64) NOT NULL,
	[SYS_VERSION] [bigint] NOT NULL,
	CONSTRAINT [PK_ORG_IMPL_AUGAH_ARCH] PRIMARY KEY CLUSTERED 
	(
		[APPLICATION_USER_ROLE_ASSIGNMENT_HISTORY_ID] ASC
	)
)
GO

ALTER TABLE [CFX_IMPL].[USER_APPLICATION_ROLE_HISTORY_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_CFX_IMPL_UARH_APPLICATION_ROLE_ARCH] FOREIGN KEY([APPLICATION_ROLE_ID])
REFERENCES [CFG].[APPLICATION_ROLE] ([APPLICATION_ROLE_ID])
GO

ALTER TABLE [CFX_IMPL].[USER_APPLICATION_ROLE_HISTORY_ARCH] CHECK CONSTRAINT [FK_CFX_IMPL_UARH_APPLICATION_ROLE_ARCH]
GO

ALTER TABLE [CFX_IMPL].[USER_APPLICATION_ROLE_HISTORY_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_CFX_IMPL_UARH_APPLICATION_USER_ARCH] FOREIGN KEY([APPLICATION_USER_ID])
REFERENCES [ORG].[APPLICATION_USER] ([APPLICATION_USER_ID])
GO

ALTER TABLE [CFX_IMPL].[USER_APPLICATION_ROLE_HISTORY_ARCH] CHECK CONSTRAINT [FK_CFX_IMPL_UARH_APPLICATION_USER_ARCH]
GO

ALTER TABLE [CFX_IMPL].[USER_APPLICATION_ROLE_HISTORY_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_CFX_IMPL_UARH_ARCH_CREATED_BY] FOREIGN KEY([SYS_CREATED_BY_ID])
REFERENCES [ORG].[APPLICATION_USER] ([APPLICATION_USER_ID])
GO

ALTER TABLE [CFX_IMPL].[USER_APPLICATION_ROLE_HISTORY_ARCH] CHECK CONSTRAINT [FK_CFX_IMPL_UARH_ARCH_CREATED_BY]
GO

ALTER TABLE [CFX_IMPL].[USER_APPLICATION_ROLE_HISTORY_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_CFX_IMPL_UARH_ARCH_UPDATED_BY] FOREIGN KEY([SYS_UPDATED_BY_ID])
REFERENCES [ORG].[APPLICATION_USER] ([APPLICATION_USER_ID])
GO

ALTER TABLE [CFX_IMPL].[USER_APPLICATION_ROLE_HISTORY_ARCH] CHECK CONSTRAINT [FK_CFX_IMPL_UARH_ARCH_UPDATED_BY]
GO
