IF OBJECT_ID(N'BFX_IMPL.DOCUMENT_SYNC_BATCH_ARCH', N'U') IS NOT NULL
	DROP TABLE BFX_IMPL.DOCUMENT_SYNC_BATCH_ARCH;
GO

CREATE TABLE [BFX_IMPL].[DOCUMENT_SYNC_BATCH_ARCH](
	[BATCH_ID] [uniqueidentifier] NOT NULL,
	[BODY] [nvarchar](max) NOT NULL,
	[HASH] [binary](32) NOT NULL,
	[STATUS] [tinyint] NOT NULL,
	CONSTRAINT [PK_BFX_IMPL_DOCUMENT_SYNC_BATCH_ARCH] PRIMARY KEY NONCLUSTERED 
	(
		[BATCH_ID] ASC
	)
)
GO