if exists (select * from sys.objects where object_id = object_id('[ACC_IMPL].[PORTFOLIO_TRANSFER_DOCUMENT_LINK]'))
begin
	DROP TABLE [ACC_IMPL].[PORTFOLIO_TRANSFER_DOCUMENT_PAYMENT_SAT];
	DROP TABLE [ACC_IMPL].[PORTFOLIO_TRANSFER_DOCUMENT_SAT];
	DROP TABLE [ACC_IMPL].[PORTFOLIO_TRANSFER_DOCUMENT_LINK];
end;
go

CREATE TABLE [ACC_IMPL].[PORTFOLIO_TRANSFER_DOCUMENT_LINK]
(
	[PORTFOLIO_TRANSFER_DOCUMENT_HKEY] [char](32) NOT NULL,
	[LOAD_DATE] [datetime2](7) NOT NULL,
	[RECORD_SOURCE] [varchar](50) NOT NULL,
	[PORTFOLIO_TRANSFER_HKEY] [char](32) NOT NULL,
	[POLICY_HKEY] [char](32) NOT NULL,
	CONSTRAINT [PK_ACC_IMPL_PORTFOLIO_TRANSFER_DOCUMENT_LINK] PRIMARY KEY NONCLUSTERED ([PORTFOLIO_TRANSFER_DOCUMENT_HKEY] ASC),
	CONSTRAINT [UQ_PORTFOLIO_TRANSFER_DOCUMENT_LINK] UNIQUE NONCLUSTERED ([PORTFOLIO_TRANSFER_HKEY] ASC, [POLICY_HKEY] ASC)
)
GO

CREATE TABLE [ACC_IMPL].[PORTFOLIO_TRANSFER_DOCUMENT_SAT]
(
	[PORTFOLIO_TRANSFER_DOCUMENT_HKEY] [char](32) NOT NULL,
	[LOAD_DATE] [datetime2](7) NOT NULL,
	[RECORD_SOURCE] [varchar](50) NOT NULL,
	[HASH_DIFF] [char](32) NOT NULL,
	[STATE] [varchar](50) NOT NULL,
	[ERROR] [nvarchar](max) NULL,
	CONSTRAINT [PK_ACC_IMPL_PORTFOLIO_TRANSFER_DOCUMENT_SAT] PRIMARY KEY NONCLUSTERED ([PORTFOLIO_TRANSFER_DOCUMENT_HKEY] ASC, [LOAD_DATE] ASC )
)
GO

CREATE TABLE [ACC_IMPL].[PORTFOLIO_TRANSFER_DOCUMENT_PAYMENT_SAT]
(
	[PORTFOLIO_TRANSFER_DOCUMENT_PAYMENT_HKEY] [char](32) NOT NULL,
	[LOAD_DATE] [datetime2](7) NOT NULL,
	[RECORD_SOURCE] [varchar](50) NOT NULL,
	[HASH_DIFF] [char](32) NOT NULL,
	[BANK_STATEMENT_ITEM_ID] [bigint] NOT NULL,
	[PAY_AMOUNT] [decimal](15, 2) NOT NULL,
	[DOC_AMOUNT] [decimal](15, 2) NOT NULL,
	CONSTRAINT [PK_ACC_IMPL_PORTFOLIO_TRANSFER_DOCUMENT_PAYMENT_SAT] PRIMARY KEY NONCLUSTERED ([PORTFOLIO_TRANSFER_DOCUMENT_PAYMENT_HKEY] ASC, [BANK_STATEMENT_ITEM_ID] ASC, [LOAD_DATE] ASC)
)
GO
