CREATE TABLE [ACC_IMPL].[XML_MESSAGE_ITEM_HISTORY](
	[XML_MESSAGE_ITEM_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BANK_STATEMENT_ITEM_ID] [bigint] NOT NULL,
	[BANK_STATEMENT_ITEM_NO] [nvarchar](256) NULL,
	[AUTHORIZED_PERSON_TAB_NUMBER] [nvarchar](256) NULL,
	[ALLOCATION_ID] [bigint] NULL,
	[DOCUMENT_NO] [nvarchar](256) NULL,
	[CREATE_DATE] [datetime2](7) NOT NULL,
	[USER_ID] [uniqueidentifier] NULL,
CONSTRAINT [PK_ACC_IMPL_XML_MESSAGE_ITEM_HISTORY_ID] PRIMARY KEY CLUSTERED 
(
	[BANK_STATEMENT_ITEM_ID] ASC,
	[XML_MESSAGE_ITEM_ID] ASC
))
GO

ALTER TABLE [ACC_IMPL].[XML_MESSAGE_ITEM_HISTORY] WITH CHECK 
ADD CONSTRAINT [FK_ACC_IMPL_XML_MESSAGE_ITEM_HISTORY_BANK_STATEMENT_ITEM_ID] FOREIGN KEY([BANK_STATEMENT_ITEM_ID])
REFERENCES [ACC_IMPL].[BANK_STATEMENT_ITEM] ([BANK_STATEMENT_ITEM_ID])
GO