IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[CLM_IMPL].[CLM_SAT]') AND TYPE IN (N'U'))
BEGIN
	IF COL_LENGTH('CLM_IMPL.CLM_SAT','CONTRACT_INSURED_NAME') IS NULL
	BEGIN
		ALTER TABLE CLM_IMPL.CLM_SAT ADD CONTRACT_INSURED_NAME nvarchar(max)
	END
END
