IF OBJECT_ID(N'BFX_IMPL.FILE_METADATA_ARCH', N'U') IS NOT NULL
	DROP TABLE BFX_IMPL.FILE_METADATA_ARCH;
GO

CREATE TABLE [BFX_IMPL].[FILE_METADATA_ARCH](
	[FILE_METADATA_ID] [uniqueidentifier] NOT NULL,
	[FILENAME] [nvarchar](250) NULL,
	[MEDIA_TYPE] [nvarchar](100) NULL,
	[STATUS] [int] NULL,
	[TOTAL_SIZE] [bigint] NULL,
	[CHECKSUM] [nvarchar](64) NULL,
	[SYS_CREATED_ON] [datetime] NOT NULL,
	[SYS_UPDATED_ON] [datetime] NOT NULL,
	[SYS_CLIENT_ID] [nvarchar](64) NOT NULL,
	[SYS_CREATED_BY_ID] [uniqueidentifier] NOT NULL,
	[SYS_UPDATED_BY_ID] [uniqueidentifier] NOT NULL,
	[ENCODING] [nvarchar](100) NULL,
	CONSTRAINT [PK_BFX_IMPL_FILE_METADATA_ARCH] PRIMARY KEY NONCLUSTERED 
	(
		[FILE_METADATA_ID] ASC
	)
)
GO

ALTER TABLE [BFX_IMPL].[FILE_METADATA_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_CREATED_BFX_IMPL_FILE_METADATA_ARCH] FOREIGN KEY([SYS_CREATED_BY_ID])
REFERENCES [ORG].[APPLICATION_USER] ([APPLICATION_USER_ID])
GO

ALTER TABLE [BFX_IMPL].[FILE_METADATA_ARCH] CHECK CONSTRAINT [FK_CREATED_BFX_IMPL_FILE_METADATA_ARCH]
GO

ALTER TABLE [BFX_IMPL].[FILE_METADATA_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_UPDATED_BFX_IMPL_FILE_METADATA_ARCH] FOREIGN KEY([SYS_UPDATED_BY_ID])
REFERENCES [ORG].[APPLICATION_USER] ([APPLICATION_USER_ID])
GO

ALTER TABLE [BFX_IMPL].[FILE_METADATA_ARCH] CHECK CONSTRAINT [FK_UPDATED_BFX_IMPL_FILE_METADATA_ARCH]
GO
