IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[FK_BFX_IMPL_ATTACHMENT_ARCH_FILE_METADATA]') AND TYPE IN (N'F'))
BEGIN
ALTER TABLE [BFX_IMPL].[ATTACHMENT_ARCH] DROP CONSTRAINT [FK_BFX_IMPL_ATTACHMENT_ARCH_FILE_METADATA]
END
GO