CREATE TABLE ACC_IMPL.DOCUMENT_TYPE_CODE_VIEW (
    ID INT IDENTITY(1, 1) PRIMARY KEY,
    DOCUMENT_TYPE_CODE NVARCHAR(255) NOT NULL,
	CODE_VIEW INT NOT NULL,
	CONSTRAINT fk_codeview_document_type FOREIGN KEY (DOCUMENT_TYPE_CODE) REFERENCES BFX_IMPL.DOCUMENT_TYPE (CODE)
)