IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'BFX_IMPL.RATE_OF_RETURN') AND TYPE IN (N'U'))
BEGIN

    IF COL_LENGTH('BFX_IMPL.RATE_OF_RETURN','STRATEGY_CODE') IS NULL
    BEGIN
    ALTER TABLE BFX_IMPL.RATE_OF_RETURN ADD STRATEGY_CODE nvarchar(255)
    END

END