
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[QUOTE_SAT]') AND TYPE IN (N'U'))
BEGIN
    IF COL_LENGTH('PAS_IMPL.QUOTE_SAT','STRATEGY_DESCRIPTION_FULL') IS NULL
    BEGIN
    	ALTER TABLE PAS_IMPL.QUOTE_SAT
    	ADD STRATEGY_DESCRIPTION_FULL NVARCHAR(MAX)
    END
END

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[POLICY_SAT]') AND TYPE IN (N'U'))
BEGIN
    IF COL_LENGTH('PAS_IMPL.POLICY_SAT','STRATEGY_DESCRIPTION_FULL') IS NULL
    BEGIN
    	ALTER TABLE PAS_IMPL.POLICY_SAT
    	ADD STRATEGY_DESCRIPTION_FULL NVARCHAR(MAX)
    END
END


IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[REPORT_CONTRACT]') AND TYPE IN (N'U'))
BEGIN
    IF COL_LENGTH('PAS_IMPL.REPORT_CONTRACT','STRATEGY_DESCRIPTION_FULL') IS NULL
    BEGIN
    	ALTER TABLE PAS_IMPL.REPORT_CONTRACT
    	ADD STRATEGY_DESCRIPTION_FULL NVARCHAR(MAX)
    END
END
