IF OBJECT_ID(N'BFX_IMPL.CODE_TABLE_ITEM_HISTORY_ARCH', N'U') IS NOT NULL
	DROP TABLE BFX_IMPL.CODE_TABLE_ITEM_HISTORY_ARCH;
GO

CREATE TABLE [BFX_IMPL].[CODE_TABLE_ITEM_HISTORY_ARCH](
	[CODE_TABLE_ITEM_HISTORY_ID] [uniqueidentifier] NOT NULL,
	[CODE_TABLE_ITEM_ID] [uniqueidentifier] NOT NULL,
	[CODE] [nvarchar](64) NOT NULL,
	[BODY] [nvarchar](max) NOT NULL,
	[PUBLISHED_ARTIFACT_ID] [uniqueidentifier] NOT NULL,
	[SYS_CREATED_ON] [datetime] NOT NULL,
	[SYS_UPDATED_ON] [datetime] NOT NULL,
	[SYS_CLIENT_ID] [nvarchar](64) NOT NULL,
	[SYS_VERSION] [bigint] NOT NULL,
	[SYS_CREATED_BY_ID] [uniqueidentifier] NOT NULL,
	[SYS_UPDATED_BY_ID] [uniqueidentifier] NOT NULL,
	CONSTRAINT [PK_BFX_IMPL_CODE_TABLE_ITEM_HISTORY_ARCH] PRIMARY KEY NONCLUSTERED 
	(
		[CODE_TABLE_ITEM_HISTORY_ID] ASC
	)
)
GO

ALTER TABLE [BFX_IMPL].[CODE_TABLE_ITEM_HISTORY_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_BFX_IMPL_CODE_TABLE_ITEM_HISTORY_ARCH_CODE_TABLE_ITEM_ID] FOREIGN KEY([CODE_TABLE_ITEM_ID])
REFERENCES [BFX].[CODE_TABLE_ITEM] ([CODE_TABLE_ITEM_ID])
GO

ALTER TABLE [BFX_IMPL].[CODE_TABLE_ITEM_HISTORY_ARCH] CHECK CONSTRAINT [FK_BFX_IMPL_CODE_TABLE_ITEM_HISTORY_ARCH_CODE_TABLE_ITEM_ID]
GO

ALTER TABLE [BFX_IMPL].[CODE_TABLE_ITEM_HISTORY_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_CREATED_BFX_IMPL_CODE_TABLE_ITEM_HISTORY_ARCH] FOREIGN KEY([SYS_CREATED_BY_ID])
REFERENCES [ORG].[APPLICATION_USER] ([APPLICATION_USER_ID])
GO

ALTER TABLE [BFX_IMPL].[CODE_TABLE_ITEM_HISTORY_ARCH] CHECK CONSTRAINT [FK_CREATED_BFX_IMPL_CODE_TABLE_ITEM_HISTORY_ARCH]
GO

ALTER TABLE [BFX_IMPL].[CODE_TABLE_ITEM_HISTORY_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_UPDATED_BFX_IMPL_CODE_TABLE_ITEM_HISTORY_ARCH] FOREIGN KEY([SYS_UPDATED_BY_ID])
REFERENCES [ORG].[APPLICATION_USER] ([APPLICATION_USER_ID])
GO

ALTER TABLE [BFX_IMPL].[CODE_TABLE_ITEM_HISTORY_ARCH] CHECK CONSTRAINT [FK_UPDATED_BFX_IMPL_CODE_TABLE_ITEM_HISTORY_ARCH]
GO
