IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[PRODUCT_CONF]') AND TYPE IN (N'U'))
BEGIN
    IF COL_LENGTH('BFX_IMPL.PRODUCT_CONF','IS_PRODUCT_LINKED_TO_ASSET') IS NULL
    BEGIN
        ALTER TABLE BFX_IMPL.PRODUCT_CONF
        ADD IS_PRODUCT_LINKED_TO_ASSET BIT NULL
    END
END