if object_id(N'ACC_IMPL.PORTFOLIO_TRANSFER_HUB', N'U') is not null
	drop table ACC_IMPL.PORTFOLIO_TRANSFER_HUB;
GO

if object_id(N'ACC_IMPL.PORTFOLIO_TRANSFER_SAT', N'U') is not null
	drop table ACC_IMPL.PORTFOLIO_TRANSFER_SAT;
GO

if object_id(N'ACC_IMPL.PORTFOLIO_TRANSFER_ITEM_LINK', N'U') is not null
	drop table ACC_IMPL.PORTFOLIO_TRANSFER_ITEM_LINK;
go

if object_id(N'ACC_IMPL.PORTFOLIO_TRANSFER_ITEM_SAT', N'U') is not null
	drop table ACC_IMPL.PORTFOLIO_TRANSFER_ITEM_SAT;
GO

CREATE TABLE [ACC_IMPL].[PORTFOLIO_TRANSFER_HUB]
(
	[PORTFOLIO_TRANSFER_HKEY] [char](32) NOT NULL,
	[LOAD_DATE] [datetime2](7) NOT NULL,
	[RECORD_SOURCE] [varchar](50) NOT NULL,
	[PORTFOLIO_TRANSFER_NUMBER] [nvarchar](128) NOT NULL,
	CONSTRAINT [PK_ACC_IMPL_PORTFOLIO_TRANSFER_HUB] PRIMARY KEY NONCLUSTERED ([PORTFOLIO_TRANSFER_HKEY] ASC),
	CONSTRAINT [UQ_PORTFOLIO_TRANSFER_HUB] UNIQUE CLUSTERED ([PORTFOLIO_TRANSFER_NUMBER] ASC)
)
GO

CREATE TABLE [ACC_IMPL].PORTFOLIO_TRANSFER_SAT
(
	[PORTFOLIO_TRANSFER_HKEY] [char](32) NOT NULL,
	[LOAD_DATE] [datetime2](7) NOT NULL,
	[RECORD_SOURCE] [varchar](50) NOT NULL,
	[HASH_DIFF] [char](32) NOT NULL,
	[AGENT_TAB_NUMBER_FROM] NVARCHAR(MAX) NULL,
	[AGENT_TAB_NUMBER_TO] NVARCHAR(MAX) NULL,
	[SAD_NUMBER_FROM] NVARCHAR(MAX) NULL,
	[SAD_NUMBER_TO] NVARCHAR(MAX) NULL,
	[ISSUE_DATE] DATE NULL,
	[SERVICE_PROVIDER_CODE_FROM] NVARCHAR(128) NULL,
	[SERVICE_PROVIDER_CODE_TO] NVARCHAR(128) NULL,
	[SERVICE_PROVIDER_NAME_FROM] NVARCHAR(128) NULL,
	[SERVICE_PROVIDER_NAME_TO] NVARCHAR(128) NULL,
	[AA_NUMBER_FROM] NVARCHAR(50) NULL,
	[AA_NUMBER_TO] NVARCHAR(50) NULL,
	[DOCUMENT_STATE] NVARCHAR(128) NULL,
	CONSTRAINT [PK_ACC_IMPL_PORTFOLIO_TRANSFER_SAT] PRIMARY KEY NONCLUSTERED
	(
		[PORTFOLIO_TRANSFER_HKEY] ASC,
		[LOAD_DATE] ASC
	)
)
GO

CREATE TABLE [ACC_IMPL].[PORTFOLIO_TRANSFER_ITEM_LINK]
(
	[PORTFOLIO_TRANSFER_ITEM_HKEY] [char](32) NOT NULL,
	[LOAD_DATE] [datetime2](7) NOT NULL,
	[RECORD_SOURCE] [varchar](50) NOT NULL,
	[CONTRACT_NUMBER] [nvarchar](50) NOT NULL,
	[DUE_DATE] [date] NOT NULL,
	[PORTFOLIO_TRANSFER_HKEY] [char](32) NOT NULL,
	CONSTRAINT [PK_ACC_IMPL_PORTFOLIO_TRANSFER_ITEM_LINK] PRIMARY KEY NONCLUSTERED ([PORTFOLIO_TRANSFER_ITEM_HKEY] ASC),
	CONSTRAINT [UQ_PORTFOLIO_TRANSFER_ITEM_LINK] UNIQUE NONCLUSTERED
	(
		[PORTFOLIO_TRANSFER_HKEY] ASC,
		[CONTRACT_NUMBER] ASC,
		[DUE_DATE] ASC
	)
)
GO

CREATE TABLE [ACC_IMPL].[PORTFOLIO_TRANSFER_ITEM_SAT]
(
	[PORTFOLIO_TRANSFER_ITEM_HKEY] [char](32) NOT NULL,
	[LOAD_DATE] [datetime2](7) NOT NULL,
	[RECORD_SOURCE] [varchar](50) NOT NULL,
	[HASH_DIFF] [char](32) NOT NULL,
	[IS_DELETED] [bit] NULL,
	[START_DATE] DATE NOT NULL,
	[CONTRACT_STATE] NVARCHAR(128) NOT NULL,
	[TRANSFER_STATE] NVARCHAR(64) NULL,
	[HOLDER_NAME] NVARCHAR(100) NOT NULL,
	[PRODUCT_DESC] NVARCHAR(256) NOT NULL,
	[CODE_NAME] NVARCHAR(64) NOT NULL,
	[USERNAME] NVARCHAR(64) NOT NULL,
	CONSTRAINT [PK_ACC_IMPL_PORTFOLIO_TRANSFER_ITEM_SAT] PRIMARY KEY NONCLUSTERED
	(
		[PORTFOLIO_TRANSFER_ITEM_HKEY] ASC,
		[LOAD_DATE] ASC
	)
)
GO