IF OBJECT_ID(N'BFX_IMPL.ATTACHMENT_ARCH', N'U') IS NOT NULL
	DROP TABLE BFX_IMPL.ATTACHMENT_ARCH;
GO

CREATE TABLE [BFX_IMPL].[ATTACHMENT_ARCH](
	[ATTACHMENT_ID] [uniqueidentifier] NOT NULL,
	[ATTACHMENT_TYPE] [nvarchar](120) NULL,
	[NAME] [nvarchar](250) NULL,
	[DESCRIPTION] [nvarchar](250) NULL,
	[DMS_LOCATION] [nvarchar](250) NULL,
	[FILE_METADATA_ID] [uniqueidentifier] NULL,
	[UPLOAD_STATUS] [int] NOT NULL,
	[STATUS] [int] NULL,
	[MEDIA_TYPE] [nvarchar](100) NULL,
	[RECEIPT_DATE] [datetime] NULL,
	[SYS_CREATED_ON] [datetime] NOT NULL,
	[SYS_UPDATED_ON] [datetime] NOT NULL,
	[SYS_CLIENT_ID] [nvarchar](64) NOT NULL,
	[SYS_VERSION] [bigint] NOT NULL,
	[SYS_CREATED_BY_ID] [uniqueidentifier] NOT NULL,
	[SYS_UPDATED_BY_ID] [uniqueidentifier] NOT NULL,
	CONSTRAINT [PK_BFX_IMPL_ATTACHMENT_ARCH] PRIMARY KEY NONCLUSTERED 
	(
		[ATTACHMENT_ID] ASC
	)
)
GO

ALTER TABLE [BFX_IMPL].[ATTACHMENT_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_CREATED_BFX_IMPL_ATTACHMENT_ARCH] FOREIGN KEY([SYS_CREATED_BY_ID])
REFERENCES [ORG].[APPLICATION_USER] ([APPLICATION_USER_ID])
GO

ALTER TABLE [BFX_IMPL].[ATTACHMENT_ARCH] CHECK CONSTRAINT [FK_CREATED_BFX_IMPL_ATTACHMENT_ARCH]
GO

ALTER TABLE [BFX_IMPL].[ATTACHMENT_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_UPDATED_BFX_IMPL_ATTACHMENT_ARCH] FOREIGN KEY([SYS_UPDATED_BY_ID])
REFERENCES [ORG].[APPLICATION_USER] ([APPLICATION_USER_ID])
GO

ALTER TABLE [BFX_IMPL].[ATTACHMENT_ARCH] CHECK CONSTRAINT [FK_UPDATED_BFX_IMPL_ATTACHMENT_ARCH]
GO
