IF
	EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[RISKS]') AND TYPE IN (N'U'))
	AND
	NOT EXISTS (SELECT * FROM sys.columns WHERE Name = N'FNS_TYPE' AND Object_ID = Object_ID(N'[BFX_IMPL].[RISKS]'))
BEGIN
	ALTER TABLE BFX_IMPL.RISKS ADD FNS_TYPE NVARCHAR(255)
END
GO

IF
	EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[RISKS]') AND TYPE IN (N'U'))
	AND
	EXISTS (SELECT * FROM sys.columns WHERE Name = N'FNS_TYPE' AND Object_ID = Object_ID(N'[BFX_IMPL].[RISKS]'))
BEGIN
	ALTER TABLE BFX_IMPL.RISKS WITH CHECK ADD CONSTRAINT [FK_BFX_IMPL_RISKS_FNS_TYPE] FOREIGN KEY([FNS_TYPE])
	REFERENCES [BFX_IMPL].[RISK_TYPE] ([RISK_TYPE])
END
GO