IF OBJECT_ID(N'BFX_IMPL.INTEGRATION_MESSAGE_GROUP_ARCH', N'U') IS NOT NULL
	DROP TABLE BFX_IMPL.INTEGRATION_MESSAGE_GROUP_ARCH;
GO

CREATE TABLE [BFX_IMPL].[INTEGRATION_MESSAGE_GROUP_ARCH](
	[MESSAGE_GROUP] [nvarchar](256) NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
	[STATUS] [int] NOT NULL,
	[SYS_CREATED_ON] [datetime] NOT NULL,
	[SYS_CREATED_BY_ID] [uniqueidentifier] NOT NULL,
	[SYS_UPDATED_ON] [datetime] NOT NULL,
	[SYS_UPDATED_BY_ID] [uniqueidentifier] NOT NULL,
	[SYS_CLIENT_ID] [nvarchar](64) NOT NULL,
	[SYS_VERSION] [bigint] NOT NULL,
	[LAST_PROCESSED_TIMESTAMP] [datetime2](7) NULL
)
GO