IF 
    EXISTS (SELECT * FROM SYS.OBJECTS WHERE object_id = OBJECT_ID(N'[PAS_IMPL].[AA_BASE_COMM_SAT]') AND TYPE IN (N'U'))
    AND
    NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[PAS_IMPL].[AA_BASE_COMM_SAT]') AND name = 'INSURANCE_YEAR_TO')
BEGIN
	ALTER TABLE [PAS_IMPL].[AA_BASE_COMM_SAT]
	ADD INSURANCE_YEAR_TO INT NULL 
END
GO

IF 
    EXISTS (SELECT * FROM SYS.OBJECTS WHERE object_id = OBJECT_ID(N'[PAS_IMPL].[AA_BASE_COMM_SAT]') AND TYPE IN (N'U'))
    AND
    EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[PAS_IMPL].[AA_BASE_COMM_SAT]') AND name = 'INSURANCE_YEAR')
BEGIN
	UPDATE [PAS_IMPL].[AA_BASE_COMM_SAT] 
	SET INSURANCE_YEAR_TO = aa.INSURANCE_YEAR
	FROM [PAS_IMPL].[AA_BASE_COMM_SAT] aa

	EXEC sp_rename '[PAS_IMPL].[AA_BASE_COMM_SAT].INSURANCE_YEAR', 'INSURANCE_YEAR_FROM', 'COLUMN';
END
GO

IF 
    EXISTS (SELECT * FROM SYS.OBJECTS WHERE object_id = OBJECT_ID(N'[PAS_IMPL].[AA_BASE_COMM_SAT]') AND TYPE IN (N'U'))
    AND
    NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[PAS_IMPL].[AA_BASE_COMM_SAT]') AND name = 'INSURANCE_YEAR_INCLUDE_FROM')
BEGIN
	ALTER TABLE [PAS_IMPL].[AA_BASE_COMM_SAT]
	ADD INSURANCE_YEAR_INCLUDE_FROM BIT NULL;
END
GO

IF 
    EXISTS (SELECT * FROM SYS.OBJECTS WHERE object_id = OBJECT_ID(N'[PAS_IMPL].[AA_BASE_COMM_SAT]') AND TYPE IN (N'U'))
    AND
    EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[PAS_IMPL].[AA_BASE_COMM_SAT]') AND name = 'INSURANCE_YEAR_INCLUDE_FROM')
BEGIN
	UPDATE [PAS_IMPL].[AA_BASE_COMM_SAT]
	SET INSURANCE_YEAR_INCLUDE_FROM = 1
	WHERE INSURANCE_YEAR_INCLUDE_FROM IS NULL
END
GO

IF 
    EXISTS (SELECT * FROM SYS.OBJECTS WHERE object_id = OBJECT_ID(N'[PAS_IMPL].[AA_BASE_COMM_SAT]') AND TYPE IN (N'U'))
    AND
    NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[PAS_IMPL].[AA_BASE_COMM_SAT]') AND name = 'INSURANCE_YEAR_INCLUDE_TO')
BEGIN
	ALTER TABLE [PAS_IMPL].[AA_BASE_COMM_SAT]
	ADD INSURANCE_YEAR_INCLUDE_TO BIT NULL
END
GO

IF 
    EXISTS (SELECT * FROM SYS.OBJECTS WHERE object_id = OBJECT_ID(N'[PAS_IMPL].[AA_BASE_COMM_SAT]') AND TYPE IN (N'U'))
    AND
    EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[PAS_IMPL].[AA_BASE_COMM_SAT]') AND name = 'INSURANCE_YEAR_INCLUDE_TO')
BEGIN
	UPDATE [PAS_IMPL].[AA_BASE_COMM_SAT]
	SET INSURANCE_YEAR_INCLUDE_TO = 1
	WHERE INSURANCE_YEAR_INCLUDE_TO IS NULL
END
GO
