IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[EWT_IMPL].[EWT_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('EWT_IMPL.EWT_SAT','FIXED_EXCH_RATE') IS NULL
BEGIN
ALTER TABLE EWT_IMPL.EWT_SAT ADD FIXED_EXCH_RATE decimal(15,7)
END

IF COL_LENGTH('EWT_IMPL.EWT_SAT','USE_FIXED_EXCH_RATE') IS NULL
BEGIN
ALTER TABLE EWT_IMPL.EWT_SAT ADD USE_FIXED_EXCH_RATE bit
END

END