IF OBJECT_ID(N'PTY_IMPL.PARTY_HISTORY_ARCH', N'U') IS NOT NULL
	DROP TABLE PTY_IMPL.PARTY_HISTORY_ARCH;
GO

CREATE TABLE [PTY_IMPL].[PARTY_HISTORY_ARCH](
	[PARTY_HISTORY_ID] [uniqueidentifier] NOT NULL,
	[PARTY_ID] [uniqueidentifier] NOT NULL,
	[BODY] [nvarchar](max) NOT NULL,
	[COMMON_BODY] [nvarchar](max) NOT NULL,
	[PUBLISHED_ARTIFACT_ID] [uniqueidentifier] NOT NULL,
	[SYS_CREATED_ON] [datetime] NOT NULL,
	[SYS_UPDATED_ON] [datetime] NOT NULL,
	[SYS_CLIENT_ID] [nvarchar](64) NOT NULL,
	[SYS_VERSION] [bigint] NOT NULL,
	[PARTY_CODE] [nvarchar](64) NOT NULL,
	[SYS_CREATED_BY_ID] [uniqueidentifier] NOT NULL,
	[SYS_UPDATED_BY_ID] [uniqueidentifier] NOT NULL,
	[DUPLICATE_MASTER_ID] [uniqueidentifier] NULL,
	CONSTRAINT [PK_PTY_IMPL_PARTY_HISTORY_ARCH] PRIMARY KEY NONCLUSTERED 
	(
		[PARTY_HISTORY_ID] ASC
	)
)
GO

ALTER TABLE [PTY_IMPL].[PARTY_HISTORY_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_CREATED_PTY_IMPL_PARTY_HISTORY_ARCH] FOREIGN KEY([SYS_CREATED_BY_ID])
REFERENCES [ORG].[APPLICATION_USER] ([APPLICATION_USER_ID])
GO

ALTER TABLE [PTY_IMPL].[PARTY_HISTORY_ARCH] CHECK CONSTRAINT [FK_CREATED_PTY_IMPL_PARTY_HISTORY_ARCH]
GO

ALTER TABLE [PTY_IMPL].[PARTY_HISTORY_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_PTY_IMPL_PARTY_HIS_ARCH_CFX_PUBL_ART] FOREIGN KEY([PUBLISHED_ARTIFACT_ID])
REFERENCES [CFX].[PUBLISHED_ARTIFACT] ([PUBLISHED_ARTIFACT_ID])
GO

ALTER TABLE [PTY_IMPL].[PARTY_HISTORY_ARCH] CHECK CONSTRAINT [FK_PTY_IMPL_PARTY_HIS_ARCH_CFX_PUBL_ART]
GO

ALTER TABLE [PTY_IMPL].[PARTY_HISTORY_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_PTY_IMPL_PARTY_HISTORY_ARCH_DUPLICATE_MASTER] FOREIGN KEY([DUPLICATE_MASTER_ID])
REFERENCES [PTY].[PARTY] ([PARTY_ID])
GO

ALTER TABLE [PTY_IMPL].[PARTY_HISTORY_ARCH] CHECK CONSTRAINT [FK_PTY_IMPL_PARTY_HISTORY_ARCH_DUPLICATE_MASTER]
GO

ALTER TABLE [PTY_IMPL].[PARTY_HISTORY_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_PTY_IMPL_PARTY_HISTORY_ARCH_PARTY] FOREIGN KEY([PARTY_ID])
REFERENCES [PTY].[PARTY] ([PARTY_ID])
GO

ALTER TABLE [PTY_IMPL].[PARTY_HISTORY_ARCH] CHECK CONSTRAINT [FK_PTY_IMPL_PARTY_HISTORY_ARCH_PARTY]
GO

ALTER TABLE [PTY_IMPL].[PARTY_HISTORY_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_UPDATED_PTY_IMPL_PARTY_HISTORY_ARCH] FOREIGN KEY([SYS_UPDATED_BY_ID])
REFERENCES [ORG].[APPLICATION_USER] ([APPLICATION_USER_ID])
GO

ALTER TABLE [PTY_IMPL].[PARTY_HISTORY_ARCH] CHECK CONSTRAINT [FK_UPDATED_PTY_IMPL_PARTY_HISTORY_ARCH]
GO
