IF OBJECT_ID(N'BFX_IMPL.INTEGRATION_MESSAGE_ERROR_ARCH', N'U') IS NOT NULL
	DROP TABLE BFX_IMPL.INTEGRATION_MESSAGE_ERROR_ARCH;
GO

CREATE TABLE [BFX_IMPL].[INTEGRATION_MESSAGE_ERROR_ARCH](
	[INTEGRATION_MESSAGE_ID] [uniqueidentifier] NOT NULL,
	[SERVICE_MESSAGE_ID] [uniqueidentifier] NOT NULL,
	[MESSAGE_GROUP] [nvarchar](256) NOT NULL,
	[MESSAGE_TYPE] [nvarchar](512) NOT NULL,
	[ENTITY_TYPE] [nvarchar](256) NULL,
	[EVENT_TYPE] [nvarchar](256) NOT NULL,
	[MESSAGE_BODY] [nvarchar](max) NOT NULL,
	[PROCESSED_ROUTES] [nvarchar](1024) NULL,
	[FAILED_ROUTES] [nvarchar](1024) NULL,
	[ERROR_TYPE] [nvarchar](512) NOT NULL,
	[ERROR_DETAIL] [nvarchar](max) NULL,
	[SYS_CREATED_ON] [datetime] NOT NULL,
	[SYS_CREATED_BY_ID] [uniqueidentifier] NOT NULL,
	[SYS_UPDATED_ON] [datetime] NOT NULL,
	[SYS_UPDATED_BY_ID] [uniqueidentifier] NOT NULL,
	[SYS_CLIENT_ID] [nvarchar](64) NOT NULL,
	[SYS_VERSION] [bigint] NOT NULL,
	[STATUS] [int] NULL,
	[ORIGINATING_SERVICE_MESSAGE_ID] [uniqueidentifier] NULL,
	[TIMESTAMP] [datetime] NULL,
	[RECORD_ID] [uniqueidentifier] NULL,
	CONSTRAINT [PK_BFX_IMPL_INTEGRATION_MESSAGE_ARCH_ERROR] PRIMARY KEY NONCLUSTERED 
	(
		[INTEGRATION_MESSAGE_ID] ASC
	)
)
GO