alter table PAS_IMPL.COLLECTIVE_POLICY_RISK_DATA_EXP alter column REINS_RATE decimal(10,8)

alter table PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST add REINSURER_CODE nvarchar(32)

alter table PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST add REINSURER_NAME nvarchar(256)

alter table PAS_IMPL.COLLECTIVE_POLICY_INSURED_LIST add REINSURER_SHARE decimal(10,8)