if object_id(N'PAS_IMPL.CF_POLICY_SAT', N'U') is not null
	drop table PAS_IMPL.CF_POLICY_SAT;
go

CREATE TABLE [PAS_IMPL].[CF_POLICY_SAT](
	[CF_POLICY_HKEY] [char](32) NOT NULL,
	[LOAD_DATE] [datetime2](7) NOT NULL,
	[RECORD_SOURCE] [varchar](50) NOT NULL,
	[HASH_DIFF] [char](32) NOT NULL,
	[PRODUCT_DESCRIPTION] [nvarchar](max) NULL,
	[CF_POLICY] [nvarchar](50) NOT NULL,
	[CF_POLICY_ORIGINAL] [nvarchar](50) NOT NULL,
	CONSTRAINT [PK_PAS_IMPL_CF_POLICY_SAT] PRIMARY KEY NONCLUSTERED 
	(
		[CF_POLICY_HKEY] ASC,
		[LOAD_DATE] ASC
	)
)

CREATE INDEX IDX_CF_POLICY_SAT_CF_POLICY_ORIGINAL ON PAS_IMPL.CF_POLICY_SAT(CF_POLICY_ORIGINAL)