IF OBJECT_ID(N'BFX_IMPL.ETL_EXECUTION_STATUS_ARCH', N'U') IS NOT NULL
	DROP TABLE BFX_IMPL.ETL_EXECUTION_STATUS_ARCH;
GO

CREATE TABLE [BFX_IMPL].[ETL_EXECUTION_STATUS_ARCH](
	[ETL_EXECUTION_STATUS_ID] [uniqueidentifier] NOT NULL,
	[CONFIGURATION_NAME] [nvarchar](128) NOT NULL,
	[VERSION] [nvarchar](2) NOT NULL,
	[BODY] [nvarchar](max) NOT NULL,
	[BODY_HASH] [nvarchar](32) NOT NULL,
	[STATUS] [int] NOT NULL,
	[SYS_CREATED_ON] [datetime] NOT NULL,
	[SYS_UPDATED_ON] [datetime] NOT NULL,
	[SYS_CLIENT_ID] [nvarchar](64) NOT NULL,
	[SYS_VERSION] [bigint] NOT NULL,
	[SYS_CREATED_BY_ID] [uniqueidentifier] NOT NULL,
	[SYS_UPDATED_BY_ID] [uniqueidentifier] NOT NULL,
	[PROCESSING_MESSAGE] [nvarchar](max) NULL,
	CONSTRAINT [PK_BFX_IMPL_ETL_EXECUTION_STATUS_ARCH] PRIMARY KEY NONCLUSTERED 
	(
		[ETL_EXECUTION_STATUS_ID] ASC
	)
)
GO

ALTER TABLE [BFX_IMPL].[ETL_EXECUTION_STATUS_ARCH] ADD  DEFAULT (newid()) FOR [ETL_EXECUTION_STATUS_ID]
GO
