IF OBJECT_ID(N'BFX_IMPL.AUDIT_TRAIL_ARCH', N'U') IS NOT NULL
	DROP TABLE BFX_IMPL.AUDIT_TRAIL_ARCH;
GO

CREATE TABLE [BFX_IMPL].[AUDIT_TRAIL_ARCH](
	[AUDIT_TRAIL_ID] [uniqueidentifier] NOT NULL,
	[USERNAME] [nvarchar](64) NOT NULL,
	[EVENT_TIMESTAMP] [datetime] NOT NULL,
	[IP] [nvarchar](64) NULL,
	[DOMAIN] [nvarchar](64) NOT NULL,
	[EVENT_TYPE] [nvarchar](128) NOT NULL,
	[BODY] [nvarchar](max) NULL,
	[SYS_CREATED_ON] [datetime] NOT NULL,
	[SYS_CREATED_BY_ID] [uniqueidentifier] NOT NULL,
	[SYS_UPDATED_ON] [datetime] NOT NULL,
	[SYS_UPDATED_BY_ID] [uniqueidentifier] NOT NULL,
	[SYS_CLIENT_ID] [nvarchar](128) NOT NULL,
	[SYS_VERSION] [bigint] NOT NULL,
	[SYS_TENANT_ID] [uniqueidentifier] NULL,
	CONSTRAINT [PK_BFX_IMPL_AUDIT_TRAIL_ARCH] PRIMARY KEY NONCLUSTERED 
	(
		[AUDIT_TRAIL_ID] ASC
	)
)
GO