IF
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[SEND_EVENT]'))
AND
EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'EVENT_TYPE' AND OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[SEND_EVENT]'))
BEGIN
	ALTER TABLE BFX_IMPL.SEND_EVENT
	ALTER COLUMN EVENT_TYPE NVARCHAR(64) NOT NULL
END
GO

IF
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[SEND_EVENT_HISTORY]'))
AND
EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'EVENT_TYPE' AND OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[SEND_EVENT_HISTORY]'))
BEGIN
	ALTER TABLE BFX_IMPL.SEND_EVENT_HISTORY
	ALTER COLUMN EVENT_TYPE NVARCHAR(64) NOT NULL
END
GO