IF
EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[PAS_IMPL].[ASSET_CONDITION_SAT]'))
AND
EXISTS (SELECT 1 FROM sys.columns WHERE NAME = N'LIMIT')
BEGIN
	ALTER TABLE PAS_IMPL.ASSET_CONDITION_SAT 
    ALTER COLUMN [LIMIT] decimal(15,2) NULL
END
GO