IF OBJECT_ID(N'BFX_IMPL.ATTACHMENT_RELATED_ENTITY_ARCH', N'U') IS NOT NULL
	DROP TABLE BFX_IMPL.ATTACHMENT_RELATED_ENTITY_ARCH;
GO

CREATE TABLE [BFX_IMPL].[ATTACHMENT_RELATED_ENTITY_ARCH](
	[ATTACHMENT_RELATED_ENTITY_ID] [uniqueidentifier] NOT NULL,
	[ATTACHMENT_ID] [uniqueidentifier] NOT NULL,
	[ENTITY_REF_ID] [uniqueidentifier] NOT NULL,
	[REFERENCE] [nvarchar](max) NULL,
	[IS_PRIMARY_ASSOCIATION] [bit] NULL,
	[SYS_CREATED_ON] [datetime] NOT NULL,
	[SYS_UPDATED_ON] [datetime] NOT NULL,
	[SYS_CLIENT_ID] [nvarchar](64) NOT NULL,
	[SYS_CREATED_BY_ID] [uniqueidentifier] NOT NULL,
	[SYS_UPDATED_BY_ID] [uniqueidentifier] NOT NULL,
    CONSTRAINT [PK_BFX_IMPL_ATT_REL_ENT_ARCH] PRIMARY KEY NONCLUSTERED 
    (
        [ATTACHMENT_RELATED_ENTITY_ID] ASC
    )
)
GO
