IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[DECLARATION_SPORT_QUESTIONS]') AND TYPE IN (N'U'))
BEGIN
    DROP TABLE [BFX_IMPL].[DECLARATION_SPORT_QUESTIONS]
END
GO

CREATE TABLE [BFX_IMPL].[DECLARATION_SPORT_QUESTIONS] (
    [ID] [UNIQUEIDENTIFIER] NOT NULL,
    [ITEM_TEXT] NVARCHAR(MAX) NOT NULL,
PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[DECLARATION_SPORT]') AND TYPE IN (N'U'))
BEGIN
    DROP TABLE [BFX_IMPL].[DECLARATION_SPORT]
END
GO

CREATE TABLE [BFX_IMPL].[DECLARATION_SPORT](
	[ID] [uniqueidentifier] NOT NULL,
	[PRODUCT_CODE] [nvarchar](max) NOT NULL,
	[ITEM_NUMBER] [nvarchar](max) NOT NULL,
	[ITEM_TEXT_ID] [nvarchar](255) NOT NULL,
	[DEPARTAMENT] [nvarchar](255) NOT NULL,
	[ACTIVE_FROM_DATE] [date] NOT NULL DEFAULT ('1900-01-01'),
	[ACTIVE_TO_DATE] [date] NOT NULL DEFAULT ('2099-01-01'),
PRIMARY KEY CLUSTERED (	[ID] ASC) 
)