IF OBJECT_ID(N'ORG_IMPL.APPLICATION_USER_GROUP_ASSIGNMENT_HISTORY_ARCH', N'U') IS NOT NULL
	DROP TABLE ORG_IMPL.APPLICATION_USER_GROUP_ASSIGNMENT_HISTORY_ARCH;
GO

CREATE TABLE [ORG_IMPL].[APPLICATION_USER_GROUP_ASSIGNMENT_HISTORY_ARCH](
	[APPLICATION_USER_GROUP_ASSIGNMENT_HISTORY_ID] [uniqueidentifier] NOT NULL,
	[APPLICATION_USER_GROUP_ID] [uniqueidentifier] NOT NULL,
	[APPLICATION_USER_ID] [uniqueidentifier] NOT NULL,
	[ASSIGNMENT_CREATED_DATE] [datetime] NOT NULL,
	[ASSIGNMENT_DELETED_DATE] [datetime] NULL,
	[SYS_CREATED_ON] [datetime] NOT NULL,
	[SYS_CREATED_BY_ID] [uniqueidentifier] NOT NULL,
	[SYS_UPDATED_ON] [datetime] NOT NULL,
	[SYS_UPDATED_BY_ID] [uniqueidentifier] NOT NULL,
	[SYS_CLIENT_ID] [nvarchar](64) NOT NULL,
	[SYS_VERSION] [bigint] NOT NULL,
	CONSTRAINT [PK_ORG_IMPL_AUGAH_ARCH] PRIMARY KEY CLUSTERED 
	(
		[APPLICATION_USER_GROUP_ASSIGNMENT_HISTORY_ID] ASC
	)
)
GO

ALTER TABLE [ORG_IMPL].[APPLICATION_USER_GROUP_ASSIGNMENT_HISTORY_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_ORG_IMPL_AUGAH_ARCH_APPLICATION_GROUP] FOREIGN KEY([APPLICATION_USER_GROUP_ID])
REFERENCES [ORG].[APPLICATION_USER_GROUP] ([APPLICATION_USER_GROUP_ID])
GO

ALTER TABLE [ORG_IMPL].[APPLICATION_USER_GROUP_ASSIGNMENT_HISTORY_ARCH] CHECK CONSTRAINT [FK_ORG_IMPL_AUGAH_ARCH_APPLICATION_GROUP]
GO

ALTER TABLE [ORG_IMPL].[APPLICATION_USER_GROUP_ASSIGNMENT_HISTORY_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_ORG_IMPL_AUGAH_ARCH_APPLICATION_USER] FOREIGN KEY([APPLICATION_USER_ID])
REFERENCES [ORG].[APPLICATION_USER] ([APPLICATION_USER_ID])
GO

ALTER TABLE [ORG_IMPL].[APPLICATION_USER_GROUP_ASSIGNMENT_HISTORY_ARCH] CHECK CONSTRAINT [FK_ORG_IMPL_AUGAH_ARCH_APPLICATION_USER]
GO

ALTER TABLE [ORG_IMPL].[APPLICATION_USER_GROUP_ASSIGNMENT_HISTORY_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_ORG_IMPL_AUGAH_ARCH_CREATED_BY] FOREIGN KEY([SYS_CREATED_BY_ID])
REFERENCES [ORG].[APPLICATION_USER] ([APPLICATION_USER_ID])
GO

ALTER TABLE [ORG_IMPL].[APPLICATION_USER_GROUP_ASSIGNMENT_HISTORY_ARCH] CHECK CONSTRAINT [FK_ORG_IMPL_AUGAH_ARCH_CREATED_BY]
GO

ALTER TABLE [ORG_IMPL].[APPLICATION_USER_GROUP_ASSIGNMENT_HISTORY_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_ORG_IMPL_AUGAH_ARCH_UPDATED_BY] FOREIGN KEY([SYS_UPDATED_BY_ID])
REFERENCES [ORG].[APPLICATION_USER] ([APPLICATION_USER_ID])
GO

ALTER TABLE [ORG_IMPL].[APPLICATION_USER_GROUP_ASSIGNMENT_HISTORY_ARCH] CHECK CONSTRAINT [FK_ORG_IMPL_AUGAH_ARCH_UPDATED_BY]
GO
