IF OBJECT_ID(N'PAS_IMPL.CONTRACT_HISTORY_ARCH', N'U') IS NOT NULL
	DROP TABLE PAS_IMPL.CONTRACT_HISTORY_ARCH;
GO

CREATE TABLE [PAS_IMPL].[CONTRACT_HISTORY_ARCH](
	[CONTRACT_HISTORY_ID] [uniqueidentifier] NOT NULL,
	[CONTRACT_ID] [uniqueidentifier] NOT NULL,
	[CONTRACT_NUMBER] [nvarchar](64) NOT NULL,
	[BODY] [nvarchar](max) NOT NULL,
	[STATE_ID] [int] NOT NULL,
	[PUBLISHED_ARTIFACT_ID] [uniqueidentifier] NOT NULL,
	[CASE_ID] [uniqueidentifier] NULL,
	[SYS_CREATED_ON] [datetime] NOT NULL,
	[SYS_UPDATED_ON] [datetime] NOT NULL,
	[SYS_CLIENT_ID] [nvarchar](64) NOT NULL,
	[SYS_VERSION] [bigint] NOT NULL,
	[COMMON_BODY] [nvarchar](max) NULL,
	[SNAPSHOT_BODY] [nvarchar](max) NULL,
	[SEQ_NUMBER] [int] NOT NULL,
	[ORIGINAL_DOCUMENT_ID] [uniqueidentifier] NOT NULL,
	[PREVIOUS_DOCUMENT_ID] [uniqueidentifier] NULL,
	[VALID_FROM] [datetime] NULL,
	[VALID_TO] [datetime] NULL,
	[SOURCE_ENTITY_ID] [uniqueidentifier] NULL,
	[SOURCE_ENTITY_TYPE_ID] [uniqueidentifier] NULL,
	[VERSION_STATE] [nvarchar](64) NULL,
	[SYS_CREATED_BY_ID] [uniqueidentifier] NOT NULL,
	[SYS_UPDATED_BY_ID] [uniqueidentifier] NOT NULL,
	CONSTRAINT [PK_PAS_IMPL_CONTRACT_HISTORY_ARCH] PRIMARY KEY NONCLUSTERED 
	(
		[CONTRACT_HISTORY_ID] ASC
	)
)
GO

ALTER TABLE [PAS_IMPL].[CONTRACT_HISTORY_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_PAS_IMPL_CONTRACT_HISTORY_ARCH_CASE_ID] FOREIGN KEY([CASE_ID])
REFERENCES [CFX].[BUSINESS_CASE] ([CASE_ID])
GO

ALTER TABLE [PAS_IMPL].[CONTRACT_HISTORY_ARCH] CHECK CONSTRAINT [FK_PAS_IMPL_CONTRACT_HISTORY_ARCH_CASE_ID]
GO

ALTER TABLE [PAS_IMPL].[CONTRACT_HISTORY_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_PAS_IMPL_CONTRACT_HISTORY_ARCH_CONTRACT] FOREIGN KEY([CONTRACT_ID])
REFERENCES [PAS].[CONTRACT] ([CONTRACT_ID])
GO

ALTER TABLE [PAS_IMPL].[CONTRACT_HISTORY_ARCH] CHECK CONSTRAINT [FK_PAS_IMPL_CONTRACT_HISTORY_ARCH_CONTRACT]
GO

ALTER TABLE [PAS_IMPL].[CONTRACT_HISTORY_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_PAS_IMPL_CONTRACT_HISTORY_ARCH_CREATED_BY_ID] FOREIGN KEY([SYS_CREATED_BY_ID])
REFERENCES [ORG].[APPLICATION_USER] ([APPLICATION_USER_ID])
GO

ALTER TABLE [PAS_IMPL].[CONTRACT_HISTORY_ARCH] CHECK CONSTRAINT [FK_PAS_IMPL_CONTRACT_HISTORY_ARCH_CREATED_BY_ID]
GO

ALTER TABLE [PAS_IMPL].[CONTRACT_HISTORY_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_PAS_IMPL_CONTRACT_HISTORY_ARCH_PUBLISHED_ARTIFACT] FOREIGN KEY([PUBLISHED_ARTIFACT_ID])
REFERENCES [CFX].[PUBLISHED_ARTIFACT] ([PUBLISHED_ARTIFACT_ID])
GO

ALTER TABLE [PAS_IMPL].[CONTRACT_HISTORY_ARCH] CHECK CONSTRAINT [FK_PAS_IMPL_CONTRACT_HISTORY_ARCH_PUBLISHED_ARTIFACT]
GO

ALTER TABLE [PAS_IMPL].[CONTRACT_HISTORY_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_PAS_IMPL_CONTRACT_HISTORY_ARCH_UPDATED_BY_ID] FOREIGN KEY([SYS_UPDATED_BY_ID])
REFERENCES [ORG].[APPLICATION_USER] ([APPLICATION_USER_ID])
GO

ALTER TABLE [PAS_IMPL].[CONTRACT_HISTORY_ARCH] CHECK CONSTRAINT [FK_PAS_IMPL_CONTRACT_HISTORY_ARCH_UPDATED_BY_ID]
GO
