IF OBJECT_ID(N'BFX_IMPL.NOTIFICATION_MAILBOX_ARCH', N'U') IS NOT NULL
	DROP TABLE BFX_IMPL.NOTIFICATION_MAILBOX_ARCH;
GO

CREATE TABLE [BFX_IMPL].[NOTIFICATION_MAILBOX_ARCH](
	[NOTIFICATION_ID] [uniqueidentifier] NOT NULL,
	[ORIGINATING_NOTIFICATION_ID] [uniqueidentifier] NULL,
	[PUBLISHED_ARTIFACT_ID] [uniqueidentifier] NOT NULL,
	[ORIGINATING_APPLICATION_USER_ID] [uniqueidentifier] NOT NULL,
	[TARGET_APPLICATION_USER_ID] [uniqueidentifier] NULL,
	[NOTIFICATION_STATE] [nvarchar](64) NOT NULL,
	[NOTIFICATION_PRIORITY] [nvarchar](64) NOT NULL,
	[NOTIFICATION_TYPE] [nvarchar](64) NOT NULL,
	[NOTIFICATION_CREATED_ON] [datetime] NOT NULL,
	[SUBJECT] [nvarchar](max) NULL,
	[CONTENT] [nvarchar](max) NULL,
	[ENTITY_REF_ID] [uniqueidentifier] NULL,
	[NOTIFICATION_END_TIME] [datetime] NULL,
	[IS_SYSTEM_NOTIFICATION] [bit] NOT NULL,
	[IS_DELETED] [bit] NOT NULL,
	[SYS_CREATED_ON] [datetime] NOT NULL,
	[SYS_UPDATED_ON] [datetime] NOT NULL,
	[SYS_CREATED_BY_ID] [uniqueidentifier] NOT NULL,
	[SYS_UPDATED_BY_ID] [uniqueidentifier] NOT NULL,
	[SYS_CLIENT_ID] [nvarchar](64) NOT NULL,
	[SYS_VERSION] [bigint] NOT NULL,
	[SYS_TENANT_ID] [uniqueidentifier] NULL,
	CONSTRAINT [PK__BFX_IMPL_NOTIFICATION_MAILBOX_ARCH_ID] PRIMARY KEY CLUSTERED 
	(
		[NOTIFICATION_ID] ASC
	)
)
GO

ALTER TABLE [BFX_IMPL].[NOTIFICATION_MAILBOX_ARCH] ADD  DEFAULT ((0)) FOR [IS_DELETED]
GO

ALTER TABLE [BFX_IMPL].[NOTIFICATION_MAILBOX_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_BFX_IMPL_NOTIFICATION_MAILBOX_ARCH_CREATED_BY] FOREIGN KEY([SYS_CREATED_BY_ID])
REFERENCES [ORG].[APPLICATION_USER] ([APPLICATION_USER_ID])
GO

ALTER TABLE [BFX_IMPL].[NOTIFICATION_MAILBOX_ARCH] CHECK CONSTRAINT [FK_BFX_IMPL_NOTIFICATION_MAILBOX_ARCH_CREATED_BY]
GO

ALTER TABLE [BFX_IMPL].[NOTIFICATION_MAILBOX_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_BFX_IMPL_NOTIFICATION_MAILBOX_ARCH_ENTITY_REF_ID] FOREIGN KEY([ENTITY_REF_ID])
REFERENCES [BFX].[ENTITY_REF] ([ENTITY_REF_ID])
GO

ALTER TABLE [BFX_IMPL].[NOTIFICATION_MAILBOX_ARCH] CHECK CONSTRAINT [FK_BFX_IMPL_NOTIFICATION_MAILBOX_ARCH_ENTITY_REF_ID]
GO

ALTER TABLE [BFX_IMPL].[NOTIFICATION_MAILBOX_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_BFX_IMPL_NOTIFICATION_MAILBOX_ARCH_UPDATED_BY] FOREIGN KEY([SYS_UPDATED_BY_ID])
REFERENCES [ORG].[APPLICATION_USER] ([APPLICATION_USER_ID])
GO

ALTER TABLE [BFX_IMPL].[NOTIFICATION_MAILBOX_ARCH] CHECK CONSTRAINT [FK_BFX_IMPL_NOTIFICATION_MAILBOX_ARCH_UPDATED_BY]
GO
