IF
	EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[BFX_IMPL].[RISKS]') AND TYPE IN (N'U'))
	AND
	EXISTS (SELECT * FROM sys.columns WHERE Name = N'FNS_TYPE' AND Object_ID = Object_ID(N'[BFX_IMPL].[RISKS]'))
BEGIN
	ALTER TABLE BFX_IMPL.RISKS
	ALTER COLUMN FNS_TYPE NVARCHAR(255) NOT NULL
END
GO