IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[UNI_IMPL].[AGENT_VERIFICATION_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('UNI_IMPL.AGENT_VERIFICATION_SAT','LIST_NUMBER') IS NULL
BEGIN
ALTER TABLE UNI_IMPL.AGENT_VERIFICATION_SAT ADD LIST_NUMBER NVARCHAR(100)
END

END