IF OBJECT_ID(N'BFX_IMPL.NOTIFICATION_JOURNAL_ARCH', N'U') IS NOT NULL
	DROP TABLE BFX_IMPL.NOTIFICATION_JOURNAL_ARCH;
GO

CREATE TABLE [BFX_IMPL].[NOTIFICATION_JOURNAL_ARCH](
	[NOTIFICATION_ID] [uniqueidentifier] NOT NULL,
	[PUBLISHED_ARTIFACT_ID] [uniqueidentifier] NULL,
	[ENTITY_TYPE] [nvarchar](256) NULL,
	[NOTIFICATION_STATUS] [nvarchar](64) NOT NULL,
	[RECORD_ID] [uniqueidentifier] NULL,
	[SYS_CREATED_ON] [datetime] NOT NULL,
	[SYS_UPDATED_ON] [datetime] NOT NULL,
	[SYS_CREATED_BY_ID] [uniqueidentifier] NOT NULL,
	[SYS_UPDATED_BY_ID] [uniqueidentifier] NOT NULL,
	[SYS_CLIENT_ID] [nvarchar](64) NOT NULL,
	[SYS_VERSION] [bigint] NOT NULL,
	[SYS_TENANT_ID] [uniqueidentifier] NULL,
	CONSTRAINT [PK__BFX_IMPL_NOTIFICATION_ARCH_ID] PRIMARY KEY NONCLUSTERED 
	(
		[NOTIFICATION_ID] ASC
	)
)
GO

ALTER TABLE [BFX_IMPL].[NOTIFICATION_JOURNAL_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_BFX_IMPL_NOTIFICATION_JOURNAL_ARCH_CREATED_BY] FOREIGN KEY([SYS_CREATED_BY_ID])
REFERENCES [ORG].[APPLICATION_USER] ([APPLICATION_USER_ID])
GO

ALTER TABLE [BFX_IMPL].[NOTIFICATION_JOURNAL_ARCH] CHECK CONSTRAINT [FK_BFX_IMPL_NOTIFICATION_JOURNAL_ARCH_CREATED_BY]
GO

ALTER TABLE [BFX_IMPL].[NOTIFICATION_JOURNAL_ARCH]  WITH CHECK ADD  CONSTRAINT [FK_BFX_IMPL_NOTIFICATION_JOURNAL_ARCH_UPDATED_BY] FOREIGN KEY([SYS_UPDATED_BY_ID])
REFERENCES [ORG].[APPLICATION_USER] ([APPLICATION_USER_ID])
GO

ALTER TABLE [BFX_IMPL].[NOTIFICATION_JOURNAL_ARCH] CHECK CONSTRAINT [FK_BFX_IMPL_NOTIFICATION_JOURNAL_ARCH_UPDATED_BY]
GO
