IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[ACC_IMPL].[CRT_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('ACC_IMPL.CRT_SAT','CONTRACT_TYPE_CODE') IS NULL
BEGIN
ALTER TABLE ACC_IMPL.CRT_SAT ADD CONTRACT_TYPE_CODE NVARCHAR(64)
END

END
GO