IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[PTY_IMPL].[PARTY_INFO_SAT]') AND TYPE IN (N'U'))
BEGIN
	IF COL_LENGTH('PTY_IMPL.PARTY_INFO_SAT','IS_NOTIFICATION_SENT') IS NULL
	BEGIN
		ALTER TABLE PTY_IMPL.PARTY_INFO_SAT
		ADD IS_NOTIFICATION_SENT BIT NULL
	END
END