IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[CLM_IMPL].[CLM_BENEFICIARY_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('CLM_IMPL.CLM_BENEFICIARY_SAT','ASSIGNED_PO_NUMBER') IS NULL
BEGIN
ALTER TABLE CLM_IMPL.CLM_BENEFICIARY_SAT ADD ASSIGNED_PO_NUMBER nvarchar(255)
CREATE INDEX IDX_CLM_BEN_SAT_PO_NUMBER ON CLM_IMPL.CLM_BENEFICIARY_SAT(ASSIGNED_PO_NUMBER);
END

IF COL_LENGTH('CLM_IMPL.CLM_BENEFICIARY_SAT','RECORD_ID') IS NULL
BEGIN
ALTER TABLE CLM_IMPL.CLM_BENEFICIARY_SAT ADD RECORD_ID uniqueidentifier NOT NULL DEFAULT NEWID()
END

IF COL_LENGTH('CLM_IMPL.CLM_BENEFICIARY_SAT','BANK_ACCOUNT_NUMBER') IS NULL
BEGIN
ALTER TABLE CLM_IMPL.CLM_BENEFICIARY_SAT ADD BANK_ACCOUNT_NUMBER nvarchar(256);
CREATE INDEX IDX_CLM_BEN_SAT_BA_NUMBER ON CLM_IMPL.CLM_BENEFICIARY_SAT(BANK_ACCOUNT_NUMBER);
END

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME ='PK_CLM_IMPL_CLM_BENEFICIARY_SAT')
BEGIN
ALTER TABLE CLM_IMPL.CLM_BENEFICIARY_SAT DROP [PK_CLM_IMPL_CLM_BENEFICIARY_SAT]
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME ='PK_CLM_IMPL_CLM_BENEFICIARY_SAT')
BEGIN

ALTER TABLE CLM_IMPL.CLM_BENEFICIARY_SAT ADD CONSTRAINT [PK_CLM_IMPL_CLM_BENEFICIARY_SAT] PRIMARY KEY NONCLUSTERED 
(
	[CLM_BENEFICIARY_HKEY] ASC,
	[LOAD_DATE] ASC,
	[RECORD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]

END

END