IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[CLM_IMPL].[IE_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('CLM_IMPL.IE_SAT','FIXED_EXCH_RATE') IS NULL
BEGIN
ALTER TABLE CLM_IMPL.IE_SAT ADD FIXED_EXCH_RATE decimal(15,7)
END

IF COL_LENGTH('CLM_IMPL.IE_SAT','USE_FIXED_EXCH_RATE') IS NULL
BEGIN
ALTER TABLE CLM_IMPL.IE_SAT ADD USE_FIXED_EXCH_RATE bit
END

END


IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[CLM_IMPL].[CLM_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('CLM_IMPL.CLM_SAT','FIXED_EXCH_RATE') IS NULL
BEGIN
ALTER TABLE CLM_IMPL.CLM_SAT ADD FIXED_EXCH_RATE decimal(15,7)
END

IF COL_LENGTH('CLM_IMPL.CLM_SAT','USE_FIXED_EXCH_RATE') IS NULL
BEGIN
ALTER TABLE CLM_IMPL.CLM_SAT ADD USE_FIXED_EXCH_RATE bit
END

END