CREATE TABLE CLM_IMPL.COLLECTIVE_CLM_RECIPIENT
(
	RECORD_ID UNIQUEIDENTIFIER DEFAULT NEWID(),
	CLAIM_NUMBER NVARCHAR (64),
	PARTY_CODE NVARCHAR (64),
	FULL_NAME NVARCHAR (500),
	BIRTH_DATE DATE,
	AMOUNT DECIMAL (15,7),
	FRANCHISE DECIMAL (15,7),
	TOTAL_AMOUNT DECIMAL (15,7),
	SERVICE_DESCRIPTION NVARCHAR (1000),
	SERV_PROVIDER_NAME NVARCHAR (1000),
	CONSTRAINT PK_C_CLAIM_RECORD
	PRIMARY KEY CLUSTERED (RECORD_ID ASC)
)
GO

CREATE INDEX IDX_COLLECTIVE_CLM_RECIPIENT_CLAIM_NUMBER ON CLM_IMPL.COLLECTIVE_CLM_RECIPIENT(CLAIM_NUMBER)
GO
CREATE INDEX IDX_COLLECTIVE_CLM_RECIPIENT_PARTY_CODE ON CLM_IMPL.COLLECTIVE_CLM_RECIPIENT(PARTY_CODE)
GO
CREATE INDEX IDX_COLLECTIVE_CLM_RECIPIENT_FULL_NAME ON CLM_IMPL.COLLECTIVE_CLM_RECIPIENT(FULL_NAME)
GO