IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[EWT_IMPL].[EWT_BENEFICIARY_SAT]') AND TYPE IN (N'U'))
BEGIN

IF COL_LENGTH('EWT_IMPL.EWT_BENEFICIARY_SAT','IS_MANUAL_PIT') IS NULL
BEGIN
ALTER TABLE EWT_IMPL.EWT_BENEFICIARY_SAT ADD IS_MANUAL_PIT bit
END

END
GO