IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_BASE_COMM_SAT_START_DATE'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_BASE_COMM_SAT') ) BEGIN
	CREATE INDEX IDX_AA_BASE_COMM_SAT_START_DATE ON
PAS_IMPL.AA_BASE_COMM_SAT(START_DATE)
END

------------------
IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
name = 'IDX_AA_BASE_COMM_SAT_END_DATE'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_BASE_COMM_SAT') ) BEGIN
	CREATE INDEX IDX_AA_BASE_COMM_SAT_END_DATE ON
PAS_IMPL.AA_BASE_COMM_SAT(END_DATE)
END

------------------
IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
name = 'IDX_AA_BASE_COMM_SAT_REGISTRATOR_NUMBER'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_BASE_COMM_SAT') ) BEGIN
	CREATE INDEX IDX_AA_BASE_COMM_SAT_REGISTRATOR_NUMBER ON
PAS_IMPL.AA_BASE_COMM_SAT(REGISTRATOR_NUMBER)
END

------------------
IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
name = 'IDX_AA_BASE_COMM_SAT_PRODUCT_CODE'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_BASE_COMM_SAT') ) BEGIN
	CREATE INDEX IDX_AA_BASE_COMM_SAT_PRODUCT_CODE ON
PAS_IMPL.AA_BASE_COMM_SAT(PRODUCT_VALUE_REF_ID)
END

------------------
IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
name = 'IDX_AA_BASE_COMM_SAT_INSURANCE_YEAR_FROM'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_BASE_COMM_SAT') ) BEGIN
	CREATE INDEX IDX_AA_BASE_COMM_SAT_INSURANCE_YEAR_FROM ON
PAS_IMPL.AA_BASE_COMM_SAT(INSURANCE_YEAR_FROM)
END

------------------
IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
name = 'IDX_AA_BASE_COMM_SAT_INSURANCE_YEAR_TO'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_BASE_COMM_SAT') ) BEGIN
	CREATE INDEX IDX_AA_BASE_COMM_SAT_INSURANCE_YEAR_TO ON
PAS_IMPL.AA_BASE_COMM_SAT(INSURANCE_YEAR_TO)
END

------------------
IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
name = 'IDX_AA_BASE_COMM_SAT_INSURANCE_YEAR_INCLUDE_FROM'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_BASE_COMM_SAT') ) BEGIN
	CREATE INDEX IDX_AA_BASE_COMM_SAT_INSURANCE_YEAR_INCLUDE_FROM ON
PAS_IMPL.AA_BASE_COMM_SAT(INSURANCE_YEAR_INCLUDE_FROM)
END

------------------
IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
name = 'IDX_AA_BASE_COMM_SAT_INSURANCE_YEAR_INCLUDE_TO'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_BASE_COMM_SAT') ) BEGIN
	CREATE INDEX IDX_AA_BASE_COMM_SAT_INSURANCE_YEAR_INCLUDE_TO ON
PAS_IMPL.AA_BASE_COMM_SAT(INSURANCE_YEAR_INCLUDE_TO)
END

------------------
IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
name = 'IDX_AA_BASE_COMM_SAT_INSURANCE_CURRENCY'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_BASE_COMM_SAT') ) BEGIN
	CREATE INDEX IDX_AA_BASE_COMM_SAT_INSURANCE_CURRENCY ON
PAS_IMPL.AA_BASE_COMM_SAT(INSURANCE_CURRENCY)
END

------------------
IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
name = 'IDX_AA_BASE_COMM_SAT_INSURANCE_TERM_FROM'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_BASE_COMM_SAT') ) BEGIN
	CREATE INDEX IDX_AA_BASE_COMM_SAT_INSURANCE_TERM_FROM ON
PAS_IMPL.AA_BASE_COMM_SAT(INSURANCE_TERM_FROM)
END

------------------
IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
name = 'IDX_AA_BASE_COMM_SAT_INSURANCE_TERM_INCLUDE_FROM'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_BASE_COMM_SAT') ) BEGIN
	CREATE INDEX IDX_AA_BASE_COMM_SAT_INSURANCE_TERM_INCLUDE_FROM ON
PAS_IMPL.AA_BASE_COMM_SAT(INSURANCE_TERM_INCLUDE_FROM)
END

------------------
IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
name = 'IDX_AA_BASE_COMM_SAT_INSURANCE_TERM_TO'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_BASE_COMM_SAT') ) BEGIN
	CREATE INDEX IDX_AA_BASE_COMM_SAT_INSURANCE_TERM_TO ON
PAS_IMPL.AA_BASE_COMM_SAT(INSURANCE_TERM_TO)
END

------------------
IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
name = 'IDX_AA_BASE_COMM_SAT_INSURANCE_TERM_INCLUDE_TO'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_BASE_COMM_SAT') ) BEGIN
	CREATE INDEX IDX_AA_BASE_COMM_SAT_INSURANCE_TERM_INCLUDE_TO ON
PAS_IMPL.AA_BASE_COMM_SAT(INSURANCE_TERM_INCLUDE_TO)
END

------------------
IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
name = 'IDX_AA_BASE_COMM_SAT_PREMIUM_PERIOD_FROM'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_BASE_COMM_SAT') ) BEGIN
	CREATE INDEX IDX_AA_BASE_COMM_SAT_PREMIUM_PERIOD_FROM ON
PAS_IMPL.AA_BASE_COMM_SAT(PREMIUM_PERIOD_FROM)
END

------------------
IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
name = 'IDX_AA_BASE_COMM_SAT_PREMIUM_PERIOD_INCLUDE_FROM'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_BASE_COMM_SAT') ) BEGIN
	CREATE INDEX IDX_AA_BASE_COMM_SAT_PREMIUM_PERIOD_INCLUDE_FROM ON
PAS_IMPL.AA_BASE_COMM_SAT(PREMIUM_PERIOD_INCLUDE_FROM)
END

------------------
IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
name = 'IDX_AA_BASE_COMM_SAT_PREMIUM_PERIOD_TO'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_BASE_COMM_SAT') ) BEGIN
	CREATE INDEX IDX_AA_BASE_COMM_SAT_PREMIUM_PERIOD_TO ON
PAS_IMPL.AA_BASE_COMM_SAT(PREMIUM_PERIOD_TO)
END

------------------
IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
name = 'IDX_AA_BASE_COMM_SAT_PREMIUM_PERIOD_INCLUDE_TO'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_BASE_COMM_SAT') ) BEGIN
	CREATE INDEX IDX_AA_BASE_COMM_SAT_PREMIUM_PERIOD_INCLUDE_TO ON
PAS_IMPL.AA_BASE_COMM_SAT(PREMIUM_PERIOD_INCLUDE_TO)
END

------------------
IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
name = 'IDX_AA_BASE_COMM_SAT_PREMIUM_PERIOD_TYPE_CODE'
	AND object_id = OBJECT_ID('PAS_IMPL.AA_BASE_COMM_SAT') ) BEGIN
	CREATE INDEX IDX_AA_BASE_COMM_SAT_PREMIUM_PERIOD_TYPE_CODE ON
PAS_IMPL.AA_BASE_COMM_SAT(PREM_PERIOD_VALUE_REF_ID)
END