IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_RECIPIENT_SAT_FULL_NAME'
	AND object_id = OBJECT_ID('ACC_IMPL.PO_RECIPIENT_SAT') ) BEGIN
	CREATE INDEX IDX_PO_RECIPIENT_SAT_FULL_NAME ON
ACC_IMPL.PO_RECIPIENT_SAT(FULL_NAME)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_RECIPIENT_SAT_INN_NUMBER'
	AND object_id = OBJECT_ID('ACC_IMPL.PO_RECIPIENT_SAT') ) BEGIN
	CREATE INDEX IDX_PO_RECIPIENT_SAT_INN_NUMBER ON
ACC_IMPL.PO_RECIPIENT_SAT(INN_NUMBER)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_RECIPIENT_SAT_KPP_NUMBER'
	AND object_id = OBJECT_ID('ACC_IMPL.PO_RECIPIENT_SAT') ) BEGIN
	CREATE INDEX IDX_PO_RECIPIENT_SAT_KPP_NUMBER ON
ACC_IMPL.PO_RECIPIENT_SAT(KPP_NUMBER)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_RECIPIENT_SAT_PARTY_TYPE'
	AND object_id = OBJECT_ID('ACC_IMPL.PO_RECIPIENT_SAT') ) BEGIN
	CREATE INDEX IDX_PO_RECIPIENT_SAT_PARTY_TYPE ON
ACC_IMPL.PO_RECIPIENT_SAT(PARTY_TYPE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_RECIPIENT_SAT_BANK_BIC'
	AND object_id = OBJECT_ID('ACC_IMPL.PO_RECIPIENT_SAT') ) BEGIN
	CREATE INDEX IDX_PO_RECIPIENT_SAT_BANK_BIC ON
ACC_IMPL.PO_RECIPIENT_SAT(BANK_BIC)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_RECIPIENT_SAT_CORR_BANK_ACCOUNT'
	AND object_id = OBJECT_ID('ACC_IMPL.PO_RECIPIENT_SAT') ) BEGIN
	CREATE INDEX IDX_PO_RECIPIENT_SAT_CORR_BANK_ACCOUNT ON
ACC_IMPL.PO_RECIPIENT_SAT(CORRESPONDENT_BANK_ACCOUNT)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_RECIPIENT_SAT_BANK_ACCOUNT'
	AND object_id = OBJECT_ID('ACC_IMPL.PO_RECIPIENT_SAT') ) BEGIN
	CREATE INDEX IDX_PO_RECIPIENT_SAT_BANK_ACCOUNT ON
ACC_IMPL.PO_RECIPIENT_SAT(BANK_ACCOUNT)
END

------------------
