DROP TABLE IF EXISTS [PAS_IMPL].[UL_PRODUCTS]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_PRODUCTS_HISTORY]
GO
DROP TRIGGER IF EXISTS [PAS_IMPL].[UL_PRODUCTS_HISTORY_TRIGGER]
GO
DROP VIEW IF EXISTS [PAS_IMPL].[UL_PRODUCTS_VIEW]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_INVESTMENT_OBSERVATION_DATES]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_INVESTMENT_OBSERVATION_DATES_HISTORY]
GO
DROP TRIGGER IF EXISTS [PAS_IMPL].[UL_INVESTMENT_OBSERVATION_DATES_HISTORY_TRIGGER]
GO
DROP VIEW IF EXISTS [PAS_IMPL].[UL_INVESTMENT_OBSERVATION_DATES_VIEW]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_PRODUCT_VERSION]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_PRODUCT_VERSION_HISTORY]
GO
DROP TRIGGER IF EXISTS [PAS_IMPL].[UL_PRODUCT_VERSION_HISTORY_TRIGGER]
GO
DROP VIEW IF EXISTS [PAS_IMPL].[UL_PRODUCT_VERSION_VIEW]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_GUARANTEE_FUND]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_GUARANTEE_FUND_HISTORY]
GO
DROP TRIGGER IF EXISTS [PAS_IMPL].[UL_GUARANTEE_FUND_HISTORY_TRIGGER]
GO
DROP VIEW IF EXISTS [PAS_IMPL].[UL_GUARANTEE_FUND_VIEW]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_PIP_GF]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_PIP_GF_HISTORY]
GO
DROP TRIGGER IF EXISTS [PAS_IMPL].[UL_PIP_GF_HISTORY_TRIGGER]
GO
DROP VIEW IF EXISTS [PAS_IMPL].[UL_PIP_GF_VIEW]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_RATE_MIX]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_RATE_MIX_HISTORY]
GO
DROP TRIGGER IF EXISTS [PAS_IMPL].[UL_RATE_MIX_HISTORY_TRIGGER]
GO
DROP VIEW IF EXISTS [PAS_IMPL].[UL_RATE_MIX_VIEW]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_RATES]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_RATES_HISTORY]
GO
DROP TRIGGER IF EXISTS [PAS_IMPL].[UL_RATES_HISTORY_TRIGGER]
GO
DROP VIEW IF EXISTS [PAS_IMPL].[UL_RATES_VIEW]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_GUARANTEES]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_GUARANTEES_HISTORY]
GO
DROP TRIGGER IF EXISTS [PAS_IMPL].[UL_GUARANTEES_HISTORY_TRIGGER]
GO
DROP VIEW IF EXISTS [PAS_IMPL].[UL_GUARANTEES_VIEW]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_GUARANTEE_DATES]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_GUARANTEE_DATES_HISTORY]
GO
DROP TRIGGER IF EXISTS [PAS_IMPL].[UL_GUARANTEE_DATES_HISTORY_TRIGGER]
GO
DROP VIEW IF EXISTS [PAS_IMPL].[UL_GUARANTEE_DATES_VIEW]
GO
DROP TABLE  IF EXISTS [PAS_IMPL].[UL_RISK_FUND]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_RISK_FUND_HISTORY]
GO
DROP TRIGGER IF EXISTS [PAS_IMPL].[UL_RISK_FUND_HISTORY_TRIGGER]
GO
DROP VIEW IF EXISTS [PAS_IMPL].[UL_RISK_FUND_VIEW]
GO
DROP TABLE  IF EXISTS [PAS_IMPL].[UL_RISK_FUND_GROUP]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_RISK_FUND_GROUP_HISTORY]
GO
DROP TRIGGER IF EXISTS [PAS_IMPL].[UL_RISK_FUND_GROUP_HISTORY_TRIGGER]
GO
DROP VIEW IF EXISTS [PAS_IMPL].[UL_RISK_FUND_GROUP_VIEW]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_CASH]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_CASH_HISTORY]
GO
DROP TRIGGER IF EXISTS [PAS_IMPL].[UL_CASH_HISTORY_TRIGGER]
GO
DROP VIEW IF EXISTS [PAS_IMPL].[UL_CASH_VIEW]
GO
DROP TABLE  IF EXISTS [PAS_IMPL].[UL_PIP_RF]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_PIP_RF_HISTORY]
GO
DROP TRIGGER IF EXISTS [PAS_IMPL].[UL_PIP_RF_HISTORY_TRIGGER]
GO
DROP VIEW IF EXISTS [PAS_IMPL].[UL_PIP_RF_VIEW]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_PAY_OFF]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_PAY_OFF_HISTORY]
GO
DROP TRIGGER IF EXISTS [PAS_IMPL].[UL_PAY_OFF_HISTORY_TRIGGER]
GO
DROP VIEW IF EXISTS [PAS_IMPL].[UL_PAY_OFF_VIEW]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_BARRIER_TYPE]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_BARRIER_TYPE_HISTORY]
GO
DROP TRIGGER IF EXISTS [PAS_IMPL].[UL_BARRIER_TYPE_HISTORY_TRIGGER]
GO
DROP VIEW IF EXISTS [PAS_IMPL].[UL_BARRIER_TYPE_VIEW]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_OBSERVATION_BARRIER]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_OBSERVATION_BARRIER_HISTORY]
GO
DROP TRIGGER IF EXISTS [PAS_IMPL].[UL_OBSERVATION_BARRIER_HISTORY_TRIGGER]
GO
DROP VIEW IF EXISTS [PAS_IMPL].[UL_OBSERVATION_BARRIER_VIEW]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_BASIC_ASSETS]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_BASIC_ASSETS_HISTORY]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_BASIC_ASSETS_GROUP]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_BASIC_ASSETS_GROUP_HISTORY]
GO
DROP TRIGGER IF EXISTS [PAS_IMPL].[UL_BASIC_ASSETS_GROUP_HISTORY_TRIGGER]
GO
DROP VIEW IF EXISTS [PAS_IMPL].[UL_BASIC_ASSETS_GROUP_VIEW]
GO
DROP TRIGGER IF EXISTS [PAS_IMPL].[UL_BASIC_ASSETS_HISTORY_TRIGGER]
GO
DROP VIEW IF EXISTS [PAS_IMPL].[UL_BASIC_ASSETS_VIEW]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_TOOLS]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_TOOLS_HISTORY]
GO
DROP TRIGGER IF EXISTS [PAS_IMPL].[UL_TOOLS_HISTORY_TRIGGER]
GO
DROP VIEW IF EXISTS [PAS_IMPL].[UL_TOOLS_VIEW]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_STOCKS]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_STOCKS_HISTORY]
GO
DROP TRIGGER IF EXISTS [PAS_IMPL].[UL_STOCKS_HISTORY_TRIGGER]
GO
DROP VIEW IF EXISTS [PAS_IMPL].[UL_STOCKS_VIEW]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_HISTORICAL_PROFITABILITY]
GO
DROP TABLE IF EXISTS [PAS_IMPL].[UL_HISTORICAL_PROFITABILITY_HISTORY]
GO
DROP TRIGGER IF EXISTS [PAS_IMPL].[UL_HISTORICAL_PROFITABILITY_HISTORY_TRIGGER]
GO
DROP VIEW IF EXISTS [PAS_IMPL].[UL_HISTORICAL_PROFITABILITY_VIEW]
GO