SELECT *
FROM 
  PAS_IMPL.UL_PRODUCT_VERSION productVersion 
  JOIN PAS_IMPL.UL_PRODUCTS products ON products.PRODUCT_VERSION_ID = productVersion.PRODUCT_VERSION_ID 
  JOIN PAS_IMPL.UL_INVESTMENT_OBSERVATION_DATES investmentObservationDates ON investmentObservationDates.INVESTMENT_OBSERVATION_DATES_ID = products.INVESTMENT_OBSERVATION_DATES_ID 
  JOIN PAS_IMPL.UL_GUARANTEES guarantees ON guarantees.GUARANTEE_ID = productVersion.GUARANTEE_ID 
  JOIN PAS_IMPL.UL_GUARANTEE_DATES guaranteeDates ON guaranteeDates.GUARANTEE_DATES_ID = guarantees.GUARANTEE_DATES_ID 
  JOIN PAS_IMPL.UL_GUARANTEE_FUND guaranteeFund ON guaranteeFund.GUARANTEE_FUND_ID = productVersion.GUARANTEE_FUND_ID 
  JOIN PAS_IMPL.UL_PIP_GF pipGf ON pipGf.PIP_GF_ID = guaranteeFund.PIP_GF_ID 
  JOIN PAS_IMPL.UL_RATE_MIX rateMix ON rateMix.RATE_MIX_ID = pipGf.RATE_MIX_ID 
  JOIN PAS_IMPL.UL_RATES rates ON rates.RATE_ID = rateMix.RATE_ID 
  JOIN PAS_IMPL.UL_HISTORICAL_PROFITABILITY historicalProfitability ON historicalProfitability.HISTORICAL_PROFITABILITY_ID = productVersion.HISTORICAL_PROFITABILITY_ID 
  JOIN PAS_IMPL.UL_RISK_FUND riskFund ON riskFund.RISK_FUND_ID = productVersion.RISK_FUND_ID 
  JOIN PAS_IMPL.UL_CASH cash ON cash.CASH_ID = riskFund.CASH_ID 
  JOIN PAS_IMPL.UL_PIP_RF pipRf ON pipRf.PIP_RF_ID = riskFund.PIP_RF_ID 
  JOIN PAS_IMPL.UL_PAY_OFF payOff ON payOff.PAY_OFF_ID = pipRf.PAY_OFF_ID 
  JOIN PAS_IMPL.UL_BARRIER_TYPE barrierType ON barrierType.BARRIER_TYPE_ID = payOff.BARRIER_TYPE_ID 
  JOIN PAS_IMPL.UL_BASIC_ASSETS basicAssets ON basicAssets.BASIC_ASSET_ID = pipRf.BASIC_ASSET_ID 
  JOIN PAS_IMPL.UL_TOOLS tools ON tools.TOOL_ID = basicAssets.TOOL_ID 
  JOIN PAS_IMPL.UL_STOCKS stocks ON stocks.MIC = tools.MIC