-- CREATE TABLE UL_BARRIER_TYPE
CREATE TABLE [PAS_IMPL].[UL_BARRIER_TYPE]
(
	[BARRIER_TYPE_ID] [UNIQUEIDENTIFIER],
	[BARRIER_NAME] [NVARCHAR](255),
	[OBSERVATION_FREQUENCY] [NVARCHAR](255),
	[MORATORIUM_END_CHECK_NUMBER] [INT]
		CONSTRAINT [PK_UL_BARRIER_NAME]
PRIMARY KEY CLUSTERED ([BARRIER_TYPE_ID] ASC)
)
GO

-- CREATE HISTORY TABLE
CREATE TABLE [PAS_IMPL].[UL_BARRIER_TYPE_HISTORY]
(
	[BARRIER_TYPE_HISTORY_ID] [UNIQUEIDENTIFIER],
	[BARRIER_TYPE_ID] [UNIQUEIDENTIFIER],
	[BARRIER_NAME] [NVARCHAR](255),
	[OBSERVATION_FREQUENCY] [NVARCHAR](255),
	[MORATORIUM_END_CHECK_NUMBER] [INT],
	[OPERATION] [NVARCHAR](1),
	CONSTRAINT [PK_UL_BARRIER_NAME_HISTORY]
PRIMARY KEY CLUSTERED ([BARRIER_TYPE_HISTORY_ID] ASC)
)
GO

-- CREATE TRIGGER
CREATE TRIGGER [PAS_IMPL].[UL_BARRIER_TYPE_HISTORY_TRIGGER]
ON [PAS_IMPL].[UL_BARRIER_TYPE]
AFTER INSERT, UPDATE, DELETE
AS  
BEGIN
	DECLARE @operation NVARCHAR(1)
	IF EXISTS(SELECT *
	FROM inserted)
	  IF EXISTS(SELECT *
	FROM deleted)
	    SELECT @operation = 'U'
	ELSE
	    SELECT @operation = 'I'
	ELSE
		IF EXISTS(SELECT *
	FROM deleted)
    SELECT @operation = 'D'

	DECLARE @barrierTypeId UNIQUEIDENTIFIER;
	DECLARE @barrierName NVARCHAR(255);
	DECLARE @observationFrequency NVARCHAR(255);
	DECLARE @moratoriumEndCheckNumber INT;

	IF @operation != 'D'
	
		SELECT @barrierTypeId = BARRIER_TYPE_ID, @barrierName = BARRIER_NAME, @observationFrequency = OBSERVATION_FREQUENCY, @moratoriumEndCheckNumber = MORATORIUM_END_CHECK_NUMBER
	FROM inserted
	ELSE 
		SELECT @barrierTypeId = BARRIER_TYPE_ID, @barrierName = BARRIER_NAME, @observationFrequency = OBSERVATION_FREQUENCY, @moratoriumEndCheckNumber = MORATORIUM_END_CHECK_NUMBER
	FROM deleted

	INSERT INTO PAS_IMPL.UL_BARRIER_TYPE_HISTORY
		(BARRIER_TYPE_HISTORY_ID, BARRIER_TYPE_ID, BARRIER_NAME, OBSERVATION_FREQUENCY, MORATORIUM_END_CHECK_NUMBER, OPERATION)
	VALUES
		(NEWID(), @barrierTypeId, @barrierName, @observationFrequency, @moratoriumEndCheckNumber, @operation)
END

SET QUOTED_IDENTIFIER ON
GO

-- CREATE VIEW
CREATE VIEW [PAS_IMPL].[UL_BARRIER_TYPE_VIEW]
AS
	SELECT
		[BARRIER_TYPE_ID] AS BARRIER_TYPE_ID,
		[BARRIER_NAME] AS BARRIER_NAME,
		[OBSERVATION_FREQUENCY] AS OBSERVATION_FREQUENCY,
		[MORATORIUM_END_CHECK_NUMBER] AS MORATORIUM_END_CHECK_NUMBER
	FROM [PAS_IMPL].[UL_BARRIER_TYPE]
GO