-- CREATE TABLE UL_RISK_FUND_GROUP
CREATE TABLE [PAS_IMPL].[UL_BASIC_ASSETS_GROUP]
(
	[BASIC_ASSETS_GROUP_ID] [UNIQUEIDENTIFIER]
		CONSTRAINT [PK_UL_BASIC_ASSETS_GROUP]
PRIMARY KEY CLUSTERED ([BASIC_ASSETS_GROUP_ID] ASC)
)
GO

-- CREATE HISTORY TABLE
CREATE TABLE [PAS_IMPL].[UL_BASIC_ASSETS_GROUP_HISTORY]
(
	[BASIC_ASSETS_GROUP_HISTORY_ID] [UNIQUEIDENTIFIER],
	[BASIC_ASSETS_GROUP_ID] [UNIQUEIDENTIFIER],
	[OPERATION] [NVARCHAR](1),
	CONSTRAINT [PK_UL_BASIC_ASSETS_GROUP_HISTORY]
PRIMARY KEY CLUSTERED ([BASIC_ASSETS_GROUP_HISTORY_ID] ASC)
)
GO

-- CREATE TRIGGER
CREATE TRIGGER [PAS_IMPL].[UL_BASIC_ASSETS_GROUP_HISTORY_TRIGGER]
ON [PAS_IMPL].[UL_BASIC_ASSETS_GROUP]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
	DECLARE @operation NVARCHAR(1)
	IF EXISTS(SELECT *
	FROM inserted)
	  IF EXISTS(SELECT *
	FROM deleted)
	    SELECT @operation = 'U'
	ELSE
	    SELECT @operation = 'I'
	ELSE
		IF EXISTS(SELECT *
	FROM deleted)
    SELECT @operation = 'D'

	DECLARE @basicAssetsGroupId UNIQUEIDENTIFIER;

	IF @operation != 'D'

		SELECT @basicAssetsGroupId = BASIC_ASSETS_GROUP_ID
	FROM inserted
	ELSE
		SELECT @basicAssetsGroupId = BASIC_ASSETS_GROUP_ID
	FROM deleted

	INSERT INTO PAS_IMPL.UL_BASIC_ASSETS_GROUP_HISTORY
		(BASIC_ASSETS_GROUP_HISTORY_ID, BASIC_ASSETS_GROUP_ID, OPERATION)
	VALUES
		(NEWID(), @basicAssetsGroupId, @operation)
END

SET QUOTED_IDENTIFIER ON
GO

-- CREATE VIEW
CREATE VIEW [PAS_IMPL].[UL_BASIC_ASSETS_GROUP_VIEW]
AS
	SELECT
		[BASIC_ASSETS_GROUP_ID] AS BASIC_ASSETS_GROUP_ID
	FROM [PAS_IMPL].[UL_BASIC_ASSETS_GROUP]
GO