-- CREATE TABLE UL_BASIC_ASSETS
CREATE TABLE [PAS_IMPL].[UL_BASIC_ASSETS]
(
	[BASIC_ASSET_ID] [UNIQUEIDENTIFIER],
	[BASIC_ASSETS_GROUP_ID] [UNIQUEIDENTIFIER],
	[MARKETING_ASSET_NAME] [NVARCHAR](255),
	[TOOL_ID] [UNIQUEIDENTIFIER],
	CONSTRAINT [PK_UL_BASIC_ASSETS]
PRIMARY KEY CLUSTERED ([BASIC_ASSET_ID] ASC)
)
GO

ALTER TABLE [PAS_IMPL].[UL_BASIC_ASSETS]  WITH CHECK ADD  CONSTRAINT [FK_PAS_IMPL_UL_BASIC_ASSETS_TOOL_ID] FOREIGN KEY([TOOL_ID])
REFERENCES [PAS_IMPL].[UL_TOOLS] ([TOOL_ID])
GO

ALTER TABLE [PAS_IMPL].[UL_BASIC_ASSETS]  WITH CHECK ADD  CONSTRAINT [FK_PAS_IMPL_UL_BASIC_ASSETS_GROUP_ID] FOREIGN KEY([BASIC_ASSETS_GROUP_ID])
REFERENCES [PAS_IMPL].[UL_BASIC_ASSETS_GROUP] ([BASIC_ASSETS_GROUP_ID])
GO

-- CREATE HISTORY TABLE
CREATE TABLE [PAS_IMPL].[UL_BASIC_ASSETS_HISTORY]
(
	[BASIC_ASSET_HISTORY_ID] [UNIQUEIDENTIFIER],
	[BASIC_ASSET_ID] [UNIQUEIDENTIFIER],
	[BASIC_ASSETS_GROUP_ID] [UNIQUEIDENTIFIER],
	[MARKETING_ASSET_NAME] [NVARCHAR](255),
	[TOOL_ID] [UNIQUEIDENTIFIER],
	[OPERATION] [NVARCHAR](1),
	CONSTRAINT [PK_UL_BASIC_ASSETS_HISTORY]
PRIMARY KEY CLUSTERED ([BASIC_ASSET_HISTORY_ID] ASC)
)
GO

-- CREATE TRIGGER
CREATE TRIGGER [PAS_IMPL].[UL_BASIC_ASSETS_HISTORY_TRIGGER]
ON [PAS_IMPL].[UL_BASIC_ASSETS]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
	DECLARE @operation NVARCHAR(1)
	IF EXISTS(SELECT *
	FROM inserted)
	  IF EXISTS(SELECT *
	FROM deleted)
	    SELECT @operation = 'U'
	ELSE
	    SELECT @operation = 'I'
	ELSE
		IF EXISTS(SELECT *
	FROM deleted)
    SELECT @operation = 'D'

	DECLARE @basicAssetId UNIQUEIDENTIFIER;
	DECLARE @basicAssetsGroupId UNIQUEIDENTIFIER;
	DECLARE @marketingAssetName NVARCHAR(255);
	DECLARE @toolId UNIQUEIDENTIFIER;

	IF @operation != 'D'

		SELECT @basicAssetId = BASIC_ASSET_ID, @basicAssetsGroupId = BASIC_ASSETS_GROUP_ID, @marketingAssetName = MARKETING_ASSET_NAME, @toolId = TOOL_ID
	FROM inserted
	ELSE
		SELECT @basicAssetId = BASIC_ASSET_ID, @basicAssetsGroupId = BASIC_ASSETS_GROUP_ID, @marketingAssetName = MARKETING_ASSET_NAME, @toolId = TOOL_ID
	FROM deleted

	INSERT INTO PAS_IMPL.UL_BASIC_ASSETS_HISTORY
		(BASIC_ASSET_HISTORY_ID, BASIC_ASSET_ID, BASIC_ASSETS_GROUP_ID, MARKETING_ASSET_NAME, TOOL_ID, OPERATION)
	VALUES
		(NEWID(), @basicAssetId, @basicAssetsGroupId, @marketingAssetName, @toolId, @operation)
END

SET QUOTED_IDENTIFIER ON
GO

-- CREATE VIEW
CREATE VIEW [PAS_IMPL].[UL_BASIC_ASSETS_VIEW]
AS
	SELECT
		[BASIC_ASSET_ID] AS BASIC_ASSET_ID,
		[BASIC_ASSETS_GROUP_ID] as BASIC_ASSETS_GROUP_ID,
		[MARKETING_ASSET_NAME] AS MARKETING_ASSET_NAME,
		[TOOL_ID] AS TOOL_ID
	FROM [PAS_IMPL].[UL_BASIC_ASSETS]
GO