-- CREATE TABLE UL_CASH
CREATE TABLE [PAS_IMPL].[UL_CASH]
(
	[CASH_ID] [UNIQUEIDENTIFIER],
	[CASH_TYPE] [NVARCHAR](255),
	[STARTING_QUOTATION] [DECIMAL](15,6),
	[RATE] [DECIMAL](15,6),
	[CURRENCY] [NVARCHAR](255),
	CONSTRAINT [PK_UL_CASH]
PRIMARY KEY CLUSTERED ([CASH_ID] ASC)
)
GO

-- CREATE HISTORY TABLE
CREATE TABLE [PAS_IMPL].[UL_CASH_HISTORY]
(
	[CASH_HISTORY_ID] [UNIQUEIDENTIFIER],
	[CASH_ID] [UNIQUEIDENTIFIER],
	[CASH_TYPE] [NVARCHAR](255),
	[STARTING_QUOTATION] [DECIMAL](15,6),
	[RATE] [DECIMAL](15,6),
	[CURRENCY] [NVARCHAR](255),
	[OPERATION] [NVARCHAR](1),
	CONSTRAINT [PK_UL_CASH_HISTORY]
PRIMARY KEY CLUSTERED ([CASH_HISTORY_ID] ASC)
)
GO

-- CREATE TRIGGER
CREATE TRIGGER [PAS_IMPL].[UL_CASH_HISTORY_TRIGGER]
ON [PAS_IMPL].[UL_CASH]
AFTER INSERT, UPDATE, DELETE
AS  
BEGIN
	DECLARE @operation NVARCHAR(1)
	IF EXISTS(SELECT *
	FROM inserted)
	  IF EXISTS(SELECT *
	FROM deleted)
	    SELECT @operation = 'U'
	ELSE
	    SELECT @operation = 'I'
	ELSE
		IF EXISTS(SELECT *
	FROM deleted)
    SELECT @operation = 'D'

	DECLARE @cashId UNIQUEIDENTIFIER;
	DECLARE @cashType NVARCHAR(255);
	DECLARE @startingQuotation DECIMAL(15,6);
	DECLARE @rate DECIMAL(15,6);
	DECLARE @currency NVARCHAR(255);

	IF @operation != 'D'
	
		SELECT @cashId = CASH_ID, @cashType = CASH_TYPE, @startingQuotation = STARTING_QUOTATION, @rate = RATE, @currency = CURRENCY
	FROM inserted
	ELSE 
		SELECT @cashId = CASH_ID, @cashType = CASH_TYPE, @startingQuotation = STARTING_QUOTATION, @rate = RATE, @currency = CURRENCY
	FROM deleted

	INSERT INTO PAS_IMPL.UL_CASH_HISTORY
		(CASH_HISTORY_ID, CASH_ID, CASH_TYPE, STARTING_QUOTATION, RATE, CURRENCY, OPERATION)
	VALUES
		(NEWID(), @cashId, @cashType, @startingQuotation, @rate, @currency, @operation)
END

SET QUOTED_IDENTIFIER ON
GO

-- CREATE VIEW
CREATE VIEW [PAS_IMPL].[UL_CASH_VIEW]
AS
	SELECT
		[CASH_ID] AS CASH_ID,
		[CASH_TYPE] AS CASH_TYPE,
		[STARTING_QUOTATION] AS STARTING_QUOTATION,
		[RATE] AS RATE,
		[CURRENCY] AS CURRENCY
	FROM [PAS_IMPL].[UL_CASH]
GO