-- CREATE TABLE UL_GUARANTEE_FUND
CREATE TABLE [PAS_IMPL].[UL_GUARANTEE_FUND]
(
	[GUARANTEE_FUND_ID] [UNIQUEIDENTIFIER],
	[PIP_GF_ID] [UNIQUEIDENTIFIER],
	[PIP_SHARE] [DECIMAL](15,6),
	[PIP_TARIFF_QUOTATION] [DECIMAL](15,6)
		CONSTRAINT [PK_UL_GUARANTEE_FUND]
PRIMARY KEY CLUSTERED ([GUARANTEE_FUND_ID] ASC)
)
GO

ALTER TABLE [PAS_IMPL].[UL_GUARANTEE_FUND]  WITH CHECK ADD  CONSTRAINT [FK_PAS_IMPL_UL_GUARANTEE_FUND_PIP_GF_ID] FOREIGN KEY([PIP_GF_ID])
REFERENCES [PAS_IMPL].[UL_PIP_GF] ([PIP_GF_ID])
GO

-- CREATE HISTORY TABLE
CREATE TABLE [PAS_IMPL].[UL_GUARANTEE_FUND_HISTORY]
(
	[GUARANTEE_FUND_HISTORY_ID] [UNIQUEIDENTIFIER],
	[GUARANTEE_FUND_ID] [UNIQUEIDENTIFIER],
	[PIP_GF_ID] [UNIQUEIDENTIFIER],
	[PIP_SHARE] [DECIMAL](15,6),
	[PIP_TARIFF_QUOTATION] [DECIMAL](15,6),
	[OPERATION] [NVARCHAR](1),
	CONSTRAINT [PK_UL_GUARANTEE_FUND_HISTORY]
PRIMARY KEY CLUSTERED ([GUARANTEE_FUND_HISTORY_ID] ASC)
)
GO

-- CREATE TRIGGER
CREATE TRIGGER [PAS_IMPL].[UL_GUARANTEE_FUND_HISTORY_TRIGGER]
ON [PAS_IMPL].[UL_GUARANTEE_FUND]
AFTER INSERT, UPDATE, DELETE
AS  
BEGIN
	DECLARE @operation NVARCHAR(1)
	IF EXISTS(SELECT *
	FROM inserted)
	  IF EXISTS(SELECT *
	FROM deleted)
	    SELECT @operation = 'U'
	ELSE
	    SELECT @operation = 'I'
	ELSE
		IF EXISTS(SELECT *
	FROM deleted)
    SELECT @operation = 'D'

	DECLARE @guaranteeFUNDId UNIQUEIDENTIFIER;
	DECLARE @pipGFId NVARCHAR(255);
	DECLARE @pipShare DECIMAL(15,6);
	DECLARE @pipTariffQuotation DECIMAL(15,6);

	IF @operation != 'D'
	
		SELECT @guaranteeFUNDId = GUARANTEE_FUND_ID, @pipGFId = PIP_GF_ID, @pipShare = PIP_SHARE, @pipTariffQuotation = PIP_TARIFF_QUOTATION
	FROM inserted
	ELSE 
		SELECT @guaranteeFUNDId = GUARANTEE_FUND_ID, @pipGFId = PIP_GF_ID, @pipShare = PIP_SHARE, @pipTariffQuotation = PIP_TARIFF_QUOTATION
	FROM deleted

	INSERT INTO PAS_IMPL.UL_GUARANTEE_FUND_HISTORY
		(GUARANTEE_FUND_HISTORY_ID, GUARANTEE_FUND_ID, PIP_GF_ID, PIP_SHARE, PIP_TARIFF_QUOTATION, OPERATION)
	VALUES
		(NEWID(), @guaranteeFUNDId, @pipGFId, @pipShare, @pipTariffQuotation, @operation)
END

SET QUOTED_IDENTIFIER ON
GO

-- CREATE VIEW
CREATE VIEW [PAS_IMPL].[UL_GUARANTEE_FUND_VIEW]
AS
	SELECT
		[GUARANTEE_FUND_ID] AS GUARANTEE_FUND_ID,
		[PIP_GF_ID] AS PIP_GF_ID,
		[PIP_SHARE] AS PIP_SHARE,
		[PIP_TARIFF_QUOTATION] AS PIP_TARIFF_QUOTATION
	FROM [PAS_IMPL].[UL_GUARANTEE_FUND]
GO