-- CREATE TABLE UL_GUARANTEES
CREATE TABLE [PAS_IMPL].[UL_GUARANTEES]
(
	[GUARANTEE_ID] [UNIQUEIDENTIFIER],
	[TARIFF_RATE_CURRENCY] [NVARCHAR](255),
	[CAPITAL_PROTECTION] [DECIMAL](15,6),
	[GUARANTEED_COUPON] [DECIMAL](15,6),
	[GUARANTEED_COUPON_FREQUENCY] [INT],
	[GUARANTEE_DATES_ID] [UNIQUEIDENTIFIER]
	CONSTRAINT [PK_UL_GUARANTEES]
PRIMARY KEY CLUSTERED ([GUARANTEE_ID] ASC)
)
GO

ALTER TABLE [PAS_IMPL].[UL_GUARANTEES] WITH CHECK ADD CONSTRAINT [FK_PAS_IMPL_UL_GUARANTEES_GUARANTEE_DATES_ID] FOREIGN KEY([GUARANTEE_DATES_ID])
REFERENCES [PAS_IMPL].[UL_GUARANTEE_DATES] ([GUARANTEE_DATES_ID])
GO

-- CREATE HISTORY TABLE
CREATE TABLE [PAS_IMPL].[UL_GUARANTEES_HISTORY]
(
	[GUARANTEE_HISTORY_ID] [UNIQUEIDENTIFIER],
	[GUARANTEE_ID] [UNIQUEIDENTIFIER],
	[TARIFF_RATE_CURRENCY] [NVARCHAR](255),
	[CAPITAL_PROTECTION] [DECIMAL](15,6),
	[GUARANTEED_COUPON] [DECIMAL](15,6),
	[GUARANTEED_COUPON_FREQUENCY] [INT],
	[GUARANTEE_DATES_ID] [UNIQUEIDENTIFIER],
	[OPERATION] [NVARCHAR](1),
	CONSTRAINT [PK_UL_GUARANTEES_HISTORY]
PRIMARY KEY CLUSTERED ([GUARANTEE_HISTORY_ID] ASC)
)
GO

-- CREATE TRIGGER
CREATE TRIGGER [PAS_IMPL].[UL_GUARANTEES_HISTORY_TRIGGER]
ON [PAS_IMPL].[UL_GUARANTEES]
AFTER INSERT, UPDATE, DELETE
AS  
BEGIN
	DECLARE @operation NVARCHAR(1)
	IF EXISTS(SELECT *
	FROM inserted)
	  IF EXISTS(SELECT *
	FROM deleted)
	    SELECT @operation = 'U'
	ELSE
	    SELECT @operation = 'I'
	ELSE
		IF EXISTS(SELECT *
	FROM deleted)
    SELECT @operation = 'D'

	DECLARE @guaranteeId UNIQUEIDENTIFIER;
	DECLARE @tariffRateCurrency NVARCHAR(255);
	DECLARE @capitalProtection DECIMAL(15,6);
	DECLARE @guranteedCoupon DECIMAL(15,6);
	DECLARE @guranteedCouponFrequency NVARCHAR(255);
	DECLARE @guaranteeDatesID NVARCHAR(255);
	
	IF @operation != 'D'
	
		SELECT @guaranteeId = GUARANTEE_ID, @tariffRateCurrency = TARIFF_RATE_CURRENCY, @capitalProtection = CAPITAL_PROTECTION, @guranteedCoupon = GUARANTEED_COUPON, @guranteedCouponFrequency = GUARANTEED_COUPON_FREQUENCY, @guaranteeDatesID = GUARANTEE_DATES_ID
		FROM inserted
	ELSE 
		SELECT @guaranteeId = GUARANTEE_ID, @tariffRateCurrency = TARIFF_RATE_CURRENCY, @capitalProtection = CAPITAL_PROTECTION, @guranteedCoupon = GUARANTEED_COUPON, @guranteedCouponFrequency = GUARANTEED_COUPON_FREQUENCY, @guaranteeDatesID = GUARANTEE_DATES_ID
		FROM deleted
	
	INSERT INTO PAS_IMPL.UL_GUARANTEES_HISTORY
		(GUARANTEE_HISTORY_ID, GUARANTEE_ID, TARIFF_RATE_CURRENCY, CAPITAL_PROTECTION, GUARANTEED_COUPON, GUARANTEED_COUPON_FREQUENCY, GUARANTEE_DATES_ID, OPERATION)
	VALUES
		(NEWID(), @guaranteeId, @tariffRateCurrency, @capitalProtection, @guranteedCoupon, @guranteedCouponFrequency, @guaranteeDatesID, @operation)
END

SET QUOTED_IDENTIFIER ON
GO

-- CREATE VIEW
CREATE VIEW [PAS_IMPL].[UL_GUARANTEES_VIEW]
AS
	SELECT
		[GUARANTEE_ID] AS ID,
		[TARIFF_RATE_CURRENCY] AS TARIFF_RATE_CURRENCY,
		[CAPITAL_PROTECTION] AS CAPITAL_PROTECTION,
		[GUARANTEED_COUPON] AS GUARANTEED_COUPON,
		[GUARANTEED_COUPON_FREQUENCY] AS GUARANTEED_COUPON_FREQUENCY,
		[GUARANTEE_DATES_ID] AS GUARANTEE_DATES_ID
	FROM [PAS_IMPL].[UL_GUARANTEES]
GO