-- CREATE TABLE UL_INVESTMENT_OBSERVATION_DATES
CREATE TABLE [PAS_IMPL].[UL_INVESTMENT_OBSERVATION_DATES]
(
	[INVESTMENT_OBSERVATION_DATES_ID] [UNIQUEIDENTIFIER],
	[TRANSH_TYPE] [NVARCHAR](MAX),
	CONSTRAINT [PK_UL_INVESTMENT_OBSERVATION_DATES]
PRIMARY KEY CLUSTERED ([INVESTMENT_OBSERVATION_DATES_ID] ASC)
)
GO

-- CREATE HISTORY TABLE
CREATE TABLE [PAS_IMPL].[UL_INVESTMENT_OBSERVATION_DATES_HISTORY]
(
	[INVESTMENT_OBSERVATION_DATES_HISTORY_ID] [UNIQUEIDENTIFIER],
	[INVESTMENT_OBSERVATION_DATES_ID] [UNIQUEIDENTIFIER],
	[OPERATION] [NVARCHAR](1),
	[TRANSH_TYPE] [NVARCHAR](MAX),
	CONSTRAINT [PK_UL_INVESTMENT_OBSERVATION_DATES_HISTORY]
PRIMARY KEY CLUSTERED ([INVESTMENT_OBSERVATION_DATES_HISTORY_ID] ASC)
)
GO

-- CREATE TRIGGER
CREATE TRIGGER [PAS_IMPL].[UL_INVESTMENT_OBSERVATION_DATES_HISTORY_TRIGGER]
ON [PAS_IMPL].[UL_INVESTMENT_OBSERVATION_DATES]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
	DECLARE @operation NVARCHAR(1)
	IF EXISTS(SELECT *
	FROM inserted)
	  IF EXISTS(SELECT *
	FROM deleted)
	    SELECT @operation = 'U'
	ELSE
	    SELECT @operation = 'I'
	ELSE
		IF EXISTS(SELECT *
	FROM deleted)
    SELECT @operation = 'D'

	DECLARE @id UNIQUEIDENTIFIER;
	DECLARE @transh_type NVARCHAR(MAX);

	IF @operation != 'D'

		SELECT @id = INVESTMENT_OBSERVATION_DATES_ID,
		       @transh_type = TRANSH_TYPE
		FROM inserted
	ELSE
		SELECT @id = INVESTMENT_OBSERVATION_DATES_ID,
		       @transh_type = TRANSH_TYPE
		FROM deleted

	INSERT INTO PAS_IMPL.UL_INVESTMENT_OBSERVATION_DATES_HISTORY
		(INVESTMENT_OBSERVATION_DATES_HISTORY_ID, INVESTMENT_OBSERVATION_DATES_ID, TRANSH_TYPE, OPERATION)
	VALUES
		(NEWID(), @id, @transh_type, @operation)
END

SET QUOTED_IDENTIFIER ON
GO

-- CREATE VIEW
CREATE VIEW [PAS_IMPL].[UL_INVESTMENT_OBSERVATION_DATES_VIEW]
AS
	SELECT
		[INVESTMENT_OBSERVATION_DATES_ID] AS INVESTMENT_OBSERVATION_DATES_ID,
		[TRANSH_TYPE] as TRANSH_TYPE
	FROM [PAS_IMPL].[UL_INVESTMENT_OBSERVATION_DATES]
GO