-- CREATE TABLE UL_PRODUCTS
CREATE TABLE [PAS_IMPL].[UL_PRODUCTS]
(
	[UL_PRODUCT_ID] [UNIQUEIDENTIFIER],
	[PRODUCT_ID] [UNIQUEIDENTIFIER],
	[PRODUCT_VERSION_ID] [UNIQUEIDENTIFIER],
	[INVESTMENT_OBSERVATION_DATES_ID] [UNIQUEIDENTIFIER],
	CONSTRAINT [PK_UL_PRODUCTS]
PRIMARY KEY CLUSTERED ([UL_PRODUCT_ID] ASC)
)
GO

ALTER TABLE [PAS_IMPL].[UL_PRODUCTS]  WITH CHECK ADD  CONSTRAINT [FK_PAS_IMPL_UL_PRODUCTS_INVESTMENT_OBSERVATION_DATES_ID] FOREIGN KEY([INVESTMENT_OBSERVATION_DATES_ID])
REFERENCES [PAS_IMPL].[UL_INVESTMENT_OBSERVATION_DATES] ([INVESTMENT_OBSERVATION_DATES_ID])
GO

ALTER TABLE [PAS_IMPL].[UL_PRODUCTS]  WITH CHECK ADD  CONSTRAINT [FK_PAS_IMPL_UL_PRODUCTS_PRODUCT_CODE] FOREIGN KEY([PRODUCT_ID])
REFERENCES [BFX_IMPL].[PRODUCTS] ([ID])
GO

-- CREATE HISTORY TABLE
CREATE TABLE [PAS_IMPL].[UL_PRODUCTS_HISTORY]
(
	[PRODUCT_HISTORY_ID] [UNIQUEIDENTIFIER],
	[UL_PRODUCT_ID] [UNIQUEIDENTIFIER],
	[PRODUCT_ID] [UNIQUEIDENTIFIER],
	[PRODUCT_VERSION_ID] [UNIQUEIDENTIFIER],
	[INVESTMENT_OBSERVATION_DATES_ID] [UNIQUEIDENTIFIER],
	[OPERATION] [NVARCHAR](1),
	CONSTRAINT [PK_UL_PRODUCTS_HISTORY]
PRIMARY KEY CLUSTERED ([PRODUCT_HISTORY_ID] ASC)
)
GO

-- CREATE TRIGGER
CREATE TRIGGER [PAS_IMPL].[UL_PRODUCTS_HISTORY_TRIGGER]
ON [PAS_IMPL].[UL_PRODUCTS]
AFTER INSERT, UPDATE, DELETE
AS  
BEGIN
	DECLARE @operation NVARCHAR(1)
	IF EXISTS(SELECT *
	FROM inserted)
	  IF EXISTS(SELECT *
	FROM deleted)
	    SELECT @operation = 'U'
	ELSE
	    SELECT @operation = 'I'
	ELSE
		IF EXISTS(SELECT *
	FROM deleted)
    SELECT @operation = 'D'

	DECLARE @ulProductId UNIQUEIDENTIFIER;
	DECLARE @productId UNIQUEIDENTIFIER;
	DECLARE @productVersionId UNIQUEIDENTIFIER;
	DECLARE @investmentObservationDatesId UNIQUEIDENTIFIER;

	IF @operation != 'D'
	
		SELECT @ulProductId = UL_PRODUCT_ID, @productId = PRODUCT_ID, @productVersionId = PRODUCT_VERSION_ID, @investmentObservationDatesId = INVESTMENT_OBSERVATION_DATES_ID
	FROM inserted
	ELSE 
		SELECT @ulProductId = UL_PRODUCT_ID, @productId = PRODUCT_ID, @productVersionId = PRODUCT_VERSION_ID, @investmentObservationDatesId = INVESTMENT_OBSERVATION_DATES_ID
	FROM deleted

	INSERT INTO PAS_IMPL.UL_PRODUCTS_HISTORY
		(PRODUCT_HISTORY_ID, UL_PRODUCT_ID, PRODUCT_ID, PRODUCT_VERSION_ID, INVESTMENT_OBSERVATION_DATES_ID, OPERATION)
	VALUES
		(NEWID(), @ulProductId, @productId, @productVersionId, @investmentObservationDatesId, @operation)
END

SET QUOTED_IDENTIFIER ON
GO

-- CREATE VIEW
CREATE VIEW [PAS_IMPL].[UL_PRODUCTS_VIEW]
AS
	SELECT
		[UL_PRODUCT_ID] AS UL_PRODUCT_ID,
		[PRODUCT_ID] AS PRODUCT_ID,
		[PRODUCT_VERSION_ID] AS PRODUCT_VERSION_ID,
		[INVESTMENT_OBSERVATION_DATES_ID] AS INVESTMENT_OBSERVATION_DATES_ID
	FROM [PAS_IMPL].[UL_PRODUCTS]
GO
