-- CREATE TABLE UL_PRODUCT_VERSION
CREATE TABLE [PAS_IMPL].[UL_PRODUCT_VERSION]
(
	[PRODUCT_VERSION_ID] [UNIQUEIDENTIFIER],
	[PRODUCT_MARKET_TYPE] [NVARCHAR](255),
	[STATUS] [NVARCHAR](255),
	[CREATION_DATE] [DATE],
	[APPROVAL_DATE] [DATE],
	[CONTRACT_CURRENCY] [NVARCHAR](255),
	[PRODUCT_TERM] [NVARCHAR](255),
	[GUARANTEE_FUND_ID] [UNIQUEIDENTIFIER],
	[GUARANTEE_ID] [UNIQUEIDENTIFIER],
	[GUARANTEE_FUND_SHARE] [DECIMAL](15,6),
	[INSURANCE_SHARE] [DECIMAL](15,6),
	[BUDGET_RULE_ID] [UNIQUEIDENTIFIER],
	[MOTIVATION] [DECIMAL](15,6),
	[TOTAL_ACQUIS_SHARE] [DECIMAL](15,6),
	[RISK_FUND_GROUP_ID] [UNIQUEIDENTIFIER],
	[RISK_FUND_SHARE] [DECIMAL](15,6),
	[SKMARGIN] [DECIMAL](15,6),
	[OPTIONS_ID] [NVARCHAR](255),
	[HISTORICAL_PROFITABILITY_ID] [UNIQUEIDENTIFIER],
	[UNIT_INITIAL_COST] [DECIMAL](15,6)
		CONSTRAINT [PK_UL_PRODUCT_VERSION]
PRIMARY KEY CLUSTERED ([PRODUCT_VERSION_ID] ASC)
)
GO

ALTER TABLE [PAS_IMPL].[UL_PRODUCT_VERSION]  WITH CHECK ADD  CONSTRAINT [FK_PAS_IMPL_UL_PRODUCT_VERSION_GUARANTEE_FUND_ID] FOREIGN KEY([GUARANTEE_FUND_ID])
REFERENCES [PAS_IMPL].[UL_GUARANTEE_FUND] ([GUARANTEE_FUND_ID])
GO

ALTER TABLE [PAS_IMPL].[UL_PRODUCT_VERSION]  WITH CHECK ADD  CONSTRAINT [FK_PAS_IMPL_UL_PRODUCT_VERSION_RISK_FUND_GROUP_ID] FOREIGN KEY([RISK_FUND_GROUP_ID])
REFERENCES [PAS_IMPL].[UL_RISK_FUND_GROUP] ([RISK_FUND_GROUP_ID])
GO

ALTER TABLE [PAS_IMPL].[UL_PRODUCT_VERSION]  WITH CHECK ADD  CONSTRAINT [FK_PAS_IMPL_UL_PRODUCT_VERSION_HISTORICAL_PROFITABILITY_ID] FOREIGN KEY([HISTORICAL_PROFITABILITY_ID])
REFERENCES [PAS_IMPL].[UL_HISTORICAL_PROFITABILITY] ([HISTORICAL_PROFITABILITY_ID])
GO

ALTER TABLE [PAS_IMPL].[UL_PRODUCT_VERSION]  WITH CHECK ADD  CONSTRAINT [FK_PAS_IMPL_UL_PRODUCT_VERSION_GUARANTEE_ID] FOREIGN KEY([GUARANTEE_ID])
REFERENCES [PAS_IMPL].[UL_GUARANTEES] ([GUARANTEE_ID])
GO

-- CREATE HISTORY TABLE
CREATE TABLE [PAS_IMPL].[UL_PRODUCT_VERSION_HISTORY]
(
	[PRODUCT_VERSION_HISTORY_ID] [UNIQUEIDENTIFIER],
	[PRODUCT_VERSION_ID] [UNIQUEIDENTIFIER],
	[PRODUCT_MARKET_TYPE] [NVARCHAR](255),
	[STATUS] [NVARCHAR](255),
	[CREATION_DATE] [DATE],
	[APPROVAL_DATE] [DATE],
	[GUARANTEE_FUND_ID] [UNIQUEIDENTIFIER],
	[GUARANTEE_ID] [UNIQUEIDENTIFIER],
	[GUARANTEE_FUND_SHARE] [DECIMAL](15,6),
	[INSURANCE_SHARE] [DECIMAL](15,6),
	[BUDGET_RULE_ID] [UNIQUEIDENTIFIER],
	[MOTIVATION] [DECIMAL](15,6),
	[TOTAL_ACQUIS_SHARE] [DECIMAL](15,6),
	[RISK_FUND_GROUP_ID] [UNIQUEIDENTIFIER],
	[RISK_FUND_SHARE] [DECIMAL](15,6),
	[SKMARGIN] [DECIMAL](15,6),
	[OPTIONS_ID] [NVARCHAR](255),
	[HISTORICAL_PROFITABILITY_ID] [NVARCHAR](255),
	[UNIT_INITIAL_COST] [DECIMAL](15,6),
	[OPERATION] [NVARCHAR](1),
	CONSTRAINT [PK_UL_PRODUCT_VERSION_HISTORY]
PRIMARY KEY CLUSTERED ([PRODUCT_VERSION_HISTORY_ID] ASC)
)
GO

-- CREATE TRIGGER
CREATE TRIGGER [PAS_IMPL].[UL_PRODUCT_VERSION_HISTORY_TRIGGER]
ON [PAS_IMPL].[UL_PRODUCT_VERSION]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
	DECLARE @operation NVARCHAR(1)
	IF EXISTS(SELECT *
	FROM inserted)
	  IF EXISTS(SELECT *
	FROM deleted)
	    SELECT @operation = 'U'
	ELSE
	    SELECT @operation = 'I'
	ELSE
		IF EXISTS(SELECT *
	FROM deleted)
    SELECT @operation = 'D'

	DECLARE @productVersionId UNIQUEIDENTIFIER;
	DECLARE @productMarketType NVARCHAR(255);
	DECLARE @status NVARCHAR(255);
	DECLARE @creationDate DATE;
	DECLARE @approvalDate DATE;
	DECLARE @guaranteeFundId UNIQUEIDENTIFIER;
	DECLARE @guaranteeId UNIQUEIDENTIFIER;
	DECLARE @guaranteeFundShare DECIMAL(15,6);
	DECLARE @insuranceShare DECIMAL(15,6);
	DECLARE @budgetRuleId UNIQUEIDENTIFIER;
	DECLARE @motivation DECIMAL(15,6);
	DECLARE @totalAcquisShare DECIMAL(15,6);
	DECLARE @riskFundGroupId  UNIQUEIDENTIFIER;
	DECLARE @riskFundShare DECIMAL(15,6);
	DECLARE @skmargin DECIMAL(15,6);
	DECLARE @optionsId NVARCHAR(255);
	DECLARE @paymentFrequency NVARCHAR(255);
	DECLARE @endowmentPaymentOptions NVARCHAR(255);
	DECLARE @productType NVARCHAR(255);
	DECLARE @productSubtype NVARCHAR(255);
	DECLARE @historicalProfitAbilityId NVARCHAR(255);
	DECLARE @unitInitialCost DECIMAL(15,6);


	IF @operation != 'D'
		SELECT
		@productVersionId = PRODUCT_VERSION_ID,
		@productMarketType = PRODUCT_MARKET_TYPE,
		@status = STATUS,
		@creationDate = CREATION_DATE,
		@approvalDate = APPROVAL_DATE,
		@guaranteeFundId = GUARANTEE_FUND_ID,
		@guaranteeId = GUARANTEE_ID,
		@guaranteeFundShare = GUARANTEE_FUND_SHARE,
		@insuranceShare = INSURANCE_SHARE,
		@budgetRuleId = BUDGET_RULE_ID,
		@motivation = MOTIVATION,
		@totalAcquisShare = TOTAL_ACQUIS_SHARE,
		@riskFundGroupId = RISK_FUND_GROUP_ID,
		@riskFundShare = RISK_FUND_SHARE,
		@skmargin = SKMARGIN,
		@optionsId = OPTIONS_ID,
		@historicalProfitAbilityId = HISTORICAL_PROFITABILITY_ID,
		@unitInitialCost = UNIT_INITIAL_COST

	FROM inserted
	ELSE
		SELECT
		@productVersionId = PRODUCT_VERSION_ID,
		@productMarketType = PRODUCT_MARKET_TYPE,
		@status = STATUS,
		@creationDate = CREATION_DATE,
		@approvalDate = APPROVAL_DATE,
		@guaranteeFundId = GUARANTEE_FUND_ID,
		@guaranteeId = GUARANTEE_ID,
		@guaranteeFundShare = GUARANTEE_FUND_SHARE,
		@insuranceShare = INSURANCE_SHARE,
		@budgetRuleId = BUDGET_RULE_ID,
		@motivation = MOTIVATION,
		@totalAcquisShare = TOTAL_ACQUIS_SHARE,
		@riskFundGroupId = RISK_FUND_GROUP_ID,
		@riskFundShare = RISK_FUND_SHARE,
		@skmargin = SKMARGIN,
		@optionsId = OPTIONS_ID,
		@historicalProfitAbilityId = HISTORICAL_PROFITABILITY_ID,
		@unitInitialCost = UNIT_INITIAL_COST

	FROM deleted

	INSERT INTO PAS_IMPL.UL_PRODUCT_VERSION_HISTORY
		(PRODUCT_VERSION_HISTORY_ID, PRODUCT_VERSION_ID, PRODUCT_MARKET_TYPE, STATUS, CREATION_DATE, APPROVAL_DATE, GUARANTEE_FUND_ID, GUARANTEE_ID, GUARANTEE_FUND_SHARE, INSURANCE_SHARE, BUDGET_RULE_ID, MOTIVATION, TOTAL_ACQUIS_SHARE, RISK_FUND_GROUP_ID, RISK_FUND_SHARE, SKMARGIN, OPTIONS_ID, HISTORICAL_PROFITABILITY_ID, UNIT_INITIAL_COST, OPERATION)
	VALUES
		(NEWID(), @productVersionId, @productMarketType, @status, @creationDate, @approvalDate, @guaranteeFundId, @guaranteeId, @guaranteeFundShare, @insuranceShare, @budgetRuleId, @motivation, @totalAcquisShare, @riskFundGroupId, @riskFundShare, @skmargin, @optionsId, @historicalProfitAbilityId, @unitInitialCost, @operation)



END

SET QUOTED_IDENTIFIER ON
GO

-- CREATE VIEW
CREATE VIEW [PAS_IMPL].[UL_PRODUCT_VERSION_VIEW]
AS
	SELECT
		[PRODUCT_VERSION_ID] AS PRODUCT_VERSION_ID,
		[STATUS] AS STATUS,
		[CREATION_DATE] AS CREATION_DATE,
		[APPROVAL_DATE] AS APPROVAL_DATE,
		[GUARANTEE_FUND_ID] AS GUARANTEE_FUND_ID,
		[GUARANTEE_ID] AS GUARANTEE_ID,
		[GUARANTEE_FUND_SHARE] AS GUARANTEE_FUND_SHARE,
		[INSURANCE_SHARE] AS INSURANCE_SHARE,
		[BUDGET_RULE_ID] AS BUDGET_RULE_ID,
		[MOTIVATION] AS MOTIVATION,
		[TOTAL_ACQUIS_SHARE] AS TOTAL_ACQUIS_SHARE,
		[RISK_FUND_GROUP_ID] AS RISK_FUND_GROUP_ID,
		[RISK_FUND_SHARE] AS RISK_FUND_SHARE,
		[SKMARGIN] AS SKMARGIN,
		[OPTIONS_ID] AS OPTIONS_ID,
		[HISTORICAL_PROFITABILITY_ID] AS HISTORICAL_PROFITABILITY_ID,
		[UNIT_INITIAL_COST] as UNIT_INITIAL_COST
	FROM [PAS_IMPL].[UL_PRODUCT_VERSION]
GO