-- CREATE TABLE UL_PIP_RF
CREATE TABLE [PAS_IMPL].[UL_PIP_RF]
(
	[PIP_RF_ID] [UNIQUEIDENTIFIER],
	[PIP_CATEGORY] [NVARCHAR](255),
	[PAY_OFF_ID] [UNIQUEIDENTIFIER],
	[BASIC_ASSETS_GROUP_ID] [UNIQUEIDENTIFIER],
	[TARIFF_RATE_CURRENCY] [NVARCHAR](255),
	[IS_PIP_QUANTUMED] [NVARCHAR](255),
	[MFEE] [DECIMAL](15,6),
		CONSTRAINT [PK_UL_PIP_RF]
PRIMARY KEY CLUSTERED ([PIP_RF_ID] ASC)
)
GO

ALTER TABLE [PAS_IMPL].[UL_PIP_RF]  WITH CHECK ADD  CONSTRAINT [FK_PAS_IMPL_UL_PIP_RF_BASIC_ASSET_GROUP_ID] FOREIGN KEY([BASIC_ASSETS_GROUP_ID])
REFERENCES [PAS_IMPL].[UL_BASIC_ASSETS_GROUP] ([BASIC_ASSETS_GROUP_ID])
GO


-- CREATE HISTORY TABLE
CREATE TABLE [PAS_IMPL].[UL_PIP_RF_HISTORY]
(
	[PIP_RF_HISTORY_ID] [UNIQUEIDENTIFIER],
	[PIP_RF_ID] [UNIQUEIDENTIFIER],
	[PIP_CATEGORY] [NVARCHAR](255),
	[PAY_OFF_ID] [NVARCHAR](255),
	[BASIC_ASSETS_GROUP_ID] [UNIQUEIDENTIFIER],
	[TARIFF_RATE_CURRENCY] [NVARCHAR](255),
	[IS_PIP_QUANTUMED] [NVARCHAR](255),
	[MFEE] [DECIMAL](15,6),
	[OPERATION] [NVARCHAR](1),
	CONSTRAINT [PK_UL_PIP_RF_HISTORY]
PRIMARY KEY CLUSTERED ([PIP_RF_HISTORY_ID] ASC)
)
GO

-- CREATE TRIGGER
CREATE TRIGGER [PAS_IMPL].[UL_PIP_RF_HISTORY_TRIGGER]
ON [PAS_IMPL].[UL_PIP_RF]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
	DECLARE @operation NVARCHAR(1)
	IF EXISTS(SELECT *
	FROM inserted)
	  IF EXISTS(SELECT *
	FROM deleted)
	    SELECT @operation = 'U'
	ELSE
	    SELECT @operation = 'I'
	ELSE
		IF EXISTS(SELECT *
	FROM deleted)
    SELECT @operation = 'D'

	DECLARE @pipRfId UNIQUEIDENTIFIER;
	DECLARE @pipCategory NVARCHAR(255);
	DECLARE @payOffId NVARCHAR(255);
	DECLARE @basicAssetsGroupId UNIQUEIDENTIFIER;
	DECLARE @tariffRateCurrency NVARCHAR(255);
	DECLARE @isPipQuantumed NVARCHAR(255);
	DECLARE @mFee DECIMAL(15,6);

	IF @operation != 'D'

		SELECT @pipRfId = PIP_RF_ID, @pipCategory = PIP_CATEGORY, @payOffId = PAY_OFF_ID, @basicAssetsGroupId = BASIC_ASSETS_GROUP_ID, @tariffRateCurrency = TARIFF_RATE_CURRENCY, @isPipQuantumed = IS_PIP_QUANTUMED, @mFee = MFEE
	FROM inserted
	ELSE
		SELECT @pipRfId = PIP_RF_ID, @pipCategory = PIP_CATEGORY, @payOffId = PAY_OFF_ID, @basicAssetsGroupId = BASIC_ASSETS_GROUP_ID, @tariffRateCurrency = TARIFF_RATE_CURRENCY, @isPipQuantumed = IS_PIP_QUANTUMED, @mFee = MFEE
	FROM deleted

	INSERT INTO PAS_IMPL.UL_PIP_RF_HISTORY
		(PIP_RF_HISTORY_ID, PIP_RF_ID, PIP_CATEGORY, PAY_OFF_ID, BASIC_ASSETS_GROUP_ID, TARIFF_RATE_CURRENCY, IS_PIP_QUANTUMED, MFEE, OPERATION)
	VALUES
		(NEWID(), @pipRfId, @pipCategory, @payOffId, @basicAssetsGroupId, @tariffRateCurrency, @isPipQuantumed, @mFee, @operation)
END

SET QUOTED_IDENTIFIER ON
GO

-- CREATE VIEW
CREATE VIEW [PAS_IMPL].[UL_PIP_RF_VIEW]
AS
	SELECT
		[PIP_RF_ID] AS PIP_RF_ID,
		[PIP_CATEGORY] AS PIP_CATEGORY,
		[PAY_OFF_ID] AS PAY_OFF_ID,
		[BASIC_ASSETS_GROUP_ID] AS BASIC_ASSETS_GROUP_ID,
		[TARIFF_RATE_CURRENCY] AS TARIFF_RATE_CURRENCY,
		[IS_PIP_QUANTUMED] AS IS_PIP_QUANTUMED,
		[MFEE] AS MFEE
	FROM [PAS_IMPL].[UL_PIP_RF]
GO