-- CREATE TABLE UL_PIP_GF
CREATE TABLE [PAS_IMPL].[UL_PIP_GF]
(
	[PIP_GF_ID] [UNIQUEIDENTIFIER],
	[RATE_MIX_ID] [UNIQUEIDENTIFIER],
	[MFEE] [DECIMAL](15,6),
	[TARIFF_RATE] [DECIMAL](15,6),
	[CURRENCY] [NVARCHAR](255),
	CONSTRAINT [PK_UL_PIP_GF]
PRIMARY KEY CLUSTERED ([PIP_GF_ID] ASC)
)
GO

ALTER TABLE [PAS_IMPL].[UL_PIP_GF]  WITH CHECK ADD  CONSTRAINT [FK_PAS_IMPL_UL_PIP_GF_RATE_MIX_ID] FOREIGN KEY([RATE_MIX_ID])
REFERENCES [PAS_IMPL].[UL_RATE_MIX] ([RATE_MIX_ID])
GO

-- CREATE HISTORY TABLE
CREATE TABLE [PAS_IMPL].[UL_PIP_GF_HISTORY]
(
	[PIP_GF_HISTORY_ID] [UNIQUEIDENTIFIER],
	[PIP_GF_ID] [UNIQUEIDENTIFIER],
	[RATE_MIX_ID] [UNIQUEIDENTIFIER],
	[MFEE] [DECIMAL](15,6),
	[TARIFF_RATE] [DECIMAL](15,6),
	[CURRENCY] [NVARCHAR](255),
	[OPERATION] [NVARCHAR](1),
	CONSTRAINT [PK_UL_PIP_GF_HISTORY]
PRIMARY KEY CLUSTERED ([PIP_GF_HISTORY_ID] ASC)
)
GO

-- CREATE TRIGGER
CREATE TRIGGER [PAS_IMPL].[UL_PIP_GF_HISTORY_TRIGGER]
ON [PAS_IMPL].[UL_PIP_GF]
AFTER INSERT, UPDATE, DELETE
AS  
BEGIN
	DECLARE @operation NVARCHAR(1)
	IF EXISTS(SELECT *
	FROM inserted)
	  IF EXISTS(SELECT *
	FROM deleted)
	    SELECT @operation = 'U'
	ELSE
	    SELECT @operation = 'I'
	ELSE
		IF EXISTS(SELECT *
	FROM deleted)
    SELECT @operation = 'D'

	DECLARE @pipGFId UNIQUEIDENTIFIER;
	DECLARE @rateMixID UNIQUEIDENTIFIER;
	DECLARE @mfee DECIMAL(15,6);
	DECLARE @tariffRate DECIMAL(15,6);
	DECLARE @currency NVARCHAR(255);

	IF @operation != 'D'
	
		SELECT @pipGFId = PIP_GF_ID, @rateMixID=RATE_MIX_ID, @mfee = MFEE, @tariffRate = TARIFF_RATE, @currency = CURRENCY
	FROM inserted
	ELSE 
		SELECT @pipGFId = PIP_GF_ID, @rateMixID=RATE_MIX_ID, @mfee = MFEE, @tariffRate = TARIFF_RATE, @currency = CURRENCY
	FROM deleted

	INSERT INTO PAS_IMPL.UL_PIP_GF_HISTORY
		(PIP_GF_HISTORY_ID, PIP_GF_ID, RATE_MIX_ID, MFEE, TARIFF_RATE, CURRENCY, OPERATION)
	VALUES
		(NEWID(), @pipGFId, @rateMixID, @mfee, @tariffRate, @currency, @operation)
END

SET QUOTED_IDENTIFIER ON
GO

-- CREATE VIEW
CREATE VIEW [PAS_IMPL].[UL_PIP_GF_VIEW]
AS
	SELECT
		[PIP_GF_ID] AS PIP_GF_ID,
		[RATE_MIX_ID] AS RATE_MIX_ID,
		[MFEE] AS MFEE,
		[TARIFF_RATE] AS TARIFF_RATE,
		[CURRENCY] AS CURRENCY
	FROM [PAS_IMPL].[UL_PIP_GF]
GO