-- CREATE TABLE UL_RISK_FUND
CREATE TABLE [PAS_IMPL].[UL_RISK_FUND]
(
	[RISK_FUND_ID] [UNIQUEIDENTIFIER],
	[RISK_FUND_GROUP_ID] [UNIQUEIDENTIFIER],
	[PIP_RF_ID] [UNIQUEIDENTIFIER],
	[PIP_SHARE] [DECIMAL](15,6),
	[PIP_TARIFF_QUOTATION] [DECIMAL](15,6),
	[KU_SIZE] [DECIMAL](15,6),
	[COUPON_SIZE] [DECIMAL](15,6),
	[CASH_ID] [UNIQUEIDENTIFIER],
	CONSTRAINT [PK_UL_RISK_FUND]
PRIMARY KEY CLUSTERED ([RISK_FUND_ID] ASC)
)
GO

ALTER TABLE [PAS_IMPL].[UL_RISK_FUND]  WITH CHECK ADD  CONSTRAINT [FK_PAS_IMPL_UL_RISK_FUND_PIP_RF_ID] FOREIGN KEY([PIP_RF_ID])
REFERENCES [PAS_IMPL].[UL_PIP_RF] ([PIP_RF_ID])
GO

ALTER TABLE [PAS_IMPL].[UL_RISK_FUND]  WITH CHECK ADD  CONSTRAINT [FK_PAS_IMPL_UL_RISK_FUND_CASH_ID] FOREIGN KEY([CASH_ID])
REFERENCES [PAS_IMPL].[UL_CASH] ([CASH_ID])
GO

ALTER TABLE [PAS_IMPL].[UL_RISK_FUND]  WITH CHECK ADD  CONSTRAINT [FK_PAS_IMPL_UL_RISK_FUND_GROUP_ID] FOREIGN KEY([RISK_FUND_GROUP_ID])
REFERENCES [PAS_IMPL].[UL_RISK_FUND_GROUP] ([RISK_FUND_GROUP_ID])
GO

-- CREATE HISTORY TABLE
CREATE TABLE [PAS_IMPL].[UL_RISK_FUND_HISTORY]
(
	[RISK_FUND_HISTORY_ID] [UNIQUEIDENTIFIER],
	[RISK_FUND_ID] [UNIQUEIDENTIFIER],
	[RISK_FUND_GROUP_ID] [UNIQUEIDENTIFIER],
	[PIP_RF_ID] [UNIQUEIDENTIFIER],
	[PIP_SHARE] [DECIMAL](15,6),
	[PIP_TARIFF_QUOTATION] [DECIMAL](15,6),
	[KU_SIZE] [DECIMAL](15,6),
	[COUPON_SIZE] [DECIMAL](15,6),
	[CASH_ID] [UNIQUEIDENTIFIER],
	[OPERATION] [NVARCHAR](1),
	CONSTRAINT [PK_UL_RISK_FUND_HISTORY]
PRIMARY KEY CLUSTERED ([RISK_FUND_HISTORY_ID] ASC)
)
GO

-- CREATE TRIGGER
CREATE TRIGGER [PAS_IMPL].[UL_RISK_FUND_HISTORY_TRIGGER]
ON [PAS_IMPL].[UL_RISK_FUND]
AFTER INSERT, UPDATE, DELETE
AS  
BEGIN
	DECLARE @operation NVARCHAR(1)
	IF EXISTS(SELECT *
	FROM inserted)
	  IF EXISTS(SELECT *
	FROM deleted)
	    SELECT @operation = 'U'
	ELSE
	    SELECT @operation = 'I'
	ELSE
		IF EXISTS(SELECT *
	FROM deleted)
    SELECT @operation = 'D'

	DECLARE @riskFundId UNIQUEIDENTIFIER;
	DECLARE @riskFundGroupId UNIQUEIDENTIFIER;
	DECLARE @pipRfId UNIQUEIDENTIFIER;
	DECLARE @pipShare DECIMAL(15,6);
	DECLARE @pipTariffQuotation DECIMAL(15,6);
	DECLARE @kuSize DECIMAL(15,6);
	DECLARE @couponSize DECIMAL(15,6);
	DECLARE @cashId UNIQUEIDENTIFIER;

	IF @operation != 'D'
	
		SELECT @riskFundId = RISK_FUND_ID, @riskFundGroupId = RISK_FUND_GROUP_ID, @pipRfId = PIP_RF_ID, @pipShare = PIP_SHARE, @pipTariffQuotation = PIP_TARIFF_QUOTATION, @kuSize = KU_SIZE, @couponSize = COUPON_SIZE, @cashId = CASH_ID
	FROM inserted
	ELSE 
		SELECT @riskFundId = RISK_FUND_ID, @riskFundGroupId = RISK_FUND_GROUP_ID, @pipRfId = PIP_RF_ID, @pipShare = PIP_SHARE, @pipTariffQuotation = PIP_TARIFF_QUOTATION, @kuSize = KU_SIZE, @couponSize = COUPON_SIZE, @cashId = CASH_ID
	FROM deleted

	INSERT INTO PAS_IMPL.UL_RISK_FUND_HISTORY
		(RISK_FUND_HISTORY_ID, RISK_FUND_ID, RISK_FUND_GROUP_ID, PIP_RF_ID, PIP_SHARE, PIP_TARIFF_QUOTATION, KU_SIZE, COUPON_SIZE, CASH_ID, OPERATION)
	VALUES
		(NEWID(), @riskFundId, @riskFundGroupId, @pipRfId, @pipShare, @pipTariffQuotation, @kuSize, @couponSize, @cashId, @operation)
END

SET QUOTED_IDENTIFIER ON
GO

-- CREATE VIEW
CREATE VIEW [PAS_IMPL].[UL_RISK_FUND_VIEW]
AS
	SELECT
		[RISK_FUND_ID] AS RISK_FUND_ID,
		[RISK_FUND_GROUP_ID] AS RISK_FUND_GROUP_ID,
		[PIP_RF_ID] AS PIP_RF_ID,
		[PIP_SHARE] AS PIP_SHARE,
		[PIP_TARIFF_QUOTATION] AS PIP_TARIFF_QUOTATION,
		[KU_SIZE] AS KU_SIZE,
		[COUPON_SIZE] AS COUPON_SIZE,
		[CASH_ID] AS CASH_ID
	FROM [PAS_IMPL].[UL_RISK_FUND]
GO