-- CREATE TABLE UL_STOCKS
CREATE TABLE [PAS_IMPL].[UL_STOCKS]
(
	[MIC] [NVARCHAR](255),
	[OPERATING_MIC] [NVARCHAR](255),
	[OPRT_SGMT] [NVARCHAR](255),
	[MARKET_NAME] [NVARCHAR](255),
	[ISO_COUNTRY_CODE] [NVARCHAR](255),
	[CITY] [NVARCHAR](255),
	[WEBSITE] [NVARCHAR](255),
	[STATUS] [NVARCHAR](255),
	[COMMENTS] [NVARCHAR](255)
		CONSTRAINT [PK_UL_STOCKS]
PRIMARY KEY CLUSTERED ([MIC] ASC)
)
GO

-- CREATE HISTORY TABLE
CREATE TABLE [PAS_IMPL].[UL_STOCKS_HISTORY]
(
	[STOCK_HISTORY_ID] [UNIQUEIDENTIFIER],
	[MIC] [NVARCHAR](255),
	[OPERATING_MIC] [NVARCHAR](255),
	[OPRT_SGMT] [NVARCHAR](255),
	[MARKET_NAME] [NVARCHAR](255),
	[ISO_COUNTRY_CODE] [NVARCHAR](255),
	[CITY] [NVARCHAR](255),
	[WEBSITE] [NVARCHAR](255),
	[STATUS] [NVARCHAR](255),
	[COMMENTS] [NVARCHAR](255),
	[OPERATION] [NVARCHAR](1),
	CONSTRAINT [PK_UL_STOCKS_HISTORY]
PRIMARY KEY CLUSTERED ([STOCK_HISTORY_ID] ASC)
)
GO

-- CREATE TRIGGER
CREATE TRIGGER [PAS_IMPL].[UL_STOCKS_HISTORY_TRIGGER]
ON [PAS_IMPL].[UL_STOCKS]
AFTER INSERT, UPDATE, DELETE
AS  
BEGIN
	DECLARE @operation NVARCHAR(1)
	IF EXISTS(SELECT *
	FROM inserted)
	  IF EXISTS(SELECT *
	FROM deleted)
	    SELECT @operation = 'U'
	ELSE
	    SELECT @operation = 'I'
	ELSE
		IF EXISTS(SELECT *
	FROM deleted)
    SELECT @operation = 'D'

	DECLARE @mic [NVARCHAR](255);
	DECLARE @operating_mic [NVARCHAR](255);
	DECLARE @oprt_sgmt [NVARCHAR](255);
	DECLARE @marketName [NVARCHAR](255);
	DECLARE @iso_country_code [NVARCHAR](255);
	DECLARE @city [NVARCHAR](255);
	DECLARE @website [NVARCHAR](255);
	DECLARE @status [NVARCHAR](255);
	DECLARE @comments [NVARCHAR](255);

	IF @operation != 'D'
	
		SELECT @mic = MIC, @operating_mic = OPERATING_MIC, @oprt_sgmt = OPRT_SGMT, @marketName = MARKET_NAME, @iso_country_code = ISO_COUNTRY_CODE, @city = CITY, @website = WEBSITE, @status = STATUS, @comments = COMMENTS
	FROM inserted
	ELSE 
		SELECT @mic = MIC, @operating_mic = OPERATING_MIC, @oprt_sgmt = OPRT_SGMT, @marketName = MARKET_NAME, @iso_country_code = ISO_COUNTRY_CODE, @city = CITY, @website = WEBSITE, @status = STATUS, @comments = COMMENTS
	FROM deleted

	INSERT INTO PAS_IMPL.UL_STOCKS_HISTORY
		(STOCK_HISTORY_ID, MIC, OPERATING_MIC, OPRT_SGMT, MARKET_NAME, ISO_COUNTRY_CODE, CITY, WEBSITE, STATUS, COMMENTS, OPERATION)
	VALUES
		(NEWID(), @mic, @operating_mic, @oprt_sgmt, @marketName, @iso_country_code, @city, @website, @status, @comments, @operation)
END

SET QUOTED_IDENTIFIER ON
GO

-- CREATE VIEW
CREATE VIEW [PAS_IMPL].[UL_STOCKS_VIEW]
AS
	SELECT
		[MIC] AS MIC,
		[OPERATING_MIC] AS OPERATING_MIC,
		[OPRT_SGMT] AS OPRT_SGMT,
		[MARKET_NAME] AS MARKET,
		[ISO_COUNTRY_CODE] AS ISO_COUNTRY_CODE,
		[CITY] AS CITY,
		[WEBSITE] AS WEBSITE,
		[STATUS] AS STATUS,
		[COMMENTS] AS COMMENTS
	FROM [PAS_IMPL].[UL_STOCKS]
GO