IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_CTR_MOD_EXECUTION_ID'
	AND object_id = OBJECT_ID('BFX_IMPL.CONTRACT_MODIFICATION_HISTORY') ) BEGIN
	CREATE INDEX IDX_AA_CTR_MOD_EXECUTION_ID ON
BFX_IMPL.CONTRACT_MODIFICATION_HISTORY(EXECUTION_ID)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_CTR_MOD_CONTRACT_NUMBER'
	AND object_id = OBJECT_ID('BFX_IMPL.CONTRACT_MODIFICATION_HISTORY') ) BEGIN
	CREATE INDEX IDX_AA_CTR_MOD_CONTRACT_NUMBER ON
BFX_IMPL.CONTRACT_MODIFICATION_HISTORY(CONTRACT_NUMBER)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_CTR_MOD_ORIGINAL_CONTRACT_NUMBER'
	AND object_id = OBJECT_ID('BFX_IMPL.CONTRACT_MODIFICATION_HISTORY') ) BEGIN
	CREATE INDEX IDX_AA_CTR_MOD_ORIGINAL_CONTRACT_NUMBER ON
BFX_IMPL.CONTRACT_MODIFICATION_HISTORY(ORIGINAL_CONTRACT_NUMBER)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_CTR_MOD_MODIFICATION_TYPE'
	AND object_id = OBJECT_ID('BFX_IMPL.CONTRACT_MODIFICATION_HISTORY') ) BEGIN
	CREATE INDEX IDX_AA_CTR_MOD_MODIFICATION_TYPE ON
BFX_IMPL.CONTRACT_MODIFICATION_HISTORY(MODIFICATION_TYPE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_AA_CTR_MOD_SEQ_NUMBER'
	AND object_id = OBJECT_ID('BFX_IMPL.CONTRACT_MODIFICATION_HISTORY') ) BEGIN
	CREATE INDEX IDX_AA_CTR_MOD_SEQ_NUMBER ON
BFX_IMPL.CONTRACT_MODIFICATION_HISTORY(SEQ_NUMBER)
END