module.exports = function resultMapping(input) {

    const result = input.data.map(item => {
        return {
            contractNumber: item.resultData.contractNumber || '',
            sysCreatedOn: item.resultData.sysCreatedOn || '',
            startDate: item.resultData.startDate || '',
            endDate: item.resultData.endDate || '',
            insuranceTerms: item.resultData.insuranceTerms || '',
            productDescription: item.resultData.productDescription || '',
            investmentStrategyDescription: item.resultData.investmentStrategyDescription || '',
            baseActiveDescription: item.resultData.baseActiveDescription || '',
            windowStartDate: item.resultData.windowStartDate || '',
            windowEndDate: item.resultData.windowEndDate || '',
            purchaseDate: item.resultData.purchaseDate || '',
            didBeginDate: item.resultData.didBeginDate || '',
            didEndDate: item.resultData.didEndDate || '',
            currencyCode: item.resultData.currencyCode || '',
            couponPeriodWatchDate1: item.resultData.couponPeriodWatchDate1 || '',
            couponPeriodBeginDate1: item.resultData.couponPeriodBeginDate1 || '',
            couponPeriodEndDate1: item.resultData.couponPeriodEndDate1 || '',
            barrier1: item.resultData.barrier1 || '',
            barrierAutoCall1: item.resultData.barrierAutoCall1 || '',
            couponPeriodWatchDate2: item.resultData.couponPeriodWatchDate2 || '',
            couponPeriodBeginDate2: item.resultData.couponPeriodBeginDate2 || '',
            couponPeriodEndDate2: item.resultData.couponPeriodEndDate2 || '',
            barrier2: item.resultData.barrier2 || '',
            barrierAutoCall2: item.resultData.barrierAutoCall2 || '',
            couponPeriodWatchDate3: item.resultData.couponPeriodWatchDate3 || '',
            couponPeriodBeginDate3: item.resultData.couponPeriodBeginDate3 || '',
            couponPeriodEndDate3: item.resultData.couponPeriodEndDate3 || '',
            barrier3: item.resultData.barrier3 || '',
            barrierAutoCall3: item.resultData.barrierAutoCall3 || '',
            couponPeriodWatchDate4: item.resultData.couponPeriodWatchDate4 || '',
            couponPeriodBeginDate4: item.resultData.couponPeriodBeginDate4 || '',
            couponPeriodEndDate4: item.resultData.couponPeriodEndDate4 || '',
            barrier4: item.resultData.barrier4 || '',
            barrierAutoCall4: item.resultData.barrierAutoCall4 || '',
            couponPeriodWatchDate5: item.resultData.couponPeriodWatchDate5 || '',
            couponPeriodBeginDate5: item.resultData.couponPeriodBeginDate5 || '',
            couponPeriodEndDate5: item.resultData.couponPeriodEndDate5 || '',
            barrier5: item.resultData.barrier5 || '',
            barrierAutoCall5: item.resultData.barrierAutoCall5 || '',
            endowmentPercent: item.resultData.endowmentPercent || '',
            dischargeDate: item.resultData.dischargeDate || '',
            participationCoeff: item.resultData.participationCoeff || '',
            strategyType: item.resultData.strategyType || '',
            optionPrice: item.resultData.optionPrice || '',
            partnerDescription: item.resultData.partnerDescription || '',
            agentAgreementNumber: item.resultData.agentAgreementNumber || '',
            commission: item.resultData.commission || '',
            systemName: item.resultData.systemName || '',
            hedgeCost: item.resultData.hedgeCost || '',
            spreadBA: item.resultData.spreadBA || '',
            payOffShortDescription: item.resultData.payOffShortDescription || '',
            toolType: item.resultData.toolType || '',
            measureToolNominal: item.resultData.measureToolNominal || '',
            calculatingAgent: item.resultData.calculatingAgent || '',
            priceOfMeasureTool: item.resultData.priceOfMeasureTool || '',
            partOfPremiumForTool: item.resultData.partOfPremiumForTool || ''
        };
    });

    return result;

};
