IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_INS_ACT_NUMBER'
	AND object_id = OBJECT_ID('ACC_IMPL.PO_INSURANCE_ACT_SAT') ) BEGIN
	CREATE INDEX IDX_PO_INS_ACT_NUMBER ON
ACC_IMPL.PO_INSURANCE_ACT_SAT(ACT_NUMBER)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_INS_ACT_ACT_DATE'
	AND object_id = OBJECT_ID('ACC_IMPL.PO_INSURANCE_ACT_SAT') ) BEGIN
	CREATE INDEX IDX_PO_INS_ACT_ACT_DATE ON
ACC_IMPL.PO_INSURANCE_ACT_SAT(ACT_DATE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_INS_ACT_EXECUTOR_PARTY_CODE'
	AND object_id = OBJECT_ID('ACC_IMPL.PO_INSURANCE_ACT_SAT') ) BEGIN
	CREATE INDEX IDX_PO_INS_ACT_EXECUTOR_PARTY_CODE ON
ACC_IMPL.PO_INSURANCE_ACT_SAT(EXECUTOR_PARTY_CODE)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_INS_ACT_SIGNED_ON'
	AND object_id = OBJECT_ID('ACC_IMPL.PO_INSURANCE_ACT_SAT') ) BEGIN
	CREATE INDEX IDX_PO_INS_ACT_SIGNED_ON ON
ACC_IMPL.PO_INSURANCE_ACT_SAT(SIGNED_ON)
END

------------------

IF NOT EXISTS (
SELECT
	1
FROM
	sys.indexes
WHERE
	name = 'IDX_PO_INS_ACT_SIGNER_CODE'
	AND object_id = OBJECT_ID('ACC_IMPL.PO_INSURANCE_ACT_SAT') ) BEGIN
	CREATE INDEX IDX_PO_INS_ACT_SIGNER_CODE ON
ACC_IMPL.PO_INSURANCE_ACT_SAT(SIGNER_CODE)
END

------------------
